### ISSUE TITLE
Charts get cut off on the top

### ISSUE THREAD

**Issue by atishdawande** [chartist-js/chartist#1006]
Charts get cut off on the top. i think its issue on svg. 
![cut-off](https://user-images.githubusercontent.com/31304485/29654148-ac516caa-88c9-11e7-91e1-bf9a4c2c5f04.png)

**Comment by nguyenlamlll** [comment]
Hey, I know it's pretty old but have you looked at #247? There is one property `chartPadding` that you can send when you create the chart.

```
new Chartist.Pie('.ct-chart', {
  series: [20, 10, 30, 40]
}, {
  chartPadding: 30,
});
```
