### ISSUE TITLE
Draw Mixed Chart

### ISSUE THREAD

**Issue by karneaud** [chartist-js/chartist#1007]
Hello,

I was researching for a way to render both a bar and a line chart using the framework but saw no way other than the "overlay charts" which to me is impractical and inefficient for my project. 

If there was a way to "stop" drawing based on conditions that would have allowed me to alter the way elements are drawn. 

I saw you a discussion on having a "beforeDraw" and "afterDraw" event which may help me achieve the goal but not sure what happened there.

Is there another way to achieve a mixed chart display?

**Comment by Arantiryo** [comment]
Unfortunately multitype charts are not supported as of right now.

#1284
