### ISSUE TITLE
axis autoscale for custom indexes

### ISSUE THREAD

**Issue by faceless105** [chartist-js/chartist#1008]
I'm working on a project where I'm polling a lot of data and polling 1 hour averages to display. As such all of my axis labels are labelled along the lines of "8/29 10AM, 8/29 11AM, etc"

The chart works great, but if I showing a week worth of data, then my chart gets incredibly crammed with text and I'd like a way to display every 10th axis label. I found the autoscale setting, but when I applied it, it looks like it tried to convert my xaxis labels into floats, which made all of my points jump off of the chart.

I don't have a publicly available live version, but I can supply one if necessary. My question is, how can I go about either using the autoscale for the xaxis or simply only show every Nth tick on the xaxis labels? As I have them right now, they are overlapping and unreadable.

**Comment by Arantiryo** [comment]
This can be achieved by using `labelInterpolationFnc` and filtering out excessive ticks.
