### ISSUE TITLE
Refresh Chartist JS line chart 

### ISSUE THREAD

**Issue by BeginnerBen87** [chartist-js/chartist#1014]
Hi, 
I'm just a beginner in JavaScript and I am using the basic line graphing library for my graph, currently the graph refreshes when I refresh the page, how ever I would like the graph to refresh using a javascript timer, does anyone know how to do this?  
this is very important to me, your help would be much appreciated 
thanks 
Ben

**Comment by KinnaT** [comment]
You can use the `update()` function, [documented here](https://gionkunz.github.io/chartist-js/api-documentation.html#chartistbase-function-update), to do this and tie it to a timer function. I don't believe this is the most elegant way to go about it, but it's the clearest way for those who aren't familiar with JavaScript APIs.

Example:
```
window.setTimeout(timerFunction, 3000); // Generic timer function called after 3 seconds
var myChart = new Chartist.Line(. . .); // The variable you used to create the chart
function timerFunction() {
    var newData = {"data1":"value1", "data2":"value2"}; // Make sure this matches the format of your original data
    myChart.update(newData);
};
```

You can also use timers within the Chartist API for more complex functionality such as delayed animations.

**Comment by gionkunz** [comment]
Thanks @KinnaT

**Comment by sll1966** [comment]
Here is an example which has an API call for data

`
                //define chart
		var chart24 = new Chartist.Line('#TargetRate',  { labels: [],  series: [] }, optionsLine);

		//initial data get 
		GetTargetRateData();

		window.setTimeout(GetTargetRateData, 60000); // How often to refresh data 

		function GetTargetRateData() {
			const req24 = new XMLHttpRequest()
			req24.addEventListener("load", reqListener24);
			req24.open("GET", '../../api/24HourTrend/{{{ParmLocation}}}/{{{ParmLine}}}');
			req24.send();
			
			function reqListener24 () {
				const result = JSON.parse(this.responseText);
				//console.log("api result:" + result);
				const labels = [];
				let series = [];
				result.forEach(function(row){
					labels.push(Object.values(Object.values(row))[0]);
					series.push([Object.values(Object.values(row))[1],
								Object.values(Object.values(row))[2],
								Object.values(Object.values(row))[3]]);
				});
				//rotate the series 90 degrees counter clockways
				series = rotateMatrix90(series,"left");
				const chartdata = { labels: labels,  series: series };
				//console.log(`C2 JSON:  ` + JSON.stringify(chartdata))
				chart24.update(chartdata);
			}
		}
`
