### ISSUE TITLE
Full width, no axis, no labels?

### ISSUE THREAD

**Issue by johnalberthughes** [chartist-js/chartist#1018]
I'm trying various combinations of options but it's not clear to me how to do this. I am trying to just draw stacked colored bars which essentially fill up an entire div, with no axis, no labels, and most importantly no scaling or resizing; I want the entire bar used with the last data bar abutting the right end of my div, basically. But I find wasted space at the end because the total of my bars is, say, 176, and chartist insists I have a nice round bounding range of 200 instead. Is there a way to do this?

**Comment by gionkunz** [comment]
The default AutoScaleAxis is calculating order of magnitude to come up with better scales. You need to switch to FixedScaleAxis to disable that:

```javascript
new Chartist.Bar('.chart', {
  labels: ['1', '2', '3'],
  series: [[80], [170], [40]]
}, {
  horizontalBars: true,
  height: 100,
  chartPadding: 0,
  axisY: {
    showLabel: false,
    showGrid: false,
    offset: 0
  },
  axisX: {
    showLabel: false,
    showGrid: false,
    offset: 0,
    type: Chartist.FixedScaleAxis
  }
})
```
