### ISSUE TITLE
Line charts with different showLine/showPoint styles

### ISSUE THREAD

**Issue by Fizpok1** [chartist-js/chartist#1019]
A simple examlpe: I have points (first dataset) and I need to draw Less Squares (second dataset).
The first dataset should be displayed using points (circles) only (no connecting lines), while the second dataset should be using no points (lines only).

I tried hiding lines, but it seems I can only hide them for all datasets simultaneously. How to do it for a particular dataset, without affecting the others?

A complete example would be great, but any advices are appreciated.
Thanks.

**Comment by gionkunz** [comment]
Hi there. You can use series overrides: http://gionkunz.github.io/chartist-js/examples.html#example-line-series-override
