### ISSUE TITLE
NS_ERROR_FAILURE in Firefox

### ISSUE THREAD

**Issue by baires** [chartist-js/chartist#102]
Everything works fine in Chrome and IE, but FF keeps throwing NS_ERROR_FAILURE exception. Even on gionkunz.github.io/chartist-js

**Comment by gionkunz** [comment]
Hi there. Thanks for the issue. I'll look into this ASAP. The chart still displays correctly right?

**Comment by lo3ty** [comment]
I got the same exception. No chart is displayed. Don't know if its connected but in chrome the same chart is visible but only after about 30 seconds. before that, only one point is displayed and no grid :(

**Comment by gionkunz** [comment]
@lo3ty can you provide some example code?

**Comment by lo3ty** [comment]
not right now but I will set something of for you. the weird thing is, about a month ago, it worked perfectly fine

**Comment by baires** [comment]
It happens every time you open a new tab. I think that is trying to drwa a svg but the elemments if hidden, so firefox rise an  NS_ERROR_FAILURE.

Try to resize the viewport and you will the console going nuts with erros

**Comment by chriskief** [comment]
Also seeing the same issue in Firefox. And just to reiterate, this is happening with the examples on http://gionkunz.github.io/chartist-js/.

**Comment by danreed121** [comment]
It appears that the animated chart is causing the NS errors on the chartist home page.  Watching fire bug, each time that chart is redrawn the NS error is thrown again and again. ( in firefox 33.1 mac)

![image](https://cloud.githubusercontent.com/assets/6267025/5349955/02e29816-7f0c-11e4-80ed-92d246c603f5.png)

**Comment by gionkunz** [comment]
The NS_ERROR_FAILURE occurs because FF is not able to animate foreignObject attrbutes with animate elements that are inside of the foreignObject. All labels are rendered using foreignObject to solve the multi-line issue. 

I'm not sure whether FF is right or wrong (usually I think Firefox is right in terms of W3C specs) but in all other browsers (still don't count IE a browser) this is possible. Maybe @longsonr could tell if we should open a bug for this :smile:

I'll close this issue for now as 6319cda is kind of a graceful degradation.

**Comment by longsonr** [comment]
This is your bug not ours ;-). For keySplines if you read the SVG specification on them (http://www.w3.org/TR/SVG/animate.html#KeySplinesAttribute): The values must all be in the range 0 to 1. You have negative numbers which is why we're reporting an error.

**Comment by gionkunz** [comment]
Hey @longsonr. Yeah splines I agree :-) Even though Chrome supports negative values, allowing you to animate with a slight backwards movement http://easings.net/de#easeInBack . 

But what about SMIL animate elements inside of foreignObjects animating attributes of the foreignObject? I couldn't find anything in the extensibility spec nor in the SMIL spec. Webkit seems to support animations of foreignElement attributes by placing the animate element inside the foreignElement.

**Comment by longsonr** [comment]
If you want to embed SVG in html you must start from an `<svg>` node. I.e. you can't in html have `<body><rect/></body>`, the `<rect>` must be wrapped in an `<svg>` node. foreignObject allows you to embed SVG or html or mathml but the contents must be valid so if it's SVG the child must be an `<svg>` node. I suppose that `<svg>` node could have an animate child but then it's a grandparent and without an xlink:href it won't target its grandparent's attributes.

**Comment by gionkunz** [comment]
I think I get what you're saying. So you're saying that I'd need a container for the animate element that has the SVG XMLNS. I assumed that if I just add the animate element directly into the foreign object and put the XMLNS there it's still a valid child SVG node that affects its parent with the animation.

**Comment by longsonr** [comment]
Yes. I updated the comment above so the markup works. It makes much more sense now. All SVG data must have an ancestor that is an `<svg>` node and you stop looking for ancestors when you get to a foreignObject, the root node or a non-SVG namespace node.
