### ISSUE TITLE
Change colour of chart

### ISSUE THREAD

**Issue by remedcu** [chartist-js/chartist#1033]
Hello,

I have been using chartlist for my website, and thank you for making this 👍 

I wanted to customise the colour, and saw some of the already made issues, but I was not able to use that for me.

In the 
> _chartlist.scss

I changed the code as shown:

```
$ct-include-classes: true !default;

// If this is set to true the CSS will contain colored series. You can extend or change the color with the
// properties below
$ct-include-colored-series: $ct-include-classes !default;

// If set to true this will include all responsive container variations using the scales defined at the top of the script
$ct-include-alternative-responsive-containers: $ct-include-classes !default;

// Series names and colors. This can be extended or customized as desired. Just add more series and colors.
$ct-series-names: (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) !default;
$ct-series-colors: (
  $new-black,
  $new-blue,
  $new-orange,
  $new-green,
  $new-orange,
  $new-black,
  $new-black,
  $social-google,
  $social-tumblr,
  $social-youtube,
  $social-twitter,
  $social-pinterest,
  $social-behance,
  #6188e2,
  #a748ca
) !default;
```
Any change made in the above colours is not changing the colours in my charts.

**Comment by Arantiryo** [comment]
Hello @remedcu 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the question is still relevant to you so we can further look into it!
