### ISSUE TITLE
ctPointLabels label undefined when 0

### ISSUE THREAD

**Issue by srternasco** [chartist-js/chartist#1039]
I'm implementing ctPointLabels but I get undefined when serie value is 0.

![screen shot 2017-11-22 at 15 46 43](https://user-images.githubusercontent.com/28518/33133215-6402e900-cf9c-11e7-9f1d-bc94a871dc84.png)

What I'm doing wrong? Is this a bug?

```
new Chartist.Line(chart_wrapper, {
  labels: [1, 2, 3, 4, 5],
  series: [
    [1, 1, 8, 0, 7]
  ]
  },
  {
    axisX: {
      showGrid: false,
      showLabel: false,
      offset: 0
    },
    axisY: {
      showGrid: false,
      showLabel: false,
      offset: 0
    },
    chartPadding: {
      top: 15,
      right: 10,
      bottom: 0,
      left: 10
    },
    fullWidth: true,
    lineSmooth: false,
    showArea: true,
    plugins: [
      Chartist.plugins.ctPointLabels({
        labelOffset: {
          x: 0,
          y: -7
        },
        textAnchor: 'middle'
      })
    ]
  })
```

Thanks in advance.

**Comment by echosalik** [comment]
For anyone who has the same problem add the following line:
`if(typeof d === "undefined") d = "0";`
below this line:
`function b(b, c) {
                var d = void 0 !== c.value.x && c.value.y ? c.value.x + ", " + c.value.y : c.value.y || c.value.x;`
