### ISSUE TITLE
[Question] Animate custom images in line chart

### ISSUE THREAD

**Issue by FPeters84** [chartist-js/chartist#1044]
Hi,

First of all, thanks for the very nice chart library! :)

What I would like to do is based on the following post and related jsbin example
https://github.com/gionkunz/chartist-js/issues/704
http://jsbin.com/wadoteg/edit?html,css,js,output

Now I would like to animate an image from one point in the graph to another point in the graph, along the graph line. So for example in the jsbin move the apple to the location of the strawberry.

I now this is a bit far fetched :) So this is just a question, not an issue.

Any help with this is greatly appreciated, many thanks in advance :)

Kind regards,
Frank

**Comment by FPeters84** [comment]
Hi @gionkunz ,

Since you also helped me out greatly with my other question (drawing an image on top of a bar chart), perhaps you have an idea if what described above is possible?

No worries if it is not :)

Thanks in advance for your answer!
Frank

**Comment by FPeters84** [comment]
Ok, I was able to work something out for this myself :)

Example here: http://jsbin.com/sumolagelo/1/edit?html,css,js,console,output

What I did:
- calculate position for 2nd and 3rd image with jQuery
- calculate difference in position between both
- use jQuery keyframes plugin (https://github.com/Keyframes/jQuery.Keyframes; code added in jsbin example on top of javascript code) to create the keyframes with the dynamic values above and add the animation to the 2nd image

I used the plugin because I found no easy way to change the keyframes in the css (changing the class is not a problem, but did not found something straight forward for the keyframes).

So for me this topic can be closed :)
Thanks again for the awesome plugin. 
Very happy with the fact I can do all kind of crazy stuff with images on the graph now :)

Kind regards,
Frank

**Comment by gionkunz** [comment]
Awesome news you figured out a solution which works for you :-)
