### ISSUE TITLE
Best Way to Render a Projected Line?

### ISSUE THREAD

**Issue by gordonjl** [chartist-js/chartist#1047]
# Problem
I want a projection line to appear on a chart. What's the best way to do that?

## Details
I am charting the progress of a budget. I want to show a 'perfect path' by drawing a diagonal line from the start of a project to the end of a project. Given the start and end are always fixed, what's the best way to draw this line?

## Example

<img width="785" alt="pww_metrics_and_new_issue_ _gionkunz_chartist-js" src="https://user-images.githubusercontent.com/718041/33775586-d96fceca-dc0c-11e7-9633-52b59c2b447f.png">

**Comment by gordonjl** [comment]
I found a solution. If you know a better way to do this, please let me know.

```coffeescript
  ready: ->

    budget = 200000
    labels = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
    perfectLine = new Array(labels.length)
    stepAmount = budget / labels.length

    perfectLine[0] = 0

    for currentPoint, i in perfectLine
      if currentPoint == 0
        continue
      perfectLine[i] = perfectLine[i - 1] + stepAmount



    series = [
      perfectLine,
      [1, 3, 4]
    ]

    new Chartist.Line('.budget-chart', {
      labels: labels,
      series: series
    }, {
      fullWidth: true,
      chartPadding: {
        right: 40
      }
    });

```

**Comment by gionkunz** [comment]
I'd switch to fixed or auto scale axis for the X axis and then provide leaner series data which will be projected by chartist. Check the documentation on how to switch axis types: https://gionkunz.github.io/chartist-js/getting-started.html#switching-axis-type
