### ISSUE TITLE
Reduce datapoints shown on X-Axis, responsive

### ISSUE THREAD

**Issue by lembi0** [chartist-js/chartist#1049]
Is there an easy way to reduce the number of shown datapoints on X-Axis if the screen width is pretty small? I have 1440 datapoints for my charts. This is OK if you have a screen width above 1280px, but it looks a little bad if the sreen width is smaler.

Do i have to rebuild the values array and reduce the number of elements in it or is there a function to reduce the shown datapoints on X-Axis responsively?

Thanks.
Alex

**Comment by mlumbroso** [comment]
Hello,

Try to use AutoScaleAxis or FixedScaleAxis, as defined in the beginning of documentation : https://gionkunz.github.io/chartist-js/api-documentation.html

With FixedScale, you can put a fixed number of ticks using the divisor like this : 
``` 
    axisX: {
              type: Chartist.FixedScaleAxis,
              divisor: 6,
```

Alternatively you can use labelInterpolationFnc to make a custom display function

**Comment by mestaritonttu** [comment]
I think this is exactly what you are looking for: https://github.com/gionkunz/chartist-js/issues/99#issuecomment-65251829

I actually use that mobile-first, having the skipping by default and then having a labelInterpolationFnc without the skipping in a min-width responsiveOptions rule.

Please close the issue, if happy.
