### ISSUE TITLE
Pie chart per-segment class names

### ISSUE THREAD

**Issue by ioquatix** [chartist-js/chartist#105]
I'd like to be able to supply per-segment class names so that I can style parts of the charts without having to guarantee the order (i.e. `ct-series-{a,b,c}`).

Basically, I'd like a pie chart showing  distribution of languages, and I'd like to colour specific languages certain colours.

Thanks.

**Comment by gionkunz** [comment]
Hey there. Just use the object data notation for the series in your pie chart:

``` javascript
var chart = new Chartist.Pie('.ct-chart', {
  labels: [1, 2, 3, 4],
  series: [{
    data: 3, className: 'my-series-one'
  }, {
    data: 2, className: 'ct-series-b'
  }, {
    data: 4, className: 'my-series-three'
  }, {
    data: 1, className: 'my-series-four'
  }]
});
```

**Comment by gionkunz** [comment]
Hey there. I hope this helped. If not please reopen the issue.

**Comment by ioquatix** [comment]
Yes this is great, but just wondering if this is on the chartists website/documentation. I certainly looked for something like this but couldn't find it.

**Comment by gionkunz** [comment]
Of course you're completely right :-) I've added some documentation for this.

**Comment by ioquatix** [comment]
@gionkunz awesome thanks :D

**Comment by dezaen** [comment]
@gionkunz Thanks for the help above; but it seems that the latest version of chartist isn't working with the custom class name.
Can you check what is causing this?

Here is the code snippet and screenshot from the chartist example page.

```
var chart = new Chartist.Pie('.ct-chart', {
  series: [{
    value: 20,
    name: 'Series 1',
    meta: 'Meta One'
  }, {
    value: 10,
    name: 'Series 2',
    className: 'my-custom-class-two',
    meta: 'Meta Two'
  }, {
    value: 70,
    name: 'Series 3',
    className: 'my-custom-class-three',
    meta: 'Meta Three'
  }]
}, {
  donut: true,
  showLabel: false
});
<img width="836" alt="screen shot 2016-07-19 at 9 13 57 pm" src="https://cloud.githubusercontent.com/assets/5160140/16956256/5f1d4e50-4df5-11e6-9ab3-6038113e761e.png">

```
