### ISSUE TITLE
Draw image at the top of a bar in a bar chart

### ISSUE THREAD

**Issue by FPeters84** [chartist-js/chartist#1053]
Hi all,

First of all: thanks for chartist, really enjoy using it and it is exactly what I need for my project :)

I would like to draw an image at the top of a bar chart.
I know it is possible to draw images in line charts, example from @gionkunz : http://jsbin.com/wadoteg/edit?html,css,js,output

However, I was not able to figure out a way to do the same for a line chart.
The reason is probably because the points drawn in the line chart are replaced by images, but there are no points drawn in bar charts.

If anybody knows a way how to do is, many thanks in advance!

Kind regards,
Michiel

**Comment by gionkunz** [comment]
Hi @FPeters84 thanks for the kind words :-) Here's an updated example using bar charts. Not much different from line charts, except that you need to append to the parent instead of replace the dot.
http://jsbin.com/regipab/1/edit?html,css,js,output

**Comment by MichielJ87** [comment]
@gionkunz many thanks for this, exactly what I need :)

Kind regards,
Frank

**Comment by FPeters84** [comment]
Many thanks for this, exactly what I need :)

For me this story can be closed.

Kind regards,
Frank
