### ISSUE TITLE
Cannot draw a Vertical line

### ISSUE THREAD

**Issue by deQuota** [chartist-js/chartist#1055]
Chartist line chart
If we use two points like 
 [{x:15,y:2},{x:15,y:2.5}]
which should generate a vertical line fails to generate one.

but when I use [{x:15,y:2},{x:15.000001,y:2.5}] it is working but for data which are having sensible decimal values this hack won't work.

I think that this occurs because chartist line chart accepts the data values in an exponential order(second x is always larger than first x)

**Comment by stswoon** [comment]
Same issue. 
It's not good, but for my case next WA is appropriat: if (xBefore - x) < 0.1 then I add 0.1 to x

**Comment by wbrannoc** [comment]
I had this same issue and just had to turn off lineSmooth for the series.  Default is on.
