### ISSUE TITLE
line chart with 3 series, two with one left scale and other with right scale

### ISSUE THREAD

**Issue by emazzu** [chartist-js/chartist#1067]
hi, how are you, 
chartist, support multi lines with differente scales ?? on the left and right ?

example:
one serie: 2000, 5000, 2500, 3400, 2345, 
two serie: 1.33, 0.50, 4.55, 7.44, 5.44

with the same x !!!!
regards
Eduardo

**Comment by Arantiryo** [comment]
Hello @emazzu 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the question is still relevant to you so we can further look into it!
