### ISSUE TITLE
Question: Multiple Data Sets in One Chart

### ISSUE THREAD

**Issue by gktowle** [chartist-js/chartist#107]
I'm wondering if it's possible to display multiple (or in this case, two) data sets in one chart. Attached is an example. I don't see any examples of this. I tried simply adding a second array of labels, but that broke the code.

Here is an example:
![2014-12-09_08-03-17](https://cloud.githubusercontent.com/assets/2250105/5360809/d78217da-7f7b-11e4-96c8-710afac19db6.jpg)

**Comment by danreed121** [comment]
stacked bars.... I was actually going to review the code to see if this was something that could be added by using combo data points like [23,12,4], [12,22,53], etc.

I actually have a list of things that I wanted to attempt to add to a local copy of the lib... this is one item, along with combo (line+bar, same axes, on one chart) and having a mix of smooth and non-smooth lines on a single chart.  Just need to find the time... have it on my todo over the holidays.

**Comment by gktowle** [comment]
@danreed121 - you can do stacked bars. I accomplished it with this code:

```
new Chartist.Bar('.ct-chart', {
  labels: ['Oak Elementary','Washington High School','Sage Middle School','West Elm Elementary','JFK Middle'],
  series: [
    [2500, 2000, 1500, 2000, 500],
    [2200, 1700, 900, 1500, 250]
  ]
}, {
  seriesBarDistance: 0,
  axisY: {
    scaleMinSpace: 15
  }
});
```

And I also adjusted the bar width in chartist-settings.scss:

`$ct-bar-width: 30px !default;`

Screenshot of results:
![2014-12-09_10-33-48](https://cloud.githubusercontent.com/assets/2250105/5363213/e0587e22-7f8e-11e4-932f-799da7efa56d.jpg)

**Comment by gionkunz** [comment]
@danreed121 Your probably looking for #37 

@gktowle Stacked bar charts, where one bar is showing the total of all series for the given data point is tracked here #23 

I'm closing this issue in favor of the other two. This issue will be referenced there and thanks for your inputs!

**Comment by gionkunz** [comment]
Sorry @danreed121  you actually opened #37 :laughing:

**Comment by danreed121** [comment]
heh.  thanks @gionkunz 

@gktowle,  I don't want to have to change my data to fit.... but that is slick all the same. #23 is certainly what I need.  great.  I can use your method in the short term if it becomes a real need.

**Comment by gktowle** [comment]
Yes, thanks @gionkunz. Besides the stacked bars, the other element I'd request is the second set of labels, as in the sample I provided. Is that covered in #23?
