### ISSUE TITLE
Axis labels cropped when labelInterpolationFnc creates longer label

### ISSUE THREAD

**Issue by jezmck** [chartist-js/chartist#1070]
I'm prefixing the Y Axis labels with a currency symbol and it's getting cropped off for the longer labels, as illustrated below:

![screen shot 2018-02-15 at 13 25 31](https://user-images.githubusercontent.com/89996/36258751-c7e006e8-1253-11e8-811c-84be01855f17.png)

I realise I can manually set the `offset` for that axis, but it feels clumsy.

Related, but more complex: #158.

**Comment by Arantiryo** [comment]
Hi @jezmck 👋 

In case this is still relevant here's [a suggested solution](https://github.com/chartist-js/chartist/issues/158#issuecomment-518138875).

**Comment by jezmck** [comment]
Thanks @Arantiryo. I've long since moved on!
