### ISSUE TITLE
Multiple Charts with same .on('draw', function(data)... ) ?

### ISSUE THREAD

**Issue by dakicks87** [chartist-js/chartist#1071]
I am assigning new Pie charts to different variables. I want all of the pie charts to have the same animation settings etc... Is there an easy way to do this with out doing repetitive code, chart.on('draw', function(data){...} and chart.on('created', function() {..] for every chart?

**Comment by gionkunz** [comment]
Like this?:
```javascript
function drawHandler() {}

chart1.on('draw', drawHandler);
chart2.on('draw', drawHandler);
```

Or if you want, like this:

```javascript
function addDrawHandler(chart) {
  chart.on('draw', function() {});
}

addDrawHandler(chart1);
addDrawHandler(chart1);
```
