### ISSUE TITLE
Put the documentation on top of the github 

### ISSUE THREAD

**Issue by amir20** [chartist-js/chartist#1072]
I find myself going to http://gionkunz.github.io/chartist-js/ a lot. Would it be possible to add this link to the github page at the top? You can do it at the top when you click edit. Here is my repo as an example. 

<img width="1034" alt="screen shot 2018-03-01 at 5 51 03 pm" src="https://user-images.githubusercontent.com/260667/36879539-29a25414-1d79-11e8-8968-90511e8bd124.png">

**Comment by gionkunz** [comment]
Cool, thanks for the hint! I've added that.
