### ISSUE TITLE
Label bug in Firefox 34.0.5

### ISSUE THREAD

**Issue by dzuncoi** [chartist-js/chartist#108]
As my image, Chrome display label normally but Firefox doesn't :(
![untitled](https://cloud.githubusercontent.com/assets/7270403/5374473/46f66172-8092-11e4-8867-b1df4ea7e0d1.png)
Is anyone know how to fix it?

**Comment by gionkunz** [comment]
Can you post your example on jsbin?

**Comment by dzuncoi** [comment]
I dont know why it doesn't work with chartist.min.js on cdn, my .js local file still works fine. 
Here is my example: http://jsbin.com/junajiqipa/2/edit?html,js,output

**Comment by gionkunz** [comment]
Hi There. I've already noticed this issue and it's because SMIL animations on foreign objects behave a bit different in firefox. I'll investigate this issue in the context of #102

**Comment by dzuncoi** [comment]
Please let me know if you have any solution, thank you.

**Comment by gionkunz** [comment]
Closing this task in favor of #102
