### ISSUE TITLE
Chartist languaje localization (spanish)

### ISSUE THREAD

**Issue by ganar** [chartist-js/chartist#1086]
Is there a way to localize Chartist for Spanish?

Fractions in Spanish are written with a comma (,) instead of a period (.). For instance `5,3` 

Is there a way to show `axis` numbers and `pointlabels` like that?

**Comment by ganar** [comment]
is there a way to use [Number.toLocaleString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString)? where should I set this up?

**Comment by gionkunz** [comment]
search for `labelInterpolationFnc`

**Comment by ganar** [comment]
Thanks a lot for your answer!

I wrote this —shabby— function:

```
     function eSpanish(x){
        if (options.roundNumber=="true"){x = Math.round(x,0);return x; };
        if(x){return x.toLocaleString('es-Es');} else{
          return x;
        }
      };
```

I called it within `chartist-plugin-pointlabels.js` and solved the issue, but do wonder how to use the `labelInterpolationFnc ` ([I did find this](https://github.com/gionkunz/chartist-js/issues/576))
