### ISSUE TITLE
Is it over? 

### ISSUE THREAD

**Issue by eddr** [chartist-js/chartist#1087]
Hi

Any clue if this project will be maintained any further?

Thanks

**Comment by gionkunz** [comment]
No, it's not over :-) Chartist 0.x will still receive critical fixes. At the same time, we will start working on https://github.com/chartist-js/chartist again, once some of my other higher priorities are solved. Critical fixes to 0.x are done regardless of my other priorities.

**Comment by eddr** [comment]
Great to hear, gionkunz!

**Comment by eddr** [comment]
If I can help without coding, let me know

**Comment by Arantiryo** [comment]
Hello @eddr 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).
