### ISSUE TITLE
How could i hide cleanly a graph ?

### ISSUE THREAD

**Issue by kevincaradant** [chartist-js/chartist#109]
Hi everybody :)

Great job , it's very nice . But i'm confusing because i can't hide a graph in JS without have a error like that (every time, when i want to hide and show the div which contains the graph ).

Have you any idea to avoid that ? :)

Thx a lot for your answers :)

![capturecjs](https://cloud.githubusercontent.com/assets/6093175/5383982/29014b86-80b6-11e4-9bae-81594e9a3ee3.PNG)

**Comment by gionkunz** [comment]
Hey there. I think this is related to #102 . This error should not cause any problems in your chart though. Can you post your code example on jsbin?

**Comment by kevincaradant** [comment]
Hey ,

So,  I found a mistake that was in my code and that generate the " NS_ERROR_FAILURE " error. OK for that. Now i eliminate my code as responsible , but when I change with differents tabs on Firefox , and then I come back on my website , I have this error again ( but not all the time , it's really random).

As my question initial was my mistake. I close this topic. The other problem that i'm speaking is already explained , topic #102 as you say. 

Thank you again :)
