### ISSUE TITLE
FixedScaleAxis with inclusive min and max label

### ISSUE THREAD

**Issue by rob-gordon** [chartist-js/chartist#1097]
My data is between 0% and 100%. I'm trying to show increments of 10% on the y axis.

Using Chartist.FixedScaleAxis and a divisor of 10 shows the correct ticks up to 90% but leaves off the 100% which just looks odd. Is there anyway to specify that the high and low should be included in labels as well?

    new Chartist.Bar(
        '.chart',
        {
            series: [
                {
                    name: 'Percentage 1',
                    data: ['43', '56', '70'],
                    className: 'ct-series-a'
                },
                {
                    name: 'Percentage 2',
                    data: ['57', '44', '30'],
                    className: 'ct-series-b'
                }
            ],
            labels: ['Group 1', 'Group 2', 'Group 3']
        },
        {
            stackBars: true,
            height: 400,
            axisY: {
                type: Chartist.FixedScaleAxis,
                divisor: 10,
                labelInterpolationFnc: function(value) {
                    return value + '%';
                }
            }
        }
    ).on('draw', function(data) {
        if (data.type === 'bar') {
            data.element.attr({
                style: 'stroke-width: 30px'
            });
        }
    });

[Same Question on StackOverflow](https://stackoverflow.com/questions/50395428/chatist-js-fixedscaleaxis-with-inclusive-min-and-max-label)

**Comment by SankarshanDudhate** [comment]
You can use the ticks option.

`var options: { ticks: [10,20,30,40,50,60,70,80,90,100] };`

Hope that helps...
