### ISSUE TITLE
Rounding issues with label numbers on scale below 1

### ISSUE THREAD

**Issue by jasminetsai** [chartist-js/chartist#110]
I am having some issue with the decimal places for the labels on the Y-axis. It seems like it's unable to round to an appropriate number of d.p. Is there some way I can customize this, short of writing my own function to override it?

Screenshot attached. 

![screen shot 2014-12-10 at 2 48 07 pm](https://cloud.githubusercontent.com/assets/1663847/5385952/dfae3cc6-807b-11e4-8844-4198a2756fa8.png)

**Comment by gionkunz** [comment]
Hey there. It looks like there are rounding issues with an internal function of chartist.js when it comes to small numbers below 1. Im flaging this as a bug. In the meantime you could use the `labelInterpolationFnc` to round your labels. Just put something similar to this in your options:

``` javascript
{
  axisY: {
    labelInterpolationFnc: function(value) {
      return Math.round(value * 100) / 100;
    }
  }
}
```

**Comment by jasminetsai** [comment]
Awesome. Thanks for the quick reply.

On Wed, Dec 10, 2014 at 11:26 PM, Gion Kunz notifications@github.com
wrote:

> Hey there. It looks like there are rounding issues with an internal
> function of chartist.js when it comes to small numbers below 1. Im flaging
> this as a bug. In the meantime you could use the labelInterpolationFnc to
> round your labels. Just put something similar to this in your options:
> 
> {
>   axisY: {
>     labelInterpolationFnc: function(value) {
>       return Math.round(value \* 100) / 100;
>     }
>   }
> }
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/gionkunz/chartist-js/issues/110#issuecomment-66582083
> .

## 

Jasmine Y. Tsai
+1 415 812 2219

**Comment by Timmmm** [comment]
The root cause of the problem is in `src/scripts/core.js` in the `getBounds()` function:

```
 bounds.values = [];
for (i = bounds.min; i <= bounds.max; i += bounds.step) {
bounds.values.push(i);
}
```

For example if min is 0, and step is 0.05, you get (try this in the javascript console):

```
> 0 + 0.05 + 0.05 + 0.05
< 0.15000000000000002
```

This is because 0.05 can't be exactly represented as floating point values. One solution is to round it to a certain number of significant figures. A better one is to keep the steps above 1, and record the order-of-magnitude like this (obviously this code can be cleaned up a lot):

```
m = Math.pow(10, -bounds.oom+1); // Order-of-magnitude multiplier.
intStep = Math.round(bounds.step * m); // This has probably already been calculated further up in the function but I didn't look.
vals = []; // Y values
for (i = bounds.min * m; i <= bounds.max * m; i += intStep) {
vals.push(i / m);
}
```

I'll use the rounding hack for now.

I haven't tested this much but it seems to work.

**Comment by gionkunz** [comment]
@Timmmm Thanks for your investigations! We can sure use them to optimize the OOM code!

**Comment by martinsznapka** [comment]
I wanted to report this bug, but it already exists ;)
I use Math.round10 from http://goo.gl/RdV7Ur

bug: http://codepen.io/martinsznapka/pen/emGQKr
fix: http://codepen.io/martinsznapka/pen/azLQKQ

**Comment by gionkunz** [comment]
Well Math.round10 is a bit of a overkill :-) I guess this would do it too:

``` javascript
function roundWithAccuracy(value, digits) {
  var accuracy = Math.pow(10, digits);
  return Math.round(value * accuracy) / accuracy;
}
```

Assuming float point precision is accurate till exp 13 you could call this function in your `labelInterpolationFnc` like this:

``` javascript
{
  axisY: {
    labelInterpolationFnc: function(value) {
      return roundWithAccuracy(value, 13);
    }
  }
}
```

We should add this to the OOM function directly.
