### ISSUE TITLE
Any built-in capability for dots bar?

### ISSUE THREAD

**Issue by eddr** [chartist-js/chartist#1100]
Hi, great plugin

I want to create a "bar" chart with dots only. Every column will be a bunch of dots, not belonging to a different series. Is there any option?

Thanks

**Comment by SleepProgger** [comment]
You could do that with CSS.
Something like:

```
.ct-bar{
  stroke-dasharray: 1, 15;
  stroke-linecap: round;
}
```

should do the trick.
