### ISSUE TITLE
chartPadding should be updated in API docs

### ISSUE THREAD

**Issue by atertel-synexxus** [chartist-js/chartist#1104]
Minor issue but you should update your docs for chartPadding. They still show chartPadding taking a number, which causes a compilation error.

`Types of property 'chartPadding' are incompatible.
    Type 'number' has no properties in common with type 'IChartPadding'.`

Based on the source, chartPadding now takes an object with top, right, bottom, and left values.

**Comment by holtkamp** [comment]
@atertel-synexxus maybe you can provide a Pull Request with the suggested changes?

**Comment by Arantiryo** [comment]
No longer causes an error.
