### ISSUE TITLE
TypeError: Cannot read property 'querySelectorAll' of null

### ISSUE THREAD

**Issue by Saifer707** [chartist-js/chartist#1105]
Hi, 

As title says, i get this error using Chartist. I don't use the querySelectorAll method in my Typescript code. 

The error:
![image](https://user-images.githubusercontent.com/13942770/41223573-75801024-6d6a-11e8-8219-216345e2c5f4.png)

Can anyone help me? Thank you.

**Comment by Saifer707** [comment]
I solved. 

There was a method that searched for a Chartist id that was commented out.

**Comment by shriram9494** [comment]
same problem

**Comment by shriram9494** [comment]
saifer707 how to solve this

**Comment by Saifer707** [comment]
In my previous response, i said that there was a function call to a commented Chartist ID.
