### ISSUE TITLE
Horizontal bar chart with long labels

### ISSUE THREAD

**Issue by boompig** [chartist-js/chartist#1106]
I am using this code to generate a chart

```
const chart = new Chartist.Bar("#book-title-histogram", {
        labels: labels,
        series: [y],
    }, {
        horizontalBars: true,
        reverseData: true,
        axisX: {
            onlyInteger: true,
        }
    });
```

And getting this result: 

![screen shot 2018-06-11 at 2 11 53 pm](https://user-images.githubusercontent.com/2791268/41257360-68c3f53c-6d81-11e8-98f4-452bd8c8e2b4.png)

As you can see, the labels on the left are squashed. Is this expected behaviour?

**Comment by boompig** [comment]
The aspect ratio I am using is `ct-square`. Does that have something to do with it?

**Comment by ruggedjungleboy** [comment]
Hi, did you find a solution? I'm struggling with the same issue.

**Comment by omer-repo** [comment]
Same problem here, is there any solution?

**Comment by omer-repo** [comment]
Finally found:
 axisY: {
    offset: **400**
  }
