### ISSUE TITLE
Android 4.4 support

### ISSUE THREAD

**Issue by jgardynik** [chartist-js/chartist#1109]
The website lists Android 4.4 (and 4.3) support, but visiting your site on a device with Android 4.4.2 shows that all of the charts are broken, often only showing a very small amount of the graphics all crushed into the upper left corner.  I don't know if something has changed in the past year or two, but it's not working now.

Since the Kitkat browser is basically Chromium 11, I also downloaded that to check for errors. There are no errors, but it displays exactly the same way. 

Normally I'd just ignore a 7 year old browser, but apparently a vast number of tablets still have Kitkat on them with no upgrade path, and I'm trying to use this for an embedded device that will generally get configured/viewed with tablets. I was hoping not to have to resort to a huge bloated charting library.

**Comment by gionkunz** [comment]
Just looking at the example site on Android 4.4 (I don't have 4.3 available right now) renders just fine for me.

**Comment by jgardynik** [comment]
Which browser are you using? If I use the newest Chrome version from the Google Play store it runs just fine. But the default browser on my older Galaxy Tab (which I assume is the Samsung browser) is based on Chrome 11, and it definitely does not run fine.

Honestly, I'm about ready to just disable the chart if it's a super-old browser, and reminisce of the good ol' days of IE6 telling people to go download a real browser.

**Comment by gionkunz** [comment]
I'm using an emulated Galaxy Tab 4 10.1 with Android 4.4 and with the original Samsung browser

**Comment by gionkunz** [comment]
And you're looking at the website example charts? Or is it something else that uses Chartist?

**Comment by jgardynik** [comment]
Both the website example charts and an app I developed are doing the same thing.

What's the user agent string of the browser on that? The Galaxy Tab 3 7" I have reports as "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/11.0.696.34 Safari/534.24".
