### ISSUE TITLE
x-axis maximum value

### ISSUE THREAD

**Issue by mesokalos** [chartist-js/chartist#111]
is it possible to prevent the end of the graph from having one last x-tick mark beyond the actual data. I am trying to make an area graph that will fill the entire container, but there is always this empty space at the end of the x-axis that I can't figure out how to get rid of.

So right now my chart looks like this: 
![screen shot 2014-12-11 at 3 22 17 pm](https://cloud.githubusercontent.com/assets/7890362/5401468/97e107d8-8149-11e4-8df8-e299dce74a3b.png)
but I am trying to make it look like this;
![image](https://cloud.githubusercontent.com/assets/7890362/5401474/a952d67c-8149-11e4-81b7-02152f451c87.png)

**Comment by gionkunz** [comment]
Closing in favor of #18
