### ISSUE TITLE
bar chart gradient fill

### ISSUE THREAD

**Issue by eldadts** [chartist-js/chartist#1110]
Hi,

I'm trying to fill the bars' in gradient color.
I've tried [this](http://jsbin.com/toqobowosa/1/edit?css,js,output) method but it works only for a line chart.
I also tried the suggestion @ [976](https://github.com/gionkunz/chartist-js/issues/976) but I could not get it to work. is it possible at all to have individual bars with different gradient color?

**Comment by webiotsanjali** [comment]
hi,
i am also try fill the bars in gradient color
http://jsbin.com/kedeta/edit?css,js,output check this link it works
