### ISSUE TITLE
stackMode missing from typings

### ISSUE THREAD

**Issue by MacMaru** [chartist-js/chartist#1111]
First off, what a great nifty lib this is, excellent work.
One thing I run in to is Typescript does not know about `stackMode`. I happen to need this, it is in defaultOptions for the bar chart, but now typescript complains about `stackMode does not exist in IBarChartOptions`.

**Comment by MacMaru** [comment]
Sorry for raising this issue here, I'll make a PR at DefinitelyTyped.

**Comment by MacMaru** [comment]
I'm not sure how and where to get the stackMode added to the typings, if you could do/generate this that'd be sweet.

**Comment by gionkunz** [comment]
Hi there. I'm not maintaining the typings of Chartist. They were created by some comunity members. Please check who comitted the typings for Chartist and contact them.
