### ISSUE TITLE
Mobile Scrolling with touch event starting on static chart

### ISSUE THREAD

**Issue by Ecksters** [chartist-js/chartist#1114]
I recently discovered on our application that's using Chartist that users cannot scroll through the page if their touch event starts on one of the Chartist graphs.

I understand that sometimes Chartist features are enabled that would make touch an important event that should be controlled at the graph level, and not the entire page, but in my specific case, we simply have static graphs, which I'd like users to be able to scroll past without having to avoid touching the graph when they start scrolling.

Is there any quick setting that lets me prevent the charts from intercepting the touch event?

**Comment by hansmaad** [comment]
Have you tried to use the `pointer-events` or `touch-action` CSS properties on the charts?
https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events 
https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action

**Comment by Ecksters** [comment]
Ah yes, it looks like in my CSS, SVG elements were assigned the CSS value `touch-action: none;`, thanks for the suggestion, wasn't sure exactly what I was looking for.
