### ISSUE TITLE
x-axis maximum value

### ISSUE THREAD

**Issue by mesokalos** [chartist-js/chartist#112]
is it possible to prevent the end of the graph from having one last x-tick mark beyond the actual data. I am trying to make an area graph that will fill the entire container, but there is always this empty space at the end of the x-axis that I can't figure out how to get rid of.

So right now my chart looks like this: 
![screen shot 2014-12-11 at 3 22 17 pm](https://cloud.githubusercontent.com/assets/7890362/5401468/97e107d8-8149-11e4-8df8-e299dce74a3b.png)
but I am trying to make it look like this;
![screen shot 2014-12-11 at 3 22 27 pm](https://cloud.githubusercontent.com/assets/7890362/5401488/ce87e87e-8149-11e4-8f9a-7e91a4e02ada.png)

**Comment by gionkunz** [comment]
Hi. Thanks for your report. This seems to be a duplicate of #18
