### ISSUE TITLE
width and height are hard-coded on the svg element

### ISSUE THREAD

**Issue by alamothe** [chartist-js/chartist#1120]
Hello,
I would like to set width and height of SVG based on device width using Bootstrap classes e.g. `class="ht-200 ht-sm-300"`.

As far I have experimented so far, this cannot be done because Chartist will always add width and height attributes to the SVG element (even if not specified, they will default to 100%). 

Would it be possible to not set width and height at all? Or if what I'm trying can be accomplished in another way? 

Thanks!

**Comment by j-mikhail** [comment]
Create an outer div that holds the svg and set your classes on that. The svg will adjust to fit your bounding box.
