### ISSUE TITLE
Custom y-axis labels

### ISSUE THREAD

**Issue by bkostic** [chartist-js/chartist#1126]
Hi,
I'm having a problem with displaying custom labels for y-axis.

`function populateGraph(x, y, yLabels, yValues) {`
`	var chart = new Chartist.Line('#topic-result-overview', {`
`		labels: x,`
`		series: [{ name: 'topic-result', data: y }]`
`	},`
`		{`
`			series: {`
`				'topic-result': {`
`					lineSmooth: Chartist.Interpolation.step()`
`				}`
`			},`
`			low: 0,`
`			high: 100,`
`			showArea: true,`
`			lineSmooth: false,`
`			showLine: true,`
`			chartPadding: 30,`
`			axisX: {`
`				showLabel: true,`
`				showGrid: true,`
`				offset: 50`
`			},`
`			plugins: [`
`				Chartist.plugins.tooltip()`
`			],`
`			axisY: {`
`				onlyInteger: true,`
`				labelInterpolationFnc: function (value, index) {`
`					if (yLabels !== null && yLabels.length > 0) {`
`						console.log("Label: ", yLabels[index])`
`						console.log("Value: ", yValues[index])`
`						return yLabels[index];`
`					}`
`					else {`
`						return value;`
`					}`
`				},`
`				stretch: true`
`			}`
`		});`
`}`

And I'm getting results like on image below.

![capture](https://user-images.githubusercontent.com/17779389/44858434-45acc580-ac72-11e8-9b09-f5c488f7cd05.JPG)

If you check console log you will notice that my labels LOW, MID, HIGH have values 0, 50, 100 respectively, but they are not shown on y-axis properly. Can you please help me with this.

**Comment by Arantiryo** [comment]
Hello @bkostic 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the issue is still relevant to you so we can further look into it!
