### ISSUE TITLE
Changing label color dynamically not working

### ISSUE THREAD

**Issue by datoml** [chartist-js/chartist#1127]
Hello,
I try to change the color of the labels in my code using the listener event but it seems like the attribute isn't working correctly.

This is my react element:
```
<ChartistGraph
    className="ct-chart"
    data={sampleBarChart.data}
    type="Bar"
    options={sampleBarChart.options}
    responsiveOptions={sampleBarChart.responsiveOptions}
    listener={{
      draw(context) {
        if (context.type === 'label') {
          context.element.attr({
            style: 'fill: rgba(255, 255, 255, 0.4) !important',
          });
        }
      },
    }}
  />
```

It seems like the CSS is always prefered instead of the foreign object.
Did I something wrong here?

Thanks

![image](https://user-images.githubusercontent.com/10552487/44909915-74ce4000-ad21-11e8-9aa3-450068892b5f.png)

**Comment by melvudin** [comment]
Try changing the span color property inside the foreignObject tag.

```
var element = document.getElementsByTagName("foreignObject"), index;
for (index = element.length - 1; index >= 0; index--) {
	element[index].firstChild.style.color="blue";
}
```

**Comment by datoml** [comment]
> Try changing the span color property inside the foreignObject tag.
> 
> ```
> var element = document.getElementsByTagName("foreignObject"), index;
> for (index = element.length - 1; index >= 0; index--) {
> 	element[index].firstChild.style.color="blue";
> }
> ```

Thanks for the tip. I'll try it.
