### ISSUE TITLE
not working at phone

### ISSUE THREAD

**Issue by imhitt** [chartist-js/chartist#1135]
hi !
set all options to default, require scripts from cdn servers, used 1st example from "get started"
but not working at phone :c

**Comment by maulerjan** [comment]
Hi, it's impossible to help with as few information as you have provided.

Which phone? Which android version? How does you project look like? Using within any frontend framework? Using Webpack/Babel/...? Please provide as much information as possible. I'm able to run the 1st example with no problem so my guess is there's something wrong with your project structure.

Thanks
