### ISSUE TITLE
Bar chart not showing series with val zero

### ISSUE THREAD

**Issue by iFernandoSousa** [chartist-js/chartist#1138]
Hi, I have a plugin to custom labels in each bar, so they put the value after the bar, but the plugin don't receive any value that is zero, is it a configuration or a bug?

My option is

```
var options = {...
plugins: [
    Chartist.plugins.ctBarLabels({
        labelInterpolationFnc: function (value) {
	    return value + '%';
	 }
   })
]};
```

What  can I do to show 0 on my bar chart?

**Comment by melvudin** [comment]
A similar problem I have encountered was with the line chart using the ctPointLabels plugin. The zero value was returned as undefined!
I've found help on this page:
[https://github.com/gionkunz/chartist-plugin-pointlabels/issues/19](url)
Credit: @stomachfat
For me:
`return value ? value: 0`
did the fix!

**Comment by iFernandoSousa** [comment]
Thanks :)
