### ISSUE TITLE
Problem : AxisX show grid but not labels

### ISSUE THREAD

**Issue by moh6mmad** [chartist-js/chartist#1140]
Hey
Thank you for your good plugin
I need some way that I can show labels for each 5 days but show grid for all days
` axisX: {
			  showGrid: true,
				labelInterpolationFnc: function skipLabels(value, index) {
			  return index % 5  === 0 ? value : null;
			}
			}`

it shows labels and grid per 5 days but I need grid for all days

**Comment by duchuy** [comment]
axisX: { showGrid: true, labelInterpolationFnc: function skipLabels(value, index) { return index % 5 === 0 ? value : ""; } }
