### ISSUE TITLE
Pie Charts with Exploded Labels

### ISSUE THREAD

**Issue by dpkonofa** [chartist-js/chartist#1145]
I'm using a pie chart with exploded labels that put them outside the area of the pie chart. Unfortunately, the labels are cut off if they extend outside of the vertical or horizontal boundaries of the actual chart itself:

<img width="466" alt="screen shot 2018-11-28 at 3 18 15 pm" src="https://user-images.githubusercontent.com/6332378/49186167-12d1a680-f321-11e8-84e0-13e6aa3f8231.png">

If exploding and offsets are given as options, the chart's size should probably include the dimensions including the labels.

**Comment by consciousimages** [comment]
I believe I had a similiar 'problem' (using axis labels) - I increased the chart padding and that resolved it:

		  chartPadding: {
		  	top: 40,
		  	right: 40,
		  	bottom: 40,
		  	left: 40
		  },

`
