### ISSUE TITLE
width not 100% for the chart in Safari 5.1.7(7534.57.2) in windows 7 but fine in chrome.

### ISSUE THREAD

**Issue by ranand16** [chartist-js/chartist#1152]
In safari,
![image](https://user-images.githubusercontent.com/13871067/50221324-bf4ff700-03ba-11e9-8e01-9290c58ed3b0.png)

In chrome
![image](https://user-images.githubusercontent.com/13871067/50221277-9f203800-03ba-11e9-8002-161a66322c60.png)

` var options = {showPoint: false, lineSmooth: true,fullWidth: true, height: "200px", length: "100%",
        axisX: {showGrid: false,showLabel: false},
        axisY: {labelInterpolationFnc: function(value) {return value;}}
    };`

The problem is that I want to set width of the graph such that it stretches fully on the parent div(i,e; same as screen width) in all browsers(atleast for mobile screens). But it doesnot work on Safari but works on chrome. 
I have tried all sorts of solutions but in vain.

**Comment by OriginalEXE** [comment]
Why do you care about Safari on Windows? It's a dead browser.
