### ISSUE TITLE
Mixed Charts Impossible?

### ISSUE THREAD

**Issue by MrDevDevy** [chartist-js/chartist#1158]
This is common in a few charting APIs I've used, but I haven't seen an example here. Does anyone have working code that demonstrates it's possible? I wanted to combine bar and line charts into a single graph. Thanks!

**Comment by MrDevDevy** [comment]
I ended up creating a plug-in with a custom SVG path! Worked for me. Not sure if there's a feature out of the box to get mixed charts.

**Comment by sntran** [comment]
@MrDevDevy would you mind sharing your solution?
