### ISSUE TITLE
Line Chart is not displaying correctly.

### ISSUE THREAD

**Issue by ljlamudi** [chartist-js/chartist#1161]
<img width="524" alt="screenshot 2019-02-15 at 15 42 24" src="https://user-images.githubusercontent.com/47099521/52843161-4b249c00-313c-11e9-9839-dfd0fb539d23.png">

What is the possible fix for this?

**Comment by christiangoltz** [comment]
You might be missing the include for the chartist css file!

**Comment by ljlamudi** [comment]
Yes. Issue fixed.
