### ISSUE TITLE
[Styling] yAxis labels width

### ISSUE THREAD

**Issue by guiguitcho** [chartist-js/chartist#1162]
I would like to modify the width of the yAxis. By default it seems 30px:

![image](https://user-images.githubusercontent.com/25325841/53330605-393aba00-38ef-11e9-89d4-f61e359174dc.png)

I tried 
`.ct-label.ct-vertical{
    width: 10px !important;
}`
but it doesn't do the thing (label width is well decreased but the plot width is not changed, hence creating a space between labels and plot).

I also tried the yAxis option offset, but it adds a "magic" number with does not adapt with the label text width.

Is there any option to automatically adapt the label width ? And a corollary question, where are documented all the options available for axis and plot ? I can find some in the examples but a complete listing of them would be highly appreciated ! 

Thanks in advance

**Comment by iphilippenko** [comment]
I've fixed it with
`me.chart.on('draw', (context) => {
                    if(context.type === 'label') {
                        context.element.attr({
                            width: '50px'
                        });
                    }
                });`
+ add styles `.ct-labels span {width: inherit !important;}`
There's a demo https://codepen.io/iphilippenko/pen/gEYygK
