### ISSUE TITLE
Retain Line color in Series

### ISSUE THREAD

**Issue by prakis** [chartist-js/chartist#1164]
Hi,

My Series change dynamically, example: 
LineChart
series: [
       [1,2,3],              // should always be RED
       [15,16,17],        //    GREEN 
       [21,29,23]        //     YELLOW
]
I have 3 lines  here, user can show/hide a particular line, with colors set per line. If user clicks to hide(or remove) the second line the color of the third line is changing to second. That is very confusing. 

Is there a way to set a line to a particular predefined color?

Thank you

**Comment by ManuLintz** [comment]
Hi,

I'd say that this is because when you hide this line, you remove the serie: 
`series: [`
`[1,2,3], // should always be RED`
`[21,29,23] // YELLOW  `
`]`
Maybe you should try by replacing it by an empty array: 
`series: [`
`[1,2,3], // should always be RED`
`[],`
`[21,29,23] // YELLOW  `
`]`

**Comment by pierre-fromager** [comment]
Hi,
IChartistSeriesData has a className prop.
Setting one className per serie and defining className colors from your custom css class should do the trick.

**Comment by prakis** [comment]
@pierre-fromager Thank you, I will try that.

@ManuLintz Thanks for your suggestion. Unfortunately what you suggest may not work for us because we don't know how many lines will be there in the initial stage. So we cant have dummy arrays.
