### ISSUE TITLE
Can't show small value when axis has large number

### ISSUE THREAD

**Issue by jaydeepakbari** [chartist-js/chartist#1165]
![image](https://user-images.githubusercontent.com/6220995/55702086-0f4adc00-59f3-11e9-96d9-cae0349a1fa3.png)

Check  4th column has value but can't show

![image](https://user-images.githubusercontent.com/6220995/55702124-37d2d600-59f3-11e9-8cc5-e8afe073b57c.png)

**Comment by ManuLintz** [comment]
When I face that issue I change the value programmatically so it becomes readable: 
`let series = dataArrays.map((dataArray) => {`
    `return {`
        `data: dataArray.map((val) => val === 0 // If value is 0, it is set at 0.1 so something appears on the chart`
                `? 0.1`
                `: val`
            `)`
    `}`
`}`

**Comment by jaydeepakbari** [comment]
Value is 1 not zero

**Comment by ManuLintz** [comment]
You just need to change the condition: 
`data: dataArray.map((val) => val < 2 `
`? 2`
`: val`
In that case for example the value would always be at least 2
