### ISSUE TITLE
Stacked bar starting at negative values

### ISSUE THREAD

**Issue by carlkenne** [chartist-js/chartist#1167]
I've been trying to get a bar chart starting at below 0 by changing the series values to negative [-10, 20, 40]. But so far this has been giving me some really strange results. Is there a correct way of doing this?

I want something looking like this:

![image](https://user-images.githubusercontent.com/1203085/56132357-0c6b6080-5f8a-11e9-9818-2c6d3331b6fb.png)

**Comment by ManuLintz** [comment]
If I understand well, this issue is adressed in that conversation: #835
The short answer is that the case of negative numbers in stacked bar charts doesn't seem to be supported as for now.

However there is an open PR that seems to implement that feature: #1113

**Comment by rarias8404** [comment]
I developed a solution using jQuery, maybe I can serve you. Here is the code
`// Lower limit of the y axis
        const limit = $('.ct-series-a > line').first().attr('y1');
        // If exist a ct-series-b
        if ($('.ct-series-b').length > 0) {
            $('.ct-series-a > line').each(function (index, element) {
                // If negative
                if (element.getAttribute('ct:value').valueOf() < 0) {
                    // If the lower limit of the element of series b is below the value 0 (visual) on the Y axis
                    // Then the lower limit will be equal to the value 0 (visual) of Y axis
                    if ($('.ct-series-b > line').eq(index).attr('y1') > limit) {
                        $('.ct-series-b > line').eq(index).attr('y1', limit);
                    }
                }
            });
        }`

**Comment by rarias8404** [comment]
Take a look
![graph](https://user-images.githubusercontent.com/12527809/64816781-6c385880-d576-11e9-99b8-a1e13655ad9d.png)
