### ISSUE TITLE
Invalid value for <path>

### ISSUE THREAD

**Issue by sakujo** [chartist-js/chartist#117]
Hi there!
Im using chartist.js for a project. My chart is working well, but my console is showing this error:
Error: Invalid value for <path> attribute d="Mundefined,undefined"

Any ideas?

**Comment by gionkunz** [comment]
Hey there :-) What browser? Could you post the code on jsbin?

**Comment by sakujo** [comment]
Im using Chrome. I ve figured something... one way to fill the data Array is like you stated in the docs:
 data = {
      labels: ["1", "2", "3"],
      series: [ [-1.0, -2.0, -2.3] ]
};
If i fill data like above, there are no errors.

But im filling the Array in another way. Im using angular.js. I have two rootScopes for labels and series that i fill like this in a function:
chartistCTRL {
...
function xy (a, b) {       //this function is called when i switch to a certain tab for im updating the data
          $rootScope.labels = new Array();
          $rootScope.series = new Array();
...
          $rootScope.labels.push($scope.test.length + " ");
          $rootScope.series.push(test2[i].id);
}

then:
data = {
      labels: $rootScope.labels,
      series: [ $rootScope.series ]
};
...
new Chartist.Line('.ct-chart', data, options, responsiveOptions);
}

This gives me the error like in my first post.

p.s. dunno how i can put in jsbin xD Sry!

**Comment by gionkunz** [comment]
Hey there :-) its really hard to tell from your code snippets whats going wrong. Any chance you can prepare your case on http://plnkr.co and share it?

**Comment by sakujo** [comment]
I found my problem. The data Array im filling isn't filled when i enter the view (with my chart on it) for the first time thus i get that error and no line is shown on my chart (grid is there). However, if i enter the view for the second time, my chart is shown because my data Array is now filled. It's more a problem im causing myself rather than chartist. Sry for bothering you for my own mistake ^^'

**Comment by gionkunz** [comment]
Hey there :-) no worries Im glad you sorted it out. Cheers Gion
