### ISSUE TITLE
Bug with rescue-campaign

### ISSUE THREAD

**Issue by KenorFR** [chartist-js/chartist#1174]
Hello,

You added a little script to, I suppose, add a message for your campaign on kickstarter during the installation from NPM.

But this last bug, I have this error "Cannot find module "chalk'" which blocks the installation.

I had to use "--ignore-scripts" to make it work.

Have a good day,

**Comment by jmdsg** [comment]
Same here

**Comment by gionkunz** [comment]
Hi, thanks for this. I'll look into this.

**Comment by primus852** [comment]
> I had to use "--ignore-scripts" to make it work.

worked for me too

**Comment by jmdsg** [comment]
> > I had to use "--ignore-scripts" to make it work.
> 
> worked for me too

Adding chalk to dependencies also works (in case someone needs scripts and ignore-scripts is not an option). It is currently used as devDependency in chartist.

**Comment by gionkunz** [comment]
Hey, I've removed the rescue campaign for now. I will add it again when I start another campaign, however, next time I think I might skip chalk completely. I don't want a prod dependency listed on the package. If one of you could try to install 0.11.3 and check if the error is gone? Thanks!

**Comment by jmdsg** [comment]
Yeah the error is gone for me. Builded successfully in circleci.

**Comment by KenorFR** [comment]
That's perfect, no more mistakes.
