### ISSUE TITLE
Version mismatch NPM <-> GitHub

### ISSUE THREAD

**Issue by viniciuskneves** [chartist-js/chartist#1179]
On GitHub we have version `0.11.1` (https://github.com/gionkunz/chartist-js/releases/tag/v0.11.1) while on NPM we have version `0.11.2` (apparently this tag doesn't even exist on NPM).

Is it intentional? I've had an issue with that as Dependabot tried to update the package to `0.11.2` and it crashed my application.

Apparently I can't even install `0.11.1` as well:

`npm i --save --save-exact chartist@0.11.1`
```
100 verbose stack Error: chartist@0.11.1 postinstall: `node ./rescue-campaign.js`
100 verbose stack Exit status 1
100 verbose stack     at EventEmitter.<anonymous> (/Users/viniciuskneves/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
100 verbose stack     at EventEmitter.emit (events.js:198:13)
100 verbose stack     at ChildProcess.<anonymous> (/Users/viniciuskneves/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
100 verbose stack     at ChildProcess.emit (events.js:198:13)
100 verbose stack     at maybeClose (internal/child_process.js:982:16)
100 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
101 verbose pkgid chartist@0.11.1
102 verbose cwd /Users/viniciuskneves/workspace/homeday/city-explorer
103 verbose Darwin 18.6.0
104 verbose argv "/Users/viniciuskneves/.nvm/versions/node/v10.16.0/bin/node" "/Users/viniciuskneves/.nvm/versions/node/v10.16.0/bin/npm" "i" "--save" "--save-exact" "chartist@0.11.1"
105 verbose node v10.16.0
106 verbose npm  v6.9.0
107 error code ELIFECYCLE
108 error errno 1
109 error chartist@0.11.1 postinstall: `node ./rescue-campaign.js`
109 error Exit status 1
110 error Failed at the chartist@0.11.1 postinstall script.
110 error This is probably not a problem with npm. There is likely additional logging output above.
111 verbose exit [ 1, true ]
```

When installing version `0.11.2` I get the following error:
`Uncaught TypeError: Cannot read property 'window' of undefined`
![Chartist screenshot](https://user-images.githubusercontent.com/1734873/60509018-40723a00-9ccc-11e9-814d-658061dfa32b.png)

I'm not sure but apparently this PR has some relation to it: https://github.com/gionkunz/chartist-js/pull/776

**Comment by gionkunz** [comment]
Hi there. Thanks for reporting. I've pushed 0.11.3 which removes the rescue campaign and with it the issue with chalk. I've also pushed the version to NPM.
