### ISSUE TITLE
Uncaught TypeError: Cannot read property 'window' of undefined

### ISSUE THREAD

**Issue by sakethkalikiri** [chartist-js/chartist#1180]
Hi, 
I've been getting this issue and because of this, my whole application is not working. Please help me out in this ASAP. 
I'm using version 0.11.2
![chartist](https://user-images.githubusercontent.com/14901812/61537218-37b38f00-aa54-11e9-9692-80b9260604e8.PNG)

**Comment by blueskyfish** [comment]
Hi @gionkunz,

I use the version `0.11.3` and I have the same error.

I think the reason is for the AMD prefix in the javascript file:

![chartist-globalRoot-is-undefined](https://user-images.githubusercontent.com/1814374/61582925-5d629600-ab31-11e9-899a-46321fea08e1.png)

**Usage**:

* Chrome (current version)
* Angular 8.1
* chartist 0.11.3

Please help me.

Thank you

**Comment by gionkunz** [comment]
@larrybotha, would this be addressed by https://github.com/gionkunz/chartist-js/pull/1177 ?

**Comment by larrybotha** [comment]
@gionkunz yup!

Edit: Let me know if I should revert conflicts to before my changes; I imagine you'd want to handle versions etc. on your side before publishing to npm

Edit2: Side note - it may be a good idea not to commit built files in the repo to avoid conflicts, while ensuring they are still published to npm

**Comment by wilsongis** [comment]
Is there a solution for this issue?

**Comment by gionkunz** [comment]
@larrybotha, yeah, can you exclude the dist files from your PR? I will then build and commit after merging.

**Comment by larrybotha** [comment]
@gionkunz done!

**Comment by ghost** [comment]
when the next release ?

**Comment by jh1777** [comment]
Any updates here? Also facing same issue and don't want to use another chart engine.

**Comment by larrybotha** [comment]
Until https://github.com/gionkunz/chartist-js/pull/1177 is published to a new release on npm lock your version of Chartist in `package.json` to [0.10.1](https://github.com/gionkunz/chartist-js/releases/tag/v0.10.1)

EDIT: @gionkunz what's missing from the latest release is the latest build for `dist` that includes the changes from https://github.com/gionkunz/chartist-js/pull/1177

**Comment by gionkunz** [comment]
This should be fixed with the v0.11.4 release which is now public on NPM

**Comment by HamidNiakan** [comment]
hi, I have a problem with
main-es2015.6e67fdaf70aac61e8b1c.js:1 Uncaught TypeError: Cannot read property 'window' of undefined
when building project angular 8
please help me?please
