### ISSUE TITLE
Charts don't show up in tabs

### ISSUE THREAD

**Issue by pieterjandesmedt** [chartist-js/chartist#119]
When trying to add charts into [Foundation tabs](http://foundation.zurb.com/docs/components/tabs.html) or [Material Design tabs](https://material.angularjs.org/#/demo/material.components.tabs), the charts don't show up or show only on the first tab.

**Comment by pieterjandesmedt** [comment]
[JSBin example](http://jsbin.com/wozabimiwi/1/edit?html,css,js,output)

**Comment by sakujo** [comment]
That's somehintg i wanted to state too.Two charts in one template doesn't work either.

I tried this:
Example: 1. chart in template:   <div class = "ct-chart"></div>
                2. chart in template:   <div class = "ct-chart2"></div>

Controller:  chart 1:    var chart = new Chartist.Line('.ct-chart', {
                  chart 2:    var chart2 = new Chartist.Line('.ct-chart2', {
Just the first one is showing. Btw. is it even possible to rename "ct-chart" to "ct-chat2"?

**Comment by fredrivett** [comment]
I second @pieterjandesmedt's findings, I've got my own tab style setup using jQuery to display:none & display:block but if the chart starts in display:none then it doesn't load properly. Strangely though if I start the Chrome inspector whilst looking at where the chart should be it kicks it into gear and it then works as expected.

Also @sakujo you can use more than one, just use this markup (or similar):

```
<div class="ct-chart ct-line ct-golden-section"></div>
<div class="ct-chart ct-pie ct-golden-section"></div>
```

Then something like this (depending on whether you have data & options):

```
<script>
[...]
new Chartist.Line('.ct-line', data, options);
new Chartist.Pie('.ct-pie', data, options, responsiveOptions);
[...]
</script>
```

The classes `ct-line` & `ct-pie` can be anything, I just named them those for ease of use. This seems to work for me. Just make sure you keep ct-chart in there, as the other javascript hooks off of that.

**Comment by gionkunz** [comment]
Hey guys. The problem with `display: none` is that containing elements do not layout and therefore don't have `width` nor `height`. As your using a intrinsic container to layout the charts, Chartist will use 0 width and 0 height for creating the chart in a container that is `display: none`. Chartist needs to calculate the available width and height to construct the initial `chartRect`that is used to draw the chart.

You can fix this by updating your chart on activated tabs: http://jsbin.com/bawofakogu/1/edit?html,css,js,output

**Comment by sakujo** [comment]
@fredheimholm It works for me too! Thank you!

**Comment by gionkunz** [comment]
@fredheimholm, loading the chrome console triggers a `window.resize` event which Chartist listens for in order to update the drawing.

**Comment by fredrivett** [comment]
@gionkunz Thanks for the swift reply Gion! I'll be sure to take a look at that link later this week, doing so today probably wouldn't go down well with the family. Merry Christmas to you :)

@sakujo Glad I could be of use! :)

**Comment by fredrivett** [comment]
Hey @gionkunz thanks for your support on this, really appreciate that. Your fix worked perfectly :)

**Comment by gionkunz** [comment]
@pieterjandesmedt , I'm closing this issue. If you have the feeling these comments don't provide enough or if you think this must be solved differently please re-open the issue.

**Comment by pieterjandesmedt** [comment]
To get this to work in [AngularJS](https://angularjs.org/) + [Material Design tabs](https://material.angularjs.org/#/demo/material.components.tabs) + [ng-chartistjs](https://github.com/paradox41/ng-chartist.js), it needs a `$timeout` wrapper as well.

html:

``` html
<div data-ng-controller="ChartController as chctrl">
...
<md-tabs md-selected="selectedIndex">
    <md-tab ng-repeat="(key, value) in allTheCharts" id="{{key}}" label="{{key}}" md-on-select="chctrl.tabToggled(key)">
        <div class="chartwrapper" height="400px">
            <chartist class="ct-chart" chartist-data="value.data" chartist-chart-options="value.options" chartist-chart-type="Bar"></chartist>
        </div>
    </md-tab>
</md-tabs>
```

controller:

``` javascript
angular.module('mapApps.controllers')
.controller('ChartController', [
    '$timeout',
    'ChartService',
    function ChartController ($timeout, ChartService) {

        var ctrl = this;

        ctrl.allTheCharts = ChartService.charts;

        ctrl.tabToggled = function(tab){
            $timeout(function(){
                angular.element('#content_'+tab).find('chartist').each(function(i, e) {
                    e.__chartist__.update();
                });
            }, 100);
        }
    }]);
```

The element created by `angular-material` containing the charts has an id starting with `#content_`. This is the one you'll need to do `.find('chartist')` on.

@gionkunz thanks for your support!

**Comment by SarasArya** [comment]
Hey @gionkunz  How would you do this is angular? 
`$('[data-tab]').on('toggled', function (event, tab) {  
    tab.find('.ct-chart').each(function(i, e) {  
      e.__chartist__.update();  
    });  
});`
I want to do this inside a controller.

**Comment by SarasArya** [comment]
@pieterjandesmedt I was able to replicate whatever you did. here is the GitHub [link](https://github.com/SarasArya/Angular-Chartist-Tab-Example). Please head over here for a complete example in angular.

**Comment by regmish** [comment]
```
var chart = new Chartist.Pie() ....

```

For Bootstarp Tabbed navigation
`$('a[data-toggle="tab"]').on('shown.bs.tab', function(event) { 
            chart.update();
        });`

**Comment by dezaen** [comment]
Here is the fix for bootstrap

```
$('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
    $(e.currentTarget.hash).find('.chart').each(function(el, tab) {
      tab.__chartist__.update();
    });
  });
```
