### ISSUE TITLE
Thanks for chartist, For information chartist is used in Grafana Flowcharting with success

### ISSUE THREAD

**Issue by algenty** [chartist-js/chartist#1193]
Hi,
I'am writing it to say first thanks for chartis.  
I'am the author of Grafana Flowcharting 
https://github.com/algenty/grafana-flowcharting
and i choose chartist for no depedencies and the size.
i need it to display graph into tooltip like it and here is the result  
![example_graph](https://user-images.githubusercontent.com/47012725/66673281-83936000-ec60-11e9-9d2c-8551b4dc4e8f.gif)

I love the render but i don't know to change color of line and area of each graph in last tooltip with 3 graphs. How to change color for each graph without change CSS ?

Another question : 
each value have a timestamp epoc style like

...
1570817317 : 45
1570817404 : 53
1570817613 : 35
...
All the timestamp have the same difference
How to make a graph where each value point are above of his timestamp

Best regards,
Arnaud

**Comment by algenty** [comment]
For the fisrt question : i found 
https://gionkunz.github.io/chartist-js/getting-started.html#dynamic-colouring
i'll try it

**Comment by gionkunz** [comment]
Hi there

You can apply custom CSS by adding a special class to the 3rd chart. Then
apply styles to that class and sub elements. Easiest thing is to inspect
the CSS styles on the chart elements to see how to override the styles.

Cheers
Gion

Am Sa., 12. Okt. 2019 um 01:41 Uhr schrieb Arnaud GENTY <
notifications@github.com>:

**Comment by algenty** [comment]
Thanks,
It work for dynamic colors, the render is beautiful
![tooltip_graph_ani_2](https://user-images.githubusercontent.com/47012725/66704992-b2253f80-ed21-11e9-8b44-54896f6f6a02.gif)

and i think i found response for the second question at the end of getting started
var data = {
  labels: ['A', 'B', 'C'],
  series: [[
    {x: undefined, y: 10},
    {x: undefined, y: 8},
    {x: undefined, y: 14}
  ]]
};

On tweeter, I took the liberty of thanking you
https://twitter.com/gf_flowcharting/status/1182933612255236096

Arnaud

**Comment by tomm1996** [comment]
@algenty I think you linked the wrong guy on your tweet, dude.
This appears to be his account: https://twitter.com/gionkunz?lang=en
you seem to be missing the 'z' in his twitter.
