### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rubyzhao** [chartist-js/chartist#1194]
When I make new Chartist.Line, if  the data points of series>130000, the errors come as below:
chartist.js:168 Uncaught RangeError: Maximum call stack size exceeded
    at Object.b.times (chartist.js:168)
    at Object.b.normalizeData (chartist.js:390)
    at f.c [as createChart] (chartist.js:3374)
    at f.g (chartist.js:1930)

**Comment by leeoniya** [comment]
SVG-based libs are not well suited for large datasets.

shameless plug, but definitely relevant: https://github.com/leeoniya/uPlot

you can also evaluate quite a few alternatives in the bench section.

**Comment by rubyzhao** [comment]
Wow, Just tried your uPlot. It is great even for 100000000 data points. Thanks.

**Comment by gionkunz** [comment]
Chartist is just not made for those large datasets. Try switching to a canvas based solution like suggested.
