### ISSUE TITLE
[Feature] Add Data Without A Full Reconstruction Of The SVG DOM

### ISSUE THREAD

**Issue by KoltonG** [chartist-js/chartist#120]
**Question:** I was wondering if it is possible to update the data in the Chartist chart for realtime data graphing. I tried a few way however using the `update` does a full reconstruction of the SVG DOM which makes it super difficult to make it look good while updating.

Is it possible to do this, I am still new at all things JS, or could this be a new feature!

Here is something similar to what I was thinking:
The `load` Data from C3 Charts -> http://c3js.org/gettingstarted.html
The `flow` command from C3 Charts -> http://c3js.org/samples/api_flow.html

**Comment by gionkunz** [comment]
Hey there! Thanks for your issue report and sorry for the delayed reply. This is actually already a hot topic #3 and is underway for the next major release. Please track any further progress in the mentioned ticket. Cheers
