### ISSUE TITLE
Change the colours of a bar chart

### ISSUE THREAD

**Issue by Lucas015** [chartist-js/chartist#1200]
I have a problem changing the colours of the bar chat:
my code below:
```
var chartData = {
            labels: ['Minor', 'Major', 'Critical', 'Catastrophic'],
            series: [{
                className: 'ct-series ct-series-a',
                data: {stroke:'yellow', value: 3},
                data: {stroke:'green', value: 6},
                data: {stroke:'orange', value: 5},
                data: {stroke:'red', value: 8},
            }
            ]
        };```

**Comment by mistryhn** [comment]
var chart =  new Chartist.Bar('#barchart' ,data ,options);
     chart.on('draw', function(context) {
                if(context.type === 'bar') {
                    context.element.attr({
                    style: 'stroke: hsl(' + Math.floor(context.seriesIndex * 50) + ', 50%, 50%);'
                  });
                  ind = context.seriesIndex;
                }
              });




This will help you to make custom colors of your values
