### ISSUE TITLE
Scale/transform issue

### ISSUE THREAD

**Issue by Hatead1** [chartist-js/chartist#1202]
Hi! 
Look at https://codepen.io/hatead1/pen/RwwXjam

If you just move the nodes or change the size (wheel), it's okay.
However, if you resize and then move the window border, the chart resizes.

![chartist1](https://user-images.githubusercontent.com/41296890/69912560-00121600-143c-11ea-9209-1dbb51d0b663.gif)
How to stop it?

**Comment by Hatead1** [comment]
Test with chart.js - ok, expected behavior

https://codepen.io/hatead1/pen/povzqwL

**Comment by Hatead1** [comment]
And the winner is... chart.js!

**Comment by W4G1** [comment]
I have the same issue. Any idea how to fix this with Chartist?
