### ISSUE TITLE
How to install without bower?

### ISSUE THREAD

**Issue by omexlu** [chartist-js/chartist#1207]
Hello,

How can i install chartist and plugins without bower?

Thanks in advance.

**Comment by hansmaad** [comment]
Using npm?
https://www.npmjs.com/search?q=chartist

Or simply from a CDN (https://gionkunz.github.io/chartist-js/getting-started.html#use-a-cdn-alternatively)

**Comment by Arantiryo** [comment]
A quickstart guide can be found [here](https://github.com/chartist-js/chartist#quickstart).
