### ISSUE TITLE
A More Advanced Line Chart Points Behavior Example?

### ISSUE THREAD

**Issue by markudevelop** [chartist-js/chartist#121]
Hello,

I love chartist! Finally nice responsive charts. I was wondering if you guys can consider to do a more advanced example of the "ADDING BEHAVIOR TO YOUR CHARTS" right now it will only show tooltip on `mouseenter` how about:
1. Show tooltip when the mouse is near (examples: http://morrisjs.github.io/morris.js/, Google Analytics, ChartJS, HighCharts etc..) I know it's a really nice feature and many look for (Me too)
2. Show in that same tooltip all points values and line colors. Also have the text custom for each point such as (day of the month etc)

What you guys think?

**Comment by gionkunz** [comment]
Hey there. Thanks for expressing your thoughts about more examples. This kind of feedback is really helpful. We should consider such examples in the advanced topic in the documentation. I'll give it a go the next time I work on the docs. Cheers.

**Comment by nickyhajal** [comment]
Just more feedback that I would really appreciate this as well!

**Comment by Dhruuva** [comment]
Hi ! 
it will be really useful for my needs also 
I'm trying find the way to get nearest ct-point object on mousemove event and fired tooltip on it 
$(document).on('mousemove', '.ct-chart', function() {
   some like that may be ??
     var p = $(this).closest('.ct-point').attr('ct:value');
    $('#tx').text(p);
});

**Comment by phs1919** [comment]
+1

**Comment by exside** [comment]
This would be really nice, I'm also looking for a way to be able to basically mousemove over the chart (anywhere) and have a Tooltip displayed as soon as I hit an axis with points (vertical one)...without success yet....

**Comment by Dhruuva** [comment]
Hi! 
 try my plugin code https://github.com/Dhruuva/chartist-plugin-crosshair
I hope it will help.

**Comment by gionkunz** [comment]
Closing this in favor of #733
