### ISSUE TITLE
Only 15 pie colors, no more

### ISSUE THREAD

**Issue by zaferaltug** [chartist-js/chartist#1211]
I have done the suggested solution that offered [here](https://github.com/gionkunz/chartist-js/issues/844) for the pie charts. That is working for bar charts but not pie charts.

Here is the [CODE](https://jsbin.com/wobodileku/edit?css,js,output)

**Comment by Arantiryo** [comment]
Hi @zaferaltug 👋 

You can still use the suggested solution from #844 just use `ct-series.ct-series-p .ct-slice-pie` as selector and `fill` property.
