### ISSUE TITLE
axisX.scaleMinSpace creates unnecessary gap on both edges of the X axis

### ISSUE THREAD

**Issue by wujekbogdan** [chartist-js/chartist#1219]
I wanted to increase the gap between labels, so I set `axisX.scaleMinSpace` to 60, but now both edges of the chart are pushed by 60 pixels from the edge of the chart.

Is it possible to increase the spacing between labels but keep the minimum and the maximum value aligned to the edges of the chart?

I'm not sure is it a bug or is it the expected behaviour. To me it looks like a bug because increasing the labels gap shouldn't affect the main chart area.

<img width="543" alt="Zrzut ekranu 2020-02-24 o 14 40 29" src="https://user-images.githubusercontent.com/533954/75161761-41048880-5714-11ea-8b07-ef55e5564233.png">

**Comment by gionkunz** [comment]
The problem is that we don't have a date axis currently. The Auto Scale axis is optimized for order of magnitude, which means that it tries to show a nice series of numbers (like 0, 1000, 2000, 3000 etc.). I'd just use a FixedScaleAxis and provide the ticks (dates) yourself.

**Comment by wujekbogdan** [comment]
So it's not a bug that `axisX.scaleMinSpace` causes an offset? Based on docs it looks like this setting should only affect the way how labels are rendered, so I was surprised that it affects the chart area too.

**Comment by gionkunz** [comment]
No it's not a bug. The AutoScaleAxis may behave a bit strange you could think. But it's just searching for the right order of magnitude first, based on the numbers it needs to display. Then it rounds off / up with one unit in the order of magnitude to find the start or end position of the graph. This end up in a graph where you have clear start and end points (lets say 0 or 2000 or 20000 or something).

I'd really suggest, you're using the FixedScaleAxis and provide ticks where you want to draw lines (let's say, 1. of every month). Or working with the divisor setting to 12 and set `low` to your first datapoints time. If you share a Codepen / JSBin / Stackblitz online code snippet, I could also help you finding an appropriate configuration. Also if you search for date or time in the issues, you might find some good ideas here in the github issues.

**Comment by wujekbogdan** [comment]
Thanks for the detailed explanation. I've been using `FixedScaleAxis` in the past, but after I found the `AutoScaleAxis` feature it seemed a better choice for me. I'll give the `FixedScaleAxis` one more try then.
