### ISSUE TITLE
'Chartist' is not defined. in AngularJS app

### ISSUE THREAD

**Issue by edouardsouan** [chartist-js/chartist#122]
Hi there, 

I'm actully using Chartist on an Angular JS app and I can't fix this issue. 
I have installed the module through bower and have it referenced in the 'app.module' of Angular. 

When i launch the app the chart are drawn but when using Grunt to minify files, the console says : 
"'Chartist' is not defined."
Here is my code: 
        var buildChart = function (labels, series) {
            var data = {
                labels: labels,
                series: series
            };

```
        var options = {
            low: 0,
            showArea: true,
            lineSmooth: false
        };

        new Chartist.Line('#connectionChart', data, options);
    };
```

More over, I have the Angular error: 
        Error: [$injector:nomod] Module 'angular-chartist' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument. 

Do you have any hint or idea of what I'm missing ? 

Thank you for your time

**Comment by gionkunz** [comment]
Hi there. Are you using an angular directive that already exists? ( like https://github.com/paradox41/ng-chartist.js ) or are you embedding Chartist directly?

Maybe you can reproduce the issue on http://jsbin.com ? It's way easier to debug there.

**Comment by edouardsouan** [comment]
Hi , 

Thank you for your answer. I was writing back to let you know that I solved the problem . 
I'm using the angular directive but it wasn't working until I re-installed ng-chartistjs. 
I assume that it was the version of chartist which was wrong but it's probably more exact to say that I was the problem. 

Everything work fine now , so thanks a lot for your time.
