### ISSUE TITLE
Using Chartist.js and need to move position of Y axis 

### ISSUE THREAD

**Issue by Shreya1771** [chartist-js/chartist#1221]
I need to move Y axis to 0 and give display few negative fields and few positive .How Can we move Y axis or get expected output shown in Image .In Image red are positive value legends and blue negative value .![image](https://user-images.githubusercontent.com/22524668/75420829-e743ce80-595e-11ea-93d6-60b6be0002ef.png)

**Comment by Arantiryo** [comment]
Hi @Shreya1771 👋 

It can be achieved by catching the `draw` event and adding necessary classes to elements with positive and negative values. And then styling them. Here's [a small example](https://codesandbox.io/s/priceless-oskar-x079o8?file=/index.ts) to demonstrate.
