### ISSUE TITLE
Different colors in the line chart

### ISSUE THREAD

**Issue by it-delta** [chartist-js/chartist#1231]
Hello!

I can`t find information how can I do this chart:
![image](https://user-images.githubusercontent.com/10139266/76997866-16999a00-6965-11ea-8ae3-89775b9156a4.png)

Is it possible with Chartist?

Thanks!

**Comment by Arantiryo** [comment]
Hi @it-delta 👋 

I don't think there's a built in option for that, it might be possible by listening to the `draw` event ([an example](https://codesandbox.io/s/github/chartist-js/chartist/main/sandboxes/line/modify-drawing)) and then on `data.type === 'line'` you can rebuild the SVG and change the colors based on `data.values`.
