### ISSUE TITLE
Trouble Capturing Right Click Event

### ISSUE THREAD

**Issue by BPortfolio** [chartist-js/chartist#1232]
Thank you for this library!

I am having trouble capturing the right click event. 

I tried adding the right click event, "contextmenu", using the api below.
https://gionkunz.github.io/chartist-js/api-documentation.html#chartistevent-function-addeventhandler

 canvas.eventEmitter.addEventHandler("contextmenu", function(){alert('Handle Context Menu')}); 

This code compiles but does not work.  
I know that it needs the eventEmitter object.   Without it, it doesn't compile. 

I was able to add a left click event on the point on the graph with the code below.

 canvas.on("created", function () {
         // attach the necessary events to the nodes:
         //$('.ct-chart-line .ct-point').click(function () {
         $('.ct-chart-line .ct-point').click(function () {
                   alert('EventCreated');
                   var val = $(this).attr("ct:value");
                   console.log(val);
           });                        
  });

However, I was not able to add a right click event with the approach below.

 canvas.on("created", function () {
                        $('contextmenu').click(function () {
                            alert('Right Click Event');
                            console.log('Right Click Event');
                        });
                    });  

I am looking for suggestions.  To be clear, I am testing the right click event with an alert message.  I am not trying to pop-up a menu.  My full code is below.  

  <html>
    <head>
        <link rel="stylesheet" href="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
        <script src="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
        
         <link href="https://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
        <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script> 
        <script src="Context-menu/contextmenu.js"></script> 
  
        <script>
                function init(){
                    var data = {
                      // A labels array that can contain any sort of values
                      labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                      // Our series array that contains series objects or in this case series data arrays
                      series: [
                        [5, 2, 4, 2, 0]
                      ]
                    };

                    // Create a new line chart object where as first parameter we pass in a selector
                    // that is resolving to our chart container element. The Second parameter
                    // is the actual data object.
                    var canvas = new Chartist.Line('.ct-chart', data);
                    
                    //This is from the js library 
                    //this.eventEmitter.addEventHandler("optionsChanged",function()
                    //this.eventEmitter.addEventHandler("optionsChanged",function(){this.update()}

                    var $menu = $('#contextMenu');
                    canvas.eventEmitter.addEventHandler("contextmenu", function(){alert('Handle Context Menu')});
                    //canvas.eventEmitter.addEventHandler('mousedown', function(){alert('handleMouseDown')});

                    canvas.on("created", function () {
                        // attach the necessary events to the nodes:
                        //$('.ct-chart-line .ct-point').click(function () {
                        $('.ct-chart-line .ct-point').click(function () {
                            alert('EventCreated');
                            var val = $(this).attr("ct:value");
                            console.log(val);
                        });
                        
                        $('contextmenu').click(function () {
                            alert('Right Click Event');
                            console.log('Right Click Event');
                        });
                    });                    
                }
                
                /*
                function handleContextMenu(e){
                  alert('Handle Context Menu');   
                  e.preventDefault();
                  e.stopPropagation();
                  var x = parseInt(e.clientX-offsetX);
                  var y = parseInt(e.clientY-offsetY);
                  $menu.css({left:x,top:y});
                  $menu.show();
                  return(false);
                }

                function handleMouseDown(e){
                  alert('handleMouseDown');  
                  $menu.hide();
                }
                */
                
                menu = function(n){
                  console.log("select menu "+n);
                  $menu.hide();
                }
                
        </script>
        
      
      
</head>
<body onload="init()">
 
    <div class="ct-chart ct-perfect-fourth"></div>
    

   
    <div id="context-menu" style="display:none"> 
      
      <ul class="dropdown-menu">
        <li><a href="#">Action 1</a></li>
        <li><a href="#">Action 2</a></li>
        <li><a href="#">Action 3</a></li>
        <li class="divider"></li>
        <li><a href="#">Action 4</a></li>
        <li><a href="#">Action 5</a></li>
        <li><a href="#">Action 6</a></li>
      </ul>
    </div> 

    
</body>
</html>

**Comment by Arantiryo** [comment]
Hi @BPortfolio 👋 

Something like this should work to capture the right click event on `ct-point`s:

```
chart.on("created", () => {
  const elems = document.querySelectorAll(".ct-point");

  elems.forEach((el) => {
    el.addEventListener("contextmenu", () => console.log("Right Click"));
  });
});
``` 

Here's a [code sandbox with a small example](https://codesandbox.io/s/sad-cohen-q86hmf?file=/index.ts).
