### ISSUE TITLE
Replace Grunt with Webpack

### ISSUE THREAD

**Issue by marverix** [chartist-js/chartist#1234]
I think that it would be nice to replace Grunt with Webpack + move project to CommonJS syntax. This should allow to:
* lower down technical debt
* coding will be much fun
* support for Node.js 12 (developing - https://github.com/gionkunz/chartist-js/issues/1233)
What do you think?

**Comment by gionkunz** [comment]
This project is in maintenance mode and version 1 is already based on a more modern stack. Although development is also paused there until I can dedicate more time again. https://github.com/chartist-js/chartist

**Comment by gionkunz** [comment]
I think I will start all over again with version 1 and switch from jspm to webpack. I ported the whole code to ES2015 and now I'm even playing with the thought of moving it to TypeScript.

**Comment by marverix** [comment]
Ok, so:
1. In my opinion, this repo (gionkunz/chartist-js) should be archived, and big information should be visible that new official repo is chartist-js/chartist. So other guys will know to develop that 2nd repo :)
2. Great to hear about ES2015 etc! To be honest meanwhile I was waiting for your answer, I have started to move the current code (gionkunz/chartist) to ES2015 hehe :D If you need help, then I can try. I don't have a huge experience in TypeScript, but I think that it's a pretty cool idea. Good thing that if you would switch to Webpack, then you can do switch from ES6 to TS in parts. As Webpack loaders will take care of it.

**Comment by marverix** [comment]
P.S. We can move this conversation to the new repo if you want.

**Comment by gionkunz** [comment]
@marverix Yeah, the new chartist 1.0 repo is still under development and not yet ready to release. So it's still inofficial. However, we should only fix critical bugs in 0.9.x and focus on getting the new version ready. However, there's still a lot to do there. You can checkout the new repo. It's already ported to ES2015 and also some of the underlying core architecture changes are also worked on there.

Yeah, the good thing about TypeScript is that it's 100% ES2015 forward compatible or in other words, you can just run ES2015 code, without type annotations, and it works just nicely. So there's no need to a separate loader in Webpack. The TypeScript loader will be just fine.

**Comment by gionkunz** [comment]
Yeah, let's close this issue and continue there!
