### ISSUE TITLE
chartinst is drawing the series of numbers with two problems

### ISSUE THREAD

**Issue by marcusrogerio** [chartist-js/chartist#1236]
chartinst is drawing the series of numbers with two problems:
1) the numbers are not exactly the ones that are passed by parameter (for example, in the image above, the correct number is 50,  not 52.5
2) the graph is being displayed in reverse, for example, the number 50 is shown above and 100 is shown below

[
<img width="751" alt="Captura de Tela 2020-04-02 às 03 12 20" src="https://user-images.githubusercontent.com/4357020/78216250-c99ee300-748f-11ea-9dc1-0f0c3613db07.png">
](url)

**Comment by gionkunz** [comment]
Please post the code to reproduce the issue.

**Comment by marcusrogerio** [comment]
// Total Transaction
  // -----------------
  var TotalTransactionLine = new Chartist.Line(
      "#total-transaction-line-chart",
      {
    	  series: [[100, 150, 50, 150, 60, 50, 40, 70, 90, 100]]
      },
      {
          chartPadding: 0,
          axisX: {
              showLabel: true,
              showGrid: true
          },
          axisY: {
              showLabel: true,
              showGrid: true,
              low: 0,
              high: 200,
              scaleMinSpace: 40
          },
          lineSmooth: Chartist.Interpolation.simple({
              divisor: 2
          }),
          plugins: [Chartist.plugins.tooltip({ class: "total-transaction-tooltip", appendToBody: true })],
          fullWidth: true
      }
  );

  TotalTransactionLine.on("created", function (data) {
      var defs = data.svg.querySelector("defs") || data.svg.elem("defs");
      defs
          .elem("linearGradient", {
              id: "lineLinearStats",
              x1: 0,
              y1: 0,
              x2: 1,
              y2: 0
          })
          .elem("stop", {
              offset: "0%",
              "stop-color": "rgba(255, 82, 249, 0.1)"
          })
          .parent()
          .elem("stop", {
              offset: "10%",
              "stop-color": "rgba(255, 82, 249, 1)"
          })
          .parent()
          .elem("stop", {
              offset: "30%",
              "stop-color": "rgba(255, 82, 249, 1)"
          })
          .parent()
          .elem("stop", {
              offset: "95%",
              "stop-color": "rgba(133, 3, 168, 1)"
          })
          .parent()
          .elem("stop", {
              offset: "100%",
              "stop-color": "rgba(133, 3, 168, 0.1)"
          });

      return defs;

  }).on("draw", function (data) {
      var circleRadius = 5;
      if (data.type === "point") {
          var circle = new Chartist.Svg("circle", {
              cx: data.x,
              cy: data.y,
              "ct:value": data.y,
              r: circleRadius,
              class: data.value.y === 35 ? "ct-point ct-point-circle" : "ct-point ct-point-circle-transperent"
          });
          data.element.replace(circle);
      }
  });

**Comment by marcusrogerio** [comment]
it was a bug...solved now

if (data.type === "point") {
      var circle = new Chartist.Svg("circle", {
        cx: data.x,
        cy: data.y,
        "ct:value": data.value.y,  // Change here <--------------------------
        r: circleRadius,
        class:
          data.value.y === 35
            ? "ct-point ct-point-circle"
            : "ct-point ct-point-circle-transperent"
      })
      data.element.replace(circle)
    }

**Comment by gionkunz** [comment]
Cool, glad you found the issue
