### ISSUE TITLE
How to add color and its label on side with chart.

### ISSUE THREAD

**Issue by MuzaffarMahmood** [chartist-js/chartist#1246]
Can we do something line this. Both number and percentage inside and labels outside,
![image](https://user-images.githubusercontent.com/18557321/82560630-3fb7f000-9b8b-11ea-8573-781b42c2b85a.png)

**Comment by Arantiryo** [comment]
Hi @MuzaffarMahmood 👋 

Absolutely! You can use `labelInterpolationFnc` function to modify labels inside the chart (here's [an example](https://codesandbox.io/s/github/chartist-js/chartist/main/sandboxes/pie/simple?file=/index.ts:144-165)) and create your own legend outside the chart.
