### ISSUE TITLE
Svg.Path.parse fails on negative values

### ISSUE THREAD

**Issue by hansmaad** [chartist-js/chartist#1248]
Hey Gion,

the `Svg.Path.parse` function fails if the path contains negative values like
```d="M-10,10L-100,-100"```

This line
https://github.com/gionkunz/chartist-js/blob/e7e78201bffe9609915e5e53cfafa29a5d6c49f9/src/scripts/svg-path.js#L192

must probably be changed to
```var chunks = path.replace(/([A-Za-z])(-?[0-9])/g, '$1 $2') ```

**Comment by gionkunz** [comment]
Hi Hannes. Hope youre doing well. Thanks for the bug report. I have not touched Chartist for quite some time since I'm very busy with other things. Would appreciate a PR if you or anyone would have time.
