### ISSUE TITLE
Composite Bar Graph Possible w. Chart.JS ?

### ISSUE THREAD

**Issue by fresh83** [chartist-js/chartist#125]
When I first saw your "Stacked" bar graph I instinctively thought it was a "Composite Bar Graph" , is this possible w. Chartist.js?  http://www.tigerlogic.com/tigerlogic/omnis/developers/images/technews/g2mstackedbargraph.jpg

**Comment by gionkunz** [comment]
Hey there. Yeah thats possible by using the `stackBars` option on bar charts. The scale will automatically be adjusted for the total of all series values for the given data point.

**Comment by fresh83** [comment]
Did you look at the picture I sent? In this graph each bar's height represents a total and inside of each bar are the categories that make up that total sort of like a pie graph inside of each bar in the graph.  If you did understand what I was talking about would you be able to provide some sort of super basic example of this because I am significantly stumped at the moment.

**Comment by gionkunz** [comment]
Yup. Stacked mode is exactly what you're looking for. Just add an other series to this example http://gionkunz.github.io/chartist-js/examples.html#stacked-bar-chart and you have exactly the same as in your picture

**Comment by gionkunz** [comment]
Hi @fresh83 I hope you have resolved your problems with Chartist. If you still need help please feel free to reopen the issue.
