### ISSUE TITLE
classnames inversion issue

### ISSUE THREAD

**Issue by JCL2** [chartist-js/chartist#1250]
Hi,

I'm having the following issue trying to specify the classnames of my series in a bar chart. It seems these classnames are assigned to the wrong series. Any advice on why this happens to me?

Here is the code by which I create the two series specifying 'last' and 'forecast' as classnames:
![image](https://user-images.githubusercontent.com/19490523/83424034-208f4d00-a42c-11ea-95b5-06e75c12c7f4.png)

Here are the elements I obtain on my page:
![image](https://user-images.githubusercontent.com/19490523/83424176-592f2680-a42c-11ea-8e45-6be12d79e6cb.png)

It seems the series classnames have been inverted.

**Comment by Arantiryo** [comment]
Hi @JCL2 👋 

Is the issue still relevant for you?

**Comment by JCL2** [comment]
Hi @Arantiryo ,
Thank you for enquiring!
The issue is not important for me as I switched approach for this particular case. Yet, I think there's a small issue there and if it's fixed one day I'd be happy to know about it.

**Comment by Arantiryo** [comment]
Thank you for the reply!

Looks like it's still there, I was able to reproduce it in [this code sandbox](https://codesandbox.io/s/friendly-dubinsky-u65xjy?file=/index.ts). We'll definetly take a stab at resolving the issue : )

**Comment by JCL2** [comment]
Thank you! Do not hesitate to drop me a message if a fix is done. I'll gladly resume using the library.

**Comment by JCL2** [comment]
thanks, great!
