### ISSUE TITLE
Horizontal bar divisor seems not working

### ISSUE THREAD

**Issue by Morbakos** [chartist-js/chartist#1253]
Hello,

I'm having a problem with horizontal bar graphs. Indeed, I try to have custom graduations (in this case, 6, which are `[0,20,40,60,80,100]`). However, it seems that the `divider` attribute doesn't work, as you can see here: https://jsfiddle.net/morbakos/wvzL6gf4/

Thank you in advance for your response

**Comment by Arantiryo** [comment]
Hi @Morbakos 👋 

Is the issue still relevant for you with the lastest version (`v1.1.2`)?

**Comment by Morbakos** [comment]
hi @Arantiryo 👋 

To be honest, I didn't used the lib since my previous comment, so I don't know :/
