### ISSUE TITLE
Support for a dark theme

### ISSUE THREAD

**Issue by BasilaryGroup** [chartist-js/chartist#1256]
This is one of our client's top requests, a dark theme. We allow our clients to switch between dark and light themes. The dark theme is the most popular for our field users.

Is this feature in the works? Is there a way that I can implement a dark theme?

**Comment by ile** [comment]
You can use CSS. Stylus example:

```stylus
.ct-chart
	background #333

.ct-grid
	stroke rgba(255, 255, 255, .2)

.ct-label
	fill rgba(255, 255, 255, 1)
	color rgba(255, 255, 255, 1)
```
