### ISSUE TITLE
More flexible selector handling

### ISSUE THREAD

**Issue by ilanbiala** [chartist-js/chartist#126]
It would be nice to be able to pass in a jqLite/jQuery selector/element instance in addition to querySelector.

**Comment by gionkunz** [comment]
You can pass a DOM node. `new Chartist.Line($('.my-chart').get(0), ....)`. What exactly are you trying to do?

**Comment by ilanbiala** [comment]
I'm trying to just pass the element argument in the link function of an AngularJS directive (the result of calling `angular.element(selector)`). I don't want to just pass class because what if I have more than one chart on the page.

**Comment by gionkunz** [comment]
Just pass the DOM node to the Chartist constructor instead of a selector query string:

``` javascript
      link: function(scope, element, attr) {
        scope.chart = new Chartist.Line(element[0], {
          labels: ['1', '2', '3', '4'],
          series: [
            [1, 2, 3, 4]
          ]
        });
      }
```

Also, checkout the angular directive by @paradox41 --> https://github.com/paradox41/ng-chartist.js

**Comment by ilanbiala** [comment]
@gionkunz Thanks, that's nice and easy! Quick question, is there any way to center the x-axis labels instead of having them at the beginning? And how can I put a title on/above the graph?
