### ISSUE TITLE
Many labels?

### ISSUE THREAD

**Issue by KevinBurton** [chartist-js/chartist#1263]
Many of  labels on my chart overlap. Is it possible to display the labels on the bottom rotated at an angle so they don't overlap? If so how? Maybe related. Is it possible to display a chart that is wider than the screen essentially automatically adding a scroll for the chart?

**Comment by Arantiryo** [comment]
Hi @KevinBurton 👋 

I'm not sure about rotating the labels, but you can put the chart inside a wrapper with a smaller width and use `overflow-x: scroll;` to view the whole thing.

Here's a [code sandbox](https://codesandbox.io/s/nice-sound-ohghy6?file=/index.html:154-173) with an example.
