### ISSUE TITLE
Stroke width bug when override draw event function in Pie Chart

### ISSUE THREAD

**Issue by ravillarreal** [chartist-js/chartist#1267]
When setting the `donutWidth` parameter to the value 30 the actual stroke-width of the donut is not 30px. Causing the donut expand out of the container div

This happens only when you override the draw event function

https://codepen.io/ravillarreal/pen/dyMWaRd

Try changing the donutWidth option and you'll see the actual stroke-width is incorrect

Of course you could solve this by setting a custom stroke-width inside the draw event like this
```
chart.on('draw', function(context) {
  if (context.type === "slice") {
    context.element.attr({
      style: "stroke-width: 30px;"
    });
  }
})
```

**Comment by dangreen** [comment]
@ravillarreal Hi. 

```js
context.element.attr({
  style: "stroke-linecap: round;"
});
```

By this you are overriding default styles. Extend styles you can by this way:

```js
context.element.getNode().style.strokeLinecap = 'round';
```
