### ISSUE TITLE
Pie chart labels

### ISSUE THREAD

**Issue by khaos13** [chartist-js/chartist#1270]
Pie chart labels don't change with the CSS used for bar charts. I don't see any other CSS to change. I have 2 charts on the same page. The bar chart labels changed with the alpha setting on ct-label and color property.

.ct-label {
  fill: rgba(0, 0, 0, 0.4);
  color: rgba(0, 0, 0, 1);
  font-size: 0.75rem;
  line-height: 1; }

**Comment by Arantiryo** [comment]
Pie chart labels are created with a `text` tag and bar chart labels are created with a `span`. So you need to use `fill` with pie chart labels and `color` with bar chart labels.
