### ISSUE TITLE
How set the color of each point on one line... 

### ISSUE THREAD

**Issue by ZNick86** [chartist-js/chartist#1272]
I need help with your "chartist-js" project. I want to draw a graph as a line with dots, but I need to set the color of each point at the time of drawing.
![Снимок экрана](https://user-images.githubusercontent.com/34825237/99820577-a4afcb00-2b59-11eb-9c3c-0c98d19bcc2a.png)

**Comment by Arantiryo** [comment]
It should be possible by listening to the `draw` event similar to how it's done is [this example](https://codesandbox.io/s/github/chartist-js/chartist/main/sandboxes/line/modify-drawing?file=/index.ts).

**Comment by igorlukanin** [comment]
Also, since Chartist renders chart elements as SVG, it's possible to style everything with CSS.
