### ISSUE TITLE
Multi-line chart click events and sharp edges

### ISSUE THREAD

**Issue by sabithapopuri** [chartist-js/chartist#1273]
Hi I am using chartist-js multi-line chart. For me, the edges of the data points in the graph are not sharp. Is it possible to do that? Also, can we give click events to data points?

<img width="345" alt="Screen Shot 2020-12-01 at 3 34 22 PM" src="https://user-images.githubusercontent.com/42812599/100793816-b2cbda00-33ea-11eb-8f3d-36b8a41b38f1.png">

**Comment by Arantiryo** [comment]
Hi @sabithapopuri 👋 

By listening for draw events that get emitted by the Chartist chart ([example](https://codesandbox.io/s/github/chartist-js/chartist/main/sandboxes/line/modify-drawing?file=/index.ts:182-246)) we can put click events on points when they are being created.
