### ISSUE TITLE
ECMA script module support

### ISSUE THREAD

**Issue by yesparthasarathy** [chartist-js/chartist#1274]
Hi,

We are using the Chartist library in our Angular 10 project. we are getting below error

WARNING in depends on 'chartist'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Can you please make chartist as ECMA module ?

**Comment by technbuzz** [comment]
I thing this is expected in todays days and age. With the like of wepback, parcel and so on we can take the advantage of treeshaking to reduce the bundle.

How you solved your problem. I am just including it the old way by adding it to angular.json?

**Comment by Arantiryo** [comment]
Since version `1.0` Chartist [supports ESM and is tree-shakable](https://github.com/chartist-js/chartist#esm). : )
