### ISSUE TITLE
SVG background color fill issue

### ISSUE THREAD

**Issue by Punitbhardwaj** [chartist-js/chartist#1275]
Hi I am using this Chartist-js , I want to fill the background color as white in donut chart, unable to do this , Please help to customize the chart. like below image
<img width="391" alt="graph" src="https://user-images.githubusercontent.com/20675916/101755181-8bbe8800-3b0f-11eb-9836-f2039e93d646.png">

**Comment by Arantiryo** [comment]
Hello @Punitbhardwaj 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the question is still relevant to you so we can further look into it!
