### ISSUE TITLE
Y axis on right side in Line graph?

### ISSUE THREAD

**Issue by jashsayani** [chartist-js/chartist#1279]
I read the docs and did not see an API to move the Y axis to the right side for a Line graph. My graph looks like this:

<img width="450" alt="Screen Shot 2021-02-13 at 10 49 50 PM" src="https://user-images.githubusercontent.com/18684/107870655-1cd31780-6e4f-11eb-9839-688be1cae0b0.png">

I want to move the Y axis to right, since its more readable (end values matter more)

**Comment by jashsayani** [comment]
This is a dupe of #302 (which was closed)

**Comment by Arantiryo** [comment]
Hi @jashsayani 👋 

This can be achieved with the following option: 
```
axisY: {
  // On the y-axis start means left and end means right
  position: 'end'
}
```

A [code sandbox](https://codesandbox.io/s/github/chartist-js/chartist/main/sandboxes/bar/label-position?file=/index.ts:360-456) with an example.
