### ISSUE TITLE
Getting TypeError when using the code with

### ISSUE THREAD

**Issue by shkesar** [chartist-js/chartist#128]
This is running under **Safari** :
[Error] TypeError: null is not an object (evaluating 'container.querySelector')
- createSvg (chartist.js, line 188)
- createChart (chartist.js, line 1905)
- initialize (chartist.js, line 1145)
- initialize ([native code], line 0)

```
var draw = function (name) {
    // clean everything from parent tag
    $("#graph").empty();

    new Chartist.Line('#chart', {
        labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        series: [
            [2, 3, 2, 4, 5],
            [0, 2.5, 3, 2, 3],
            [1, 2, 2.5, 3.5, 4]
        ]
    }, {
        width: 320,
        height: 240
    });
};

var setEvents = function () {
    $("#controls").find("button").click(function() {
        var name = $(this).html().toLowerCase();

        console.log(name + " button clicked");
        draw(name);
    })
};

window.onload = setEvents();
```

The code is the simple example I found on the smashing magazine site. It just seemingly doesn't work along bootstrap.
The HTML code is also very simple. Take a look [here](http://pastebin.com/2VZqvAVH)

The error seems to be internal to the library. It requires a lot of tracing calls. It'd be simpler if I get some help here.

**Comment by gionkunz** [comment]
Hey there. The problem is that chartist cant find any element matching `#chart`. After the call `$("#graph").empty();` the containing div is removed from the DOM.

**Comment by shkesar** [comment]
Now I feel like stupid. -_-
Thanks for making me feel like one.
