### ISSUE TITLE
Update data removing old ones

### ISSUE THREAD

**Issue by PietroMB** [chartist-js/chartist#1281]
Hi, I need to change dynamically the data inside the chart, I've read on the old issue but no solution worked to me.
I don't care if I must delete all chart and rebuild or perform an update of the data (performance in this project are not important) but I need a way to show different data (from same table) by year, month, day.
here what I've done, but it have no effect

`      function MyChart(element, labels,dataNum){

      var ctx = document.getElementById(element).getContext("2d");

      var gradientStroke = ctx.createLinearGradient(0, 230, 0, 50);

      gradientStroke.addColorStop(1, 'rgba(72,72,176,0.2)');
      gradientStroke.addColorStop(0.2, 'rgba(72,72,176,0.3)');
      gradientStroke.addColorStop(0, 'rgba(119,52,169,0.1)'); //purple colors

      var data = {
      // labels: ['1', '2', '3', '4', '5', '6'],
      labels: labels,
      datasets: [{
        label: "Profit",
        fill: true,
        backgroundColor: gradientStroke,
        borderColor: '#d048b6',
        borderWidth: 1,
        borderDash: [],
        showArea: true,
        borderDashOffset: 0.0,
        pointBackgroundColor: '#d048b6',
        pointBorderColor: 'rgba(255,255,255,0)',
        pointHoverBackgroundColor: '#d048b6',
        pointBorderWidth: 0,
        pointHoverRadius: 0,
        pointHoverBorderWidth: 0,
        pointRadius: 2,
        // data: [80, 100, 70, 80, 120, 80],
        data: dataNum.map(Number),
      }]
    };

      if (myChart != '') {
        myChart.update(data,gradientChartOptionsConfigurationWithTooltipPurple,true);
        alert(data.labels);
      }else{
        myChart = new Chart(ctx, {
          type: 'line',
          data: data,
          options: gradientChartOptionsConfigurationWithTooltipPurple
        });
      }
    }` 

thx

**Comment by Arantiryo** [comment]
Hi @PietroMB!

[Update function](https://gionkunz.github.io/chartist-js/api-documentation.html#chartistbase-function-update) should work just fine for your use case. Please take a look at [a code sandbox](https://codesandbox.io/s/relaxed-elion-u8be6q?file=/index.ts) with a simple example.
