### ISSUE TITLE
Linear Regression / Trendline Support?

### ISSUE THREAD

**Issue by nicmare** [chartist-js/chartist#1284]
i build this scatter graph chart with chartist:
![image](https://user-images.githubusercontent.com/898582/114558096-9f6b2e00-9c6a-11eb-9549-df48b429a85e.png)
now i would like to show a linear trend line like:
![image](https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F3%2F3a%2FLinear_regression.svg%2F1200px-Linear_regression.svg.png)

anyone have an idea how to achieve this? my code for the points is based on this syntax:
{x:1602827212, y:43.9582}

**Comment by Arantiryo** [comment]
Unfortunately multitype charts are not supported as of right now.
