### ISSUE TITLE
Legend with name, data elements problems

### ISSUE THREAD

**Issue by karassik** [chartist-js/chartist#129]
I had followed your previous instructions on adding a legend with pie graphs using one dimensional label and data arrays, but add I added a name, data call-out I am having much more difficulty.

Here is my current object:
data = {
            labels: ['mailed', 'new', 'received', 'problem'],
            series: [
                {
                    name: "mailed",
                    data: 20
                },
                {
                    name: "new",
                    data: 30
                },
                {
                    name: "received",
                    data: 30
                },
                {
                    name: "problem",
                    data: 10
                }
            ]
        };

previously I used:
var listItem = $('<li />')
          .addClass('ct-series-' + i)
         .html('<strong>' + val + '</strong>: ' + data.series[i] )
        .appendTo(legend);

but now I'm trying to iterate through the object with:
for(d in data){...}
series is an auto incrementing array, so it is difficult to gather the underlying elements unless I go through many nests.  Is there a better way to setup the data.series?

**Comment by gionkunz** [comment]
Hey there. Can you describe exactly what you'd like to achieve? Cheers

**Comment by karassik** [comment]
I was hoping for a function like d3;  
d3.select("#test2")
      .datum(data)
which can then be called like so:
var parentCategory = d.data.name;
It would be nice to some consistent way to deal with the data.

**Comment by gionkunz** [comment]
I'm still not 100% sure what you'd like to achieve. If you want to get the series name of a specific data element you can rely on the custom NS attribute that gets written when you use the object notation in the data series. 

For example you could iterate over your lines on a line chart and get the values and series names:

``` javascript
$('#mychart .ct-line').each(function() {
  var seriesName = $(this).closest('.ct-series').attr('ct:series-name'),
      value = $(this).attr('ct:values');
});
```

**Comment by gionkunz** [comment]
Hey there @karassik ! I'll close this issue for now as I'm going through my scheduled cleanup minutes :-) If you're having more input we can discuss further and you can re-open the ticket.
