### ISSUE TITLE
Can't get ct-bar to gradient

### ISSUE THREAD

**Issue by lurchinms** [chartist-js/chartist#1293]
.gradient-bar-chart .ct-series-a .ct-bar {
  stroke: url(#gradient-b) !important;
  stroke-width: 15px;
}

 <linearGradient id="gradient-b" x2="0%" y2="100%">
                              <stop offset="0%" stop-color="#20F381" />
                              <stop offset="100%" stop-color="transparent" />
                            </linearGradient>
                          </defs>
                        </svg>
                        </svg><div class="gradient-bar-chart" id="chartStatsHashRatePool"></div>

Any help would be appreciated.

**Comment by lurchinms** [comment]
<linearGradient id="gradient-b" x2="0%" y2="100%">
                              <stop offset="0%" stop-color="#20F381" />
                              <stop offset="100%" stop-color="transparent" />
                            </linearGradient>
                          </defs>
                        </svg>
                        </svg><div class="gradient-bar-chart" id="chartStatsHashRatePool"></div>

**Comment by Arantiryo** [comment]
Hi @lurchinms 👋 

Not sure if it's still relevant but here's [a code pen](https://codepen.io/junglist/pen/MbPgXd) with a line chart using gradient `fill`.
