### ISSUE TITLE
Add demo page to the gh-page with examples of how to use Chartist

### ISSUE THREAD

**Issue by gionkunz** [chartist-js/chartist#13]

**Comment by phun** [comment]
I'll take a look at this!

How will the demo page work? Would there be a "View Demo" button that would open a new tab with the demo?

**Comment by gionkunz** [comment]
Hi there

Great that you'd like to pick this up! Are you more excited about creating the demo examples or about the presentation of the examples? Because for the presentations I kind of have a fixed idea of using an on page edit mode that does open a ace editor with the Chartist color theme and when you type it will eval the example displayed on the side :-) 

I believe that the demo page is probably the most important page both from a UX and from a learning perspective, that's why I'd like to put some effort to this and build a live coding experience into the page.

If you don't mind I'd like to take over the part of how to present the examples, and you can go ahead and create some examples (maybe put them as Gists initially so we can comment / collaborate there?).

If you had other ideas for the presentation on the doc site please let me know.

Cheers
Gion

**Comment by phun** [comment]
For sure! I'll wait until you have it done.

**Comment by gionkunz** [comment]
@phun now you can go ahead and add examples :smile: Put them into the examples folder and then you can just add them to the yml file https://github.com/gionkunz/chartist-js/blob/develop/source/site/data/pages/examples.yml 

This Handlebar partial https://github.com/gionkunz/chartist-js/blob/develop/source/site/partials/live-example.hbs picks the data and generates example charts using the serialized example. The partial is using a helper to get the content <id>.js from the example folder.

Have fun creating demos! :-)

Cheers
GIon

**Comment by gionkunz** [comment]
@phun, I'm closing this issue. If you find time, please go ahead and add examples. I've already put a few examples there.

Cheers
Gion
