### ISSUE TITLE
Bar chart not properly rendering data

### ISSUE THREAD

**Issue by bsgbryan** [chartist-js/chartist#130]
I have an angular app and am using the `highcharts-ng` wrapper. I can successfully display pie charts with the library - and those charts update correctly as data changes.

I have an issue with bar charts, however. I have a module, shown below:

``` coffeescript
angular
  .module 'ada'
  .controller 'EntitiesController', ($scope, socket) ->
    $scope.total      = 10
    $scope.sentiments =
      labels: [ ]
      series: [ ]
    $scope.options =
      low: -10
      high: 10

    socket.wait_for_connection()
      .then (api) ->
        $scope.$watch 'total', (new_val) ->
          if new_val?
            api.get_extremes 10, (sentiments) ->
              keys   = [ ]
              values = [ ]

              sentiments.forEach (extreme, i) ->
                keys.push   extreme.entity
                values.push parseFloat extreme.sentiment

              $scope.sentiments =
                labels: keys
                series: values

              $scope.options.low  = values[0]
              $scope.options.high = values[values.length - 1]

              $scope.$apply()
```

The html associated with this code is:

``` html
<div class="row stats text-center">
  <div class="container-fluid col-xs-12 col-sm-6">
    <h3 class="col-xs-12">Extreme Sentiments</h3>
    <div chartist id="exteme-sentiments" 
      class="col-xs-12 ct-chart ct-major-twelfth" 
      chartist-data="sentiments" 
      chartist-chart-options="options"
      chartist-chart-type="Bar"></div>
  </div>
</div>
```

This matches the $scope.sentiments property to the chart data and the $scope.options to the chart options as well as specifying the chart type (Bar).

Everything in this code works correctly except that the bars do not show up in the chart - the labels and low/high values update correctly. The series values are floats. I have tried both with and without the `$scope.$apply()` (I realize this is an angular specific item, I just mention it for completeness).

I have validated that sentiments.series gets properly updated with data, the updated data just isn't being displayed in the chart.

I'm happy to look into this myself, I just don't know where to start. Any help would be greatly appreciated.

Thanks!

**Comment by gionkunz** [comment]
Assuming that you're using the angular-chartist module ( https://github.com/paradox41/ng-chartist.js ). Did you already posted your issue there? Of course I could take a look here but I think you should first post it there because there is a chance this issue is related to the chartist angular wrapper and not to the Chartist library itself. Thanks for your understanding.

Cheers
Gion

**Comment by gionkunz** [comment]
If you have more information and you know that it's related to an issue with Chartist feel free to re-open the issue.
