### ISSUE TITLE
Not an issue - but a forum for Chartist would be great

### ISSUE THREAD

**Issue by VJPandaAU** [chartist-js/chartist#1303]
As a chartist noob, there doesn't seem to be a place to ask questions or find shared knowledge.  Or am I missing something?

**Comment by Arantiryo** [comment]
Hi @xxxmicrobexxx 👋 

It's not exactly a forum but if you have a question please feel free to ask in [Cube's dataviz Slack channel](https://cube-js.slack.com/archives/C028FM9CJ85)!

**Comment by gionkunz** [comment]
Or you just use the Github discussions we recently added https://github.com/chartist-js/chartist/discussions
