### ISSUE TITLE
Change division signs in _chartist-settings.scss

### ISSUE THREAD

**Issue by Dimple-Balchandani** [chartist-js/chartist#1308]
[ERROR] DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
[ERROR] 
[ERROR] Recommendation: math.div(15, 16) or calc(15 / 16)
[ERROR] 
[ERROR] More info and automated migrator: https://sass-lang.com/d/slash-div
[ERROR] 
[ERROR]   ╷
[ERROR] 2 │ $ct-scales: ((1), (15/16), (8/9), (5/6), (4/5), (3/4), (2/3), (5/8), (1/1.618), (3/5), (9/16), (8/15), (1/2), (2/5), (3/8), (1/3), (1/4)) !default;
[ERROR]   │                    ^^^^^
[ERROR]   ╵
[ERROR]     node_modules/chartist/dist/scss/settings/_chartist-settings.scss 2:20  @import

**Comment by Arantiryo** [comment]
Hi @Dimple-Balchandani!

Is the issue still relevant for you with the latest version (`v1.1.2`)?
