### ISSUE TITLE
White line in stackBars

### ISSUE THREAD

**Issue by alejandrovasta** [chartist-js/chartist#1309]
Hey! do you know why I see this white line in between the stacked bars? it's like a glitch, not sure if it is related to the tool, or something wrong with my browser / graphics. If you know how I could fix it great. Thanks in advance. 

<img width="198" alt="image" src="https://user-images.githubusercontent.com/1189543/159979150-8549a662-2856-4044-a92b-c0f6f8defdd3.png">

**Comment by Arantiryo** [comment]
Hi @alejandrovasta 👋 

Should be fixed in the latest version. Here'a a [code sandbox](https://codesandbox.io/s/github/chartist-js/chartist/main/sandboxes/bar/stacked) with an example.
