### ISSUE TITLE
Just wanted to say thanks!

### ISSUE THREAD

**Issue by sridhar2014** [chartist-js/chartist#131]
Chartist is an awesome piece of work - very well thought out and designed. Thanks so much for building it and making it available!

**Comment by shuklaalok7** [comment]
Hey @sridhar2014, I appreciate that you like the idea and went ahead to thank the contributors. I also am feeling thankful to the Chartist guys but please don't use Issue tracker to say thanks. Use Twitter or any other channel, that's more helpful, cleaner, and appreciable.

**Comment by gionkunz** [comment]
@sridhar2014 Thanks a lot for your kind words :-) Much appreciated!
