### ISSUE TITLE
Are there any actively maintained forks?

### ISSUE THREAD

**Issue by MattApril** [chartist-js/chartist#1310]
Unfortunately, the original maintainer appears to be MIA for many years now. Does anyone know of any actively maintained forks?

**Comment by lgommans** [comment]
Among [repository forks](https://github.com/gionkunz/chartist-js/network), some that stand out to me as having more than one extra commit on top of master:

- https://github.com/hilarycheng/chartist-js
- https://github.com/crisp-dev/chartist-js
- https://github.com/sailfish-app/chartist-js (this seems the most promising one, accepted a couple PRs and the only one to at least update the readme: https://github.com/sailfish-app/chartist-js/commit/0962137bfd0bc58d052b26e9f4eada575e830944)
- https://github.com/SectorLabs/chartist-trends (also a number of commits, but not up-to-date with master)

**Comment by MattApril** [comment]
> Among [repository forks](https://github.com/gionkunz/chartist-js/network), some that stand out to me as having more than one extra commit on top of master:

Awesome thanks! I've never seen that Netowrk Graph before.

**Comment by Arantiryo** [comment]
This library is being actively maintained again and a major version `v1.0.0` was [recently released](https://github.com/chartist-js/chartist/releases/tag/v1.0.0). Please feel free to check it out : )

**Comment by MattApril** [comment]
That's excellent news, thanks!

**Comment by jrochkind** [comment]
Current updates?  Looks like maybe the active maintanance revival was short-lived? 

This is a really nice package!
