### ISSUE TITLE
overlap stackBars hides bars

### ISSUE THREAD

**Issue by alejandrovasta** [chartist-js/chartist#1312]
Hey Guys! when configuring the bar chart with stack bars and overlap, it hides bars, should not them be displayed in a specific order? 🤔 

<img width="262" alt="image" src="https://user-images.githubusercontent.com/1189543/162632543-3d3d57c5-9331-4e71-b089-a6f7476f5c11.png">

any idea how to fix it?

**Comment by Arantiryo** [comment]
Hi @alejandrovasta 👋 

Is the issue still relevant for you with the latest version (`v1.1.2`)?
