### ISSUE TITLE
How to create pie donut chart

### ISSUE THREAD

**Issue by ayoubkhan558** [chartist-js/chartist#1320]
How to create a chart like this and define its colors.
![image](https://user-images.githubusercontent.com/99708427/178939628-ef219b1e-60d3-44d0-891d-bd93714fdc13.png)

**Comment by Arantiryo** [comment]
Hi @ayoubkhan558 👋 

Please take a look at this [code sandbox](https://codesandbox.io/s/github/chartist-js/chartist/main/sandboxes/pie/donut-chart) with a donut chart example.

**Comment by ayoubkhan558** [comment]
> Hi @ayoubkhan558
> 
> Please take a look at this [code sandbox](https://codesandbox.io/s/github/chartist-js/chartist/main/sandboxes/pie/donut-chart) with a donut chart example.

Yes its good. How we can add a text in center?

**Comment by Arantiryo** [comment]
I don't think there's a built it option for that but you could use an `:after` pseudo-element to display text over the chart. I've put together a small example to demonstrate: https://codesandbox.io/s/elegant-tesla-cygizr?file=/style.css
