### ISSUE TITLE
Ability to add arbitrary labels.

### ISSUE THREAD

**Issue by Timmmm** [chartist-js/chartist#133]
It would be great if you could do something like this:

```
        Chartist.createLabel(lineChart.svg, "A Label", {
                x: p.x,
                y: p.y,
                transform: "rotate(-90, " + p.x + ", " + p.y + ")"
            }, '', false);
```

Which... you can! But it's not very obvious and calculating what x and y should be is extremely difficult because the data x,y -> pixel x,y mapping is not stored anywhere (it is only calculated when the chart is first made and then `bounds`, `chartRect` etc. are discarded).

I have managed to recreate `bounds` and `chartRect` like this (fortunately I know my data is always 0-1.

```
    lineChart = new Chartist.Line(chart, data.Curves, options);

    bounds = Chartist.getBounds(this.svg, { low: 0, high: 1 }, lineChart.options);
    chartRect = Chartist.createChartRect(this.svg, lineChart.options);
```

However the mapping is still very complicated because even `bounds` does not store the minimum and maximum X values of the axes.

**Comment by gionkunz** [comment]
Have you tried to use the draw events?

**Comment by gionkunz** [comment]
Can you tell me what youd like to achieve?

**Comment by gionkunz** [comment]
Hey @Timmmm is this still an issue? If yes please re-open the ticket and update it. Cheers Gion

**Comment by Timmmm** [comment]
Hi, yeah sorry I didn't notice the email from github. Still an issue. I'd like to achieve something like this:

![capture](https://cloud.githubusercontent.com/assets/376842/5695049/cc293be4-9983-11e4-95a5-d15c8c739628.PNG)

Where the label positions are specified in terms of the X-axis and Y-axis positions.

I haven't tried the draw events - I'm not really sure how they work. Is there documentation or an example?

Thanks!

**Comment by gionkunz** [comment]
Yeah unfortunately we currently lack a bit in documenting events and providing examples. There are a few examples if you check the example page e.g. http://gionkunz.github.io/chartist-js/examples.html#using-events-to-replace-graphics but generally this topic needs to be more documented. This should be covered with #90 .

I've implemented your example with the draw events with this code:

``` javascript
var chart = new Chartist.Line('.ct-chart', {
  labels: [1, 2, 3, 4, 5],
  series: [
    [4, 3, 6, 5, 3]
  ]
}, {
  low: 0,
  high: 10,
  fullWidth: true,
  axisX: {
    showGrid: false
  }
});

var customLabels = [];
customLabels[1] = 'A custom label';
customLabels[3] = 'An other one';

chart.on('draw', function(data) {
  if(data.type === 'point' && customLabels[data.index]) {

    data.group.elem('text', {
      x: data.x + 10,
      y: data.y + 5,
      transform: 'rotate(-90, ' + data.x + ', ' + data.y + ')'
    }, 'ct-label').text(customLabels[data.index]);
  }
});
```

You can find the running example on JSBin http://jsbin.com/qehecegolu/1/edit?html,js,output

Cheers
Gion

**Comment by Timmmm** [comment]
Thanks, that does the job, though it isn't quite as simple as I would have liked. In my case I actually get the X value where the label should go separately from the series data so I will have to manually find the nearest point... My data is like this:

```
// Because I have lots of data, most of my labels are NaN (or null or whatever).
// It seems like this kind of use isn't really what chartist is designed for.
var xlabels: [NaN, NaN, NaN........... 1, NaN, NaN, NaN, ...... 2, NaN, NaN, NaN, ...... 3];
var series: [ <lots of data> ]
// I want to label the series at their maximum point (they are bell curves)
var seriesLabels: ['series 1 max', 'series 2 max', etc.]
// These are the x locations of the labels. The y location is constant (1).
var seriesLabelXLocations: [1.45, 4.67, etc.]
```

It would be really nice if you just expose a function that maps chart X, Y points to the SVG X, Y points. Maybe that doesn't fit with your design though. Thanks for the help anyway!

**Comment by gionkunz** [comment]
Hey there. After the chart is rendered there is a `created` event emitted: https://github.com/gionkunz/chartist-js/blob/develop/src/scripts/charts/line.js#L230-L235

You can use the data to call `Chartist.projectLength` https://github.com/gionkunz/chartist-js/blob/develop/src/scripts/core.js#L254-L257. This is for the Y axis only though as X axis is not plotted but a step mechanism.

Maybe that helps a bit

Cheers
Gion

**Comment by logitimate** [comment]
is there a way to do this for bar charts on data.series? I was trying to get this to work to append labels but it's putting the labels on each data.group instead of data.series.

**Comment by gionkunz** [comment]
Hi there. This updated version works for bars and lines: http://jsbin.com/repesu/1/edit?js,output

Cheers
Gion

**Comment by viswanathmantri** [comment]
Hi my Chartist number of curves is limited to 3 curves, How can i increase it to n number of curves in a Graph Chart

**Comment by xblabs** [comment]
@gionkunz would something like these static labels be possible with a draw event and data group add construct? : 
![image](https://user-images.githubusercontent.com/556578/68261965-af282100-0039-11ea-8648-bcd4ddb62b06.png)
