### ISSUE TITLE
[Bug]: `bower install` no longer working with chartist

### ISSUE THREAD

**Issue by gorner** [chartist-js/chartist#1344]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

**Expected behaviour:** Running `bower install` in a project that depends on `"chartist": "~0.9.8"` and/or `"chartist-plugin-tooltip": "~0.0.15"` installs the packages properly.

**Actual behaviour:**

Following the relocation of Chartist to a new GitHub location and replacement of the old one with a README, we now get this result in CI:

```
bower ENORESTARGET  No tag found that was able to satisfy ~0.9.8

Additional error details:
No versions found in https://github.com/gionkunz/chartist-js.git
```

I've tried replacing the Chartist entry with `"chartist": "chartist-js/chartist#v0.9.8"` however since we're also using [chartist-plugin-tooltip](https://github.com/tmmdata/chartist-plugin-tooltip) that also fails:

```
bower chartist#v0.9.8           cached https://github.com/chartist-js/chartist.git#0.9.8
bower chartist#v0.9.8         validate 0.9.8 against https://github.com/chartist-js/chartist.git#v0.9.8
bower chartist#~0.9.4           cached https://github.com/gionkunz/chartist-js.git#0.9.8
bower chartist#~0.9.4         validate 0.9.8 against https://github.com/gionkunz/chartist-js.git#~0.9.4
bower chartist#~0.9.4     ENORESTARGET No tag found that was able to satisfy ~0.9.4

Additional error details:
No versions found in https://github.com/gionkunz/chartist-js.git
```

And it does not appear there is any way to have Bower force packages to accept other dependencies (I saw something about a `resolutions` option in bower.json but that did not seem to help).

### Reproduction

Please see above

### Chartist version

v0.9.8

### Possible solution

Long term, our team's project should stop using Bower which is [deprecated](https://bower.io/docs/creating-packages/#deprecated). 😛 (We only use it currently for packages referenced by certain older parts of our codebase we haven't needed to touch in a while.)

Short term, the maintainers would have to update the Bower package location, and if they are able to do so it'd be much appreciated.

Alternatively, we could (and probably will for now) fork chartist-plugin-tooltip in order to work around this by specifying the new GitHub location in its bower.json file.

**Comment by dangreen** [comment]
@gorner Hi. Maybe npm resolver will help you ?

https://www.npmjs.com/package/bower-npm-resolver

**Comment by gorner** [comment]
@dangreen Hi, thanks for the suggestion. I tried installing that and using the suggested syntax and got the message `ENOTFOUND Package npm:chartist not found` despite that package being [registered](https://www.npmjs.com/package/chartist) on npm.

Again, as noted above, specifying `chartist-js/chartist#v0.9.8` to use the GitHub resolution seems to work fine in terms of direct use in our own project. The problem was that the **plugin's** bower.json was still referring to the default Bower resolution in the old (wrong) location, causing a conflict – adding a different resolver unfortunately doesn't override this.

We've since found that one of our other bower dependencies has several chartist plugins as sub-dependencies, each of which would have to be forked separately in order to work around this issue if the maintainers can't update the Bower setting. (**Edit**: we've since realized these are actually devDependencies of chartist itself, which we were eventually able to work around by removing bower_components and running `bower install -p`, though it's possible the removal is more important than the `-p` for this.)

**Comment by gionkunz** [comment]
Maybe we can write back the latest release of 0.x chartist to the old repo (gionkunz/chartist-js) master branch to fix those issues?

**Comment by gionkunz** [comment]
Okay, I have just merged the latest commit and all the history of the 0.x version back into gionkunz/chartist-js. I've also pushed all tags of previous versions to prevent any further issues with direct dependents which are in maintenance mode. Let me know if that helps.

**Comment by jbtule** [comment]
Can't say if it helps, because I already spent the day switching chartist to be installed with libman from unpkg, instead of bower, across all our projects, which involved a day of work, but now I can start using libman incrementally for all our bower dependencies, so probably a step in the right direction.

**Comment by jbtule** [comment]
I take that back we had some open PRs that hadn't updated from main and they are building again without modification, so I'd say that it is fixed.

**Comment by gorner** [comment]
Can confirm that the issue appears to be fixed with our previous bower.json. Thanks, @gionkunz. Will close this issue.
