### ISSUE TITLE
[Bug]:  SASS styling no longer available

### ISSUE THREAD

**Issue by yohny** [chartist-js/chartist#1355]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

version `1.x.` of chartist no longer contains .scss files to style the charts, yet the documentation still mentiones it (https://gionkunz.github.io/chartist-js/getting-started.html#the-sass-way)

### Reproduction

install chartist 1.1.2 and observe the missing .scss files

### Chartist version

1.1.2

### Possible solution

include scss settings files in a package

**Comment by dangreen** [comment]
@yohny Hi. On that site, there is the banner

> This is the documentation of Chartist v0.11
> We now recommend using [Chartist v1](https://github.com/chartist-js/chartist#readme) instead!

**Comment by yohny** [comment]
hmm, I dont see any banner (on that site or on root page)
still havinng the .scss included in the package would make styling a lot easier and the scss files are present in this repo, so they just need to be included in package to support the sass way of styling,, no?

**Comment by yohny** [comment]
ok, I opened the page in incognito and now i saw a small message in the corner about doc being for v0.11, but once you close it you never see it again 😄

**Comment by dangreen** [comment]
@yohny Would you please describe your case, why you need precisely SCSS and just CSS doesn't suit you?

**Comment by yohny** [comment]
it makes integration in projects that already use sass more inlined, you can go sass all the way
it also allows to define your own series naming (and their corresponing colors)

**Comment by rockwood** [comment]
We're relying on the chartist scss variables for styles ($ct-line-width, $ct-series-colors, ect). We'd like to keep this behavior post 1.0.

**Comment by gionkunz** [comment]
I think this is a valid use-case. Also, chartist provides all the mixins to generate your own CSS within an existing Sass project. We should also enable this in >1.0

**Comment by dangreen** [comment]
Released in [v1.2.0](https://github.com/chartist-js/chartist/releases/tag/v1.2.0)

https://unpkg.com/browse/chartist@1.2.0/dist/index.scss
