### ISSUE TITLE
Pie chart labels

### ISSUE THREAD

**Issue by ilanbiala** [chartist-js/chartist#136]
It would be cool if I could assign the label of each section to be something other than the data.

**Comment by gionkunz** [comment]
You can do so by using the `labels` in your data object right? That's how it's done in the examples on the Chartist site. Are you looking for something else?

**Comment by ilanbiala** [comment]
That seems to work, but what is the function in the custom label pie chart example doing?

**Comment by gionkunz** [comment]
Im not sure what function youre talking about but you probably mean the `labelInterpolationFnc` ? Thats for interpolating the label string or even replace it with something else. Can be very handy when you do responsive configuration overrides. Ill close this issue now. If you have other questions please use a different issue or if youre unclear about setting labels still just reopen the issue.
