### ISSUE TITLE
Please provide a `dist` folder at the root of the repository

### ISSUE THREAD

**Issue by davidbgk** [chartist-js/chartist#1361]
### Would you like to work on this feature?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### What problem are you trying to solve?

The old repository/version had that and it was really useful to be able to copy two files and get a graph displayed. Especially for educational purpose but also for small/static experiments when you don't want to depend on node+npm, etc.

### Describe the solution you'd like

Integrate a way during the build/release process to commit the latest version of the package at the root of the repository.

### Describe alternatives you've considered

Go grab it from unpkg or similar. Maybe grab it from the (future) documentation website if not minified…

**Comment by dangreen** [comment]
@davidbgk Hi. You can grab it from unpkg: https://unpkg.com/chartist
