### ISSUE TITLE
Font size too small

### ISSUE THREAD

**Issue by ilanbiala** [chartist-js/chartist#137]
My pie chart renders like this:
![capture](https://cloud.githubusercontent.com/assets/3695164/5684671/b0715942-9800-11e4-8378-8ee361268a02.PNG)
How can I make the text more proportionately sized and easier to read?

**Comment by gionkunz** [comment]
The chart is in your DOM and you can adjust font size with regular CSS.

**Comment by ilanbiala** [comment]
@gionkunz that's definitely possible, but how come the font size is so disproportionately small on my site compared to on the chartist demo site? Is the font size not relative to the graph size? I would think that should be the default case, no?

**Comment by gionkunz** [comment]
@ilanbiala All labels in Chartist have `0.75rem` by default. Whats your root element font size? Probably you're using `10px` as `1rem` ? If you're using the Sass version of Chartist just change `$ct-text-size` to something else than `0.75rem`. Otherwise just override the `font-size` in CSS.

**Comment by ilanbiala** [comment]
I think it was 16px. Does it make sense to change it to em so that it's relative to fonts in the SVG?

**Comment by gionkunz** [comment]
Sure you can use `em` in your project if your like but I don't really like them and would prefer `rem` in the default setting in the Chartist settings Sass file. `em`s are very hard to trace and build up dependencies to parent elements which can lead to weird things. Sometimes it makes sense but personally I find them useless specially when you'd like to enforce a strict type size policy with a fixed set of type sizes.

**Comment by ilanbiala** [comment]
Can you define font size on SVG in px and build on that with em?

**Comment by gionkunz** [comment]
Yes you could do that in your project easily. Just set a font-size on the svg to pixel and the label font-size to em. However, the library should probably continue to use REM. Relative font sizes became less important as they are all about accessibility when a user resizes the base font size. However, all modern browsers (even not so modern) promote a zoom function which is not operating on base font size but on CSS pixel. So even if you use px in your CSS youd still be fine. There anly very few users that rely on changing the base font size.

In chartist the decision to use REM for text label sizes was simply to get a relative font-size that matches the design of the site its used in. If there is a site with 13px base font size the labels will also be styled relative to this. If its 16px or 18px it will be relative to this.

I dont really want to overcomplicate this.

Im closing this issue now and if you have any other concerns please let me know.

**Comment by ilanbiala** [comment]
@gionkunz to fix keeping it consistent, can't we set the svg font size to 1em and build off that? I'm not trying to overcomplicate it either, but I think it could be much better, no?

**Comment by gionkunz** [comment]
You mean 1rem? Setting an element to font-size 1em is kind of dead code :-)

**Comment by ilanbiala** [comment]
Yeah sorry 1rem, that seems to have the most advantages and fewest disadvantages, no?
