### ISSUE TITLE
[Bug]: package.json: conflict between `puppeteer` and `@storybook/addon-storyshots-puppeteer`

### ISSUE THREAD

**Issue by mayorovad** [chartist-js/chartist#1372]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

Hi! 

When running `npm install` on 164e7657d58bc247d567d3601fa6bf01f0141d81 there is error:

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @storybook/addon-storyshots-puppeteer@6.5.13
npm ERR! Found: puppeteer@14.4.1
npm ERR! node_modules/puppeteer
npm ERR!   dev puppeteer@"^14.0.0" from the root project
npm ERR!   peer puppeteer@">=1.10.0 <= 18" from @axe-core/puppeteer@4.5.0
npm ERR!   node_modules/@axe-core/puppeteer
npm ERR!     node_modules/@storybook/addon-storyshots-puppeteer
npm ERR!       dev @storybook/addon-storyshots-puppeteer@"^6.4.22" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! node_modules/@storybook/addon-storyshots-puppeteer
npm ERR!   dev @storybook/addon-storyshots-puppeteer@"^6.4.22" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: puppeteer@3.3.0
npm ERR! node_modules/puppeteer
npm ERR!   peerOptional puppeteer@"^2.0.0 || ^3.0.0" from @storybook/addon-storyshots-puppeteer@6.5.13
npm ERR!   node_modules/@storybook/addon-storyshots-puppeteer
npm ERR!     dev @storybook/addon-storyshots-puppeteer@"^6.4.22" from the root project
```

## Problem

It's seems that `puppeteer` version in [package.json](url) is `^14.0.0`, but in [`@storybook/addon-storyshots-puppeteer@6.5.13`](https://github.com/storybookjs/storybook/blob/19a6e89dc170d9b7ab5aba4d74e29e5d7a40b4e2/code/addons/storyshots/storyshots-puppeteer/package.json#L44) it is `^2.0.0 || ^3.0.0`, which results in conflict.

### Reproduction

run `npm install` (Windows 10, powershell, NodeJS v16.15.0, npm 8.5.5)

### Chartist version

v1.2.1

### Possible solution

- Talk with `@storybook/addon-storyshots-puppeteer` on bumping to newer version of `puppeteer`
- Downgrade to `puppeteer@^3.0.0`
- Get rid of `@storybook/addon-storyshots-puppeteer` dep 😄

**Comment by dangreen** [comment]
@mayorovad Hi. Please use pnpm if you want start dev environment.
