### ISSUE TITLE
precompiled releases again like before

### ISSUE THREAD

**Issue by bobmagicii** [chartist-js/chartist#1388]
### Would you like to work on this feature?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### What problem are you trying to solve?

A long time ago Chartist used to be get the JS/CSS and go. Is it possible to get there again?

We are not a JS shop. NPM install fails on our local machines with puppetmaster things with the latest release on Github here as of this posting. Servers demand three full screens of node packages to install NPM, which I don't want to do since it doesn't compile on my local machine anyway. PNPM install instructions (copy pasting a command into admin powershell) also fail on Windows.

Primary requirement in our evaluations is just, can it load via ES6 modules, because as I said, not a JS shop. I know I am a moron but I am not this big of a moron. Getting roadblocked every which way.

### Describe the solution you'd like

a `dist` folder in the releases

### Describe alternatives you've considered

installing npm on a server i dont care about
![image](https://user-images.githubusercontent.com/881944/202827586-18474b81-15b4-4a14-8279-632bae562199.png)
![image](https://user-images.githubusercontent.com/881944/202827945-993480cb-6504-4f42-90c7-1b2a3852ab61.png)

downloading release from github and compiling it in vscode. starting with npm install.
![image](https://user-images.githubusercontent.com/881944/202827699-632b30e7-0fc0-4566-9e14-9559c3ded004.png)

f7 in vs code, also installing pnpm copying their 1 line install for windows.
![image](https://user-images.githubusercontent.com/881944/202827775-52aeb83c-392a-4a30-b12a-8adcdf067fcf.png)

also tried yarn like your readme suggested but i don't want to talk about that.

**Comment by bobmagicii** [comment]
the only reason im so adamant about this is

![image](https://user-images.githubusercontent.com/881944/202828381-63f1ee68-b2cc-466d-b235-f460ad1bac54.png)

i miss this lol

**Comment by dangreen** [comment]
@bobmagicii Hi. You can use unpkg for it:

https://unpkg.com/chartist@1.3.0/dist/index.umd.js
https://unpkg.com/chartist@1.3.0/dist/index.css

**Comment by bobmagicii** [comment]
Ah, OK, cheers yeah that is fine.

I would only still persist the original request because just having it would be *nice*.

Originally how I fell down this path of pain was the home page download button currently goes to this 404: https://github.com/gionkunz/chartist-js/tree/develop/dist

Then I got crafty "ok ill get it from github releases" which the repo button on the home page takes you to the legacy repo: https://github.com/gionkunz/chartist-js

An then all my pain above. So it was really a terrible day all around.

There is something weird to me about JS people in that the JS ecosystem just never works for me and makes me cry and stuff. But when they release dists we can get along well enough.
