### ISSUE TITLE
Line Charts with missing data

### ISSUE THREAD

**Issue by oliveraustria** [chartist-js/chartist#139]
Hi,

first of all, I really like your approach of a chart library, specially because of the usage of open standards and functionality on different devices!

I am working at a line chart with three lines, however there is not always a data point for all at the same time:

```
var data = {
     labels: ['Week1', 'Week2', 'Week3', 'Week4', 'Week5', 'Week6'],
        series: [
            [1, 2, 3, 4, 5, 6],
            [3, 3, 3, 3, 3, 3],
            [6, 4, , /* missing data */, 0, 0]
         ]
};
new Chartist.Line('.ct-chart', data);
```

Is there a way that the missing data point will be interpolated to 2?

I tried "", false, null but nothing works.

Thanks a lot,
Oliver

**Comment by gionkunz** [comment]
Hey there. Chartist currently only supports step based Charts where each step has a valid data value. There is no such thing as missing data, data gaps and interpolation. However, I believe this would be a nice case for writing a plugin that can handle that http://gionkunz.github.io/chartist-js/plugins.html

**Comment by oliveraustria** [comment]
Hi,

I was trying to use your new data event, but something is wrong here.

That is the source file with your new event, right?
https://raw.githubusercontent.com/gionkunz/chartist-js/develop/dist/chartist.min.js

That is the syntax, how it should work, right?

```
var chart = new Chartist.Line('.ct-chart', data);
chart.on("data", function(d) {
    console.debug(d);
});
```

Thanks,
Oliver

**Comment by gionkunz** [comment]
Actually there is a bug #159 :(  I'll publish a fix release soon

**Comment by gionkunz** [comment]
Okay, 0.6.1 is released and #159 is fixed.

**Comment by glauberramos** [comment]
@gionkunz is there a way of currently handling missing points in the data for a line chart? I tried null, undefined, '' and 0. Nothing really works.

**Comment by gionkunz** [comment]
@glauberramos , There isn't yet but I'd appreciate a plugin for this.

**Comment by oliveraustria** [comment]
Hi,

here my first approach of the plugin for that (and my first github project :) ).

https://github.com/oliveraustria/chartist-plugin-missing-data

There is one big issue, I can include missing data points by calculation their values. However, I also want to handle missing data points at the begin and end, which means that I have to short the line.

```
chart.on('draw', function(data) {
   if(data.type == "line"){
     data.element.changePointsofLine ....
   }
});
```

Has someone a hint for me? :)

**Comment by gionkunz** [comment]
Path manipulation is nasty to do manually. You'd need to parse the SVG string and do the modifications manually. We have created #173 for this issue. Unfortunately I can't come up with an other idea to implement this right now. Maybe an additional event that allows modification at this point https://github.com/gionkunz/chartist-js/blob/develop/src/scripts/charts/line.js#L218 exposing the `pathCoordinates` array for modification would also help to do the job.

**Comment by baks** [comment]
Maybe option to solve this problem is using chart handling points xy-based and proper Axis.

**Comment by oliveraustria** [comment]
Thank you very much for for extensions in #173 ! But I don't get it. :) How do I remove for example the first point of a path?

```
chart.on('draw', function(data) {
  if(data.type == "line"){

     data.path.remove(1);
     data.path.position(0).remove(1);
     data.element.replace(data.path.clone().position(0).remove(1));
  }
});
```

None of this code really works. Could you give me a small hint? ;)

Thanks, 
Oliver

**Comment by oliveraustria** [comment]
@gionkunz Do you help out? :) Thanks!!! Oliver

**Comment by gionkunz** [comment]
@oliveraustria sorry I missed to write you back :(

The SVG path is constructed like this: MOVE > LINE > LINE > LINE .....

In order to remove the first "point" in the line one cannot simply remove the first element in the path. You need to remove the first element (which is the move) and "convert" the second element (the line / or curve if the path was smoothed) to a MOVE element. 

Also the path in data is a clone of the original path to protect the internals of Chartist. In order to replace the drawn path of element you also need to update the d (path description) attribute of the path element.

http://jsbin.com/feyegi/1/edit?js,output

**Comment by markcell** [comment]
I used [chartist-plugin-missing-data](https://github.com/oliveraustria/chartist-plugin-missing-data) to make a line chart with two series, the one with missing points only with the points.

Example: http://jsbin.com/yovibutehi/2/edit?css,js,output

I edited [chartist-plugin-missing-data](https://github.com/oliveraustria/chartist-plugin-missing-data) because the chart was wrong when resize the window:

``` js
// Data points have to be removed
if (!options.showMissingDataPoints) {
    var pointLineIndex = -1;

    chart.on('draw', function(data) { 
        // ADDED THIS QUICK FIX BECAUSE THE "pointLineIndex" NEED TO RESET ON "draw" EVENT
        if (data.type === 'grid' && data.index === 0) {
            pointLineIndex = -1;
        }

        if (data.type === 'point') {                 
            if (data.index === 0) {
                pointLineIndex++;
            } 

            // TODO store missingData in DOM to have access during resize

            if (typeof (missingData) !== 'undefined') {
                if (missingData[pointLineIndex][data.index]) {
                    data.element.remove();
                }
            }
        }
    });
}
```

**Comment by markcell** [comment]
I also noticed that the plugin is also to return some errors always passing on `chart.on('data', function (data) {});`.

For the case that exposed the above, I changed all null values for the minimum value that exists in both series. But the tooltips failed to work on some points.

**Comment by gionkunz** [comment]
Also you should make use of the `created` event of Chartist to reset the index.

**Comment by oliveraustria** [comment]
Hi,

I did some updates for the plugins: index calculation(more stable for window resizing) and line adoption.

Please find some examples here: http://oliveraustria.github.io/chartist-plugin-missing-data/

Feedback is more than welcome! ;)

**Comment by markcell** [comment]
It works well, but fails to show the tooltip at some points. That is what happened when I made the following changes:

"I also noticed that the plugin is also to return some errors always passing on chart.on('data', function (data) {});.

For the case that exposed the above, I changed all null values for the minimum value that exists in both series. But the tooltips failed to work on some points."

**Comment by oliveraustria** [comment]
Hi,

thanks for your feedback:

1.) In which browser do you get errors?
2.) Can you post a sample to describe your issues?

Thanks,
Oliver

**Comment by markcell** [comment]
With the changes that you made already there are no such errors. Only the tooltips do not appear in some points.

PS: I copied the previous topic text. Sorry for the confusion :).

**Comment by Globegitter** [comment]
@oliveraustria thank you for that plugin that has been really useful for me! Could you maybe add this to the official list of chartist plugins? Would make it much easier to find!

**Comment by gionkunz** [comment]
@oliveraustria would be awesome if you could do a PR to add it to the site! I'm closing this issue for now.

**Comment by oliveraustria** [comment]
Hi, thank you guys for your nice words! I was quite over challenged with my workload and diploma thesis, however I love to put the plugin on the official list this weekend and manage to do necessary changes with needed.

Thanks a lot/Dankeschön,
Oliver
