### ISSUE TITLE
[Bug]: old website linked in repo

### ISSUE THREAD

**Issue by jdanyow** [chartist-js/chartist#1398]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

![CleanShot 2023-02-12 at 14 23 50@2x](https://user-images.githubusercontent.com/1306747/218340945-48808b37-980a-4ced-860b-280eb21b058f.png)

Should be https://chartist.dev

### Reproduction

https://github.com/chartist-js/chartist

### Chartist version

v1

**Comment by gionkunz** [comment]
Thanks, fixed it ;-)
