### ISSUE TITLE
[Bug]: Pulling from CDN gives latest 0.x.x version

### ISSUE THREAD

**Issue by KevinMongiello** [chartist-js/chartist#1404]
### Current and expected behavior

I would expect a version available from CDN for latest V1+

### Reproduction

n/a

### Chartist version

v0.11.x

**Comment by gionkunz** [comment]
Hi, which CDN are you referring to? Cheers

**Comment by KevinMongiello** [comment]
Hi,  I am using  `cdn.jsdelivr.net`

Best, Kevin

**Edit:** To add more context, I am trying to use this lib without npm / any framework (React, etc)

**Comment by gionkunz** [comment]
Can you give the exact url your using?

You could use https://cdn.jsdelivr.net/npm/chartist or https://unpkg.com/chartist for using the global / UMD package.

Cheers
Gion

**Comment by KevinMongiello** [comment]
I am using `https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.js` referenced from the old docs.

The links you sent work.  It would be great to add the new docs. Thanks for your help!

Best,
Kevin
