### ISSUE TITLE
Ploat x and y axis line instead of grid

### ISSUE THREAD

**Issue by ashishsharma2** [chartist-js/chartist#144]
Hi,
I am trying to draw line on X and Y axis instead of Grid (Rectangle) ..
I have applied showGrid: false , but it's removed all the line ...so which method or DOM i will need to use. Share some dummy code.
Below is my requirement. 
Thanks
Ashish

|
|
|
|
|

**Comment by gionkunz** [comment]
Are you talking about the grid line styles? You're looking for a method to make the grid lines as solid lines instead of dashed?

**Comment by ashishsharma2** [comment]
Thanks Gion, Yes line style and also i want only x and y axis line instead of grid(Rectangular) below is the requirement ... only 2 line x and y axis no extra line. show when we are doing showGrid:true it's show in grid format and when we do false it's remove all line. But my requirment is to show x axis Horizontal line and y axis vertical line ...  
|
|
|
|_____________

**Comment by gionkunz** [comment]
Hey @ashish20040076 thanks for the detailed description. All style relevant things are customizable via CSS. You can remove the dashed line style by removing the `stroke-dasharray` settings:

``` css
.ct-chart .ct-grid {
  stroke-dasharray: none;
}
```

There is no option that allows you to remove the grid lines but keep an axis line, but you can make use of the Chartist `draw` events to achieve this. The following code removes all other grid lines but the first of each axis:

``` javascript
chart.on('draw', function(data) {
  if(data.type === 'grid' && data.index !== 0) {
    data.element.remove();
  }
});
```

Please find the full example in this JSBin: http://jsbin.com/xuyiregeqa/1/edit?css,js,output

Cheers
Gion

**Comment by gionkunz** [comment]
I'm closing this issue, if my answer did not resolve your issue please re-open the task.

**Comment by NegoL** [comment]
@gionkunz 
The solution does not work if there a negative values. 
Then the X-axis is at the bottom but should stay at 0.
Any idea how to handle that?

**Comment by NegoL** [comment]
Solved it:

```
chart.on( 'created', function( context ) {
         // Adding X-Axis
         var targetLineY = projectY(context, 0);
         context.svg.elem('line', {
                          x1: context.chartRect.x1,
                          x2: context.chartRect.x2,
                          y1: targetLineY,
                          y2: targetLineY }, 'x-axis');
});

function projectY( context, value ) {
   return context.chartRect.height() - context.axisY.projectValue(value) + context.chartRect.y2;
}
```

This will also work when there are negative numbers in chart, and you want the x-axis at 0.

**Comment by Neuro-Dynamics** [comment]
The posted solution still does not work. 

There is no way to leave the axis without a grid for a chart with negative values? 

This seems like very basic functionality.

**Comment by henriquezago** [comment]
> The posted solution still does not work.
> 
> There is no way to leave the axis without a grid for a chart with negative values?
> 
> This seems like very basic functionality.

I completely agree with you.
On the website you see `HIGHLY CUSTOMIZABLE RESPONSIVE CHARTS`
But you can't simply change the grid design to a simple axis line.

**Comment by henriquezago** [comment]
Can this issue be reopened?
Since the posted "solution" is basically a hack that doesn't solve the problem.

**Comment by 1pavanb** [comment]
Hey bro

Here's the solution

    <style>
        .ct-vertical {
            stroke-dasharray: 0px;
            stroke: black;
        }
        .ct-vertical~.ct-vertical {
            display: none;
        }
        .ct-horizontal {
            stroke-dasharray: 10px;
            stroke: black;
        }
        .ct-horizontal~.ct-horizontal {
            display: none;
        }
    </style>

I've tested this out below with an example I found on chartist

    <!DOCTYPE html>
    <html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
        <script src="https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
        <style>
            .ct-vertical {
                stroke-dasharray: 0px;
                stroke: black;
            }
            .ct-vertical~.ct-vertical {
                display: none;
            }
            .ct-horizontal {
                stroke-dasharray: 10px;
                stroke: black;
            }
            .ct-horizontal~.ct-horizontal {
                display: none;
            }
        </style>
    </head>
    <body>
        <div class="ct-chart ct-golden-section"></div>
        <script>
            new Chartist.Line('.ct-chart', {
                labels: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
                series: [
                    [12, 9, 7, 8, 5],
                    [2, 1, 3.5, 7, 3],
                    [1, 3, 4, 5, 6]
                ]
            }, {
                fullWidth: true,
                chartPadding: {
                    right: 40
                }
            });
        </script>
    </body>
    </html>
