### ISSUE TITLE
How to show a gauge chart?

### ISSUE THREAD

**Issue by sridhar2014** [chartist-js/chartist#145]
I'm looking for ways to approximate gauge charts, perhaps [something like this chart](http://docs.oracle.com/cd/E23943_01/bi.1111/e22254/img/xdo11g_le_gauge_ex1.gif). I'd appreciate any ideas on how to approach this. Thanks!

**Comment by danieldiekmeier** [comment]
There is a simple gauge chart here: http://gionkunz.github.io/chartist-js/examples.html#gauge-chart

You can get closer to what you seem to want with this code (just click on "Edit Example" and paste):

```
new Chartist.Pie('.ct-chart', {
  series: [20, 10, 30, 40]
}, {
  donut: true,
  donutWidth: 60,
  startAngle: 248,
  total: 160,
  showLabel: true,
  labelOffset: -50
});
```

You could then add the pointer line yourself, maybe with a HTML/SVG element, rotated depending on some value.

**Comment by gionkunz** [comment]
Thanks @danieldiekmeier ! @sridhar2014 , please re-open the issue if you need more help.

**Comment by SiddiquiImran** [comment]
Hi @gionkunz ,

What are the usage of these parameters:
donutWidth
startAngle
total
