### ISSUE TITLE
Updating options

### ISSUE THREAD

**Issue by 4lexsky** [chartist-js/chartist#148]
I am trying to update my chart's options using `update()` and it doesn't seem to work. I could not find indications about this in the doc. 

Here's what I tried : 

```
// Define chart
var theChart = new Chartist.Line('.ct-chart', theData,options);

// Later, on some event
var updateChart = function(data){
    theChart.data = data;
    if(data.labels.length > 32){
        // first method
        theChart.options.showGrid = false;
        theChart.options.showLabel = false;
        // second method
        theChart.optionsProvider.currentOptions.showGrid = false;
        theChart.optionsProvider.currentOptions.showLabel = false;
    }
    theChart.update();
}
```

The data updates, but not the options.
Any ideas?

**Comment by gionkunz** [comment]
Hey there! This will come into the next release and was implemented with https://github.com/gionkunz/chartist-js/pull/134

**Comment by gionkunz** [comment]
FYI, Chartist 0.6.0 is out and contains this feature.

**Comment by 4lexsky** [comment]
Great! Thank you for the follow up.

**Comment by salampv** [comment]
Hey,

is the data object contains both labels and series?
is it working with your above code?

Thanks 
AS
