### ISSUE TITLE
Missing comma in API docs

### ISSUE THREAD

**Issue by mcmadafly** [chartist-js/chartist#15]
On http://gionkunz.github.io/chartist-js/api-documentation.html#method-chartistline

labelInterpolationFnc: function(value){return value;} should be labelInterpolationFnc: function(value){return value;},

**Comment by phun** [comment]
Nice catch! It is the one in `axisY` and not `axisX` btw.

**Comment by mcmadafly** [comment]
:+1:

**Comment by gionkunz** [comment]
Your scanning skills are amazing @mccombs :-) thanks for pointing out and thanks for the PR @phun.

**Comment by gionkunz** [comment]
That's fixed thanks to you guys! Latest build has been pushed to gh-pages.
