### ISSUE TITLE
There is a way to get the x axis value of a point with line chart ?

### ISSUE THREAD

**Issue by Raphy** [chartist-js/chartist#151]
Hi,

First, thanks a lot for your beautiful project !

I'm wondering if there is a way to get the x axis label where a ct:point is located in ?
I'm using the line chart with tooltips for each point. The documentation shows how to get the y axis value and the serie name but I'm looking for the x axis value.

Here an example of what I'm looking for.
I don't know what to write in `'???'` 

``` javascript
$chart.on('mouseenter', '.ct-point', function() {
    var point = $(this),
        value = point.attr('ct:value'),
        seriesName = point.parent().attr('ct:series-name')
        x_axis_value = '???';
    $toolTip.html(seriesName + '<br>' + x_axis_value + ' = ' + value).show();
});
```

Thanks for the help !

**Comment by gionkunz** [comment]
Hey there! Thanks for the kind words :-) By x_axis_value do you refer to the label used on the x-axis?

**Comment by Raphy** [comment]
Yes, I'm refering to the label used on x-axis.

Here an example of my data 

``` javascript
var data = {
    labels: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    series: [
        {
            name: 'Views the last week',
            data: [123, 100, 150, 200, 50, 70, 142]
        }
};
```

According to my previous snippet, the tool tip html content for the first point (on Monday) would be :

``` html
Views the last week<br/>Monday = 123
```

Hope you understand what I'm looking for and it's possible !

**Comment by gionkunz** [comment]
@Raphy you can now use the meta data feature included in 0.6.0 for this.

``` javascript
var data = {
    labels: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    series: [
        {
            name: 'Views the last week',
            data: [
              {value: 123, meta: 'Monday'},
              {value: 100, meta: 'Tuesday'},
              {value: 150, meta: 'Wednesday'},
              {value: 123, meta: 'Thursday'},
              {value: 123, meta: 'Friday'},
              {value: 123, meta: 'Saturday'},
              {value: 123, meta: 'Sunday'}
            ]
        }
};
```

There will be an additional `ct:meta` attribute on the points of line charts or on the bars of bar charts. You can also add the whole tooltip text to the meta property. It also accepts objects / complex types. Objects will be serialized and need to be deserialized when you read them from the attributes with http://gionkunz.github.io/chartist-js/api-documentation.html#chartistcore-method-deserialize

Hope this helps.
Cheers
Gion

**Comment by Raphy** [comment]
Perfect, thank you a lot !

**Comment by rjcrystal** [comment]
Thanks a lot man, really love chartist

**Comment by kross-aeg** [comment]
I know this is closed, but is there a way to do this if you are unable to add meta to the data series? I'm handling an object that I can't alter and it's coming to me where key/value = x lables/point values.

`const chart{{ $id }} = new Chartist.Line('#{{ $id }}', {
                          labels: {!! json_encode($hours) !!},
                          series: [
                            {
                              name: 'audience by time',
                              data: {!! json_encode($values) !!}
                            }
                          ]
                        }`
