### ISSUE TITLE
Multiple charts on web page

### ISSUE THREAD

**Issue by michaelferrell** [chartist-js/chartist#152]
I'm having a hard time figuring out how to create multiple charts on one web page.  I can create one chart but anything after that doesn't work.  Is there a special way to do this?

**Comment by gionkunz** [comment]
Just give your containers ID's and then when initializing Chartist use the ID selector instead of the class selector with `.ct-chart` 

Check this simple JSBin: http://jsbin.com/vuwazo/1/edit?html,js,output

**Comment by michaelferrell** [comment]
Thanks a bunch!  I had a feeling it was going to be something super easy.  Looked all throughout your docs and didn't see any examples of charts using ID's when instantiating Chartist.  Most of your demos use the `.ct-chart` class.  Would be rad if the getting started page explained that when instantiating Chartist, the first param could be any class or ID name, not just `.ct-chart`.

**Comment by gionkunz** [comment]
sure, you're very welcome :-) I'll include a note in the getting started page!

**Comment by nicholasalanbrown** [comment]
I also need to create several charts on the same page, but when I try invoking an ID per the gauge chart example:

```
new Chartist.Pie('#chart1', {
  series: [20, 10, 30, 40]
}, {
  donut: true,
  donutWidth: 60,
  startAngle: 270,
  total: 200,
  showLabel: false
});
```

the chart renders completely garbled. It looks fine if I use the original class example (i.e. ('.ct-chart'). I've tested this just using one chart at a time. Any idea what the issue might be?

**Comment by gionkunz** [comment]
There is an example for multiple charts on one page now on the getting started page http://gionkunz.github.io/chartist-js/getting-started.html. Let me know if that helps. Cheers gion
