### ISSUE TITLE
jQuery "dependency"

### ISSUE THREAD

**Issue by zettadam** [chartist-js/chartist#156]
Perhaps this is a tiny point, but I believe it would make things clearer for newcomers to state somewhere in the docs that jQuery is used as dependency in some examples to achieve additional functionality. In response to a previous issue you wrote that other DOM manipulation libraries could be used. That's fair, but making it explicit would make documentation even better.

**Comment by gionkunz** [comment]
But the only example which uses jQuery is the tooltip example if I'm not mistaken right?

**Comment by zettadam** [comment]
Yes, I believe it is the tooltip example... for now :)

**Comment by gionkunz** [comment]
As this sentence "This example shows you how you can easily build a tool tip on top of Chartist using jQuery and some basic styling." is clear enough that jQuery is only used in the example (getting started page) I think we are fine.
