### ISSUE TITLE
Cannot have more labels than values

### ISSUE THREAD

**Issue by tylergaw** [chartist-js/chartist#161]
I'm not 100% sure if this is a bug or intended. That title says it, if the `data.labels` array has a greater length than any of the `data.series[x]` arrays there will be an Uncaught TypeError: `Cannot read property 'meta' of undefined`. That happens at about line 157 of line.js (if using a line chart). I haven't tested this will other chart types.

To illustrate further. Here is an example of the data that will cause the error:

``` javascript
 var data = {
      labels: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
      series: [
        [5, 2, 4, 2, 0]
      ]
    };
```

and a working example at http://jsbin.com/gejusi/1/edit?html,output

**Comment by tylergaw** [comment]
I'm running into this because I am creating the data.series from JSON response from a service. The labels I am generating as well, but I generate a fixed number. Sometimes the series arrays are less than the fixed number of labels.

**Comment by tylergaw** [comment]
Looking at this a bit further. This issue was introduced in `0.6.0`, I'm testing with `0.5.0` and this does not happen. In `0.5.0` the length of each series array is increased to match the length of the labels array.

The lines where the error happens look like they were added here https://github.com/gionkunz/chartist-js/commit/6cc473964e46ab979579d2dab6a95474af658dc5

**Comment by gionkunz** [comment]
Hey @tylergaw , that's clearly a bug introduced with 0.6.0. Thanks for the detailed report. This shouldn't be too hard to fix.

**Comment by tylergaw** [comment]
Nice! :+1:
