### ISSUE TITLE
How can insert two charts in the same document?

### ISSUE THREAD

**Issue by soniasjc** [chartist-js/chartist#162]
Hi, I am working/testing with Chartist. I am not a javascript expert, and I don't know how modify the code for have some charts in the same document. Could you saw an example? 

Thank you so much.

**Comment by baks** [comment]
Hi,

There is simple example how you can insert two charts : http://jsbin.com/lojawonete/1/edit?html,js,output

You need different div's for every single chart and every div must have unique id or class name.
Then you pass that id/class name to chart constructor.
'.ct-chart' class is used to style chart and is defined in chartist.min.css

**Comment by soniasjc** [comment]
Thank you.

**Comment by gionkunz** [comment]
Thanks @baks ! :+1:
