### ISSUE TITLE
XML Namespace xmlns:ct does not exist

### ISSUE THREAD

**Issue by niutech** [chartist-js/chartist#164]
Chartist is using an XML Namespace `<svg xmlns:ct="http://gionkunz.github.com/chartist-js/ct">` in rendered SVG, but the URL does not exist.

Also, according to the [SVG spec](http://www.w3.org/TR/SVG11/), "an SVG namespace declaration must be provided so that all SVG elements are identified as belonging to the SVG namespace." So please add `<svg xmlns="http://www.w3.org/2000/svg">`

**Comment by gionkunz** [comment]
Hi There. An XML namespace must be a URI but does not necessarily point to a real page that provides scheme infomation. http://www.w3.org/TR/xml-names/#ns-decl

Also modern browsers dont require the SVG namespace to be declared explicitly. This might be true for XHTML but an HTML parser knows a set of elements and their attributes and can decide on the namespace HTML, SVG or MathML. As long as there are no name clashes there is no value in providing the xmlns of default HTML5 elements (including SVG and MathML)

**Comment by niutech** [comment]
Ok, thanks for the explanation.
