### ISSUE TITLE
Refactor axis creation and coordinate projection for line and bar chart

### ISSUE THREAD

**Issue by gionkunz** [chartist-js/chartist#165]
Currently the line and bar chart have a relatively static way of how they create X and Y axis where X was always a step based axis and Y the axis that was constructed with the values and an order of magnitude linear scale. In order to make this more dynamic we should refactor the code and solve this problem more abstract.

This should include:
- Abstraction layer for axis that allows to implement different Axis / Scale types
- Each axis is responsible to project values in it's own dimension
- Order of magnitude and the value bounds (currently composite of the Chart) should be part of one specific axis (linear oom axis)
- Currently there are two individual functions for creating X and Y labels and grid lines. This should be unified with one function

If we do this correctly we should be able to implement #64 quite easily and also #26 shouldn't be too much code overhead.

**Comment by p5150j** [comment]
:thumbsup:
