### ISSUE TITLE
Wrong elements order in a SVG

### ISSUE THREAD

**Issue by TheGP** [chartist-js/chartist#167]
Labels goes behind graph lines:
https://www.evernote.com/shard/s247/sh/7cfed10e-ad76-4590-8152-19fa00c95a18/eddc09213b4f49fdb8bfcd8eeb0f260c

Current elements order in SVG is:
ct-labels, ct-grids, ct-series

In order to fix the problem order has to be:
ct-grids, ct-series, ct-labels (labels el at the end)

Or in the beginning of the month, when current data is 0 it will be always such problem.

**Comment by gionkunz** [comment]
Hmmm.. This one depends on how you prioritize the drawing order right. Maybe some people see the visibility of the line as more critical as the visibility of the labels. I guess it could be implemented easily by changing the group order of to: grids, area, line, point, labels

Let me think about this a bit more.

**Comment by gionkunz** [comment]
We can't easily change the order now and this would be a major change to the pipeline. Also you can use the xAxis offset or the simple smoothing that will never span over the chart grid. I'll close this issue, but if you still find issues with those approaches feel free to re-open.
