### ISSUE TITLE
Chart is not rendered in hidden elements

### ISSUE THREAD

**Issue by rolandschuetz** [chartist-js/chartist#169]
Hello,

a chart is not rendered correctly into hidden elements. My use case would be a tab panel. How can I fix that? Here's a [minimal test case](http://rolandschuetz.at/docs/chartist-js.html):

```
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
        <script src="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
        <style>
            .wrapper {
                border: 1px solid black;
                padding: 10px;
                margin: 10px;
            }
            #hidden {
                display: none;
            }
        </style>
    </head>
    <body>
        <div class="wrapper">
            This one is displayed right away
            <div class="ct-chart ct-chart-1"></div>
        </div>
        <div class="wrapper" id="hidden">
            This one appears later, and doesn't display the chart
            <div class="ct-chart ct-chart-2"></div>
        </div>
        <script>
        new Chartist.Bar('.ct-chart-1', {
            labels: ['Jan', 'Feb', 'Mar', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
            series: [
                [5, 4, 3, 7, 5, 10, 3, 4, 8, 10, 6, 8]
            ]
        });
        new Chartist.Bar('.ct-chart-2', {
            labels: ['Jan', 'Feb', 'Mar', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
            series: [
                [5, 4, 3, 7, 5, 10, 3, 4, 8, 10, 6, 8]
            ]
        });

        setTimeout(function() {
            document.getElementById('hidden').id = "display"
        }, 2000);
    </script>
</html>
```

**Comment by gionkunz** [comment]
Hi @rolandschuetz , Chartist needs some client rect information in order to render correctly. This is not provided for DOM elements underneath hidden DOM elements. If you have initialized charts siting in hidden parts of your web page, you need to trigger an update after un-hiding this content:

`document.querySelector('.ct-chart-2').__chartist__.update();`

I've posted your example with this code into JSBin http://jsbin.com/towaz/1/edit

**Comment by gionkunz** [comment]
This was also discussed here: #119

**Comment by gionkunz** [comment]
btw. changing the ID of an element in JavaScript feels like a transgender surgery.

**Comment by rolandschuetz** [comment]
I would NEVER use something like that in a real code, I was just to lazy to use querySelector or include jQuery, so I used an id selector.

This is a real problem, since that requires tight coupling between the tab panel logic and the content chart.

Is there a way to define a width and height so that the chart renders correctly in hidden elements?

**Comment by gionkunz** [comment]
Phew, I almost thought... poor little div :laughing: 

Well I don't think this is a problem at all. All tabs I know spit out events when they got activated and there's where you can inject your logic to update other components. If done with pub / sub style this is perfectly fine.

You could also set the width and height on your chart but then the whole responsive Idea of Chartist gets lost. For this specify a width and height property in your chart options.

**Comment by rolandschuetz** [comment]
I'm getting the right size via DOM traversal and and update on resize. Thanks for pointing me to the right place!
