### ISSUE TITLE
0.6.0 milestone still open

### ISSUE THREAD

**Issue by ilanbiala** [chartist-js/chartist#171]
0.6.1 was already released, so the 0.6.0 milestone can be closed or removed, no?

**Comment by gionkunz** [comment]
yes true :-)

**Comment by ilanbiala** [comment]
Is the next release going to be 1.0.0 or another in between?

**Comment by gionkunz** [comment]
There will be releases in between. 1.0.0 should also include progressive data updates where we aim for virtual DOM in the SVG library to increase performance. This takes time and needs to be approached once the core is stable again after the axes update.
