### ISSUE TITLE
Using metadata structure, a value of zero (as an int) is NaN

### ISSUE THREAD

**Issue by tylergaw** [chartist-js/chartist#172]
If you change the structure of the data to account for metadata as explained in https://github.com/gionkunz/chartist-js/issues/151#issuecomment-70418888 and any of the `value`s are zero as an int `0` it will cause the chart to break and JS errors to ensue.

Here's an example:
http://jsbin.com/kesosu/1/edit?html,output

If you use zero as a string `"0"` things work as expected.

**Comment by gionkunz** [comment]
Thanks @tylergaw ! Will check this bug on the weekend.

**Comment by gionkunz** [comment]
Thanks for the test data :-)

![image](https://cloud.githubusercontent.com/assets/2203704/5988984/b936d5ec-a977-11e4-934e-89aacf935457.png)

Fixed the issue now and it will come with 0.7.0 this weekend.
Cheers
