### ISSUE TITLE
Possible to pass an object for the data?

### ISSUE THREAD

**Issue by hitfactory** [chartist-js/chartist#174]
For example, 

``` javascript
new Chartist.Line('.ct-chart', {
  labels: ['1', '2'],
  series: [
    {
      name: 'Lorem ipsum',
      data: [
        {
          name: 'First value',
          value: [7]
        },
        {
          name: 'Second value',
          value: [4]
        }
      ]
    }
  ]
});
```

In my use case, I am wanting to use the 'First value', 'Second value' text as tooltips for each point.

Is the recommended solution here to use a separate data object to store my custom data and pass only the values to Chartist?

**Comment by gionkunz** [comment]
Hey there. Yes you can use the series object notation and add meta data to your chart. Here is an example: http://jsbin.com/kivole/1/edit?js,output

**Comment by hitfactory** [comment]
Sweet as! Thanks for the quick response and awesome library.

**Comment by gionkunz** [comment]
No worries glad it helped!
