### ISSUE TITLE
Chartist.Axis undefined in v0.7.0

### ISSUE THREAD

**Issue by martinsznapka** [chartist-js/chartist#176]
Chartist v0.7.0 is broken:
Cannot read property 'units' of undefined: Chartist.Axis.units.x (line 2282)

**Comment by gionkunz** [comment]
Crap :-) somehow I didnt commit my task file and the test site is including all files manually... Ill push a new release right now

**Comment by martinsznapka** [comment]
That was fast, thx ;)

**Comment by gionkunz** [comment]
Ok master is updated with v0.7.1 and so is NPM and bower. The CDN will be up to date soon. Thanks for pointing out!
