### ISSUE TITLE
ct-point first & last

### ISSUE THREAD

**Issue by martinsznapka** [chartist-js/chartist#177]
Hi Gion
I have idea for small enhancement:
Would be nice if first and last ct-point from serie contains some marker "first" or "last".

I implemented Bootstrap tooltips (http://goo.gl/ss1tG2) for Chartist diagrams (later I can share) and for first ct-point is good to use "right" tooltip and for last one "left".

Currently I have to add some marker (class) manualy:

``` javascript
chart.on('created', function() {
    chartElement.find('.ct-point:first').get(0).classList.add('first');
    chartElement.find('.ct-point:last').get(0).classList.add('last');
});
```

**Comment by gionkunz** [comment]
I agree this could be useful. Do you only use this for behaviour and not for styling right? For styling you could also use `-of-type` like here: http://jsbin.com/fopefo/1/edit?css,output

**Comment by martinsznapka** [comment]
Yes, for behaviour. Something like this:

``` javascript
var direction, left, top;
if(pointClassList.contains('first')) {
    direction = 'right';
    left = pointPosition.left + 10;
    top = pointPosition.top - toolTip.height() / 2;
}
else if(pointClassList.contains('last')) {
    direction = 'left';
    left = pointPosition.left - toolTip.width() - 20;
    top = pointPosition.top - toolTip.height() / 2;
}
else {
    direction = 'top';
    left = pointPosition.left - toolTip.width() / 2;
    top = pointPosition.top - toolTip.height() - 20;
}
```

**Comment by martinsznapka** [comment]
In case of big points density the 2nd and 3rd point also have to have tooltip direction right.
So this enhancement is useless, I solve it differently.

**Comment by gionkunz** [comment]
Maybe you should determine the tooltip direction with a mouse position detection altogether?
