### ISSUE TITLE
lineSmooth function

### ISSUE THREAD

**Issue by martinsznapka** [chartist-js/chartist#178]
Hi Gion
I have issue with lineSmooth - in some cases the line goes to values which are senseless.
F.e. you have number of sold products and values bellow zero are incorrect.

I know I can turn this feature off, but our previous charting library (Morris.js) could handle it in nice way (red is Chartist.js, blue Morris.js).

Maybe we can have more spline functions in Chartist options.

![diagrams](https://cloud.githubusercontent.com/assets/4278972/5999134/156675ae-aacf-11e4-9f80-1a1f2e20f176.png)

**Comment by gionkunz** [comment]
Hey thanks for the issue! We already have an open issue with this #92 / #155 and we are currently trying out different spline algorithms. Feel free to provide more research. I believe the example with mirror.js is using http://en.wikipedia.org/wiki/Monotone_cubic_interpolation

**Comment by gionkunz** [comment]
I'll close this issue in favor of the other one. Please post further comments there. Cheers
