### ISSUE TITLE
Creating options to allow full chart width to be used

### ISSUE THREAD

**Issue by brenwell** [chartist-js/chartist#18]
Hey nice lib, I have a question. Is there anyway to make a line graph fill the full width of the chart?

Here is a pic of my graph.

![screen shot 2014-09-01 at 14 28 57](https://cloud.githubusercontent.com/assets/802618/4108195/93dbaf28-31d3-11e4-9c25-0e3a4a376e27.png)

Cheers

**Comment by gionkunz** [comment]
Thanks :-) Currently not no. The reason behind this is that I simply didn't want to include different functionality to draw the last label on the x-axis. We could probably change this quite easily and just draw the last label on the left side of the grid line. Maybe even make it configurable...

I'll rename your issue and if others wish to change the behavior of the horizontal / x-axis distribution of points, we can prioritize this.

Thanks for opening an issue.

Cheers
Gion

**Comment by brenwell** [comment]
Easy, thanks Gion

**Comment by ilyashuma** [comment]
This would be really great!

**Comment by SekibOmazic** [comment]
+1! 

That would be super cool ;-)

**Comment by yemi** [comment]
+1

I would really like/need this to match the design for my project. 

It would be nice to be able to set some horizontal offset for the graph so that it doesn't start right at the left/right "walls".

**Comment by gionkunz** [comment]
Hi there. Offset the whole graph is possible using the draw event. Check the examples, some of them contain chart manipulation using draw events. Youd want to intercept point, line and area draw events and modify the elements using element.attr. I can post you an example later if you need it.

**Comment by gionkunz** [comment]
This is one way to offset your chart elements:
http://jsbin.com/wumebi/1/edit?js,output

However it does not solve the initial issue to use the full chart width for drawing. I think it's still valid to have an option that allows the full width of the chart area to be used. The only thing that will be a bit problematic is the last label on the x-axis. However, this could be corrected manually when it's an issue. Also the option should be used if there is enough space or one could also use `axisX: {labelOffset: {x: -something}}`

I think we should implement this asap.

**Comment by yemi** [comment]
Yes thats exactly what i'm looking for!

Thank you for taking your time to make an example.

**Comment by nicmendoza** [comment]
+1 this would be fantastic.

**Comment by gionkunz** [comment]
This will come with the next release that is likely to be published this weekend.

**Comment by nicmendoza** [comment]
Works, just have to pass fullWidth: true as an option

Thanks!

**Comment by ionas** [comment]
fullWidth will cut off my date label for the last data point.

**Comment by gionkunz** [comment]
There's an open issue for that #557 , you can find some workarounds within that ticket.

**Comment by ionas** [comment]
Thanks that's very nice of you!
