### ISSUE TITLE
Initial shift schedule

### ISSUE THREAD

**Issue by Zadvornyi** [chartist-js/chartist#181]
hello and thanks for this lib.
I have a question. How set initial shift schedule. 
The initial shift schedule 45 pixels along the axis x, how to make sure that you can set the offset for example 100 pixels.

**Comment by Zadvornyi** [comment]
set Options 
     // Options for Y-Axis
      axisY: {
        // The offset of the chart drawing area to the border of the container
        offset: 100,
      },

**Comment by gionkunz** [comment]
Glad you figured it out yourself :-) Cheers
