### ISSUE TITLE
LineChart with lineSmoothing and low:0

### ISSUE THREAD

**Issue by rolandschuetz** [chartist-js/chartist#182]
Hello,

When I draw a LineChart with showArea to show e.g. the amount of people in a bar this can never have a negative value. When I now active lineSmoothing the area sometimes has negative values.

![example image](http://i.snag.gy/edBI8.jpg)

It would be nice if low:0 had the effect of preventing this. I'm using the latest chartist, version 0.7.1

Is there maybe any way right now to prevent this?

Thanks,
Roland

**Comment by gionkunz** [comment]
Hey there. This is a side effect of the carinal / catmull-rome spline smoothing. We are currently implementing different smoothing functions in #92 that will not produce such artifacts.

**Comment by rolandschuetz** [comment]
Ok, thanks!

**Comment by danieldiekmeier** [comment]
I implemented a new smoothing function in #190 which gets rid of the artifacts.

**Comment by rolandschuetz** [comment]
Sounds good. As soon as the last problems are fixed I'll try it.
Thanks in advance for your work!

**Comment by gionkunz** [comment]
This should be available now in 0.7.2 Check the example: http://gionkunz.github.io/chartist-js/examples.html#line-interpolation-smoothing
