### ISSUE TITLE
Cannot Pass jQuery Object to Chartist

### ISSUE THREAD

**Issue by JulienMelissas** [chartist-js/chartist#184]
Maybe I'm missing something, but any time I try and pass a jQuery object to chartist, it gives me:
`Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': '[object Object]' is not a valid selector.`

For example:

```
var chart = $('.ct-chart');

new Chartist.Pie(chart, data);
```

Is there any way to pass a jQuery object to Chartist? I'm having to create individual IDs for each chart and then grab those with jQuery in order to put a dynamic amount of charts on the page, which works, but is a bit more time consuming/probably less performant.

I apologize if this has been covered before. Thanks for any help or advice anyone could give! Kickass chart lib.

**Comment by gionkunz** [comment]
Hey there. The Chartist guy hates jQuery :-) He wants the world to be less jQuery and more JavaScript. That's why Chartist only accepts DOM selector strings or DOM Node Objects as first parameter in the Chart.

If you're still using jQuery in your project, Chartist is fine with that, but when you initialize a Chart you need to extract the DOM Node object from your jQuery List:

``` javascript
new Chartist.Pie($('.ct-chart').get(0), data);
```

**Comment by gionkunz** [comment]
Btw. the Chartist guy would appreciate this much more:

``` javascript
new Chartist.Pie(document.querySelector('.ct-chart'), data);
```

**Comment by JulienMelissas** [comment]
@gionkunz thanks for the quick reply.

Sure, I understand how to make it work, and it's working by me extracting the name of each id on the charts, but it would be great if I could pass an object to chartist so that I didn't have to manually add an id to each element, as I have a dynamic amount of data and jQuery lets me iterate through that.

If the Chartist guy hates jQuery, why is he using it on his site? (http://gionkunz.github.io/chartist-js/getting-started.html#adding-behavior-to-your-charts)

I understand that some people dislike jQuery, but in this particular case, it would be a lot easier for me personally to be able to pass an object. Maybe it would be nice to include in the documentation that you _cannot_ pass a jQuery object to Chartist?

Just a want, not a need. It's still working very well. Thanks for the lightweight chart plugin!

**Comment by gionkunz** [comment]
But if you'd like to pass a list of selectors, dom nodes or a jquery list as first parameter, what will you pass as data? Do you want to initialize all chart containers with the same chart and the same data?

**Comment by gionkunz** [comment]
well the Chartist guy also hates to deal with haystacks but still he carries a hayfork around all the time... hes a weird guy you know...

**Comment by gionkunz** [comment]
Whats wrong with this? (Although very strange to use the same data for all charts)

``` javascript
$('.ct-chart').forEach(function() {
  new Chartist.Line(this, data);
});
```

**Comment by JulienMelissas** [comment]
@gionkunz - thanks again for your replies.

Each graph does have it's own data, yes. It's actually a pretty complicated setup, but I've got it working now by giving each chart their own id. Not ideal, but it's working fine!

Now I just have to get those donuts to animate :smile: 

Thanks again for your help.

**Comment by gionkunz** [comment]
Actually you could also do something like this:

``` html
<div class="ct-chart" data-ct-data='{"labels": ["1", "2", "3", "4"], "series": [["1", "5", "2", "3"]]}'></div>
<div class="ct-chart" data-ct-data='{"labels": ["1", "2", "3", "4"], "series": [["1", "5", "2", "3"]]}'></div>
<div class="ct-chart" data-ct-data='{"labels": ["1", "2", "3", "4"], "series": [["1", "5", "2", "3"]]}'></div>
```

``` javascript
$('.ct-chart').forEach(function() {
  new Chartist.Line(this, $(this).data('ctData'));
});
```

I didn't test this code but something along this line should work. jQuery is automatically parsing JSON in data attributes and returns the parsed object.

**Comment by JulienMelissas** [comment]
Not a bad solution, I'm calculating the values using JS, so I can't exactly do it like that, but an awesome example none the less.

Thanks again for the help!
