### ISSUE TITLE
How to combine tool tips with an animation?

### ISSUE THREAD

**Issue by jeffisfast** [chartist-js/chartist#186]
Hi.  I love Chartist.js.  Could someone help me get tooltips working with a line graph that has animation? This code draws the chart and animates it, but no tooltips.  

 To further complicate matters I'm drawing a graph inside a bootstrap modal.  I've got a graphs on the page, so you'll see I've given it a unique id for referencing.  

Here's my code but it isn't working.  Can someone tell me what I'm missing?

<div class="modal fade" id="myModalOxn80DsTatMVveZeD1Hi6X6IqRIXFgPB" tabindex="-1" role="dialog" aria-labelledby="Historical" aria-hidden="true">
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
<h4 class="modal-title" id="myModalLabel">Historical Data</h4>
</div>

<div class="modal-body">
<div class="mychartOxn80DsTatMVveZeD1Hi6X6IqRIXFgPB ct-chart ct-perfect-fourth"></div>

<script>
$('#myModalOxn80DsTatMVveZeD1Hi6X6IqRIXFgPB').on('shown.bs.modal', function (e) {

var chart = new Chartist.Line('.mychartOxn80DsTatMVveZeD1Hi6X6IqRIXFgPB', {
  labels: [ '02/04 5 PM', '02/04 6 PM', '02/04 7 PM', '02/04 8 PM', '02/04 9 PM', '02/04 10 PM', '02/04 11 PM', '02/05 12 AM', '02/05 01 AM', '02/05 02 AM', '02/05 03 AM', '02/05 04 AM', '02/05 05 AM', '02/05 06 AM', '02/05 07 AM', '02/05 08 AM', '02/05 09 AM', '02/05 10 AM', '02/05 11 AM', '02/05 0 PM', '02/05 1 PM', '02/05 2 PM', '02/05 3 PM', '02/05 4 PM', '02/05 5 PM', '02/05 6 PM',],
  series: [ { name: 'Temperature', data: [ 55, 56, 55, 56, 55, 55, 56, 55, 56, 56, 55, 55, 54, 55, 56, 56, 55, 56, 56, 55, 55, 55, 55, 56, 56, 55,]},
            { name: 'Humidity', data: [ 35, 35, 35, 35, 35, 35, 35, 35, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 35, 35, 35, 35, 35,]}    
  ]
}, {
  low: 0
});

// Let's put a sequence number aside so we can use it in the event callbacks
var seq = 0,
  delays = 80,
  durations = 500;

// Once the chart is fully created we reset the sequence
chart.on('created', function() {
  seq = 0;
});

// On each drawn element by Chartist we use the Chartist.Svg API to trigger SMIL animations
chart.on('draw', function(data) {
  seq++;

  if(data.type === 'line') {
    // If the drawn element is a line we do a simple opacity fade in. This could also be achieved using CSS3 animations.
    data.element.animate({
      opacity: {
        // The delay when we like to start the animation
        begin: seq * delays + 1000,
        // Duration of the animation
        dur: durations,
        // The value where the animation should start
        from: 0,
        // The value where it should end
        to: 1
      }
    });
  } else if(data.type === 'label' && data.axis === 'x') {
    data.element.animate({
      y: {
        begin: seq * delays,
        dur: durations,
        from: data.y + 100,
        to: data.y,
        // We can specify an easing function from Chartist.Svg.Easing
        easing: 'easeOutQuart'
      }
    });
  } else if(data.type === 'label' && data.axis === 'y') {
    data.element.animate({
      x: {
        begin: seq * delays,
        dur: durations,
        from: data.x - 100,
        to: data.x,
        easing: 'easeOutQuart'
      }
    });
  } else if(data.type === 'point') {
    data.element.animate({
      x1: {
        begin: seq * delays,
        dur: durations,
        from: data.x - 10,
        to: data.x,
        easing: 'easeOutQuart'
      },
      x2: {
        begin: seq * delays,
        dur: durations,
        from: data.x - 10,
        to: data.x,
        easing: 'easeOutQuart'
      },
      opacity: {
        begin: seq * delays,
        dur: durations,
        from: 0,
        to: 1,
        easing: 'easeOutQuart'
      }
    });
  } else if(data.type === 'grid') {
    // Using data.axis we get x or y which we can use to construct our animation definition objects
    var pos1Animation = {
      begin: seq * delays,
      dur: durations,
      from: data[data.axis + '1'] - 30,
      to: data[data.axis + '1'],
      easing: 'easeOutQuart'
    };

    var pos2Animation = {
      begin: seq * delays,
      dur: durations,
      from: data[data.axis + '2'] - 100,
      to: data[data.axis + '2'],
      easing: 'easeOutQuart'
    };

    var animations = {};
    animations[data.axis + '1'] = pos1Animation;
    animations[data.axis + '2'] = pos2Animation;
    animations['opacity'] = {
      begin: seq * delays,
      dur: durations,
      from: 0,
      to: 1,
      easing: 'easeOutQuart'
    };

    data.element.animate(animations);
  }
});

var $tooltipchart = $('.mychartOxn80DsTatMVveZeD1Hi6X6IqRIXFgPB');

var $toolTip = $tooltipchart
  .append('<div class="tooltip"></div>')
  .find('.tooltip')
  .hide();

$tooltipchart.on('mouseenter', '.ct-point', function() {
  var $point = $(this),
    value = $point.attr('ct:value'),
    seriesName = $point.parent().attr('ct:series-name');
  $toolTip.html(seriesName + '<br>' + value).show();
});

$tooltipchart.on('mouseleave', '.ct-point', function() {
  $toolTip.hide();
});

$tooltipchart.on('mousemove', function(event) {
  $toolTip.css({
    left: (event.offsetX || event.originalEvent.layerX) - $toolTip.width() / 2 - 10,
    top: (event.offsetY || event.originalEvent.layerY) - $toolTip.height() - 40
  });
});

});

</script>

**Comment by gionkunz** [comment]
Hey there. Thanks for the love! :-) I can't see your code. Can you provide a link to a JSBin maybe?

**Comment by jeffisfast** [comment]
Sorry about that.  I just pasted the code into this link:
http://jsbin.com/yixelasase/1/edit

For some reason the modal isn't popping up now, so I may have made a typo
pasting, but I think you'll be able to see the code.  Thanks in advance!

On Fri, Feb 6, 2015 at 5:21 AM, Gion Kunz notifications@github.com wrote:

> Hey there. Thanks for the love! :-) I can't see your code. Can you provide
> a link to a JSBin maybe?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gionkunz/chartist-js/issues/186#issuecomment-73215887
> .

## 

Jeff Tarr
jeff@tarr.com

**Comment by gionkunz** [comment]
Sorry for the late reply. I didn't had time to look at this earlier. There are three problems mainly about styling. 1) the tooltip class that was used in the chartist example is clashing with the class name from bootstrap .tooltip. So it's probably best if you rename it. I've renamed it to my-tooltip here http://jsbin.com/qesok/1/edit?css,js,output

Also you need to make sure that you tooltip has absolute positioning in your stylesheet.

**Comment by gionkunz** [comment]
If you still have issues with this please reopen this task. Cheers Gion
