### ISSUE TITLE
Path API inside pie chart.

### ISSUE THREAD

**Issue by martinsznapka** [chartist-js/chartist#187]
Please use path API https://github.com/gionkunz/chartist-js/issues/173 also in pie chart, so we can use path animations: http://gionkunz.github.io/chartist-js/examples.html#svg-path-animation
Thx!

**Comment by gionkunz** [comment]
Good one! That was missed somehow... will and in the next bugfix release

**Comment by martinsznapka** [comment]
I was trying to animate it, but looks like will be more tricky ;)
http://codepen.io/martinsznapka/pen/gbXmKx

**Comment by martinsznapka** [comment]
I did some hover effect for pie chart:
http://codepen.io/martinsznapka/pen/ZYaVJq
Feel free to use it in Chartist examples.

hmm... but in Firefox it behaves differently than in Chrome.

**Comment by gionkunz** [comment]
Cool examples! :-) Yeah, also the z-index and opacity is still a bit fishy. But the approach is great!

**Comment by gionkunz** [comment]
This PR is related #204

**Comment by gionkunz** [comment]
Thats implemented in 0.7.4
