### ISSUE TITLE
Overlaping labels

### ISSUE THREAD

**Issue by martinsznapka** [chartist-js/chartist#188]
Hi Gion
In some cases the labels are overlapping each other - f.e. big density of line chart points or small slice values in pie chart.
Examples:
http://codepen.io/martinsznapka/pen/ZYaVgN
http://codepen.io/martinsznapka/pen/wBppZP

I guess Chartist can do some recalculations of label positions/sizes/etc. and hide/move labels to "better" place.
But personally I do not think this is the right way because it requires lot of calculations and this can be performance problem - f.e. when you have many charts on one page and resize browser or change orientation on iPad.
We have bad experience with this when we used http://morrisjs.github.io/morris.js/ - browser freezing / https://www.google.com/search?q=firefox+unresponsive+script&tbm=isch / etc.

Lets share here some simple workarounds.

**Comment by martinsznapka** [comment]
For line chart issue with high density of labels could be simple workaround that we can filter out some labels:
Instead of:

``` javascript
labels: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
```

we set empty value to every 2nd label:

``` javascript
labels: ['Monday', '', 'Wednesday', '', 'Friday', '', 'Sunday']
```

We can add configurable option to Chartist which defines "displayEveryNthLabel" which default to 1.
My example would have value 2.

**Comment by gionkunz** [comment]
Have you tried to use the labelOffset and  labelDirection options? I know they won't solve this problem but if you know you will have slices where it's impossible to put the labels inside the slices, maybe you put them better outside?

There was a discussion about this in a very early ticket #21 maybe we can continue this discussion there? I'll close your ticket in favor of the original one.

**Comment by gionkunz** [comment]
Actually thats the labelOverflow option below the poor painting I did in #21 :-)

**Comment by dapello** [comment]
Hello,
I was wondering if an option like `displayEveryNthLabel` was ever created? I'd like to have a higher series density than label density and this seems to be the main option.

Thanks!

**Comment by gionkunz** [comment]
Hey there

You have the option to put the labels outside by using `labelOffset` and make them align away from the center by using `labelDirection: 'explode'` like so: http://jsbin.com/hofimu/1/edit?js,output

This still isn't perfect, I know.

Skipping each 2nd label you can achieve using the `labelInterpolationFnc` like so: http://jsbin.com/hofimu/2/edit

Or you could also say that you'd only want to display labels if the segment is "important" enought like so: http://jsbin.com/hofimu/3/edit?js,output

We're still working on a better solution which can be tracked here: #224

**Comment by maxt128** [comment]
Hi there.
I do have the same issue here (overlapping labels). As in #21 discussed a solution might be to use some kind of legend next to the chart. Is there any official guide or working best practice example available? I'm quite new to the topic (charting and all the web stuff) and I would appreciate some kind of walkthrough or working example....

Thanks...
