### ISSUE TITLE
Documentation uses anchors not buttons

### ISSUE THREAD

**Issue by JamieKnight** [chartist-js/chartist#19]
Hiya,

Documentation pages appear to use anchors rather than buttons for revealing hidden content. This slight semantic difference is important as by default OSX will not allow users to focus on links. Only buttons and form controls. (see: Control-F7 here https://developer.apple.com/library/mac/documentation/Accessibility/Conceptual/AccessibilityMacOSX/OSXAXKeyboardShortcuts/OSXAXKeyboardShortcuts.html)

This is hopefully a quick win to change. I'm up for doing a pull request, but I am not sure how to get the documentation site running locally so i can work on it.

Cheers,

Jamie + Lion

**Comment by gionkunz** [comment]
Check the contribution.md on how to get the site running. It's very straight forward. In short: npm install, bower install, grunt serve.... Tata!

Btw. fully agree with the <button> on show / hide elements. Check the button partial in the source/site/partials folder if you like to change it.

**Comment by gionkunz** [comment]
Thanks again Jamie! The changes will go into the sitedist I'll push later today.
