### ISSUE TITLE
0.7.1 error when creating a chart

### ISSUE THREAD

**Issue by ilanbiala** [chartist-js/chartist#193]
`Error: Invalid value for <foreignObject> attribute height="NaN"`

**Comment by gionkunz** [comment]
Can you provide additional details?

**Comment by gionkunz** [comment]
Also did you mean 0.7.2 ?

**Comment by ilanbiala** [comment]
No 0.7.1, and I didn't find anything upon initial investigation, I'll look into it again more in depth.

**Comment by gionkunz** [comment]
Can you post the code your using to reproduce the error?

**Comment by ilanbiala** [comment]
```
.directive('barGraph', [function() {
        return {
            restrict: 'E',
            scope: {
                data: '='
            },
            link: function($scope, element, attrs) {
                var data = {
                    // A labels array that can contain any sort of values
                    labels: $scope.data.labels,
                    // Our series array that contains series objects or in this case series data arrays
                    series: [$scope.data.data]
                };

                var options = {};

                if (attrs.gWidth && attrs.gHeight) {
                    options.width = attrs.gWidth;
                    options.height = attrs.gHeight;
                }

                $scope.graph = new Chartist.Bar(element[0], data, options);
            }
        };
    }])
    .directive('lineChart', [function() {
        return {
            restrict: 'E',
            scope: {
                data: '='
            },
            link: function($scope, element, attrs) {
                var data = {
                    // A labels array that can contain any sort of values
                    labels: $scope.data.labels,
                    // Our series array that contains series objects or in this case series data arrays
                    series: [$scope.data.data]
                };

                var options = {
                    lineSmooth: false,
                    low: 0,
                    showArea: true
                };

                if (attrs.gWidth && attrs.gHeight) {
                    options.width = attrs.gWidth;
                    options.height = attrs.gHeight;
                }

                $scope.graph = new Chartist.Line(element[0], data, options);
            }
        };
    }]);
```

Both graphs cause the same error, but I'm not sure why.

**Comment by gionkunz** [comment]
Can you also post the markup you're using? Which version of angular.js are you using?

**Comment by ilanbiala** [comment]
Angular 1.3.13

```
<bar-graph class="ct-chart ct-perfect-fourth" data="topItemsData" ng-if="topItemsData"></bar-graph>

<line-chart class="ct-chart ct-perfect-fourth" data="ordersPerDayData" ng-if="ordersPerDayData"></line-chart>
```

**Comment by Schwoebel** [comment]
I too am having this issue.  I just installed Chartist yesterday evening using bower.  Using version 0.7.2.  

And the code that I am getting the error on is the line-chart-sample code from the "Getting started" section of the Chartist website.

And in the console it says the issue is on line 1419 of chartist.js

**Comment by Schwoebel** [comment]
I checked out revision 3cd52116d93 and used that version and I do not get the error anymore.

**Comment by gionkunz** [comment]
Hey guys

I can't reproduce the problem. I'm using chartist.min.js or chartist.js from v0.7.2 tag with this code:

``` html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="chartist.min.css"/>
</head>
<body>
<div class="ct-chart ct-golden-section"></div>
<script src="chartist.min.js"></script>
<script>
  var data = {
    labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    series: [
      [5, 2, 4, 2, 0]
    ]
  };

  new Chartist.Line('.ct-chart', data);
</script>
</body>
</html>
```

I've tested in Chrome 40 and Firefox 35.

What browser are you using?

**Comment by ilanbiala** [comment]
@Schwoebel are you making an HTTP request for your data? That revision doesn't seem to have any code changes, just documentation fixes.

**Comment by Schwoebel** [comment]
I am using Chrome 40.0.2214.  I didn't try it in Firefox.

I didn't revert back step by step to see where the error stopped.  In my case I may have just gotten lucky?  It may be something that was changed after that release but before 0.7.2?

Nope, not making any HTTP requests.  In my specific case it was a straight copy/paste from the website.

I was doing it all in $(window).load(funct..... not $(document).ready if that has anything to do with it.

**Comment by gionkunz** [comment]
Is this still an issue guys?

**Comment by ilanbiala** [comment]
@gionkunz The error is thrown whenever the DOM recreates the chart on window resize. Still getting the error in 0.7.2 by the way.

**Comment by bzalasky** [comment]
This is still an issue for me as well. I can also confirm the error happens on resize, though not initially for me. Once it starts happening it gets thrown rapidly. This is perhaps a bit of a tangent, but is there any throttling or debouncing around that resize code? Also, when there's more than one chart on the page, are multiple listeners being attached to the window resize event (or is this taken care of with the event emitter)?

And another thought on debouncing... if there is a problem with calculating height during the resize, would debouncing the function to wait until window resizing has ended to resize the chart fix the bug?

**Comment by Schwoebel** [comment]
I cannot say if I am stil having the issue.  I am still using the older installation that I used to fix the problem initially.  Today I am going to try using 0.7.2 elsewhere and I will let you know.

**Comment by gionkunz** [comment]
I still can't reproduce the problem guys :-) Please give me something I can use to reproduce the problem. Can you post a JSBin and description on how to reproduce the issue?

@bzalasky , debouncing is important on things that can happen a lot like scrolling or user sleeping on his keyboard, however, that users resize their window is simply a myth I believe :-) I think if you'd track how many users resize their browser during a page visit, the outcome would be close to 0 and the leftover are developers checking out the responsiveness of your site. :-) For security / stability reason I agree with you so we should probably think about adding a debounce mechanism. There are mutlipple listeners on the window for each chart instance. The resize listener is attached during Chart creation in https://github.com/gionkunz/chartist-js/blob/develop/src/scripts/base.js#L90 and will be removed during de-initialization or if the chart is getting detached explicitly. I actually don't know what's more performant, one listener that iterates over all charts or multiple listeners (that get iterated when the event occur) that handle their own chart.

**Comment by gionkunz** [comment]
In regards to problems calculating container dimensions I'm not aware of any issues except if the container is not visible at the time of initialization.

**Comment by bzalasky** [comment]
I would have one listener on the window that publishes an event that all instances subscribe to... this event should be debounced and publish the current screen width. This is so you don't have to re-query the DOM for this information again. I agree that users probably aren't resizing a ton on desktops, but it's reasonable to imagine a user rotating a touch device.

As far as reproducing the bug, another guy on my team commented on it, and I couldn't get it to happen for a good 5-10 minutes. However, we eventually confirmed that it happens on browser resize regardless of the chart and configuration. Both Chartist line chart examples and our configured line charts exhibited the problem.

**Comment by gionkunz** [comment]
Well, we don't query the DOM for window width as we don't rely on screen width but parent container width, which we anyway need to reconsider for each chart individually. Well if your users rotate their fablets 20 times a second you probably should start debounce your window resize events :-) No, let's be serious. I completely agree with you about this and we should use debouncing just for security reasons. With the single window resize listener, as stated, probably makes sens in most cases but if you'd only want to react on the event to rearrange your internals, I don't see the direct benefit of just one event listener.

**Comment by rzane** [comment]
Also seeing this using Ember CLI Chartist using version 0.7.3. To reproduce it, I go to a page with a chart, visit a different page, then come back to the page with the chart and resize.

**Comment by gionkunz** [comment]
I still have no clue whats going on here. Can someone with Ember or React also produce this in plain JavaScript? Please re-open this ticket if this issue still persists.

**Comment by Schwoebel** [comment]
I have used the plugin on several projects since this error occured and have not gotten the error again, even with the new installation. 

I am very sorry about how long it has taken for me to get back to this thread.

**Comment by bnetter** [comment]
I'm having this too, using Ember + Chrome. It randomly happens, but doesn't break anything, just showing the error on the console.

**Comment by gionkunz** [comment]
HI @BenjaminN which version are you using? Please note that the latest state on develop also includes a fix. I'm planing to do a release later this week but to check you could also build develop yourself.

Cheers
Gion

**Comment by bnetter** [comment]
Thanks for the good work @gionkunz, I'll let you know.

**Comment by kaermorchen** [comment]
Hello.

I catch this error when use foundation tabs with chartist. If chartist bars render without tabs, all work ok. 

```
Error: Invalid value for <foreignObject> attribute height="NaN"
```

I think this is If parent div have display: none

Chrome - 42.0.2311.135
Ember - 1.11.3
jQuery - 2.1.3
foundation - 5.5.1
chartist - 0.7.4

How can I to get round this error?

**Comment by nkapatos** [comment]
@kaermorchen 0.8.0 doesn't throw this error if any of the parent elements has display: none. It does draw the chart, though it has a wrong display of the chart and the axis ticks.
My workaround, because I am also using tabs (bootstrap), was to use the chartist update method when the tab comes into view the first time. This refreshes the chart and has a correct display.
Hope it helps
