### ISSUE TITLE
Show label only on certain series?

### ISSUE THREAD

**Issue by ryexley** [chartist-js/chartist#194]
Is there any way to get chartist to show labels on some series, and not on others?

**Comment by redrobotx** [comment]
Hey, did you find the solution to this?  I would like to do the same thing.

**Comment by ryexley** [comment]
Technically, no...but I found a workaround. I pretty much just set the label of the series that I didn't want displayed to `" "` and that was good enough for me.

**Comment by gionkunz** [comment]
returning a falsey value (except 0) from the labelInterpolatioFnc will result in the label not being rendered. Check this example: http://gionkunz.github.io/chartist-js/examples.html#line-scatter-diagram-with-responsive-settings
