### ISSUE TITLE
chartPadding top right bottom left

### ISSUE THREAD

**Issue by martinsznapka** [chartist-js/chartist#195]
Hi Gion
Would be nice if chartPadding is array of numbers for top, right, bottom and left padding.

In case of 'fullWidth: true' and 'chartPadding: 0' is the right point cropped:
http://codepen.io/martinsznapka/pen/JoLLYK

I think 'chartPadding: [0, 5, 0, 0]' can solve it.

**Comment by danieldiekmeier** [comment]
Maybe also support using an object, like

```
chartPadding: {
    right: 5
}
```

to set just the values you want to set, like in CSS.

**Comment by martinsznapka** [comment]
Yepp, that's better.

**Comment by gionkunz** [comment]
Hey Martin

Thanks for this issue! It's definitely desirable to have this configuration. This would also help the fullWidth line charts to fix the last label rendering (and the point) like described in #198 

Currently only a global padding can be specified that will pad the Chart from all four sides with the same pixel value. It's desired however, for multiple reasons, to have the ability to specify the chart padding individually for each side. This could be done, as suggested here by @danieldiekmeier, by using individual properties for top, right, bottom, left like in CSS. Additionally the configuration should also be possible with a number which will internally then be used for all four sides. 

Internally, most of the code should work fine, if the chartRect calculation will be amended, so it takes this new configuration into account. Most subsequent layout processes use the chartRect object. However, there are certain positionings that rely on the chartPadding being a number. This needs to be refactored.

**Comment by Webbrother** [comment]
Possibly related with https://github.com/gionkunz/chartist-js/issues/842
