### ISSUE TITLE
Zero-padding charts

### ISSUE THREAD

**Issue by xpepermint** [chartist-js/chartist#197]
I try to design a graph like [this](https://dribbble.com/shots/1423171-Some-Analytics/attachments/208613). You can see that left/right/bottom padding is 0px. If I remove labels on the left it only hides the values but the padding remains.

``` js
  new Chartist.Line(".graph#{trigger.id}", {
    labels: [1,2,4,15,2,1,23,123,123],
    series: [[1,2,4,15,2,1,23,123,123]]
  }, {
    low: 0,
    showArea: true,
    showLine: false,
    showPoint: false,
    fullWidth: true,
    chartPadding: 0,
    height: 120,
    axisX: { showGrid: false, showLabel: false },
    axisY: { showGrid: false, showLabel: false }
  });
```

**Comment by gionkunz** [comment]
You need to set offset in both axes to 0 too.

**Comment by xpepermint** [comment]
Aaaa... thanks man. Great library, btw!

**Comment by gionkunz** [comment]
Sure thing! Thanks for the love :-)
