### ISSUE TITLE
Line chart with two values

### ISSUE THREAD

**Issue by rolandschuetz** [chartist-js/chartist#198]
Hello,

when you render a line chart with just two values it takes up only 50% of the, full with would be expected.

test case:

```
new Chartist.Line('.ct-chart', {
    labels: ['a', 'b'], // removing the full-label makes it full-width
    series: [
        [12, 22]
    ]
});
```

![showcase](http://i.snag.gy/C8mN1.jpg)

Thanks in advance,
Roland

**Comment by gionkunz** [comment]
Use the fullWidth option

**Comment by rolandschuetz** [comment]
I still think this is a bug. i would expect the last line at the same position, independent of there are two or three or 500 points.

**Comment by rolandschuetz** [comment]
When using fullWidth if there a way to define a offset from the right?
Adding a padding increased the space between labels and chart, which I don't want.

**Comment by gionkunz** [comment]
Its a visual design problem. Where do you want to put the label if you dont have space on the right? You can use the draw event to position the last label on a different position.

**Comment by rolandschuetz** [comment]
It's a even trickier design problem if the chart width changes depending on the input.
If would be great to simply be able to define a fixed offset from the right, like the offset from the left fixes the issue with the first label.

**Comment by gionkunz** [comment]
You can now draw a fullWidth chart and add only padding to the right side:

http://jsbin.com/jovepa/1/edit?js,output

**Comment by rolandschuetz** [comment]
Perfect, thanks!
