### ISSUE TITLE
Accessibility & ARIA

### ISSUE THREAD

**Issue by JamieKnight** [chartist-js/chartist#2]
Hiya,

Congrats on the launch of chartist.js, it looks awesome! It's well timed too as I am currently looking at charting libraries to use for an upcoming project at the BBC.

Something i noticed playing with the demos, is that the charts are not very accessible. For example, the pie chart on the demos page is complete invisible to voiceover, a common screen reader. However, i think i can help :D

My job at the BBC is actually in the accessibility team (i found your library while looking for tools to build our new internal dashboard with!) so I was wondering if you would like a hand at improving the accessibility of your code. 

I think I could offer the following:

1: I'm happy to take some of the examples, and attempt to rewrite them to be more accessible where possible.
2: I could write a user guide page on ensuring a11y
3: I could provide a case study / example for how accessible charting is being used in the real world.

I cannot promise anything timelines wise as the project i have in mind is yet to kick off, but i am really interested in helping.

In the mean time, i found this article: https://www.webkit.org/blog/3302/aria_and_accessibility_inspector/ i think it covers some of the simpler stuff that you guys could do today to make things a little better.

Please let me know what you think,

Cheers,

Jamie + Lion

**Comment by gionkunz** [comment]
Hey there! Thats awesome that you opened this issue becuase this is exactly one of the things i wanted to prioritize very high after reading a nice blogpost on accessibility in inline svg sugested by chris coyier a while ago! If you have time and would enjoy the work please go ahead and create a pull request. I assume that most or everything will go into the generated svg so it would probably mean to modify the generating parts of the core. If it takes too much time for you to dig into that it would also be very helpful if you take the generated examples and modify them with aria (and whatever magic youre aware) so i could adopt to that by an example on the exact subject)

Thanks for your thoughts!

Cheers
Gion

**Comment by JamieKnight** [comment]
Hiya Gion,

Thanks for you positive reply! Apologies for my slightly tardy response. For the moment this is an after hours project for me but hopefully it will be part of the day job sometime soon.

I think it would be helpful to agree a way of working before we start with the code elements. I have proposed something in https://github.com/gionkunz/chartist-js/issues/11 which might be a method we could adopt. Please let me know how you would like for me to proceed. 

Once we have a way of working and the desired UX defined, i might try and do a pull request to fix some of the low hanging fruit.

Let me know if that sounds sensible, not contributed on a project quite like this before so i am not entirely sure of the social rules ;) Remind me if i do something daft.

Cheers,

Jamie + Lion

**Comment by gionkunz** [comment]
Hi Jamie

Lets continue all our accessibility efforts in this section. Do you have an example somewhere, using a visually hidden table or something youd recommend to try? Ill open a branch for this so we can both test there.

Cheers
Gion

**Comment by JamieKnight** [comment]
Hiya Gion,

Sorry, I just noticed your reply in the other thread regarding testing. Missed the notification from github drats. 

"Is there anything we could do to automate this in our build? That validates against guidelines?"

This is something we have been working on at the beeb. Specifically, tools for verifying the present of correct ARIA rolls and the like.

Once we know what we want the markup to be we can look at how to automate it :dancer: 

" Do you have an example somewhere, using a visually hidden table or something youd recommend to try? "

Not to hand, but i will dig some out shortly. Its basically a table with theads etc etc. Wlll find a demo for you to point voiceover etc at so you can get a feel for the UX.

I think the pie chart is simplest, I have another project which needs to do something similar, so i will have a crack at making something this evening. May be a demo / example in a gist. Will be in touch.

Cheers,

Jamie + Lion

**Comment by JamieKnight** [comment]
Hiya,

Have spent some time working in code pen, to adapt the labelling techniques from the "Africa" example to the pie chart. 

I don't have anything to share yet (still exploring / learning), but will be able to spend more time on this at the weekend.

Cheers,

Jamie + Lion

**Comment by JamieKnight** [comment]
Hiya,

I have cleaned up my codepen just enough to share as a first pass. It can be found here: http://codepen.io/anon/pen/nHuLC

_Technique Details:_
- Uses Hidden SVG Text Nodes as labels
- Sets each path  the "image" role, and establishes a label element
- Uses ARIA (good support on iOS / Mac / JAWS, NVDA, not sure how well it works on android)

_Discussion points:_
- Should we include the labels, or ask people to name an ID that describes each segment?
- I think the the accessibility  of this chart is usage sensitive. Eg, if chart is used in isolation (e.g. with no text summery etc) then making the chart accessibility is important. However, if chart is a visualisation as progressive enhancement then the chart accessibility is less important as it's just repeating information already present. Should we allow for both use cases?

_API Thoughts_

API with Labels:

```
data: {
        labels: ['Zebra', 'Hippo', 'Antelope', 'Jelly Beans'],
        series: [20, 15, 40, 10]
      }
```

 Or a selector for the description node

```
   data: {
        labels: ['.zebra', '.hippo', '.antelope', '.jellybeans'],
        series: [20, 15, 40, 10]
      }
```

Or a node / nodelist.

```
   data: {
        labels: [document.getElementByID('#zebra'), document.getElementByID('#hippo'), document.getElementByID('#antelope'), document.getElementByID('#jellybeans')],
        series: [20, 15, 40, 10]
      }
```

Another option, would be an API that does both. 

Have the 'labels' option accept either:
-  an array of strings (which are used to generate hidden text) 
- or a array of HTMLElement objects which are to be references as the label / description. (does not generate hidden elements).

Hope that all makes some sense. 

Cheers,

Jamie + Lion

**Comment by gionkunz** [comment]
Great jamie! This looks fantastic! Ill dig more the upcoming weekend, open a accessibility branch and we can mess around there. I'm really happy about your contribution here. I'll also evaluate your ideas and check some options. Once we have a branch with some changes you could evaluate with the accessibility tool at your disposal and verify what we develop. The sugestions you provided all look very promising to me. I think we should habe an enable / disable config switch for the cases where the chart is just illustrating data that is already accessible. Let's keep the pace here.

Cheers
Gion

**Comment by ilanbiala** [comment]
@gionkunz we should get an accessibility expert to help us make Chartist better in that respect because if we do it ourselves we'll probably not cover all our bases.

**Comment by gionkunz** [comment]
@ilanbiala @JamieKnight is an accessibility expert ;-)

**Comment by ilanbiala** [comment]
Ah I forgot since I read this issue a couple weeks ago. @JamieKnight @gionkunz can we start a PR for adding accessibility support?

**Comment by gionkunz** [comment]
Accessibility should now be covered by https://github.com/gionkunz/chartist-plugin-accessibility

@JamieKnight If you have time please review the plugin.

I'll close this issue and we can track any missing topics or changes directly in the plugin repository.

Cheers and thanks for all your input!

**Comment by JamieKnight** [comment]
Hiya,

Sorry for my way slow reply. I'm in the USA on a work trip (been here 9 days) but can't get into github as I can't receive my Two Factor Auth SMS.

Hopefully this email will get added as a comment. Once back i will check out the plugin and provide feedback.

Cheers,

Jamie + Lio

**Comment by gionkunz** [comment]
Hey @JamieKnight good to hear from you! :-) No worries, take your time!

**Comment by fluffabelle** [comment]
Hello, may I chime into the thread? I think the table option is a great solution for charts that don't have a lot of data or that are more simple in nature. Some of the charts that I make have an absurd amount of data (ex, I have one excel file that is 150 lines of dates and decimals) that I would not even want to see, let alone have read out loud to me. For these complex charts I have come up with this solve using the SVG element chartist creates and these guidelines: 
http://www.sitepoint.com/tips-accessible-svg/
http://www.paciellogroup.com/blog/2013/12/using-aria-enhance-svg-accessibility/
The function that I have written removes the ability for the screen reader to read the SVG itself and instead provides a title and description to be read aloud instead.

<pre><code>
//prefix: a specific name we will use to generate IDs for aria; parent: the wrapping div that is given to chartist; title: same idea as the caption in the table plugin; desc: same idea as the summary in the table plugin
function addTitleDesc(prefix,parent,title,desc){
    //creating SVG title and desc tags
    var titleTag = document.createElementNS('http://www.w3.org/2000/svg', 'title' );
    var descTag = document.createElementNS('http://www.w3.org/2000/svg', 'desc' );
    var svg = $(parent).find('svg');
    //using aria to raise browser support
    //first add a specific ID to the title and desciption that we will call via aria-labelledby
    $(titleTag).attr('id', prefix + '-t').text(title);
    $(descTag).attr('id', prefix + '-d').text(desc);
    //hiding the labels as we don't need them to be read aloud, we are instead providing a description
    $(parent).find('.ct-label, .ct-labels').attr("aria-hidden", "true");
    //setting the role and aria-labelledby so that it reads the title and description
    svg.attr({
        "role" : "img",
        "aria-labelledby" : prefix + "-t" + " " + prefix + "-d"
    });
    //adding in the title and desc tags
    svg.prepend(descTag);
    svg.prepend(titleTag);
}
</code></pre>

I am then calling this after the chart is created like this:

<pre><code>
var chartistEx = new Chartist.Bar('.chartistEx', chartistExData, chartistExOptions);
chartistEx.on('created', function(){
    addTitleDesc("chartistEx1",'.chartistEx',"Title of the chart","A description of what the chart is showing");
});
</code></pre>

I did test this in JAWS and it worked as expected. I would love to know your thoughts on this approach!

**Comment by gionkunz** [comment]
Hey Christina. Thanks for your input! We were also looking into this approach in the first place and it definitely makes sens for large amounts of data to only provide a summary. However, I'd like to think about this carefully. Do you think there is any value in providing only a summary if there are 300 data points in a chart? What would the summary look like? You can maybe describe what the chart expresses but you can't reveal the content of the chart which is kind of annoying for blind people I guess. If the summary says "Temperature difference between 1995 and 2013 with 300 data points" but he can't access those points to get an idea of what the information is like, whats the point of providing a summary?

What if we think about it visually and what we do when there is too much information. We start to cluster information into meaningful chunks that can be isolated and inspected. Maybe we can find a way to represent this with ARIA? I think of something like a clusterBy configuration in the accessibility plugin configuration that allows you to cluster your data tables into chunks. This could be done with http://www.w3.org/TR/wai-aria/roles#tablist and individual accessibility tables inside tabpanels for example.

What do you think?

**Comment by fluffabelle** [comment]
I'm sure there are charts that the cluster approach would work well in, but I can't see it for the type of charts that I have been working on. Let me give some sample descriptions and see if that helps clarify how I am using the summary approach.

Example 1: a simple bar chart (the table plugin would work well for this)
Title: "Jam preferences in 2014"
Description: "Mixed berry: 42% | Strawberry: 58%"

Example 2: a line chart with many data points
Title: "Jam preferences from 1950-2014"
Description: "In 1950 mixed berry jam was a popular amongst 36% while strawberry was clearly the preference, scoring 64% by participants. Since then they have continued to be close competitors, last scored in 2014 at 42% for mixed berry and 58% for strawberry."

Example 3: a mountain chart with many data points and more visual weight on the growth (shaded regions)
Title: "Jam preferences from 1950-2014"
Description: "In 1950 mixed berry jam was a popular amongst 36% while strawberry was clearly the preference, scoring 64% by participants. Since then they have continued to be close competitors; between 1980 and 2014 mixed berry had an overall growth of 6% , and strawberry a 6% decline. Today strawberry is still the preferred jam, last scored in 2014 at 58% for strawberry and 42% for mixed berry."

I made all of this up of course so the last is probably lacking logically, but I hope you understand where I am going with it. Instead of just using numbers and labels as the description, actually writing out a summary of the gain a person looking at the chart would get; or explaining the visual chart out loud to someone who can't see it, so that they can have the same knowledge gain. This of course does add more overhead to whoever is making the chart/their team, or overhead to the client requesting it, and the accessibility is 100% dependent on the quality of the description. But I think people who are asking for features like this are probably willing to do what they can to provide meaningful context… companies that don't care about accessibility won't care to and probably won't even use the options for caption/summary.

In an example like this, how are you thinking the cluster could work? Like by year range? Would you have to specify the array numbers to chartist for the labels/data for which to group in what table (ex: [0, 1, 2, 3],[4,5,6,7],etc)? I just don't think I would want to hear 300 data points read to me, even in groups, if I could gain the same benefit faster from a description… thoughts?

**Comment by fluffabelle** [comment]
Also I think that maybe the biggest difference between the cluster/table/summary approaches is the intent of the chart… for the ones that i typically work on the numbers themselves usually aren't important, it's more about the gain/comparison and they are more illustrative exhibits. If your chart was the main focal/functioning piece on a page and the audience really wanted to know the mixed berry data point in 1983 then certainly a table or cluster approach would be better.

I also just might be a weird edge case. Maybe the table plugin could have an option to build or not build the data, then it would be one plugin to do all of this, and I could switch off the 300 point data table from being made, keeping the caption and summary, on charts that descriptions serve a better purpose for, haha. Overall I like the table approach a lot and I think it is a great solve in most cases… except for my terrible line charts :(
