### ISSUE TITLE
responsiveOptions of configuration example doesn't work in Firefox

### ISSUE THREAD

**Issue by RiZKiT** [chartist-js/chartist#20]
The example [Responsive charts configuration](http://gionkunz.github.io/chartist-js/#responsive-charts-configuration) doesn't to work in Firefox 28 (Linux) and Firefox 30 (Windows). The x-axis names do not change dynamically responsive to the viewport size. But it works in Chrome.

Quick link to the source: https://github.com/gionkunz/chartist-js/blob/develop/source/site/code-snippets/simple-responsive-settings.js#L21-L38 (I do not see the problem, otherwise I had done a pull request)

**Comment by gionkunz** [comment]
Thanks for the issue! Are you sure there are no other factors like addons that modify the media information in CSS? Because I can't reproduce the issue in Firefox 31 on windows and Ubuntu and I can't imagine why 30 and 29 should behave differently with the matchMedia API and CSS media queries.

**Comment by gionkunz** [comment]
I just tested with FF30 on Ubuntu and the responsive configuration override works for me. Please check what else could interfere the behavior in your environment.

**Comment by RiZKiT** [comment]
Seems to work now, maybe you pushed [this one](https://github.com/gionkunz/chartist-js/pull/16) online today?

**Comment by gionkunz** [comment]
Hi, yes this was pushed to gh-pages yesterday, but it was only a change in a comment. Please let me know again when you face the issue again. I'll close the issue for now. Thanks for your feedback.
