### ISSUE TITLE
Support chart legend and different bar types

### ISSUE THREAD

**Issue by Globegitter** [chartist-js/chartist#202]
I would need to create a barchart that displays the highest grossing category/genre each year (based on the data I have). So my test chart looks like this right now:
![screen shot 2015-02-23 at 09 09 47](https://cloud.githubusercontent.com/assets/2580254/6325167/bd0c746c-bb3b-11e4-9d3c-66905e0a4789.png)

But I would like each chart to have a different colour based on the category and then have a legend on the side, or direct labels for the charts, or on hover/click to get a tooltip.

Maybe something like

``` js
      chartData: {
        labels: ['2005', '2006', '2007', '2008'],
        series: [
          [ { 'name': 10000 }, { 'category2': 15000 } , { 'category3': 13000 }, { 'category2': 8000 } ],
        ]
      }
```

Is what I could imagine and chartist could choose a colour based on the key. I don't know how chartist works under the hood, but there could be maybe 10 predefined colours and it just assigns each key it finds to a colour.

What do you think of this? Does that make sense?
Of course this is just an idea about the actual implementation. You might have a better one :)

**Comment by gionkunz** [comment]
Hey there. So you have the years and inside of the years you will show values for each category right?

So it'd be more like this?
http://jsbin.com/kowida/1/edit?html,js,output

There is a different kind of bar chart where the Y-Axis is the categories (e.g. coffee consumption for each employee where each employee has its own bar). For this type of bar chart there is currently no standard way to implement this within Chartist. I believe this is a common use case and we should support it within the standard API. If you'd like to use this today, I recommend you to use the data value object notation in conjunction with the meta property. You can put anything into meta but if you use a simple value this will get directly into the attribute `ct:meta` on the bar line element.

You could then use namespace attribute selectors (although I don't like them so much) in your CSS to solve your problem.
http://jsbin.com/kowida/2/edit?html,css,js,output

Please leave this issue open as we should track this and implement a standard way to handle such cases. Maybe just add the possibility to add classes in the object value notation.

**Comment by Globegitter** [comment]
Thank you for the quick response - yep the second one does exactly what I want right now already. Perfect :) And having multiple bars per year might also be interesting in the future if I want to show the top 3 categories (better example: show top 3 grossing genres for movies in a year) and as in the second bar each category would have it's own colour

In addition to that it would be great to have an easy way to add a legend (as in describing the colours, blue: category1, green: category2, orange: category3, purple: category4, just with colour blobs instead of the colour name).

Though I suppose in the meantime I could add a tooltip quite easily right? Similar to http://gionkunz.github.io/chartist-js/examples.html#line-chart-with-tooltips but just accessing the line's `ct:meta`

And yes I agree, defining a standard way would be ideal - class names is I think a quite good idea.

**Comment by gionkunz** [comment]
Yes or do you legend in HTML using the same CSS to style your legend :-) I really endorse to use HTML for legends.

**Comment by gionkunz** [comment]
I've created #209 for the category bar chart option.
