### ISSUE TITLE
Question about plugins

### ISSUE THREAD

**Issue by simonkapell** [chartist-js/chartist#205]
hey Gion,

First, I wanna say, that I really like your work. I'am new to javascript and this with chartist.js, I build my first project.
I think I´ve a simple question... How can I include a plugin to my project! With this code it doesn't worked.

``` javascript
    new Chartist.Line('.ct-chart', {
        labels: [0, 1, 2, 3],
        series: [{
            data: [ 3,5,2,6],
            name: '°C'
        },{
            data: [ 4,7,3,1],
            name: '°C'
        }]
    }, {
        plugins: [
            Chartist.plugins.ctPointLabels({
                textAnchor: 'middle'
            })
        ]
    });
```

Thanks to advice,
Simon

**Comment by gionkunz** [comment]
Hey @Dixi86 , Did you also include the ctPointLabel script?

**Comment by simonkapell** [comment]
Wow, thanks for your prompt reply... After your hint I found this post https://github.com/gionkunz/chartist-plugin-pointlabels/issues/1

And changed my project-settings like the juanomoran is explaining in OPTION A
