### ISSUE TITLE
Change specificity of CSS selectors

### ISSUE THREAD

**Issue by gionkunz** [chartist-js/chartist#207]
Currently the chartist selectors have to much specificity for my taste. We should simply this and as we're anyway using ct- prefixes the whole nesting isn't so important. Let's remove what's not needed and what won't cause backward compatibility issues.

**Comment by odraencoded** [comment]
Yeah, I'm trying to change **only** the `fill` color of pies that use a certain kind of series(I have an overview pie chart and breakdown bars with the same kind of series) but now I have to decide between overspecifying or using `!important`.

My selector

```
.grafico-series-status-processos .ct-series-a > .ct-slice
```

Chartist's

```
.ct-chart .ct-series.ct-series-a .ct-slice:not(.ct-donut)
```

**Comment by gionkunz** [comment]
Yeah, the problem when I reduce the specificitiy and make the selectors more flat, will be that there might be some backwards compatibility issues. But I think we should do it anway.

For the moment you should probably use the same specificity as chartist uses:

`.grafico-series-status-processos .ct-series.ct-series-a .ct-slice:not(.ct-donut)`

**Comment by gionkunz** [comment]
I've pushed 0.8.3 which greatly reduces the specificity. Check http://gionkunz.github.io/chartist-js/getting-started.html#customizing-the-default-css for more information.
