### ISSUE TITLE
Browser Stucks While Updating Chart

### ISSUE THREAD

**Issue by Thomasforweb** [chartist-js/chartist#208]
Hi,
I am Facing an issue while updating Charts "Low Option". By Default the low is set to 0 

When I trigger the update to around 6000 low it works fine.But when i change it back to 0, the browser stuck up.

var updateOptions = {
   low: 6000 //works fine
 };
chart.update(data, updateOptions, true);

var updateOptions2 = {
   low: 0 // from 6000 to 0 low it stuck up
 };
chart.update(data, updateOptions2, true);

Please help me out on this.

Thanks

**Comment by gionkunz** [comment]
There was a common problem with the options and overriding mechanism. Can you check out the dev branch and do a build `grunt build` and use this version to test if the issue is still open?

**Comment by gionkunz** [comment]
0.7.3 is released, can you check if the problem persists?

**Comment by Thomasforweb** [comment]
Yeah It has been Fixed, Thanks For Fixing It!

**Comment by gionkunz** [comment]
Great! Glad to hear that :-)
