### ISSUE TITLE
Label vertical align for Pie is wrong

### ISSUE THREAD

**Issue by igor10k** [chartist-js/chartist#210]
Looks like the text is aligned by the baseline, so in 50/50 case it's easy to spot that labels are not perfectly centered vertically.

I've added a center line on the image below for more clarity.

![chart](https://cloud.githubusercontent.com/assets/1244342/6417532/a9bb7a60-beb6-11e4-9e02-3ab5d9946e6e.png)

**Comment by gionkunz** [comment]
Well whats "wrong" depends on your use case :-) Baseline is usually a good default because that's what you usually expect in text layout. If you'd like to change this just use  `alignment-baseline: middle` in your CSS.

Here is an example:
http://jsbin.com/dikobi/1/edit?css,js,output

**Comment by igor10k** [comment]
@gionkunz yeah, I agree. Your solution is just great, thanks. I skimmed through all the SVG CSS properties before filing an issue, but it looks like I missed that one.

**Comment by igor10k** [comment]
@gionkunz 

![chart](https://cloud.githubusercontent.com/assets/1244342/6427115/4aea78be-bf7f-11e4-84d0-3ea81d2dcbbf.png)

Do you have any ideas about horizontal align? Labels below the charts look out of place. It would be really nice to center them out. I tried `text-anchor: middle` but the placement for all the other labels.

**Comment by gionkunz** [comment]
Did you try to use the `labelDirection` option within the pie chart?

**Comment by igor10k** [comment]
@gionkunz `labelDirection: 'neutral'` fixes the bottom label but breaks all the others, that start overlapping the chart.
I'm thinking about a `labelDirection` that acts as `neutral` when label's at the center and as `explode` in all the other cases.

**Comment by gionkunz** [comment]
@Igor10k I think we could extend / enhance explode so that it applies `text-anchor: middle` if the label is positioned in some angle directly above and below the pie.

**Comment by igor10k** [comment]
@gionkunz it would be real nice if you do this
