### ISSUE TITLE
ct-point with horizontal label

### ISSUE THREAD

**Issue by martinsznapka** [chartist-js/chartist#213]
Hi Gion
Would be nice if ct-point element contains also value from horizontal axis, something like:

``` html
<line x1="" y1="" x2="" y2="" class="ct-point" ct:value="" ct:horizontal-label="27.02.2015"></line>
```

This value is needed for tooltips.
Currently I have workaround for this, which doesn't work when showLabel is false.

``` javascript
chart.on('created', function() {
    var horizontalLabels = svgElement.find('.ct-labels .ct-label.ct-horizontal');

    svgElement.find('.ct-series').each(function() {
        $(this).find('.ct-point').each(function(i) {
            $(this).attr('ct:horizontal-label', horizontalLabels.eq(i).text());
        });
    });
});
```

**Comment by gionkunz** [comment]
Hi Martin

Can't you use meta for this?

``` javascript
var chart = Chartist.Line('.ct-chart', {
  labels: ['One', 'Two', 'Three'],
  series: [
    [{value: 5, meta: 'One'}, {value: 8, meta: 'Two'}, {value: 13, meta: 'Three'}]
  ]
});
```

Then a `ct:meta` attribute will be written to the point line elements.

You can automate this with the following helper function:

``` javascript
function labelsToMeta(data) {
  return {
    labels: data.labels,
    series: data.series.map(function(values, valuesIndex) {
      return values.map(function(value, valueIndex) {
        return {
          value: value,
          meta: data.labels[valueIndex]
        };
      });
    })
  };
}

new Chartist.Line('.ct-chart', labelsToMeta({
  labels: ['One', 'Two', 'Three', 'Four', 'Five'],
  series: [
    [1, 5, 4, 3, 4],
    [2, 3, 2, 2, 3]
  ]
}));
```

**Comment by martinsznapka** [comment]
Well it is a plugin, so I can't manipulate data which goes into Chartist.Line constructor.
Maybe inside plugin I have to listen "on data event"?

``` javascript
chart.on('data', function() {
    labelsToMeta ...
});
```

**Comment by martinsznapka** [comment]
Doesn't work with "on data event":
http://codepen.io/martinsznapka/pen/gbjLeb?editors=101

**Comment by gionkunz** [comment]
It works as longs as you dont change the reference / create a new object. Just modify data.data instead of assigning a new object. You can replace series and labels but if you change the object reference of data.data before you modifications youll not modify the same object inside of the chartist pipeline.

**Comment by gionkunz** [comment]
``` javascript
function labelsToMeta(data) {
  data.series = data.series.map(function(values, valuesIndex) {
    return values.map(function(value, valueIndex) {
      return {
        value: value,
        meta: data.labels[valueIndex]
      };
    });
  });
}

var chart = new Chartist.Line('.ct-chart', {
  labels: ['One', 'Two', 'Three', 'Four', 'Five'],
  series: [
    [1, 5, 4, 3, 4],
    [2, 3, 2, 2, 3]
  ]
});

chart.on('data', function(data) {
  labelsToMeta(data.data);
});
```

**Comment by gionkunz** [comment]
Also useful in this context is that meta can also be a complex object where it will be serialized with `Chartist.serialize` and can be deserialized from the DOM attribute with `Chartist.deserialize`.

``` javascript
function buildMeta(data) {
  data.series = data.series.map(function(values, valuesIndex) {
    return values.map(function(value, valueIndex) {
      return {
        value: value,
        meta: {
          label: data.labels[valueIndex],
          labelIndex: valuesIndex,
          value: value,
          valueIndex: valueIndex
        }
      };
    });
  });
}

var chart = new Chartist.Line('.ct-chart', {
  labels: ['One', 'Two', 'Three', 'Four', 'Five'],
  series: [
    [1, 5, 4, 3, 4],
    [2, 3, 2, 2, 3]
  ]
});

chart.on('data', function(data) {
  buildMeta(data.data);
});

$(document).on('mouseenter', '.ct-point', function() {
  console.log(Chartist.deserialize($(this).attr('ct:meta')));
});
```

http://jsbin.com/wopoya/3/edit?js,console,output

**Comment by martinsznapka** [comment]
The meta property idea is really nice, keeps Chartist code clean and extensible. I will use it in this way, thx for that!

Just one small thing - if more plugins or main code use meta property then they will overwrite each other. Maybe meta property can contain also postfix, so each plugin will keep its meta data separate. Something like:

``` javascript
[
  {
    value: 5,
    meta: 'One',
    meta-pluginABC: '63%',
    meta-pluginXYZ: '28.10.2015'
  },
  ...
]
```

**Comment by gionkunz** [comment]
Hi Martin, that's an interesting thought! I'm not sure however, if this should be managed by Chartist or if the plugin author should be made aware of checking if meta is already present when his plugin kicks in and not wipe the existing meta object as-well as adding properties with their prefixes on their own. One thing to remember is also that meta can contain also primitive data which wont be serialized / json.stringified. In that case you have no option to destroy the logic of a plugin that was processing earlier. For multiple plugins working together I didn't had so many use cases yet, but if you take the three example plugins, they all work hand in hand and without specification order dependencies. If it's getting more complex and a few plugins work with meta in their own way, I think we will need to find a improved solution.

**Comment by martinsznapka** [comment]
Ok, good point. Lets keep it in mind in case of meta conflicts.
Thx for your help.
