### ISSUE TITLE
Start chart at 0,0

### ISSUE THREAD

**Issue by Globegitter** [chartist-js/chartist#218]
I am having a line-chart with values between 8,000-10,000 but I want to be able to play around with where the axis starts. So for example that the y-axis shows 0-10,000 rather than the automatic 8,000-10,000. I haven't found anything in the docs. Is there a possibility to do that right now?

**Comment by gionkunz** [comment]
the `low` and `high` in the options narrow or expand the range of data that is displayed. You can set `low` to 0 and then your values will be drawn in the upper 20% if you go from 8000 to 10000.

**Comment by gionkunz** [comment]
@Globegitter did this solve your issue?

**Comment by gionkunz** [comment]
Please re-open the issue or ask more questions if this was not helpful

**Comment by q2apro** [comment]
Helpful: https://gionkunz.github.io/chartist-js/api-documentation.html

```
var options = {
  high: 100,
  low: 0,
};
```

Chartist is awesome! ;-)
