### ISSUE TITLE
Plugin Idea - Tooltip

### ISSUE THREAD

**Issue by Globegitter** [chartist-js/chartist#219]
Having just looked at another Chart library, Chart.js they seem to have very easy options to just turn on/off tooltips, via some (optional) options:

``` js
    // Boolean - Determines whether to draw tooltips on the canvas or not
    showTooltips: true,
    // Function - Determines whether to execute the customTooltips function instead of drawing the built in  tooltips (See [Advanced - External Tooltips](#advanced-usage-custom-tooltips))
    customTooltips: false,
    // Array - Array of string names to attach tooltip events
    tooltipEvents: ["mousemove", "touchstart", "touchmove"],

    // String - Tooltip background colour
    tooltipFillColor: "rgba(0,0,0,0.8)",

    // String - Tooltip label font declaration for the scale label
    tooltipFontFamily: "'Helvetica Neue', 'Helvetica', 'Arial', sans-serif",

    // Number - Tooltip label font size in pixels
    tooltipFontSize: 14,

    // String - Tooltip font weight style
    tooltipFontStyle: "normal",

    // String - Tooltip label font colour
    tooltipFontColor: "#fff",

    // String - Tooltip title font declaration for the scale label
    tooltipTitleFontFamily: "'Helvetica Neue', 'Helvetica', 'Arial', sans-serif",

    // Number - Tooltip title font size in pixels
    tooltipTitleFontSize: 14,

    // String - Tooltip title font weight style
    tooltipTitleFontStyle: "bold",

    // String - Tooltip title font colour
    tooltipTitleFontColor: "#fff",

    // Number - pixel width of padding around tooltip text
    tooltipYPadding: 6,

    // Number - pixel width of padding around tooltip text
    tooltipXPadding: 6,

    // Number - Size of the caret on the tooltip
    tooltipCaretSize: 8,

    // Number - Pixel radius of the tooltip border
    tooltipCornerRadius: 6,

    // Number - Pixel offset from point x to tooltip edge
    tooltipXOffset: 10,

    // String - Template string for single tooltips
    tooltipTemplate: "<%if (label){%><%=label%>: <%}%><%= value %>",

    // String - Template string for multiple tooltips
    multiTooltipTemplate: "<%= value %>",
```

which then results in something like that:
![screen shot 2015-03-05 at 17 51 02](https://cloud.githubusercontent.com/assets/2580254/6510902/fdd2fc78-c360-11e4-8319-ee365a055e7a.png)

I know there is an example for tooltips, but I think it should just be as simple as a setting, to get this to work. I do want to implement that plugin myself, but putting it down here as a 'todo' since I won't have much time for the next two weeks and just generally to see if that seems like a good idea :)

**Comment by gionkunz** [comment]
:+1: This would be fantastic if someone would take the initialive to create a tool tip plugin

**Comment by Globegitter** [comment]
I created a very simple plugin I am currently using myself: https://github.com/Globegitter/chartist-plugin-tooltip

Can hopefully add more customisation options soon.

**Comment by gionkunz** [comment]
@Globegitter cool and thanks for taking the time to make a public plugin for this! Can you add your plugin to our documentation site? Just add an other section like this: https://github.com/gionkunz/chartist-js/blob/develop/site/data/pages/plugins.yml#L125-L150

**Comment by gionkunz** [comment]
Since you're created a plugin and we can track any improvements there, I'll go a head and close this issue :-)
