### ISSUE TITLE
Plugin Idea - Legends

### ISSUE THREAD

**Issue by Globegitter** [chartist-js/chartist#220]
Similar to tooltips, Chart.js has a simple option for showing a legend:

``` js
   //String - A legend template
    legendTemplate : "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<datasets.length; i++){%><li><span style=\"background-color:<%=datasets[i].strokeColor%>\"></span><%if(datasets[i].label){%><%=datasets[i].label%><%}%></li><%}%></ul>"
```

Showing in up as seen in the picture in https://github.com/gionkunz/chartist-js/issues/219

Again that is something I would like to implement as soon as I find some time. Any thoughts about it are appreciated.

**Comment by gionkunz** [comment]
Generally I do not support library usage for generating labels as this is such a simply and standard task. However, if it's going to be something with more behaviour, like series highlighting on legend hover, this could definitely go into a plugin then.

**Comment by gionkunz** [comment]
@Globegitter I'm closing this issue for now. If you have further ideas please comment on #290
