### ISSUE TITLE
pointOffset as an option?

### ISSUE THREAD

**Issue by gsklee** [chartist-js/chartist#222]
Could we have `pointOffset` as an easy shortcut to do the same thing that is demostrated [here](http://jsbin.com/wumebi/1/edit?js,output)?

**Comment by gionkunz** [comment]
I think this is an edge use case and therefore would not like to include this option. Generally it's more likely to use the `fullWidth` property in conjunction with the `chartPadding` option to make the chart spread in the whole area.
