### ISSUE TITLE
scaleMinSpace for X axis?

### ISSUE THREAD

**Issue by gsklee** [chartist-js/chartist#223]
Is it possible to add `scaleMinSpace` to X axis as well?

**Comment by gionkunz** [comment]
`scaleMinSpace` is only supported for the data axis currently. As the "time" axis is currently step based you should use the `labelInterpolationFnc` on the x-axis in order to skip some grid lines / labels:

``` javascript
var options = {
  axisX: {
    labelInterpolationFnc: function(value, index) {
      return index % 10 === 0 ? value : null;
    }
  }
};
```

The above example will render only every 10th label / grid line.

**Comment by ivictbor** [comment]
would be super awesome to support the same thing on x-axis

**Comment by ivictbor** [comment]
@gionkunz would be super awesome to support the same thing on x-axis
