### ISSUE TITLE
Totally broken chart

### ISSUE THREAD

**Issue by ghauray** [chartist-js/chartist#228]
Hi, 
I'm a french student, so sorry about my english.
I used Chartist some month ago, that was working well. But today, I try to use it on a new project and I have not managed to create a chart.
So, I tried to use chartist in a minimal project, (you can found the code here : https://bpaste.net/show/a8cb1373a839 ).
And I got this (labels are OK, but series are broken).
![](http://i.imgur.com/skrqqVb.jpg)

Thanks by advance ! 
(I tried to search a issue about this and didn't found anything, maybe I fail...)

**Comment by gionkunz** [comment]
It looks like your css hasnt loaded. Can you check if its still there?

**Comment by Hammster** [comment]
``` html
<head>
    <link rel="stylesheet" href="css/chartist.min.css">
    <script src="js/chartist.min.js"></script>
</head>
```

should fix it

**Comment by ghauray** [comment]
Ho no, this is so stupid ... Sorry for this useless topic.
Next time I'm blocked at 4am, I'll wait the next day to try to fix my problem.
Thanks all !
