### ISSUE TITLE
Stacked bar chart where series stack on each other instead of being next to each other

### ISSUE THREAD

**Issue by gionkunz** [chartist-js/chartist#23]

**Comment by adamawesomeface** [comment]
I would like this as well.  I have to do this for a client's site that Chartist has been amazing to work with thus far .. so i may end up forking.

**Comment by SekibOmazic** [comment]
+1!

**Comment by jackblackCH** [comment]
+1

**Comment by gionkunz** [comment]
Im working on an internal restructuring for dom recycling but after that this would be next on my list

**Comment by gionkunz** [comment]
Good news :-) This is coming with the next release which will be this weekend most likely.
