### ISSUE TITLE
crosshair is it possible?

### ISSUE THREAD

**Issue by Dhruuva** [chartist-js/chartist#230]
Hi guys
 Is it possible to implement a simple cross with the help of the chartist-js
, such as on Yahoo or google charts?
like this 
http://finance.yahoo.com/echarts?s=AAPL+Interactive#{%22scale%22%3A%22linear%22}
or like this 
http://www.google.com/finance?cid=22144
Please give some example or any advice
thanks in advance

**Comment by Hammster** [comment]
+1 would love to know

**Comment by gionkunz** [comment]
This could be easily implemented with a plugin. Check the available plugins and plugin examples on http://gionkunz.github.io/chartist-js/plugins.html

**Comment by Dhruuva** [comment]
thank You 
I hope it will be easily for me too
 regards

**Comment by Dhruuva** [comment]
Hi! guys
![cross](https://cloud.githubusercontent.com/assets/5820396/6971057/7fa4e9aa-d982-11e4-9bcd-c64b9d866881.jpg)
I had a couple free days to try create crosshair, so, that is i done please use if you need it,also if you have idea the code enhancement just do it and shared it.
I 'm not realy sure, that this code is perfect, may be there is more effective way to create crosshair with Chartist API.
Also Great Thanks to @blackburn for his post Target lines #235
and of course Gion for answer on it . From there, I found a way to do it
So see the http://jsfiddle.net/dhruuva/56qhbfpw/

have a nice day

**Comment by gionkunz** [comment]
Awesome work man! Maybe we can wrap this into a plugin? I'll look at the code when I got time but Im currently damn busy with work :-/

**Comment by Dhruuva** [comment]
Thank You . Wrap it into plugin is very important task it must be done. In next two days I 'll be implement this in my project charts, it has big data series about 365 points per chart, it will good testing for bugs and after I'll try to make test plugin. I hope can do it. I think it save your time to create quality plugin customizable for all purposes and users.
Best Regards

**Comment by Dhruuva** [comment]
Hi ! I've wrapped it and place here https://github.com/Dhruuva/chartist-plugin-crosshair
Hope it will useful for everyone
Best Regards

**Comment by gionkunz** [comment]
Great effort! Maybe you can make a pull request for the Chartist plugins page too?

**Comment by Dhruuva** [comment]
Hi !
 Ok Thank You .
I try .. my be today or later 
Gion,  are you  mean that 
I must just add my stuff to https://github.com/gionkunz/chartist-js/blob/develop/site/data/pages/plugins.yml  and after pull request from my Chartist fork?
