### ISSUE TITLE
Error Bars

### ISSUE THREAD

**Issue by nblackburn** [chartist-js/chartist#232]
How possible would it be to add error bars to line and bar charts?

![Error Bars](http://www.ats.ucla.edu/stat/stata/faq/barcap1.gif)

**Comment by gionkunz** [comment]
Whats exactly is an error bar? :-) Can you elaborate?

Cheers
Gion

**Comment by nblackburn** [comment]
They are used to show standard deviation and simply are hatted bars that sit above bars and lines to reflect the amount something deviates by.

I have added a screenshot

**Comment by gionkunz** [comment]
This can easily be done with a plugin. You can write your own plugin using these instructions: http://gionkunz.github.io/chartist-js/plugins.html
