### ISSUE TITLE
Is it possible to edit the point size?

### ISSUE THREAD

**Issue by Scribblets** [chartist-js/chartist#233]
Hi, I'd love to be able to make the points a little bit smaller (for a larger, information-intensive line chart). Is it possible to do this?

Thank you!
~ Lindsay

**Comment by Hammster** [comment]
Basically you can replace the points with new ones, dont know if there is an better solution but it works.

http://jsbin.com/ricabuzupe/1/edit?html,js,output

**Comment by gionkunz** [comment]
Use CSS to style your point size. check the CSS generated with chartist. You can just override the stroke-width on the ct-point class.

**Comment by nblackburn** [comment]
Looks like @gionkunz beat me to this one :tongue:

**Comment by gionkunz** [comment]
Closing this issue. Feel free to update and / or re-open if there are still open concerns.

**Comment by Scribblets** [comment]
Thank you!
