### ISSUE TITLE
Left grid scale cutoff on Chrome,Firefox,Opera (Not IE)

### ISSUE THREAD

**Issue by 9607835** [chartist-js/chartist#234]
jsbin.com html+js code taken directly from http://gionkunz.github.io/chartist-js/getting-started.html

http://jsbin.com/yivuvafawi/1/
http://ibin.co/1uikpZPPqOBD

Chrome: Version 41.0.2272.89 m
Firefox 36.0.1
Opera: 28.0.1750.40
IE: 10.0.9200....

please fix, if it is my fault then explain this on the getting-started.html page.
![issue](https://cloud.githubusercontent.com/assets/11466579/6647340/60628b84-c99b-11e4-8e6f-4a4d1a166871.png)

**Comment by Hammster** [comment]
You removed the identifier .ct-chart in your html.

``` HTML
<div id="chartId" class="ct-chart ct-perfect-fourth"></div>
```

But your right,
the "getting started" should show an example for two separate graphs.

**Comment by gionkunz** [comment]
@Hammster , thanks for pointing out. I've included a simple example here: https://github.com/gionkunz/chartist-js/commit/b23179f208758c8ec402f0dee0319f526b9d3a34
