### ISSUE TITLE
Target lines

### ISSUE THREAD

**Issue by nblackburn** [chartist-js/chartist#235]
Most of the plugins I have seen and the one I have worked on for a project work on the data series but was wondering if it was possible and which functions I need to draw a line at a certain value (y-axis) that spans the width of the chart to reflect a target.

**Comment by gionkunz** [comment]
Hey @nblackburn can you provide more background information about what you'd like to achieve?

**Comment by nblackburn** [comment]
Simply drawing a horizontal line at a certain value (for example 125) on the y-axis to show a target :)

I can do the rest, just need to know if there is a function to map a SVG element to a certain y-position on the chart (which I am guessing there will be but couldn't find it in the documentation).

![](http://dedicatedexcel.com/wp-content/uploads/2013/03/00057_Insert-a-Goal-Line-on-Excel-Bar-Chart_01.jpg)

**Comment by gionkunz** [comment]
I'd go with the `created` event. Unfortunately we don't expose the axis objects in that event currently. This would simplify the projection of your line. In the current implementation you need to recreate the projection function. The following example uses clean separation of concerns (styling in CSS). This could also be implemented in a plugin easily. http://jsbin.com/dajole/3/edit?css,js,output

**Comment by nblackburn** [comment]
This is perfect, thank you so much @gionkunz. I love the separation of concerns and use it extensively in my own work.

Perhaps exposing that in the future would open some windows for plugin authors?.

**Comment by gionkunz** [comment]
Yes we need to expose the axes. Ill create an issue for that

**Comment by onidlo** [comment]
Hey @gionkunz! Thank you for your great work!

In some circumstances, the line is rendered with antialiasing, check here:
http://jsbin.com/dototojiha/1/edit?css,js,output

To fix this issue, use:
`.ct-target-line {
  stroke: blue;
  stroke-width: 1px;
  stroke-dasharray: 4px;

  shape-rendering: crispEdges;
}`

**Comment by gionkunz** [comment]
Great :-) Glad it works for you. Yes, shape-rendering: crispEdges; is sometimes also nice if applied to the grid lines. Depends on the use-case.

Cheers
Gion

**Comment by cottsak** [comment]
Neither of those two jsbin links are working for me.. somehow they're triggering 500 responses. I'd like to see this code :(

**Comment by htwyford** [comment]
@cottsak The jsbin links work for me, but here's the code:
```css

 .ct-target-line {
    stroke: blue;
    stroke-width: 2px;
    stroke-dasharray: 4px;
    shape-rendering: crispEdges;
}
```
```js
var chart = new Chartist.Line('.ct-chart', response, {
    targetLine: {
        value: 100,
        class: 'ct-target-line'
    }
});

function projectY(chartRect, bounds, value) {
    return chartRect.y1 - (chartRect.height() / bounds.max * value)
}

chart.on('created', function (context) {
    var targetLineY = projectY(context.chartRect, context.bounds, context.options.targetLine.value);

    context.svg.elem('line', {
        x1: context.chartRect.x1,
        x2: context.chartRect.x2,
        y1: targetLineY,
        y2: targetLineY
    }, context.options.targetLine.class);
});
```

This code is a bit different from what was posted in the jsbin, but @OscarGodson improved the original code in https://github.com/gionkunz/chartist-js/issues/491

The one problem with this approach is that if the target line is far above your data, it doesn't show up on the canvas, since the canvas only draws as high as your highest data point. I'm getting around this by adding the value for the target line as a single-point data series then setting `showPoint: false` on that series, but that's a bit of a hack.

If anyone knows how to manually set the scale of the y-axis so I can draw it as high as my target line, that'd be much appreciated!

**Comment by sladec** [comment]
@htwyford 
var options = {
  // If high is specified then the axis will display values explicitly up to this value and the computed maximum from the data is ignored
  high: 100
}

**Comment by htwyford** [comment]
Amazing. Thank you!

**Comment by purplelady105** [comment]
I have copied the code into my own page, but I cannot get the line to appear on my chart.
What am I missing here?

```
<style>
             .ct-target-line {
                stroke: blue;
                stroke-width: 2px;
                stroke-dasharray: 4px;
                shape-rendering: crispEdges;
            } 
</style>
<script>
            var chart = new Chartist.Bar('.ct-chart', { 
                labels: ['Margin Amount'],
                series: [
                    [
                        {meta: 'Paid Margin', value: <?php echo $bar_paid; ?>}
                    ],
                    [
                        {meta: 'Pending Margin', value: <?php echo $bar_pending_pay; ?>}
                    ],
                    [
                        {meta: 'Potential Margin', value: <?php echo $bar_potential; ?>}
                    ],
                    [
                        {meta: 'Margin to Next Level', value: <?php echo $bar_goal_line; ?>}
                    ]
                ],
                targetLine: {
                    value: <?php echo $bar_goal_line;?>,
                    class: 'ct-target-line'
                }
            },
            {
                fullWidth: true,
                plugins: [
                    Chartist.plugins.tooltip({
                    currency: '$',
                    anchorToPoint: false
                  }),
                  Chartist.plugins.ctPointLabels({
                    textAnchor: 'middle'
                  })
                ],
                chartPadding: 30,
                stackBars: true,
                axisY: {
                    labelInterpolationFnc: function (value) {
                         return '$' + (value / 1000) + 'k';
                    },
                    <?php echo $set_max_y_axis;?> /*Set this value to define a max value for the bar(s) */
                }
            });
            // draw the bar chart
            chart.on('draw', function (data) {
                if (data.type === 'bar') {
                    data.element.attr({
                        style: 'stroke-width: 60px'
                    });
                }
            });
            
            function projectY(chartRect, bounds, value) {
                return chartRect.y1 - (chartRect.height() / bounds.max * value);
              }

              chart.on('created', function(context) {
                var targetLineY = projectY(context.chartRect, context.bounds, context.options.targetLine.value);

                context.svg.elem('line', {
                  x1: context.chartRect.x1,
                  x2: context.chartRect.x2,
                  y1: targetLineY,
                  y2: targetLineY
                }, context.options.targetLine.class);

                context.svg.elem('line', {
                  x1: context.chartRect.x1,
                  x2: context.chartRect.x2,
                  y1: 175000,
                  y2: 175000
                }, context.options.targetLine.class);

              });
        </script>
```

![image](https://user-images.githubusercontent.com/28715727/29191913-3392c7e6-7dd4-11e7-87b2-192d1aa2100f.png)

**Comment by htwyford** [comment]
@purplelady105 looks like you've included 
```js
targetLine: {
    value: <?php echo $bar_goal_line;?>,
    class: 'ct-target-line'
}
``` 
in your `data` object, but it should be in the `options` parameter with plugins and the like.

**Comment by htwyford** [comment]
As per @gionkunz's now two-year-old recommendation, I've made a plugin for this. I've done a couple of quick tests with both Line and Bar charts. 

https://github.com/htwyford/chartist-plugin-targetline

**Comment by purplelady105** [comment]
@htwyford Thank you so much!! This was driving me crazy all week and it was something so simple.

**Comment by MikPak** [comment]
@htwyford Just wanted to come say thanks for this plugin! Made my day.
