### ISSUE TITLE
Is it possible to tilt the labels in bar chart?

### ISSUE THREAD

**Issue by nishtha3rai** [chartist-js/chartist#237]
Hi, I was trying to figure out an option to tilt the labels in bar chart. Is there a way for that?

**Comment by Hammster** [comment]
You can use css to rotate the labels ;)

http://jsbin.com/hisomococe/1/edit?css,output

**Comment by nishtha3rai** [comment]
That's great. But I only wanted to tilt the x axis labels. Is it possible cause ct-labels is affecting both xy axis labels.

**Comment by danieldiekmeier** [comment]
All horizontal label have the classes `.ct-label` and `.ct-horizontal`, so if you use `.ct-horizontal` instead of `.ct-label`, it will work.

**Comment by nishtha3rai** [comment]
That's cool. Thanx :)

**Comment by gionkunz** [comment]
Thanks guys!

**Comment by evanleck** [comment]
Hey y'all, maybe this has already been dealt with elsewhere but I'm having an issue with CSS transforms due to <IE10 [not supporting CSS transforms on SVG elements](http://caniuse.com/#search=transform) (see the "Known issues" tab). Is there a good way to replicate the effect of a CSS transform directly from JavaScript? I'm sorry if this is silly, I'm really unfamiliar with SVG transforms and I've been digging through the docs for a bit trying to figure it out to no avail :/

Thanks!

**Comment by evanleck** [comment]
Follow up! I've basically replicated the functionality I was looking for using attributes on the SVG elements like so:

``` coffee
bar = new Chartist.Bar('.chartist-bar', data, options)

bar.on 'draw', (data) ->
  if data.type is 'label'
    n = $(data.element._node)

    if data.axis.units.dir is 'horizontal'
      x = data.x
      y = data.y

      n.css 'overflow', 'visible'
      n.attr 'transform', "translate(5, -10) rotate(30 #{ x } #{ y })"
    else if data.axis.units.dir is 'vertical'
      n.attr 'text-anchor', 'end'
```

Just thought I'd share!

**Comment by daN4cat** [comment]
Using the example from the jsbin link it looks to me like it's better to use `.ct-label.ct-horizontal` rather than `.ct-horizontal` because the latter affects the grid lines too.

**Comment by malthe** [comment]
Note that on Chrome – different from both Firefox and IE11 – attribute-based transform does not work on foreign objects.

I had to use both @evanleck's approach for IE and style-based transformation for Chrome – taking care to vendor-prefix so as not to transform doubly on Firefox.
