### ISSUE TITLE
Access total in stacked bar chart

### ISSUE THREAD

**Issue by akhasis** [chartist-js/chartist#238]
Im trying to add a tooltip in a stacked bar chart on each of the bars, displaying how much each series represents in the bar. Think of the following series:

series: [
    [800000, 1200000, 1400000, 1300000],
    [200000, 400000, 500000, 300000],
    [100000, 200000, 400000, 600000]
  ]

I want the first bar (800000) to display "800000/1100000" in the tooltip. Is it possible to access that 1100000 value?

Thanks in advance

**Comment by gionkunz** [comment]
You can use the data event to transform your data from array notation to object notation. This way you can add a meta attribute to your data points. The meta attribute will be written into the DOM as attribute ct:meta on each bar. Just modify the data during the data event is perfectly fine (as this event is designed for this). You can use simple array extra functions to re-map your data. If you're using a tool tip you can simply query your DOM for this arrtibute. I've put together an example that also uses a jQuery tooltip plugin that demonstrates how easy it is to integrate a tool tip plugin:

http://jsbin.com/yoxizu/1/edit?js,output

**Comment by akhasis** [comment]
Thanks for you reply. Keep up the great work!

**Comment by akhasis** [comment]
Sorry to keep bothering you with a problem that may be more related to my lack of expertise in javascript than to your library:

I'm try to apply your example to a series like this:

series: [
              {
              className: "ct-series-alto",
              name: "Conseguido",
              data: [800000, 1200000, 1400000, 1300000],
            },
            {
              className: "ct-series-medio",
              name: "En progreso",
              data: 
            [200000, 400000, 500000, 300000],
            },
            {
              className: "ct-series-bajo",
              name: "Sin conseguir",
              data: 
            [100000, 200000, 400000, 600000],
            },
            {
              className: "ct-series-vacio",
              name: "Sin datos",
              data: 
            [800000, 1200000, 1400000, 1300000],

```
        },
      ]
    },
```

I get the following error:
Uncaught TypeError: undefined is not a function

Thanks for your help

**Comment by gionkunz** [comment]
No worries, can you show the whole code? Maybe paste it on jsbin?

**Comment by gionkunz** [comment]
I'm closing this issue. Please provide input and re-open if needed.

**Comment by akhasis** [comment]
Sorry, recently got back from holidays and had to catch up on other issues. Besides, I was not getting emailed your reply notifications, so I couldn't reply earlier.

My example at http://jsbin.com/yajixayeqi/edit?html,js,output is very simplified (the actual chart has more than 20 bars) so please let me know if I let out any important piece of info.
