### ISSUE TITLE
Pie Chart loading issue

### ISSUE THREAD

**Issue by joshiashish23** [chartist-js/chartist#241]
I can not generate pie chart in Chartist.js 0.7.3 version but it works in Chartist.js 0.5.0. I want to generate horizontal bar chart and pie chart which is support in newer version not in older version. Can any one help me out in this? Bar chart is working fine with following data but pie chart is not working.

var CategoryValueTitleArray = [];
var CategoryValuePointsArray = [];
@foreach (var item in Model.LeadScoringExplicitValues)
{

```
<text>
CategoryValueTitleArray.push('@item.Value');
CategoryValuePointsArray.push('@item.Point');
</text>        
}
```

var data = {
labels: CategoryValueTitleArray,
series: CategoryValuePointsArray
};

```
var options = {
    labelInterpolationFnc: function (value) {
        return value[0]
    }
};

var responsiveOptions = [
  ['screen and (min-width: 640px)', {
      chartPadding: 30,
      labelOffset: 50,
      labelDirection: 'explode',
      labelInterpolationFnc: function (value) {
          return value;
      }
  }],
  ['screen and (min-width: 1024px)', {
      labelOffset: 40,
      chartPadding: 20
  }]
];

new Chartist.Pie('#explicit-value-piecanvas', data, options, responsiveOptions);
```

Passing static data like below it's working but with above code(dynamic data) it's not working

 labels: ['Bananas', 'Apples', 'Grapes'],
  series: [20, 15, 40]

**Comment by gionkunz** [comment]
You should debug what kind of array you're passing to chartist effectively. In the Pie, unlike in all other chart types, you need to pass an array of values `[1, 2, 3]`. Other charts accept an array of series arrays of values `[[1, 2, 3], [1, 2, 4]]`

**Comment by joshiashish23** [comment]
Values passing in array like below:
CategoryValueTitleArray : [ABC,DEF,GHI,Test input added by user,MNO,PQR,STU,WXY,Z,ABCD,XYZW]

CategoryValuePointsArray : [12,15,12,45,78,10,12,4,5,13,20]

Eventhen pie chart not created.
IS it a wrong way to pass data for pie Chart ?

**Comment by gionkunz** [comment]
Can you show the output when you do:

``` javascript
chart.on('data', function(data) {
  console.log(data);
});
```

**Comment by joshiashish23** [comment]
If I m wring data then it's given [object object]

but if I write data.labels then it gives = [ABC,DEF,GHI,Test input added by user,MNO,PQR,STU,WXY,Z,ABCD,XYZW]
 & if I write data.series then it gives = [12,15,12,45,78,10,12,4,5,13,20]

**Comment by joshiashish23** [comment]
Issue resolved It was a silly mistake, no need for single quotes create points array
Previous :
<text>
CategoryValueTitleArray.push('@item.Value');
CategoryValuePointsArray.push('@item.Point');
</text>
After :
<text>
CategoryValueTitleArray.push('@item.Value');
CategoryValuePointsArray.push(@item.Point);
</text>

**Comment by gionkunz** [comment]
Glad you've found the issue :-)
