### ISSUE TITLE
Adding extra 'height' to bars to avoid them being tiny

### ISSUE THREAD

**Issue by ghost** [chartist-js/chartist#243]
Hi!

I have some bar charts which contain some very small values (alongside larger one) - this can result in some bars being tiny - perhaps just 1-2px high (so far I've not seen a 0px but I guess it could happen)

I also have a tooltop/mouseover thing working - but it's VERY hard for the user to actually mouseover tiny bars like that

Is there a known trick to get around this?  I'm thinking of

a - adding a bit of height to all the bars (I don't show a Y Axis scale so that's not a problem)
b - allowing the user to mouseover the 'space' above a bar

I realise that for b I could just include a 'stacked' dataset which happens to 'fill up' the space in the chart (e.g. largest-bar-val-val) but set it to the same color as the background (same labels - thus tooltips would appear?)

Thought I'd ask to see if anyone had a better idea/there was a known trick first tho!

**Comment by gionkunz** [comment]
There are some workarounds for this I can think of but nothing will work 100%.

a) Implement your own hit testing where you track mousemove and if the mouse approximates a bar you could show the label
b) With the draw event you could draw an invisible (transparent) clone of the bar that is larger and do the mouse event handling on this clone

However if you would stack your bars, you'll have a problem again. If you have 5 stacked bars where 4 of them are just 1px in height, you can't really use the above approach.

**Comment by gionkunz** [comment]
I'm closing this for now. Feel free to comment further.
