### ISSUE TITLE
Bar chart + line chart?

### ISSUE THREAD

**Issue by nickyhajal** [chartist-js/chartist#244]
Is it possible to have a bar graph and a line graph in a single chart?

Similarly, is it possible to have 2 separate line graphs in a single chart with different left and right axis?

Thanks!

**Comment by onidlo** [comment]
Hi,

as far as I know, currently it is not possible. You can put two divs into same position, like this:
          #ct-chart-1{position:absolute;z-index:101;width: 750px;}
          #ct-chart-2{position:absolute;z-index:100;width: 750px;}

`<div style="width:750px; height: 465px; background-color: #fee">
       <div class="ct-chart ct-golden-section" id="ct-chart-1"></div>
       <div class="ct-chart ct-golden-section" id="ct-chart-2"></div>
  </div>`

And then:
var lineChart = new Chartist.Line('#ct-chart-1', {... });
new Chartist.Bar('#ct-chart-2', {});;

Regards,
Ondrej

**Comment by gionkunz** [comment]
This is tracked with #37 and I've added this to the 1.0 milestone. Please track any progress there.

Cheers
Gion

**Comment by meenaidde** [comment]
Hi,
I'm trying to  combine bar chart and line chart
I have tried with the below code, Its working fine
#ct-chart-1{position:absolute;z-index:100;width: 500px;height:500px;}
#ct-chart-2{position:absolute;z-index:100;width: 500px;height:500px}

But when i try to apply chartist  bar and line graphs on the above divs like given below
new Chartist.Line('#ct-chart-1', {... });
new Chartist.Bar('#ct-chart-2', {});;

I am not getting Labels and series of bar and line chart in same location i.e., One above the other.

Can any one help me on this or suggest me if there is some other way of doing this.
