### ISSUE TITLE
Responsive Setting Overrides in ie9

### ISSUE THREAD

**Issue by informa** [chartist-js/chartist#246]
I can't seem to work out how to get the responsive setting overrides to work in ie9.
I have included matchMedia js and this then makes the chart work in ie9 but once I include the responsive overrides in the init the chart disappears.  It doesn't work in ie9 on the the getting-started page either for the responsive sugar topping (the bar chart). 

Wondering what I am doing wrong. It looks like matchMedia is included in chartist.js as apart of the responsiveOptions so am not sure I need to add another condition in my code?

**Comment by gionkunz** [comment]
@informa I guess we should be more explicit in the documentation and I also think we are not including the right resources in the documentation page. You need to use matchMedia polyfill as well as the addListener addon on top: https://github.com/paulirish/matchMedia.js/blob/master/matchMedia.addListener.js

If you include both matchMedia.js and matchMedia.addListener.js your responsive overrides should work in IE9.

**Comment by informa** [comment]
Great thanks @gionkunz I'll give that a go. I really like chartist, I find it easier to use than other chart libraries.
