### ISSUE TITLE
Vertical labels cut off

### ISSUE THREAD

**Issue by alexcarpenter** [chartist-js/chartist#247]
The vertical labels keep getting cut off on our charts. Found no way to add some padding or account for larger numbers.

![](https://s3.amazonaws.com/f.cl.ly/items/3K2L1I430t3Z330l3z0i/Image%202015-03-26%20at%204.47.09%20PM.png)

**Comment by gionkunz** [comment]
In the API documentation check the default options of the line chart http://gionkunz.github.io/chartist-js/api-documentation.html

There is a chartPadding option.

Cheers
gion

**Comment by tecnogram888** [comment]
chartPadding does not fix the problem for me

**Comment by gionkunz** [comment]
Please open a new issue and describe your problem with an example. Thanks. @alexcarpenter I'll go a head and assume your issue is fixed. If you still have issues with this feel free to update the issue. Cheers
