### ISSUE TITLE
Space between pie chart segments

### ISSUE THREAD

**Issue by malissa** [chartist-js/chartist#248]
Is there a way to put some space between my pie chart segments?  Like so: http://www.conceptdraw.com/How-To-Guide/picture/Pie-chart-Sector-weightings.png

**Comment by Hammster** [comment]
Hi there, yeah there is an plugin avaiable for that.
you'll find more when browsing chartist-plugin on GitHub ;)

https://github.com/jeromeWeb/chartist-plugin-slicedonutmargin

**Comment by gionkunz** [comment]
I'm closing this issue for now. Feel free to dicsuss further.

**Comment by RicardoVilaca** [comment]
In case you still need an answer and the plugin doesn't work:

Try this (but replace the ct-slice-donut-solid for the class of the pie chart)

.ct-slice-donut-solid {
        stroke: white;
        stroke-width: 5px;
}
