### ISSUE TITLE
When low == high, high gets a +1

### ISSUE THREAD

**Issue by aaronik** [chartist-js/chartist#250]
I have a `Line` chart that may have all `0`s for the series values (`series: [[0, 0, 0, 0, 0...]]`). When that is the case, I'd like the chart to only show one `axisY` label. Instead, even though I'm specifying `low: 0` and `high: 0` in the options, I'm seeing this:

![image](https://cloud.githubusercontent.com/assets/1324601/6930328/21c23382-d7b7-11e4-92e2-4bfbb2d8e826.png)

Can you folks get rid of the 1 at the top and allow for a single Y label?

Oh, also, in that picture, I'm removing non-integer labels, (https://github.com/gionkunz/chartist-js/issues/77), so there's probably stuff in between as well.

For now I'll filter out the `1` like I am the non-integer labels, and I'll collapse the height of the graph if the `low` == `high` (also something my design team has specified they wanted), so this isn't a critical issue for me, just a nice-to-have :)

**Comment by gionkunz** [comment]
Hi there. Currently Chartist is not accepting the same value for low as for high. It will increase high +1 automatically if they are the same. 

I recommend you to use the data event in conjunction with the draw events to implement your requirement.

This could be something like this:
http://jsbin.com/cupawo/1/edit?js,output

Cheers
Gion

**Comment by gionkunz** [comment]
Hey there. I'm closing this issue for now. Feel free to comment further.
