### ISSUE TITLE
Setting a label at a specific series

### ISSUE THREAD

**Issue by ghost** [chartist-js/chartist#253]
Hi, thanks for a great library @gionkunz and other contributors. I have a question considering adding labels to the series. 

I have a stacked bar chart, and am using it to display time in separate types of time (i e administration, project). I've styled it a bit and it's a breeze (super-friendly to just jump into, great job:smile:).

![dump](https://cloud.githubusercontent.com/assets/5548943/6937018/7dd1c830-d858-11e4-8846-c14c95dd8eea.png)

This is just mock-data with fake initials, but it exemplifies what I'm trying to achieve: at the series labels for axisY I'd like to add a marker text at 100. This should be a custom styled span, I guess. 

How would I go about doing this?

PS. Have been looking through the API docs and Googled a bit, but haven't found anything. If I've missed it, please point me to the URL I'm looking for. DS.

**Comment by gionkunz** [comment]
Hi there!

You should use the Chartist events (which unfortunately are not yet documented #90). Maybe this example can help you: http://jsbin.com/wawabo/1/edit?js,output

Cheers
Gion

**Comment by ghost** [comment]
Thanks, I'll fiddle with your example as a starting ground. Great work. /Anton
