### ISSUE TITLE
low and high options ignored when height is specified.

### ISSUE THREAD

**Issue by thatandyrose** [chartist-js/chartist#254]
I’m finding that when a fixed height is specified and the high and low numbers are a certain number then the properties aren’t honoured.

I’ve created a Codepen for this:

http://codepen.io/thatandyrose/pen/bNZOMp

Note here that I’ve set high to 0, and low to -9000 but Chartist is ignoring this.

Also note that if I set low to -9500 then 0 is at least honoured…..

Any ideas what’s going on here?

**Comment by gionkunz** [comment]
@thatandyrose maybe you can share your findings in this issue?

**Comment by thatandyrose** [comment]
hey @gionkunz for sure. I thought I'd open a PR, you cool with that?

**Comment by gionkunz** [comment]
@thatandyrose did you came to a conclusion? The last thing I remember was that it depends on the data right? Maybe we can write up a small spec?

**Comment by gionkunz** [comment]
@thatandyrose This is no longer an issue in the current version. The available space is used in all scenarios.

**Comment by thatandyrose** [comment]
hey @gionkunz sorry I took so long to reply to this! I was actually looking at creating a PR and then got the latest version just a few days ago and saw that yes, this was no longer an issue! Good work and thank you!
