### ISSUE TITLE
Horizontal bar chart

### ISSUE THREAD

**Issue by dsbudiac** [chartist-js/chartist#26]
I know new chart types aren't a huge priority right now, but would really love to see horizontal bar/row charts added. Or documentation on how I might go about extending on my own :)

**Comment by gionkunz** [comment]
:+1:

**Comment by LeoIannacone** [comment]
+1 :+1:

**Comment by jbwl** [comment]
+1  :+1:

**Comment by jakubstrama** [comment]
:+1:

**Comment by X13454** [comment]
+1 :)

**Comment by albertocoletta** [comment]
+1 =)

**Comment by codycurley** [comment]
+1

**Comment by sheebypanda** [comment]
+1

**Comment by iansmith9876** [comment]
+1

**Comment by gionkunz** [comment]
Ok this is a most wanted feature :-) we should pick this up very soon. I'll treat this as priority.

**Comment by coderaiser** [comment]
Would be great to have ability to do this, really.

**Comment by Rodeoclash** [comment]
+1

**Comment by pawelst** [comment]
+1

**Comment by Founts** [comment]
+1 Needing this today. Going to have to use another solution to make it happen in the near-term.

**Comment by 0o-de-lally** [comment]
+1 love chartist, but must use a D3 solution until this exists.

**Comment by p5150j** [comment]
@gionkunz any working examples of this yet? fiddle me?

**Comment by gionkunz** [comment]
Hi guys. #165 is the groundwork for horizontal bar charts. Im currently working on this and the option to make the bar chats horizontal will be available very soon.

**Comment by p5150j** [comment]
:thumbsup:

**Comment by p5150j** [comment]
@gionkunz :thumbsup: I owe you a :beer:

**Comment by Vilsepi** [comment]
I was banging my head to the wall on why I couldn't get these working like the [code examples](http://gionkunz.github.io/chartist-js/examples.html#horizontal-bar-chart) show. It seems that [cdn.jsdelivr.net/chartist.js/latest/chartist.min.js](http://cdn.jsdelivr.net/chartist.js/latest/chartist.min.js) shown on the Getting Started page does not actually return the latest version, but an age-old 0.5.0. I pointed manually to the version 0.7.1 and the horizontal bars work great! :+1:

**Comment by gionkunz** [comment]
Glad you figured it out :-) I've cleared the cache on jsdelivr. Latest should now serve 0.7.1.

Cheers
Gion

**Comment by jbwl** [comment]
Thank you for implementing this! Finally I can move from dc.js to Chartist.
