### ISSUE TITLE
Document supported events in Chartist and provide some advanced examples on how to use them

### ISSUE THREAD

**Issue by gsklee** [chartist-js/chartist#260]
On http://gionkunz.github.io/chartist-js/api-documentation.html#chartistbase-function-on it says:

`event ( String )
Name of the event. Check the examples for supported events.`

Is it possible to have a list of all events being listed out here instead of checking out each example one y one?

**Comment by gionkunz** [comment]
You can use a wildcard callback. When you do `chart.on('*', cb)` where `cb` is of signature `function(eventName, data)`

Cheers
gion

**Comment by gsklee** [comment]
@gionkunz I mean, we need a documentation which lists out all available event names that we can use.

**Comment by gionkunz** [comment]
Ah sorry :-) I misunderstood your question. Of course, we need to document the events! I thought about creating even a separate page for this with introduction, event list and examples. This should be tracked here #90

**Comment by gionkunz** [comment]
I'll close this in favor of #90
