### ISSUE TITLE
Pie chart - specifying width and height in % isn't working

### ISSUE THREAD

**Issue by gsklee** [chartist-js/chartist#263]
According to the [documentation](http://gionkunz.github.io/chartist-js/api-documentation.html#chartistpie-declaration-defaultoptions), the width and height of a pie chart can be specified in %, yet it's not working correctly.

Demo - Width is being specified as 100% yet the chart shrinks to a far smaller size:
http://jsbin.com/yenepayuba/2/edit?html,js,output

**Comment by gsklee** [comment]
Additionally, a pie chart with either width or height or both being specified will not be drawn in the center of the container. I think it's more reasonable that the chart retains its center positioning.

**Comment by gionkunz** [comment]
Hey there. It looks like this fallback https://github.com/gionkunz/chartist-js/blob/develop/src/scripts/core.js#L573-L574 is the wrong way around. If width and height of the element is 0 it should actually fall back to the options and assume pixel (unitless). This is necessary specifically when used in SVG context (initialize Chartist on an SVG element itself inside of a drawing, same what's done on the Chartist landing page).

**Comment by gionkunz** [comment]
fixed with 2fe5a1d

**Comment by gsklee** [comment]
@gionkunz :+1:
