### ISSUE TITLE
Pie Chart bug when one serie is 0 and the other is equal to total

### ISSUE THREAD

**Issue by JessicaGzz** [chartist-js/chartist#265]
Hi!

I'm working with chartist and i recently found this bug, when the code to print the chart is like:

new Chartist.Pie('.ct-chart', {
  series: [{data:0,
               className: 'color1'
              }, {data: 100,
             className: 'color2'
             }]
}, {
  donut: true,
  donutWidth: 15,
  startAngle: 360,
  total: 100,
  showLabel: false
});

Also verify in the page with the live examples, I use that code because i need to declare the specific class for each serie, so please if you can help me, i really appreciate it.

Thanks in advance : D

![image](https://cloud.githubusercontent.com/assets/11434959/7073017/26df8ef4-deb6-11e4-97c3-39efcac7f85d.png)

*When all series data is different of 0 there's no problem

![image](https://cloud.githubusercontent.com/assets/11434959/7073025/3362e37e-deb6-11e4-850f-03d3904f5d37.png)

**Comment by gionkunz** [comment]
Clearly a bug. We'll work on that.

**Comment by JessicaGzz** [comment]
Thanks!  
I will keep an eye on it. :D
