### ISSUE TITLE
Start a second line mid graph?

### ISSUE THREAD

**Issue by lsteel** [chartist-js/chartist#267]
I'd like to have multiple lines on a graph, but I'd like the other lines not to start until midway through the graph:

var data = {
  labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
  series: [
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    [na, na, na, na, 5, 6, 7, 8, 9, 10, 11, 12],
    [na, na, na, na, na, na, na, 8, 9, 10, 11, 12]
  ]
};

They're not 0's, is there a way to do this?

**Comment by gionkunz** [comment]
This is a feature we are considering to include into the core. In the meanwhile check out the missing data plugin: https://github.com/oliveraustria/chartist-plugin-missing-data

**Comment by gionkunz** [comment]
We'll track any further progress on this here: #294

Cheers
Gion
