### ISSUE TITLE
Destroy the labels completely? 

### ISSUE THREAD

**Issue by bluematter** [chartist-js/chartist#269]
It is really hard to find out how to completely destroy the labels. I am not talking about doing `display:none` on the `.ct-labels, .ct-grids` but completely destroying them so I can sit the grid flush end to end.

Here is an example

![alt text](http://s1.postimg.org/tfh4eg59b/Capture.png)

**Comment by Dhruuva** [comment]
Hi !
my  be this help 
try in chart option set  chartPadding: {right: 0,left:-40 ,bottom:-50,top:0},

**Comment by gionkunz** [comment]
Or do:

``` javascript
chart.on('draw', function(context) {
  if(context.type === 'label'){
    context.element.renove();
  }
});
```

**Comment by bluematter** [comment]
Thanks guys, but unfortunately it did not work. I still have the gutter around the chart, love this project, but it would really be nice to have super minimal charts.

**Comment by gionkunz** [comment]
@Bluematter If you don't want to have labels at all, no grid lines and remove all offsets and padding you can do so but it requires quite a bit of configuration:

``` javascript
var chart = new Chartist.Line('.ct-chart', {
  labels: [1, 2, 3, 4],
  series: [
    [1, 4, 2, 5],
    [2, 3, 1, 4]
  ]
}, {
  showPoint: false,
  showLine: false,
  showArea: true,
  fullWidth: true,
  showLabel: false,
  axisX: {
    showGrid: false,
    showLabel: false,
    offset: 0
  },
  axisY: {
    showGrid: false,
    showLabel: false,
    offset: 0
  },
  chartPadding: 0,
  low: 0
});
```

http://jsbin.com/patela/1/edit?html,css,js,output

**Comment by gionkunz** [comment]
Currently chartPadding will completely replace the axis offsets, we have an open issue for this that requires deprecation #214

**Comment by gionkunz** [comment]
Closing this issue for now. If you're having any further issues please re-open.
