### ISSUE TITLE
Path API for donut charts?

### ISSUE THREAD

**Issue by Scribblets** [chartist-js/chartist#273]
Is this possible? I can't seem to find any documentation on this.

**Comment by danieldiekmeier** [comment]
Can you give more information on what you want to do?

**Comment by gionkunz** [comment]
Yes, its already implemented in develop branch and will be released soon.

**Comment by gionkunz** [comment]
Oops.. Will close this issue once released.

**Comment by Scribblets** [comment]
Yay glad to hear. Looking forward to the release.

**Comment by gionkunz** [comment]
0.7.4 is out
