### ISSUE TITLE
Question: Stacked Bar Labels

### ISSUE THREAD

**Issue by mturnwall** [chartist-js/chartist#274]
Is there a way to place labels on top of the stacked bars? 

![image](https://cloud.githubusercontent.com/assets/44970/7175273/7f314ce4-e3c7-11e4-8990-f4f8e57bb0b5.png)

**Comment by danieldiekmeier** [comment]
You can probably just use CSS `transform: translateY()` to move them up. The class is `.ct-label`.

**Comment by gionkunz** [comment]
This can be done using the draw events. Unfortunately we have a lack in documentation here. You can search the github issues for draw events https://github.com/gionkunz/chartist-js/search?q=draw+events&type=Issues&utf8=%E2%9C%93 for some examples.

**Comment by gionkunz** [comment]
Its currently a bit hacky but we'll add more information to the draw events with #293 

http://jsbin.com/wacuva/2/edit?css,js,output

Please discuss further if you need more help.

Cheers
Gion

**Comment by ghost** [comment]
@gionkunz thank you for the jsbin example. I am struggling with showing an actual bar value from data. Any help would be appreciated.

Based on your jsbin example I am trying to do something like that:

![Example](http://f.cl.ly/items/3C371K3e0l0C0h3k2c3o/Screen%20Shot%202015-09-30%20at%2010.27.07.png)

Thank you.

**Comment by gionkunz** [comment]
Just replace 

``` javascript
    context.element.root().elem('text', {
      x: context.x1,
      y: context.y2 + 5
    }, 'ct-bar-label').text(seriesName);
```

with 

``` javascript
    context.element.root().elem('text', {
      x: context.x1,
      y: context.y2 + 5
    }, 'ct-bar-label').text(context.value.y);
```

**Comment by ignaty** [comment]
@gionkunz thank you! Need more case studies on a website :)

**Comment by ghost** [comment]
@gionkunz thank you.

**Comment by ghost** [comment]
@gionkunz is there a way to check if bar labels overflow each other and push them somehow?

![screen shot 2015-10-07 at 12 46 27](https://cloud.githubusercontent.com/assets/803990/10336569/8b139e50-6cf1-11e5-9b70-da7c25b98d53.png)

As a potential solution set minimum bar height (regardless minimum value) which will make text:

a) always visible
b) never overflown each other

**Comment by mdezc** [comment]
@ignaty did you ever figure out how to avoid the stacking labels? Thanks!
