### ISSUE TITLE
Stacked bars do not play nicely with bipolarity.

### ISSUE THREAD

**Issue by livtanong** [chartist-js/chartist#276]
It looks like the issue is caused by the algorithm responsible for positioning the stacked bars. It's getting the base (or bottom, if the value is positive) position of series n from the extremity (or top, if the value is positive) of series n-1. It should clamp to 0.

Note the image below. The first bar actually has a hidden red bar behind it. The bottom of the peach bar should be anchored to the origin, rather than the extremity of the hidden red bar.

![screen shot 2015-04-17 at 03 34 32](https://cloud.githubusercontent.com/assets/869638/7189624/b591e51e-e4b2-11e4-8885-b7fd288bdb26.png)

**Comment by gionkunz** [comment]
HI @levitanong can you share the code to reproduce the issue?

Cheers
Gion

**Comment by gionkunz** [comment]
Also what behaviour would you expect from a stacked bar chart with negative values? I guess a bi-polar stacked bar chart is quite difficult to visualize? Never thought about this to be honest. I think I tried once with only negative values, but not mixed.

**Comment by gionkunz** [comment]
Hey there, I'll close this issue for now. If you can show me a valid use case where you'd include positive and negative values in a stacked bar chart, please comment on further and we can discuss.

**Comment by moneytree-doug** [comment]
@gionkunz With negative values, I would expect this type of chart: http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-http://www.highcharts.com/demo/bar-negative-stack

Is there anyway to achieve that with today's build?

**Comment by moneytree-doug** [comment]
@gionkunz Okay, so I can have it behave that way if I have the stack bars draw from the zeroPoint line at this line: https://github.com/gionkunz/chartist-js/blob/dd3fe00a6b72f9dcddb43a91f39210bbaa73d47e/src/scripts/charts/bar.js#L325

Would it be better to add an option? 
```
stackBars: true,
negativeStack: true  # this would imply that stackBars is true
```
