### ISSUE TITLE
Styling with Less

### ISSUE THREAD

**Issue by Martinomagnifico** [chartist-js/chartist#279]
Is it possible to have the styling with Less? I would like to integrate the styling into an existing Less workflow, so I can use the same color variables.

**Comment by nblackburn** [comment]
I am doing this so it's defiantly possible but not by default.

**Comment by gionkunz** [comment]
@Martinomagnifico Just copy the CSS of chartist into chartist.less and make it dynamic where you need to. There is no base support for LESS and there won't be until there is a 100% working transpiler from Sass to LESS see #84
