### ISSUE TITLE
Styling of main axis

### ISSUE THREAD

**Issue by Martinomagnifico** [chartist-js/chartist#280]
How can I style both 0-axes differently from the other gridlines? I tried .ct-grid.ct-horizontal:first-child and .ct-grid.ct-vertical:first-child, but that doesn't work. At first I thought it was because I had all vertical gridlines turned off with showGrid: false (where I only wanted to turn off the non-0-lines) , but that wasn't the issue.

**Comment by Dhruuva** [comment]
You can take code for this from my plugin https://github.com/Dhruuva/chartist-plugin-crosshair
in brief
chart.on('draw', function(data) {
            if(data.type === 'grid') {
                   if ( data.index==0){
                      data.element.addClass("axis");
                    };
});
in css add this
.ct-chart .ct-grid.ct-horizontal.axis{stroke:dimgray; stroke-dasharray: none;}
.ct-chart .ct-grid.ct-vertical.axis{stroke:dimgray; stroke-dasharray: none;}

**Comment by Martinomagnifico** [comment]
Thanks. This worked!
