### ISSUE TITLE
Value of column bar above it

### ISSUE THREAD

**Issue by Martinomagnifico** [chartist-js/chartist#281]
How can I show the value of the column above it? I thought it would be easy with the Point label plugin, but I can't get it to work. I would also even like to change the appearance of it depending on the series (first column gets larger text than the other ones).

**Comment by Martinomagnifico** [comment]
OK I fixed it. Got it to work with the example code from Bob Yexley on #196,  and 

```
var euro = function(x) {
    return '€' + x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, '.');
};
chart.on('draw', function(data) {
  var barHorizontalCenter, barVerticalCenter, label, value;
  if (data.type === "bar") {
    barHorizontalCenter = data.x1 + (data.element.width() * .5);
    barVerticalCenter = data.y1 + (data.element.height() * -1) - 10;
    value = data.element.attr('ct:value');
    if (value !== '0') {
      label = new Chartist.Svg('text');
      label.text(euro(value));
      label.addClass("ct-barlabel");
      label.attr({
        x: barHorizontalCenter,
        y: barVerticalCenter,
        'text-anchor': 'middle'
      });
      return data.group.append(label);
    }
  }
});
```

after that I can style it a bit, and can have the value above the first bar in a larger font-size.  

```
.ct-barlabel {
    font-size:16px;
}

.ct-series-a .ct-barlabel {
   font-size:20px;
}
```

**Comment by Martinomagnifico** [comment]
Fixed it so closing it.

**Comment by Martinomagnifico** [comment]
Fixed it so closing it.

**Comment by ShlomoRosenheimer** [comment]
Thanks man

**Comment by mmilito** [comment]
This is really great ... it would be awesome if you added it to the Chartist site/code. Great job!

**Comment by voodoo417RoR** [comment]
Bro, thanks a lot!!!

**Comment by carlows** [comment]
thanks, but is this working for you on firefox? it seems like the labels are horizontally off

**Comment by bridgeport** [comment]
This is a good alternative to using the tooltip plugin. Thanks @Martinomagnifico 

@Carlows If using the regular, vertical bar chart, changing this:
```
barHorizontalCenter = data.x1+ (data.element.width() * 0.5);
```

to this:
```
barHorizontalCenter = data.x1;
```

Appears to get it centered in Firefox.
