### ISSUE TITLE
Creating a band area on line charts

### ISSUE THREAD

**Issue by Martinomagnifico** [chartist-js/chartist#283]
What can I do to make a stacked area chart? Is there an (undocumented) option like stackLines: true? (preferably with an option where you get a filled area in between two lines). 
And what about being able to have straight steps in it (two lines), instead of one line from one point to another?

Sorry to ask all these questions, but these types of chart are needed if we want to move our code towards Chartist.

And the last question: is there a way to show little ticks on the axes?

**Comment by gionkunz** [comment]
Well, you could simply use the `showArea` option to make the line chart draw areas. With use of that you can draw stacked area charts: 

http://jsbin.com/sowahu/1/edit?css,js,output

> And what about being able to have straight steps in it (two lines), instead of one line from one point to another?

I don't understand what you mean by this? Can you show an example?

By ticks on the axes do you mean subdivision of the axis scales? Would you also want to subdivide the grid lines or just ticks on the axes? All of this would be easy to do with the events of Chartist (in this case probably the `draw`  event with type `grid`) that let you extend Chartist's functionality as you like.

Check this example: http://jsbin.com/sowahu/2/edit?css,js,output

**Comment by Martinomagnifico** [comment]
The stacked area chart looks great. But I need an option to have "nothing" underneath the lowest line, not covering it with a white area. I've looked it up and some call it a Band chart or a Range chart. See this page: http://www.clearlyandsimply.com/clearly_and_simply/2011/04/an-underrated-chart-type-the-band-chart.html

The stepped option is something like this:
http://jsbin.com/suquco/2/ . As you can see, both series add up to 100, and have straight steps. 

The ticks on the second example look great too! (I'll try to figure out how to only draw ticks there where there's a number. Needs to be responsive too, of course, so when there are less text-labels, there should be less ticks as well)

**Comment by Martinomagnifico** [comment]
I was thinking about the range chart, maybe you could "couple" two series of lines, where the difference gets filled. Something like rangeline-couple: "name of series-a", rangeline-areafill: "yellow". And if you do something in the other series like this: rangeline-couple: "name of series-b", rangeline-areafill: "red", then the lines are coupled, and the area is yellow if the value of series-a is higher, and gets red if the line gets under the other line. Such a thing would be cool.

**Comment by Martinomagnifico** [comment]
Edit: Should be CSS classes of course. Not colours. These things should stay separate.

**Comment by gionkunz** [comment]
@Martinomagnifico this is all possible even with the current version of Chartist. As Chartist relies on SVG and it tries to stay as open as possible you can jump into the rendering pipeline with so called events (unfortunately this is not yet documented very well, see #90 ) and modify whatever you like. I've played around with the example a bit to match your needs. It uses the `created` event and the Chartist.Svg API to modify the chart and use the second series as a SVG mask to create a band on the chart.

http://jsbin.com/yahuzun/4/edit?css,js,output

**Comment by Martinomagnifico** [comment]
Hi Gion, thanks for looking into this band chart thing. I'll try to make something reusable out of it. I'll post my endeavours here. (But I'm a designer, so don't expect great programming).
As for the stepped line, what are your thoughts about that?

**Comment by gionkunz** [comment]
Stepped line could easily be added as a line interpolation here: https://github.com/gionkunz/chartist-js/blob/develop/src/scripts/interpolation.js

**Comment by gionkunz** [comment]
I've created #295 for this

In regards to the marking plugin. You can check existing Chartist plugins on how to write the code. Also I can assist you and contribute to it (as I think it would really be a nice plugin).

Cheers
Gion

**Comment by gionkunz** [comment]
I'll close this issue in favor of the other ones and as this ticket starts to get a bit blurred. If you have specific other concerns please raise a new issue.
