### ISSUE TITLE
Cant get chartist to work using ajax

### ISSUE THREAD

**Issue by mrRiff** [chartist-js/chartist#285]
Have a simple ajax function, which returns data successfully, set up
time_str looks like: "12:29","12:24","12:19","12:14","12:09","12:04","11:59","11:54","11:49","11:44","11:39","11:34"
and total_str looks like: 1785,1797,1803,1802,1783,1711,1628,1596,1571,1555,1560,1584

if I hardcode the time_str and total_str into the function it works fine but if the function inserts them I get errors like "Unexpected value NaN parsing y1 attribute." and "Unexpected value NaN parsing y2 attribute."
I have tried changing time_str and total_str into string and int arrays respectively with no luck - any help would be hugely appreciated.

Thanks
Rob

$.ajax({
                        url: "/assets/includes/php/ajax_streaming_viz.php",
                        data: {'stationID': 1, 'api_key': 'abc'},
                        dataType: "json",
                        success: function(data) {

```
                        var time_str    = data.time_sequence,
                            total_str   = data.total_sequence;

                        console.log(time_str);
                        console.log(total_str);

                          var data = {
                              labels: [time_str],
                              series: [
                                [total_str]
                              ]
                            };

                            var chart = new Chartist.Line('.ct-chart', data, {
                                  plugins: [
                                    Chartist.plugins.ctPointLabels({
                                        labelOffset: {
                                            x: 0,
                                            y: -10
                                       },
                                      textAnchor: 'middle'
                                    })
                                  ]
                            });

                    },
                    error: function(data) {
                        console.log('error' + data);
                    }
                });
```

**Comment by gionkunz** [comment]
Hi There

I guess time_str and total_str is actually not a string but an array of stings or numbers. Therefore try this: 

``` javascript
var data = {
  labels: time_str,
  series: [total_str]
};
```

Maybe then time_arr and total_arr would also be more appropriate variable names :-)

Cheers
Gion

**Comment by mrRiff** [comment]
yeah that could do it - thanks very much for getting back

**Comment by gionkunz** [comment]
@mrRiff I'll close the issue. If you still facing problems, just keep on commenting in this issue. Cheers
