### ISSUE TITLE
Chartist.min.css Conflicts with Font Awesome

### ISSUE THREAD

**Issue by mcmadafly** [chartist-js/chartist#29]
For whatever reason, [data-icon]:before will cancel out an Font Awesome icons used outside of the chart library.

Changing `[data-icon]:before` to `.ct-chart [data-icon]:before` fixes this.

**Comment by gionkunz** [comment]
Actually [data-icon]:before should not be part of the chartist.min.css :weary: , it's only used by the site documentation. Let me check why this is part of the dist CSS.

Thanks!

**Comment by mcmadafly** [comment]
Oh possibly my fault then, I might have gotten some files mixed up.

:thumbsup:

**Comment by gionkunz** [comment]
Nope! It's my fault! :-) https://github.com/gionkunz/chartist-js/blob/develop/source/styles/modules/_icon.scss#L23

This should actually go into the site.scss rather than the module (which should only provide mixins actually).

Thanks for raising this, I'll fix that now.

**Comment by gionkunz** [comment]
First Bug! Yeah! :smile:
