### ISSUE TITLE
Latest chartist master freezes my browser

### ISSUE THREAD

**Issue by Globegitter** [chartist-js/chartist#296]
I just tried to use the latest chartist `developer` version (built it myself using grunt) and while the donut chart error is fixed it now seems line charts have some (probably unrleated) issue.

I spent ages trying to figure it out and could bot - but right now when I try to draw line charts, in certain scenarios it freezes my browser completely. Switching back to `0.7.4` and all works fine. I am sorry I don't have much more details, just tired after this debugging session :P

**Comment by gionkunz** [comment]
Hey @Globegitter thanks for the heads up. I guess we'll need to do excessive testing before the 0.7.5 release

**Comment by Globegitter** [comment]
@gionkunz Hopefully can be of more assistance soon but just in the last month of my master's degree so all quite hectic.

Anyway, I forked and just pulled in https://github.com/gionkunz/chartist-js/commit/85e4e37f4b63a71e471858ccbb582381f89abae8 and all works fine now on FF & Chrome for me!

The good thing is, there aren't too many commits that can be the cause of the issue.

**Comment by gionkunz** [comment]
@Globegitter no worries. Your contribution is highly appreciated!

**Comment by rjcrystal** [comment]
Chartist also freezes  when there is no chart data supplied. is that an issue ? or i should always supply some default values ?

**Comment by nblackburn** [comment]
@rjcrystal That's been the case for a while to my understanding.

**Comment by rjcrystal** [comment]
ohh my bad it was solved in this PR https://github.com/gionkunz/chartist-js/pull/292 but it was not included in the build i guess @gionkunz will add this in 0.7.5 release.

**Comment by gionkunz** [comment]
I'm planning the 0.8 release after this weekend, so please stay tuned. Will close this issue for now.
