### ISSUE TITLE
Issues with scatter plot x-Axis (provinding labels & label interpolation)

### ISSUE THREAD

**Issue by acki-m** [chartist-js/chartist#298]
I want to make a simple scatter plot with a lot of values:
![chartist_x_axis_issue](https://cloud.githubusercontent.com/assets/11368160/7444795/0b0b89ca-f195-11e4-8730-d83c80c098e9.jpg)
1)
Why do I have to provide labels for this? Why is not just taking the index of the data array used for this?
2)
Like you can see with default options the x axis is quite unusable, because of overlapping text.
Is the only way to fix this implementing the interpolation function for labels?
When yes, why does it work for the y-axis?

**Comment by gionkunz** [comment]
@acki-m this is just one use case out of many so it's hard to say that the behavior should always be like this. Also you probably don't want to show the index but an index starting from 1 right? You can set `axisX.showLabel` to `false` in the configuration. You can also use a `labelInterpolationFnc` on the X axis that shows the label index. You can return a falsey value (except 0) to completely skip the label and the grid line.

The y-axis is a linear scale axis where the X axis is a step / tick based axis. step axis won't check for available space as you specify which step should be shown and which not using the `labelInterpolationFnc` by returning a falsey value. You can also use the responsive settings to override this behavior on different media.

Check this example: http://gionkunz.github.io/chartist-js/examples.html#line-scatter-diagram-with-responsive-settings

**Comment by acki-m** [comment]
2) The axis should automatically provide labels for the xaxis, which make them useable.
At the moment everybody hast to implement the `labelInterpolationFnc`. 
So everybody has to reinvent the wheel. This is a no go, in library design. IMHO.

1)
Right now I have to include a plugin to get tooltip, this is also a no go. ToolTip are default, basic behavior, which everybody wants. ToolTip handling should be included in the library.

You library looks nice in the first place, but lacks a lot of default functionality, which I expect to be in such a library. I respect you effort for implementing such a library and I see a clear use case, but right now basic features are missing.

**Comment by gionkunz** [comment]
Chartist was built with complete different concerns in mind. Some people don't understand that and that's really sad. Chartist is a tool for web developers and a web developer needs 5 minutes to build tooltips with Chartist. Good library design also means that you don't include functionality that is fulfilling those 80% use cases but will break the other 20% use cases. Chartist does maybe fulfill less of the standard use cases but is open and flexible enough to fulfill your own personal use case without any pain. For me and my experience that's much more worth than trying to solve all use-cases and building a monolithic and heavy framework. I only use libraries that allow me to customize and extend whatever, wherever and however I like. If that means that they won't fulfill some use cases, some people think are essential, I'm perfectly fine with that. Monolithic approaches are doomed and there are millions of nice tooltip libraries out there. Using them with Chartist is a breeze and that's what great library design means. Relying on standards, NOT reinventing the wheel with a library, make it extensible and constumizable, and most importantly, have it only deal with the core concerns of what you'd like to solve with your library. 

I know you're having a different view and for you Chartist is not the right choice I guess. There are tons of other Charting libraries that are also commercially driven and forced to bloat their functionality and I'm sure your much better of with them.

**Comment by acki-m** [comment]
I tryed to get the tool tip running, but I failed. Btw. you have to provide for all your examples a jsfiddle link or something similar. it is simply not possible to copy past the code from your examples, also downloading the source code does not contain ready to go examples, which I expect.

Anyway back to your design decisions. There is no black and white, adding some basic functionality doesn't make you library a heavy Monolithic framework. But having to implement a functional x axis label placement is in my opinion the wrong way, here I have to reinvent the wheel again and again.

Maybe it is a good idea to make a survey and let your potential user decide what they want.
Just my two cents..

**Comment by gionkunz** [comment]
I think most people do like libraries that do everything for them out of the box :-) I don't need a survey to prove this. However, I think it's not responsible to design a library like this and I have enough people that support my view.

I agree with you that there are ways to make the axis behavior better, but this is an open source project and everybody is most welcome to support this project. Unfortunately my free time that I spend in this library is also limited.

In regards to the issue you had with running the code, please be more specific and also open a new issue for that so we can take a look.

Thanks

**Comment by gionkunz** [comment]
I'm closing this issue. Please file a new one for your issues.
