### ISSUE TITLE
Expanded gauge

### ISSUE THREAD

**Issue by nblackburn** [chartist-js/chartist#305]
It would be nice if the gauge was expanded as it's really lacking feel it's against the purpose of a gauge chart, some ideas i had for it were:
- Current value (which in turn would highlight the segment that value is contained within).
- Ticks?
- Dial?

**Comment by gionkunz** [comment]
Hi @nblackburn can you maybe elaborate on your use-case? Maybe with a visual?

**Comment by nblackburn** [comment]
Sure, he is what i had in mind. It's not hugely different from what it is but feel this would make for a huge improvement.

![Gauge](http://i.imgur.com/Dd4iMLa.png)

**Comment by gionkunz** [comment]
Don't you think that would be a perfect case for a plugin? As our gouge chart is actually just a half rendered Donut chart, it would be a bit weird to add too much functionality of a gouge. A plugin would be able to do all things a gouge should support. Dial, current value, maybe automatic coloring? What do you think? If you agree we can put it into the plugin ideas issue.

**Comment by nblackburn** [comment]
> it would be a bit weird to add too much functionality of a gauge.

It certainly could be a plugin but am not really convinced it should be as the Gauge isn't functional in it's current state as per it's intention as a chart. 

In regards to adding too much functionality, i don't feel what i have asked is a significant undertaking and would be happy to work on this with you. All that needs to be added is a means of adding the current value and optionally highlighting the current segment.

**Comment by gionkunz** [comment]
Well, the example states that it's a gauge chart, in fact it's just a half sliced donut chart :-) I know this would be nice but currently there is no real gauge chart. It's just a donut that pretends to be a gauge chart. 

If we want to have a real gauge chart with features you're talking about we could:

A) Create a new chart type for gauge. Although I'd not consider gauge charts as simple basic charts (referring to the claim of Chartist)
B) Try to build more general features into the Donut / Pie Chart that will enable a configuration with some more features that can be used to transform it into a better gauge chart
C) Create a full fledged plugin that takes a Donut / Pie Chart and makes a real gauge chart with all features you can imagine.

Thoughts?

**Comment by nblackburn** [comment]
I would say **option C** except the code for gauges (_even though technically it's not a gauge_) exists and likely would become confusing having both options (native and plugin).

**Comment by gionkunz** [comment]
Well, let's put it like this. With native Chartist you can render a half sliced donut chart that looks like a gouge. In conjunction with the plugin the half sliced donut becomes a real gauge with more features.

I'll add an entry to the plugin ideas section and reference your ticket.

**Comment by umagon** [comment]
I would like to say this pie rendering mode is misleading. I think it would be correct to change its name to "half donut" or something like that.
