### ISSUE TITLE
Bars overlay labels when drawn in Firefox

### ISSUE THREAD

**Issue by alexZielonko** [chartist-js/chartist#306]
I'm successfully overlaying horizontal bars with label information in Chrome. However in Firefox the labels are overlayed by bars.

Chrome:
![image](https://cloud.githubusercontent.com/assets/5274697/7505276/9540b6e6-f416-11e4-96ad-039bd97003e6.png)

Firefox:
![image](https://cloud.githubusercontent.com/assets/5274697/7505288/a58ccef4-f416-11e4-8e31-a61db8d26211.png)

Currently the bar chart is being drawn in the order following order: labels -> grids -> series.

I believe it is more logical to draw the chart in this order: grids -> series -> labels. 

Please advise if there is an existing way to resolve my display issue. If not, I'm happy to discuss further and/or make a pull request.

**Comment by gionkunz** [comment]
Hey there. Can you share your code? It's a bit hard to think about this if I can't see how you've implemented it. The thing with the lables is that they are actually part of the grid. They are closely coupled together in Chartist. If the label interpolation function returns falsey the grid line wont be drawn either.

You can use the `draw` event of Chartist to generate your own labels. Maybe this example helps? http://jsbin.com/wacuva/2/edit?css,js,output

Btw. I'm working on getting the events documented...

**Comment by alexZielonko** [comment]
The coupling between label and grid is useful for label interpolation.

While the example you provide is useful and appreciated, my current issue is more closely related to the SVG's painters model of rendering. It seems logical to assume I never want a label to be obscured by data. I can read data under a label, but not necessarily a label under data. When physically painting a chart on a wall, I can't imagine painting the labels prior the grid. Further, if the painter knows the labels will overlay the data, the labels would be painted after the data.

Here was a quick commit to get the charts behaving as I expected in Firefox. The only real change is the order in which Chartist.Svg.elem is invoked during bar chart instantiation. While this issue may seem somewhat philosophical, I believe it better adheres to what is expected by the W3's SVG rendering model.

https://github.com/missedtheboat/chartist-js/commit/b994671fb098c24f95526a4a9ab908c81fd8926c

**Comment by gionkunz** [comment]
You're right, it makes sense the labels are drawn on top of everything, even if they are usually outside of the chartRect. Can you make a pull request on the current source files on the develop branch?

**Comment by alexZielonko** [comment]
Cool, I'll get a pull request put together over the weekend.

**Comment by gionkunz** [comment]
@missedtheboat I've added the order you suggested with be9e6b6b10a1cb042f63ecac8e64acb7b3a0d077
