### ISSUE TITLE
Tooltips and axis label positioning

### ISSUE THREAD

**Issue by meghaklp** [chartist-js/chartist#313]
Hello, 
1) Question for @Globegitter and @gionkunz - I can't seem to get the tooltips to work on this graph -
http://dev.klp.org.in/stories/ 
The first graph you'll see type of respondents. I've had to rename the tooltip class to chartist-tooltip because of the conflict with the main css. Any help would be appreciated. I tried an example separately and that worked. I can't tell what's going on here.

2) Question for @gionkunz - when the screen size goes < 750 px, I rotate the axis labels, you'll see the 45 degree rotation of the label eats into the graph area - under the heading preschool summary. for the same respondent graph. Is this because text-anchor:middle is not working, I have a y translate of 30 px, But i was wondering if there's an elegant way to display this label?

**Comment by gionkunz** [comment]
Hi @meghaklp 

Nice to see that you're using Chartist on the school site! :-) 

1) jQuery 1.9.1 does not support adding event listeners to SVG elements with delegation. Seems that this was a bug :-( This support started with 1.10.0, can you upgrade to something above 1.10.0 ?

This does not work on SVG with jQuery < 1.10

``` javascript
$chart.on('mouseenter', '.ct-bar', function() {});
```

However, this does:

``` javascript
$chart.find('.ct-bar').on('mouseenter', function() {});
```

2) As the labels are horizontally centered, you need to set the transform origin to 50% also for the X axis. Try this style for your style below 750px:

``` css
transform-origin: 50% 50%;
transform: translateX(0px) translateY(20px) rotate(-45deg);
```

**Comment by meghaklp** [comment]
Thanks so much @gionkunz ! Both these worked. We hope to use a lot more chartist all over the website :)

**Comment by meghaklp** [comment]
@gionkunz - I still have one issue though -
http://dev.klp.org.in/stories/

There are two vertical bar  charts on this page, the tool tips on the first one Types of Respondents is working fine.

The tool tips on the Call Volume chart (if you collapse the IVRS section/accordion) has gone astray. I tried changing absolute to relative, but there's a lot of flicker as you mouse over. I'm seeing this on Chrome 42.0

**Comment by gionkunz** [comment]
@meghaklp the label is positioned absolute and therefore the chart needs to be positioned relative to form a new containing block where absolute positioned elements will be laid out. Therefore just put a `position: relative` on your chart elements if you're using tooltips.

Now it's questionable if we should't include a `position: relative` in the default styles of chartist. I guess as there's nothing the chart element need to be laid out against that is outside of the chart container it would be safe to add a `position: relative` on the container in the Chartist default styles.

@Globegitter It would be nice if you could ensure a `position: relative` on the Chartist container when your plugin gets initialized as it relies on that somehow.

**Comment by gionkunz** [comment]
I'm closing this issue for now. Feel free to comment further. Cheers Gion
