### ISSUE TITLE
How to remove padding?

### ISSUE THREAD

**Issue by rbozan** [chartist-js/chartist#314]
This is the code:

```
new Chartist.Pie('#chart-test', {
                series: [88, 12]
            }, {
                donut: true,
                donutWidth: 10,
                total: 100,
                showLabel: false,
                fullWidth: true,

                axisX: {
                    showGrid: false,
                    showLabel: false,
                    offset: 0
                },

                axisY: {
                    showLabel: false,
                    offset: 0
                }
            }
        );
```

With a width and height of 84px, this seems like it doesn't use the full 84px it has as it uses some kind of padding which I can't find out how to remove.

**Comment by gionkunz** [comment]
Check the default options of the pie. http://gionkunz.github.io/chartist-js/api-documentation.html#chartistpie-declaration-defaultoptions

There is a `chartPadding` option that is set to `5` by default.

**Comment by rbozan** [comment]
Thank you :)
