### ISSUE TITLE
Live Update / Live view

### ISSUE THREAD

**Issue by puhuang** [chartist-js/chartist#319]
May i know there are any where can make the chartist become live view? I mean it can refresh and display the chart either newdata is add or keep refreshing within few second?

**Comment by gionkunz** [comment]
You can use the update function exposed on the Chart object. http://gionkunz.github.io/chartist-js/api-documentation.html#chartistbase-function-update

**Comment by gionkunz** [comment]
I'm closing this issue for now. Please provide more input if you still face issues with the update function.
