### ISSUE TITLE
Single Line Graph Colour Change

### ISSUE THREAD

**Issue by amitjainis** [chartist-js/chartist#323]
I am using a LINE CHART WITH AREA with the default settings. I wish to change the colour of the line and its highlighted are from default red to green.

Can anyone help.

**Comment by gionkunz** [comment]
Use CSS to style your Chart, Check the default CSS to get a feel where to style. Use the Dev tools in your browser to inspect the chart elements and you'll see how to style it.

**Comment by gionkunz** [comment]
CHeck this issue for some examples: #341 I'll close this issue for now as I'll add some documentation about colors anyway.
