### ISSUE TITLE
Chart with 2 scales

### ISSUE THREAD

**Issue by ghost** [chartist-js/chartist#324]
Is it possible to make charts with 2 scales one in reverse order?

Like this one:
![graph](https://cloud.githubusercontent.com/assets/400684/7708145/15b45b10-fe54-11e4-80f7-93b0fe8fac60.png)

**Comment by gionkunz** [comment]
This is not possible yet, but this functionality will soon be available, once we have the compound charts #37

**Comment by gionkunz** [comment]
Closing in favor of #37
