### ISSUE TITLE
Change background color within donut chart?

### ISSUE THREAD

**Issue by nicholasalanbrown** [chartist-js/chartist#328]
Hello:

How do I change the background color of the space within a donut chart? That is, I don't want to change the color of a box around the chart, just the space inside to make it clear how much of the donut is filled on top of a white element. Thanks!

Nick

**Comment by gionkunz** [comment]
I'm not 100% if I understand what you mean. If you're talking about a background on the Pie / Donut, can't you just use two values where one is filling the Pie / Donut as background?

**Comment by nicholasalanbrown** [comment]
That sounds like a good option - I have no idea how to do that. Do you have an example? The tutorial examples only show standard donuts with no background values added....

**Comment by gionkunz** [comment]
Maybe this helps? http://jsbin.com/cirufu/5/edit

**Comment by gionkunz** [comment]
I'm closing this issue for now. Please go on commenting if you still have issues.
