### ISSUE TITLE
Custom build

### ISSUE THREAD

**Issue by e-gnition** [chartist-js/chartist#329]
Could not find anything about the possibility of custom builds.
For example I need bar only and no animations. 
Will it be possible to make custom builds In the future?

**Comment by gionkunz** [comment]
Currently Chartist uses a kind of revealing module pattern using global namespaces. It would be possible to create your own custom build by modifying the distribution source file inclusions in the build process. However, as soon as Chartist is re-written in ES6 you'll be able to use the files individually with more ease of use. Given the large amount of combinations possible, it would not really make sense to create individual distribution files that contain different combinations currently. Maybe someone only needs Line, or Bar and Line, or only Pie?

I'd really like to wait until we have re-written Chartist in ES6 until we support these kind of scenarios. It will make things a lot easier, as the module loader / bundler will decide what's needed based on your applications requirements. (e.g. if you include only Bar.js, it will figure out what other core modules are required through the dependency graph).

**Comment by e-gnition** [comment]
Thank you very much for such a comprehensive a fast reply. Yes, that was my intention to hack it a bit. Thanks again. Will wait for ES6 version.

**Comment by gionkunz** [comment]
Closing in favor of #808
