### ISSUE TITLE
dotted/dashed line chart example ?

### ISSUE THREAD

**Issue by JamesRumkee** [chartist-js/chartist#331]
Hi, sorry if this is obvious, i'm trying to understand how to achieve a dotted/dashed line chart ( as is demonstrated on the chartist home page ) there doesn't seem to be any example code ?

my requirement is to draw a solid linechart, but then also include a dotted/dashed projection of the values into the future. 

I'd really appreciate being pointed in the right direction.

much thanks.

**Comment by JosefWN** [comment]
If it's visible on the page, and the source code is available to you, then that means an example is also available to you.

Anyhow, just use CSS to style .ct-line? If you want the animated dashed line, this could be what you are looking for:
animation: dashoffset 1s linear infinite;

EDIT: Or try something like this if you don't need the animation:
stroke-dasharray: 5px;

**Comment by gionkunz** [comment]
Thanks @Puffton for helping out! @JohnFreedricks you can also check this example from my smashing magazine article: http://jsbin.com/zoruko/edit?html,css,output

Let me know if you need anything else, I'll close the issue for now.

**Comment by JamesRumkee** [comment]
Thanks for the replies, Looks like its as simple as setting stroke-dasharray in css. great! 
@gionkunz - yes i found your blog very useful 
http://www.smashingmagazine.com/2014/12/16/chartist-js-open-source-library-responsive-charts/
