### ISSUE TITLE
showArea and gaps in data

### ISSUE THREAD

**Issue by maligree** [chartist-js/chartist#333]
Guys, absolutely awesome job on this library. I've hit only one bump:

![screen shot 2015-05-30 at 9 33 07 pm](https://cloud.githubusercontent.com/assets/902616/7899009/9399545a-0713-11e5-9101-08b4dddd0eca.png)

Is there a workaround, or even better, any hope for a fix to this?

**Comment by gionkunz** [comment]
Hi there. This should be fixed I guess. Lets track it as an open bug.

**Comment by gionkunz** [comment]
Good news :-) This is fixed with b7ebb604bc4a7251d1aae649b23f80a164c7ac46 and will be released with 0.8.3 this weekend. The demo site already has the development build.

**Comment by maligree** [comment]
Great stuff, thanks!

—
