### ISSUE TITLE
Animating a Pie chart to build up on load

### ISSUE THREAD

**Issue by disturbed-pixel** [chartist-js/chartist#335]
Hi all,  (sorry supposed to be a QUESTION)

This might be a stupid question, but for the life of me i cannot animate my pie chart! I have surfed for hours and tried a variety of things and nothing makes it move. (looking for examples on how to).

It appears nicely, but wont animate! 

I initially tried different SVG animation types from: x, y, rotate, stroke-dashoffset, stroke-dasharray, opacity and i could not get it to do anything. I know i am missing something here, but i just don't know what.

Can anyone tell me what i am doing wrong here please or point me in the direction of a working pie chart example i can learn from. 

THANKS!

```
var options = {
  labelInterpolationFnc: function(value) {
    return value[0]
  },
  donut: true,
  donutWidth: 40,
  startAngle: 0,
  total: 100,
  showLabels:true
};

var responsiveOptions = [
  ['screen and (min-width: 640px)', {
    chartPadding: 30,
    labelOffset: -118,
    labelDirection: 'implode',
    labelInterpolationFnc: function(value) {
      return value;
    }
  }],
  ['screen and (min-width: 1024px)', {
    labelOffset: -118,
    chartPadding: 20
  }]
];
```

var chart = new Chartist.Pie('.ct-chart', {
series: [{
                    value: 70,
            text: 'Male',
                    name: 'Series 1',
                    className: 'my-custom-class-one',
                    meta: 'Meta One'
                  }, {
                    value: 30,
            text: 'female',
                    name: 'Series 2',
                    className: 'my-custom-class-two',
                    meta: 'Meta Two'
                  }],
         labels: ['male','female']
     }, options, responsiveOptions);

```
chart.on('draw', function(data) {
    if(data.type === 'slice') {

          if (data.index == 0) {
              data.element.attr({
                'style': 'stroke: rgba(193, 0, 104, 1)'
              });
              data.element.animate ({
                'stroke-dashoffset': {
                    begin: '1s',
                     dur: '21s',
                     from: '0',
                     to: '600',
                     easing: 'easeOutQuart',
                     d:"part1"
                },
                'stroke-dasharray': {
                    from: '0',
                    to: '1000'  
                }
              }, false);
          } else {
               data.element.attr({
                'style': 'stroke: rgba(102, 102, 102, 1)'
              });
              data.element.animate ({
                'stroke-dashoffset': {
                begin: "part1.end",
                 dur: 1000,
                 from: '0 250 150',
                 to: '360 250 150',
                 easing: 'easeOutQuart'
                }
              });
          }
    }
 });
```

// this i tried later on using a timeout to no avail.
     chart.on('created', function() {
      if(window.__exampleAnimateTimeout) {
        clearTimeout(window.__exampleAnimateTimeout);
        window.__exampleAnimateTimeout = null;
      }
      window.__exampleAnimateTimeout = setTimeout(chart.update.bind(chart), 120000);
    });

**Comment by gionkunz** [comment]
Well I think you were on a perfect track :-) I'd use the approach to set stroke-dasharray to the computed path length with a gap of the same length and then animate stroke-dashoffset. As I believe this is quite a common use case, if included an example on the Chartist site:

http://gionkunz.github.io/chartist-js/examples.html#animating-a-donut-with-svganimate

**Comment by gionkunz** [comment]
I'll close this issue and hope that the new example helps. If you still having issues, feel free to re-open or discuss further. Cheers
