### ISSUE TITLE
Better handling of holes in area charts

### ISSUE THREAD

**Issue by QuentinFchx** [chartist-js/chartist#340]
Currently it looks like this
![](http://cl.ly/image/0y0y1m1X2g0d/Image%202015-06-05%20at%205.03.05%20PM.png)

Would it be possible to: 
- draw an area under each slice ?
- Make sure the side borders are vertical (instead of closing on the first point) ?

**Comment by gionkunz** [comment]
Hi there. There is already a PR that tries to fix this #336 but it's currently incomplete and won't fix all edge cases. I'll take a look at this.
