### ISSUE TITLE
There should be documentation, or an example, changing colours

### ISSUE THREAD

**Issue by ChrisJefferson** [chartist-js/chartist#341]
Hi,

I want to change the colours of the lines of my chart from javascript. I've looked (I believe!) through all the examples, and documentation, but I have never found an mention, or example, of how to do this. Am I missing something?

**Comment by Martinomagnifico** [comment]
You can change the values in the scss file ( $ct-series-colors ) or the generated css file.

**Comment by gionkunz** [comment]
This is my documentation weekend so I'll write something about changing colour :-)

In the meanwhile here is the explanation why you should almost always rely on CSS to control your colours: http://gionkunz.github.io/chartist-js/getting-started.html#as-simple-as-it-can-get

You can also check the following examples:
http://jsbin.com/cecaha/1/edit?css,output
http://jsbin.com/pemute/4/edit

Cheers
Gion

**Comment by ChrisJefferson** [comment]
For me changing scss really won't work (or at least, I can't imagine how to, maybe I'm not imaginative enough!), I plot multiple graphs using user-provided data, and the colours are part of the user-provided data (well actually there is a set of about 8 colours I will use, but I still need to be able to set different series to different colours).

**Comment by gionkunz** [comment]
I just published a new chapter in the getting started guide that should help you http://gionkunz.github.io/chartist-js/getting-started.html#styling-your-chart

Let me know if that helps.

**Comment by ChrisJefferson** [comment]
Thanks, that is very helpful. I haven't been doing javascript long enough to understand why you dislike having a javascript interface so much, but I will respect your opinion on this topic!
