### ISSUE TITLE
The 'LINE CHART WITH TOOLTIPS' example is missing CSS

### ISSUE THREAD

**Issue by ChrisJefferson** [chartist-js/chartist#343]
I tried cutting+pasting the 'LINE CHART WITH TOOLTIPS' example, and it took me a while to realise this reason it doesn't work is because I need the css for .tooltip and tooltip:after.

After finding this by searching using chrome's network inspector, everything worked fine, but it might be nice if this was mentioned in place (although I realise it will make the edit-ability of the demo tricky?)

**Comment by gionkunz** [comment]
Hi there. Yeah, the CSS part is tricky in the documentation currently. I'm planning to add a more comprehensive live example mechanism where we can show HTML / CSS / JavaScript for all examples. I've created an issue to track this effort: #351 and I'll close your issue as your original concern is solved I guess.
