### ISSUE TITLE
show area hides tooltips 

### ISSUE THREAD

**Issue by rjcrystal** [chartist-js/chartist#345]
really loving chartist. great charts 
when i create a multi series chart with tooltips , it will not show tooltip when hovering on a series is at last

**Comment by gionkunz** [comment]
Hi there. Do you have any code example?

**Comment by ghost** [comment]
With `showArea: true`, the area of a series will mask the points of previous series and `mouseenter` events will not be generated for the points under the area. Points of previous series that are outside the area will trigger `mouseenter` and points of series that are on top of areas will also trigger events.

The only solution I see would be to render all the areas then render the points and lines just like the grid in rendered before series.

**Comment by gionkunz** [comment]
Did you try `pointer-event: none` on your area styles?

**Comment by gionkunz** [comment]
pointer-events that is

**Comment by ghost** [comment]
Setting `.ct-area { pointer-events: none }` to the top-level CSS allows mouseenter events to "go through" the areas. Thanks, I didn't understand how that parameter was working before now!

**Comment by rjcrystal** [comment]
sorry guys for not responding i was busy with our product launch,  thank you for your solution @gionkunz, it works.

**Comment by gionkunz** [comment]
Cool! :-) I'm closing the issue for now.

**Comment by ghugan** [comment]
For those using angular,

Just add this to your angular.json

  "node_modules/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.css"

Styling will be added to the tooltip automatically. Tadaaa!

**Comment by ghugan** [comment]
For those using angular,

Just add this to your angular.json

"node_modules/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.css"

Styling will be added to the tooltip automatically. Tadaaa!
