### ISSUE TITLE
Color data points according to value

### ISSUE THREAD

**Issue by Saturate** [chartist-js/chartist#346]
Is it possible to color data points according to value like this? The horizontal lines as well.

Look at the documentation, but I'm having a hard time figuring it out.

![Chart](http://i.imgur.com/eP9hc8K.png)

**Comment by gionkunz** [comment]
Read this section http://gionkunz.github.io/chartist-js/getting-started.html#colour-up-your-charts specially about dynamic colouring. Something like you mentioned would be easy to implement using the  `draw` events.

**Comment by Saturate** [comment]
Ah, overlooked that detail. Maybe a example of this would be good. Thanks!

**Comment by gionkunz** [comment]
Yeah, the event pipeline is very powerful but still not very well documented. I hope to find time to fix this soon also via #90 . I'll close the issue for not. If you need more input, please keep on posting onto the issue.
