### ISSUE TITLE
chartRect calculation is using wrong axis to figure out minimum width / height

### ISSUE THREAD

**Issue by amsardesai** [chartist-js/chartist#347]
I'm running into a problem when using horizontal bar charts in my application. My `options.axisY.offset` set to 160, and each row in my bar chart is roughly 50 pixels. Because of that, if I want the height of my bar chart to be less than 160, chartist actually stretches the graph to make it 160, which is not desirable.

To give an example, let's say I have a chart with 4 rows, with each row being 50 pixels, for a total chart height of 200 pixels (which is more than our `options.axisY.offset`, 160 pixels):

![screen shot 2015-06-11 at 11 45 50 am](https://cloud.githubusercontent.com/assets/2029031/8115740/553e2bb8-1032-11e5-8097-08dee4f2ab03.png)

If I were to remove a row, the total chart height would be 150 pixels, which is less than the width of the labels on the left side (160 pixels):

![screen shot 2015-06-11 at 11 47 34 am](https://cloud.githubusercontent.com/assets/2029031/8115787/a501ded8-1032-11e5-8dcb-dcf13816b39e.png)

As you can see there's a bit of stretching going on on the right side. If I remove a row again (for a total chart height of 100 pixels) it's a lot more obvious:

![screen shot 2015-06-11 at 11 47 09 am](https://cloud.githubusercontent.com/assets/2029031/8115801/c1dea900-1032-11e5-9a7b-b91e7d876e69.png)

Instead of each row being 50 pixels like I intended, Chartist is stretching the rows to 80 pixels so that the total height stays at 160 pixels. If I remove another row, the height of the last remaining row becomes 160 pixels:

![screen shot 2015-06-11 at 11 47 54 am](https://cloud.githubusercontent.com/assets/2029031/8115892/87bb9386-1033-11e5-973a-8d6b73f9f948.png)

I've pinpointed the problem to here: https://github.com/gionkunz/chartist-js/blob/45df861eb65f98a00b6c4f2ed4f6a9f37bd20265/src/scripts/core.js#L722

It looks like it's comparing the value of `options.axisY.offset` (plus padding but in our application that padding is 0) with the height of the chart, and picking the greater value.

Would it be possible to add an option to disable this behaviour? What would a solution to this look like?

**Comment by amsardesai** [comment]
It seems the calculation for the width and height I mentioned above doesn't take into account `options.horizontalBars`, which inverts the axes of the graphs. I submitted a pull request to fix the issue, and it works on my end.

**Comment by gionkunz** [comment]
Hi there. I'm not 100% sure I follow you. `options.axisY.offset` is the label width on the final rendered Y axis (on the left side, no matter where the data comes from e.g. from inversion). It's the offset from the axis to the drawing area, or space used for the labels on the given axis. This is documented in the default options http://gionkunz.github.io/chartist-js/api-documentation.html#module-chartistline

If you set `options.axisY.offset` to 160, and you're suing horizontal bars option, your labels on the left (coming from the labels array), will always have the width of 160px. How do you relate this to the height of your chart to be always less than 160px? Chartist does always use the whole available space to render a chart and divide the available space so it can render all data correctly. 

Maybe you can start with a more detailed explanation what you'd like to achieve?

Cheers
Gion

**Comment by gionkunz** [comment]
Now I think I know what problem you're referring to :-)

I think this is a bug as the chart rect calculations should be flipped in any case!

``` javascript
    width = Math.max(width, yAxisOffset + normalizedPadding.left + normalizedPadding.right);
    height = Math.max(height, xAxisOffset + normalizedPadding.top + normalizedPadding.bottom);
```

It looks like nobody ever head such large axis offset so that bug didn't came to surface :+1: 

Can you change your PR?

Cheers
Gion

**Comment by amsardesai** [comment]
I just changed my PR. @gionkunz
