### ISSUE TITLE
Extend Pie to allow concentric Donut charts?

### ISSUE THREAD

**Issue by victorhooi** [chartist-js/chartist#349]
Would it be possible to extend Pie to draw concentric donut (dougnut) charts?

![doughnut-ppt2](https://cloud.githubusercontent.com/assets/243499/8155317/6c79038c-1386-11e5-9c7b-26d35e87bea9.jpg)

So for example, you could supply Chartist with multiple series, and it would plot each one in concentric circles, and take care of for example, changing the radius of each circle to ensure they didn't overlap etc.

I believe Highcharts does it (http://www.highcharts.com/demo/pie-donut), but I'm not aware of any other JS charting libraries which can do it easily out of the box.

**Comment by gionkunz** [comment]
Hi there. This is not possible in Chartist out-of-the-box. However, it would be relatively easy to achieve if you create two donut charts in the same container and then use chartPadding on the inner chart.

I've created an example for you:
http://jsbin.com/sejohar/edit?html,css,js,output

**Comment by gionkunz** [comment]
Hey there. I hope you managed to get this chart working using two charts in the same container. If you're still having issues please keep on commenting but I'll close the issue for now.
