### ISSUE TITLE
Advanced example

### ISSUE THREAD

**Issue by leonardofaria** [chartist-js/chartist#35]
I'm trying implement the last chart from Advanced page (http://gionkunz.github.io/chartist-js/getting-started.html)

This is the code of page:

```
Chartist.Line('.ct-chart', {
  labels: ['1', '2', '3', '4', '5', '6'],
  series: [
    {
      name: 'Fibonacci sequence',
      data: [1, 2, 3, 5, 8, 13]
    },
    {
      name: 'Golden section',
      data: [1, 1.618, 2.618, 4.236, 6.854, 11.09]
    }
  ]
});

// $chart is set to a jQuery wrapper around the chart container div
var $toolTip = $chart
  .append('<div class="tooltip"></div>')
  .find('.tooltip')
  .hide();

$chart.on('mouseenter', '.ct-point', function() {
  var $point = $(this),
    value = $point.attr('ct:value'),
    seriesName = $point.parent().attr('ct:series-name');

  $point.animate({'stroke-width': '50px'}, 300, 'easeOutQuad');
  $toolTip.html(seriesName + '<br>' + value).show();
});

$chart.on('mouseleave', '.ct-point', function() {
  var $point = $(this);

  $point.animate({'stroke-width': '20px'}, 300, 'easeOutQuad');
  $toolTip.hide();
});

$chart.on('mousemove', function(event) {
  $toolTip.css({
    left: event.offsetX - $toolTip.width() / 2 - 10,
    top: event.offsetY - $toolTip.height() - 40
  });
});
```

I didn't understand this specific part: // $chart is set to a jQuery wrapper around the chart container div
Who is $chart?

**Comment by dominicrico** [comment]
You have to declare $chart.

var $chart = $('.ct-chart');

**Comment by jordanpolo** [comment]
http://gionkunz.github.io/chartist-js/getting-started.html

**Comment by LeoIannacone** [comment]
Some issues about that example:
1. **easeOutQuad** is defined in jqueryui, you need to implement it by yourself:

``` javascript
var easeOutQuad = function (x, t, b, c, d) {
        return -c * (t /= d) * (t - 2) + b;
};
```

 more info at http://jqueryui.com/easing/
1. **ct:value** and **ct:series-name** attrs are not added to DOM, see here http://jsfiddle.net/l3on/jxs375qj/

v.0.1.11

**Comment by jordanpolo** [comment]
var easeOutQuad = function (x, t, b, c, d) {
        return -c \* (t /= d) \* (t - 2) + b;
};

**Comment by gionkunz** [comment]
@leonardofaria , you're right. The problem is that the documentation is already reflecting v0.1.12 which is not yet distributed. As the custom attributes are a important feature, I'll distribute Chartist v0.1.12 now.

I don't like the jQuery UI dependency at all and always found it funny jQuery not including the advanced easing function in the core. I used https://github.com/jozefizso/bower-jquery-easing for creating the example, but specifying the function directly in the example would be better I guess. I'll switch to this or even use the standard easing (although I don't like the look of it).

Cheers
Gion

**Comment by gionkunz** [comment]
@leonardofaria, this part is confusing and the reason for this lies in the way the example page is built. This is causing confusion for a few people now and I think, for closing this issue, I'll update the example page so that it allows to use more real and complete example code.

**Comment by jordanpolo** [comment]
Thank u
