### ISSUE TITLE
Change colours for multiple charts

### ISSUE THREAD

**Issue by bebbs** [chartist-js/chartist#350]
Is it possible to have different colours for two different charts on the same page? The first chart has one series, and the second can have up to three.

**Comment by gionkunz** [comment]
Hi there. If you simply follow the styling guide http://gionkunz.github.io/chartist-js/getting-started.html#customizing-the-default-css and prepend your selectors with an ID selector, while also adding this ID to your chart containers, you can easily have different styles for different charts.

**Comment by gionkunz** [comment]
Hey there. I hope the guide helped you out. I'll close the issue for now but keep on commenting if you still have issues. Cheers

**Comment by correa77** [comment]
Hi gionkunz, I still have the problem that bebbs had. Do you know or have an example where i can see this being done. Thanks.
