### ISSUE TITLE
Empty spaces in stacked bar chart

### ISSUE THREAD

**Issue by wedgef5** [chartist-js/chartist#354]
I'm having a problem with a stacked bar chart, where there are large blank areas in the bars.  When I inspect these elements using Firebug, I can see that they are being rendered as 0 height, however, their y1/y2 values show they they are taking up space in the chart.  It seems that several of these are adding up to form the blank area.

A couple of ideas I have had as to possible causes: (1) I am passing the data for the series in as an array of objects with 'name' and 'data' attributes.  I saw this done explicitly in a Line graph example.  I assumed this was OK for a Bar graph, but I'm not 100% sure, and (2) the data ranges very widely, going from 0 to 10^9.  I wasn't sure is scaling over such a wide range might cause problems.

Here is a screen shot showing the problem.  Any suggestions are appreciated!

![stacked_bar](https://cloud.githubusercontent.com/assets/12939463/8213611/a884c252-1512-11e5-9776-0131f3b63a7b.png)

**Comment by georgerappel** [comment]
Could you show me your graph code, @wedgef5 ?

**Comment by gionkunz** [comment]
I saw negative values causing similar issues. Are you sure you only have positive values in your data?

**Comment by wedgef5** [comment]
Sorry for the slow reply...I've been out of the office for a couple of days.

@georgerappel - here is the 'success' section of my AJAX call...

``` javascript
        success: function(data) {
            chart = new Chartist.Bar('.ct-chart', data, {
                stackBars: true,
                axisY: {
                    labelInterpolationFnc: function(value) {
                        return (value / 1000) + 'k';
                    }
                },
                low: 0
                }).on('draw', function(data) {
                  if(data.type === 'bar') {
                    data.element.attr({
                      style: 'stroke-width: 30px'
                    });
                  }
            });
            var $tooltip = $('<div class="tooltip tooltip-hidden"></div>').appendTo($('.ct-chart'));

            $(document).on('mouseenter', '.ct-bar', function() {
                var seriesName = $(this).closest('.ct-series').attr('ct:series-name'),
                    value = $(this).attr('ct:value');
                $tooltip.html(seriesName + '<br/>' + value);
                $tooltip.removeClass('tooltip-hidden');
            });

            $(document).on('mouseleave', '.ct-bar', function() {
                $tooltip.addClass('tooltip-hidden');
            });

            $(document).on('mousemove', '.ct-bar', function(event) {
                $tooltip.css({
                  left: (event.offsetX || event.originalEvent.layerX) - $tooltip.width() / 2,
                  top: (event.offsetY || event.originalEvent.layerY) - $tooltip.height() - 20
                });
            });
        }
```

@gionkunz - There are zeros in the data, but no negative values.

**Comment by gionkunz** [comment]
@wedgef5 maybe you can dump the JSON response from where you get the data to display and put it somewhere for us so we can reproduce the issue?

**Comment by wedgef5** [comment]
@gionkunz - Here you go...

http://www.weather.gov/source/crh/ldmStats.json

**Comment by gionkunz** [comment]
Wow this is a lot of data :-) The problem with this is that Chartist is only generating styles for 15 series by default. You have 101 series ;-)

The class names are currently alpha numerated, and this is probably not perfect for such a usecase. We'll likely change that with 1.0 #183 

Currently Chartist will choose class names `ct-series-a` up to `ct-series-z` (a, b, c, d ...). After `z` is reached it will repeat from `a` again. The default styles include styling from `a` to `o` (15 series).

You options are that you use the Sass version of Chartist and add some more series (up to z) in the settings: https://github.com/gionkunz/chartist-js/blob/develop/src/styles/settings/_chartist-settings.scss#L68-L85

Or you just use CSS to style there series: http://jsbin.com/hekake/edit?css,js,output

**Comment by wedgef5** [comment]
Yes, it is a lot of data.  I work for a meteorological agency...we like lots of data.  ;-)

I employed the CSS option, and the chart looks much better now.

Thanks for the help!

**Comment by daN4cat** [comment]
In #451 I suggested a way to colouring pie slices using a random #rgb generation.
