### ISSUE TITLE
"onlyInteger: true" option not working

### ISSUE THREAD

**Issue by niravprajapati90** [chartist-js/chartist#358]
even though we pass onlyInteger: true option.
check below jsfiddle for reference.

http://jsfiddle.net/v6ga4cpq/

**Comment by gionkunz** [comment]
The onlyInteger option is part of the axis configuration. Check the options again https://gionkunz.github.io/chartist-js/api-documentation.html

**Comment by niravprajapati90** [comment]
@gionkunz , thanks for pointing out.
sorry for inconvenience. 
closing issue as its invalid.
