### ISSUE TITLE
Apply the same chart to multiple elements

### ISSUE THREAD

**Issue by guillaume-g** [chartist-js/chartist#360]
Hi,

My name is Guillaume and I want to thank you for your library, which is really nice and simple ! :)

I am actually using it for a project. Everything works well, but I have a little question:

``` javascript
var chart = new Chartist.Line(selector, {series: series, labels: labels}, options);
```

Here is the way to put a chart on an element.
What I would like to do is to apply the same chart to multiple elements. Well I tried to use a selector like ".blablabla" it will only apply to the first element with the class ".blablabla".

Is there any way to achieve this?

Thank you in advance!

**Comment by gionkunz** [comment]
Hi there!

Sure, the chart constructors also takes an `Element` interface.

To initialize your chart on multiple elements just use this approach:

``` javascript
var nodeList = document.querySelectorAll(selector);
for(var i = 0; i < nodeList.length; i++) {
  var chart = new Chartist.Line(nodeList[i], {series: series, labels: labels}, options);
}
```

Or, if you prefer a more functional way:

``` javascript
function createChartFactory(data, options, responsiveOptions) {
  return function createChart(element) {
    return new Chartist.Line(element, data, options, responsiveOptions);
  };
}

var elements = Array.prototype.slice.call(document.querySelectorAll(selector));
elements.forEach(createChartFactory({series: series, labels: labels}, options));
```

**Comment by guillaume-g** [comment]
Thank you for your answer ! :)
