### ISSUE TITLE
Updating chart inside 'created' event listener

### ISSUE THREAD

**Issue by astanb** [chartist-js/chartist#362]
I'm trying to amend the top padding of my chart in a plugin inside the 'created' event listener but update() does not seem to work.

Here's some code:

```
function myPlugin(options) {
            return function myPlugin(chart) {

                var theChart = chart;

                chart.on('created', function (data) {
                        theChart.options.chartPadding.top = 160;
                        theChart.update();
                });
            };
}
```

The property is updated ok, but there is no visual update - Any ideas?

**Comment by gionkunz** [comment]
This would cause an infinite event loop as `update()` will actually trigger an other `created` event.

If you'd like to add the padding top to the chart before it gets rendered use the `data` event that is triggered before the data is used / processed.

**Comment by gionkunz** [comment]
I really need to find some time to document those events :( I know this is terrible... #90

**Comment by astanb** [comment]
I'm trying to amend the chart padding within a plugin upon its initialisation (as well as in the 'data' event listener) but it doesn't seem to be picked up when the chart is drawn. The plugin is the only one running.

```

var defaultOptions = {
                    legendClass: 'ct-legend',
                    legendOffset: {
                        x: 0,
                        y: 0
                    },
                    textAnchor: 'start',
                    title: 'Legend',
                    legends: []
};

//amend the padding
options.chartPadding = {top: 100, bottom: 0, left: 0, right: 0};
options = Chartist.extend({}, defaultOptions, options);

```

I put two breakpoints in, one just after setting the padding, and it fires with the options set properly, but the second one placed in the createChartRect function in Chartist.js shows the original untouched options.

Am I missing something obvious here?

**Comment by gionkunz** [comment]
Actually you can run `chart.update(null, {chartPadding: {top: 100, bottom: 0, left: 0, right: 0}}, true)` within your plugin initialization function. Just make sure that you don't run it inside your created listener.

**Comment by gionkunz** [comment]
The true option will make sure existing options will stay but the one you specify will be overriden

**Comment by astanb** [comment]
I forgot to thank you, sorry...better late than never!
