### ISSUE TITLE
Area problem - Version 0.9.0

### ISSUE THREAD

**Issue by pomm0** [chartist-js/chartist#364]
Hey,

i've got the problem that the area of a multiple (or single, in my case multiple) series chart is NOT fully filling out the area down to 0 (or lowest visible value) in version 0.9.0. The area stopps on the lowest point. It worked in version 0.8.2 (0.8.3 i didn't test). Here a sample from your example-site:

![selection_041](https://cloud.githubusercontent.com/assets/6084030/8331210/59409e8a-1a87-11e5-9b94-0816323c7826.png)

Browser: Chrome Version 43.0.2357.130 (64-bit) on Linux - same on Firefox 38 Linux
But don't think it's a browser-bug.

Shouldn't the area go down to 0 ?

**Comment by bartveneman** [comment]
Having the same issue with 0.9.0, although I must say that on some occasions it _does_ reach down to 0. Not sure what the difference between those values is.

![screen shot 2015-06-24 at 17 01 02](https://cloud.githubusercontent.com/assets/1536852/8333328/af2ce74e-1a92-11e5-8fe5-d99e321adc2a.png)

Edit: Seems to work with 0.8.3
![screen shot 2015-06-24 at 17 06 41](https://cloud.githubusercontent.com/assets/1536852/8333485/6944f464-1a93-11e5-9779-b90e10192a19.png)

**Comment by gionkunz** [comment]
Hi Guys, this is probably related to the new data hole area handling introduced with 0.9. I'll take a look asap.

**Comment by gionkunz** [comment]
This is fixed and I've published 0.9.1 ! Thanks for the report guys!

**Comment by bartveneman** [comment]
Great job on the quick fix!

**Comment by pomm0** [comment]
Thank you!
