### ISSUE TITLE
How can I make the Y-Axis have a fixed position?

### ISSUE THREAD

**Issue by mikerandall** [chartist-js/chartist#365]
I am trying to create a really long graph, where the user can scroll it within a horizontally scrollable container. When the user scrolls the graph, I would like the Y-Axis to remain in a fixed position on screen. 

![screen shot 2015-06-24 at 11 39 57 am](https://cloud.githubusercontent.com/assets/224680/8334428/ecc644ec-1a65-11e5-9989-c789f5b3d15e.png)

Right now, my approach is to remove those Y-Axis labels during the _draw_ event and add them to a new SVG, in a container with a fixed position. Is this the best approach? Or is there another way of doing it? I noticed a thread about compound graphs and made a comment there as well. Would that be the best way to implement this functionality?

Thanks!

**Comment by gionkunz** [comment]
I'd suggest you listen for the `created` event and detach the whole label SVG group into a different SVG where you position it absolute. As everything is in the DOM you have perfect freedom. This would be a perfect usecase for a plugin!

**Comment by mikerandall** [comment]
OH, the created event...I'll definitely check that out now. Perhaps that's why I'm running into:
`Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.` when I try to add a new SVG created with Chartist.Svg to my containing div. :frowning:
