### ISSUE TITLE
Is there a way to attach different ID's to different segments of one same chart?

### ISSUE THREAD

**Issue by NicoSa** [chartist-js/chartist#366]
Hi there, first of all, great library!

I've been trying to attach js event handlers to different segments of one donut chart. It's obviously easily possible for the whole chart but is there a way to do it for separate parts?

Basically if this wasn't bad practice and would work, I'd be happy:

``` javascript
$( ".ct-series-a" ).on( "click", function() {
       console.log( "Segment a was clicked!" );
});
```

Or if there was an option like this for the **series** hash:

``` javascript
idName: "myId"
```

Couldn't hack it to work with the **className** option either.

**Comment by gionkunz** [comment]
Hi there! Maybe this jsbin helps you out? http://jsbin.com/jedapu/edit?js,output

**Comment by NicoSa** [comment]
Forgot to push at work, gonna try this out tomorrow! Thanks man!

**Comment by gionkunz** [comment]
Sure, the thing you always need to remember is that chartist re-creates DOM, sometimes very rapidly (on updates, resizes etc.). In order to create sustainable listeners use delegation:

``` javascript
$(document).on('click', '.ct-series-a', function() {
       console.log('Segment a was clicked!');
});
```

**Comment by NicoSa** [comment]
Cool, the jsbin is working for a pie chart. Let's see if I can make it work with the animated donut! Thanks for your help!

Done, it worked! Thanks man! What do you think about the idea of being able to give specific ID's for part of a chart in the series options? I'm a JS noob but I'd give it a shot sometime!

**Comment by gionkunz** [comment]
@NicoSa what parts would you give an ID and for what purpose? Can you give an example?

**Comment by NicoSa** [comment]
I thought it would make it easier to attach event handlers to the elements but it would still be the same way you suggested, which did the job!
