### ISSUE TITLE
What's the best way to align points in a line graph?

### ISSUE THREAD

**Issue by mikerandall** [chartist-js/chartist#369]
I am trying to make a line graph where the points are aligned in the center of each scale, rather than to the left. Is this configurable in a setting, or would I have to watch the `draw` event and move things around?

![screen shot 2015-06-25 at 9 34 13 am](https://cloud.githubusercontent.com/assets/224680/8355458/652a30a8-1b1d-11e5-991d-5898894b44a2.png)

**Comment by mikerandall** [comment]
Ok so rather than aligning things to the left or right, is there a way to give the graph padding? Not the padding that applies to the entire graph, but padding between the y-axis and the first graph point?

Here's what's currently happening:
![screen shot 2015-06-25 at 4 26 23 pm](https://cloud.githubusercontent.com/assets/224680/8365133/311af55e-1b59-11e5-956d-f58a26967615.png)

I'd like to give it some padding between the y-axis and that first data point like in the graphic in my first post. Is this possible?

**Comment by gionkunz** [comment]
This is probably best done with the `created` event. Also make sure you don't enable the `fullWidth` option on the line chart, as you'll need that last sector to offset your line chart into.

http://jsbin.com/zawazo/edit?js,console,output

**Comment by mikerandall** [comment]
Awesome, that helped a bunch! I found that I still have to modify the foreignObjects, as they have some x and y values that needed to be adjusted. But this worked great! 

Here's the finished product:
![screen shot 2015-06-29 at 2 10 52 pm](https://cloud.githubusercontent.com/assets/224680/8414870/c05a752a-1e68-11e5-8c48-1eefcea03029.png)

After scrolling:
![screen shot 2015-06-29 at 2 08 56 pm](https://cloud.githubusercontent.com/assets/224680/8414808/7289e164-1e68-11e5-8045-dbff7760c70e.png)

Now onto the next graph...
