### ISSUE TITLE
Question: reduce hard-curves

### ISSUE THREAD

**Issue by pomm0** [chartist-js/chartist#370]
Hey,

just a question: Is it possible to remove or reduce these "hard" curves when there's a big difference between 2 points?

![selection_045](https://cloud.githubusercontent.com/assets/6084030/8358463/962ec9e6-1b60-11e5-9546-036481c6b04e.png)

Thank you!

**Comment by danieldiekmeier** [comment]
Yes, there is: https://gionkunz.github.io/chartist-js/api-documentation.html#chartistinterpolation-method-simple

I developed this, because I had the same problem as you.

**Comment by pomm0** [comment]
Nice, thank you. I missed that.
