### ISSUE TITLE
Labels disapearing CSS positioning

### ISSUE THREAD

**Issue by pomm0** [chartist-js/chartist#373]
Hey,

i've got the problem, that my vertical-labels are disapearing after moving the svg with negative margin-left:

http://jsfiddle.net/syjzd4k6/

If you change the style on the svg from margin-left: -48px; to margin-left: -47px; it's working. It's on every Browser and i have no idea what's going on here.

Is this a SVG-issue or something that is on every browser?

Our aim is that the vertical labels are inside the chart:

![unbenannt-1](https://cloud.githubusercontent.com/assets/6084030/8427676/80e07e6a-1f19-11e5-996b-e04f790bee83.jpg)

How can i achieve this?

Thank You

**Comment by gionkunz** [comment]
You can use a combination of the `axisY.offset` option with `axisY.labelOffset.x` to achieve this.

**Comment by pomm0** [comment]
Thank you. It worked!

**Comment by pomm0** [comment]
Hey and sry but i have to reopen the issue.
I've tested it on IE 10 + IE 11 and saw that there it's not working.
I know that IE does not support foreignobjects and instead you are using 'text'-elements. Is it possible that you forgot to add the labeloffset for the text-elements-position?
When i add the same x-position which has the foreignobject in chrome to the text-element in IE it seems to be identical.

Thank You

![selection_054](https://cloud.githubusercontent.com/assets/6084030/8481876/21b866cc-20e6-11e5-9e6e-cd92670ff53b.png)

**Comment by gionkunz** [comment]
Hey there! That's very possible that this is a bug in IE! We've refactored this code a lot and our IE testing is not the most sophisticated... I'll confirm asap and see if we can get this fixed soon.

In the meanwhile you can use the `draw` events to conditionally move labels for browsers that don't support foreignObject: http://jsbin.com/limuxe/edit?html,js,output

**Comment by pomm0** [comment]
Thanks, meanwhile i'm using your script.

**Comment by mic159** [comment]
I found that setting `offset: 0` and labelOffset for both the x and y axis at the same time causes the labels to stop rendering at all.
I think it has to do with the size ending up negative.
I can see that the span has `style="width 21px; height: -10px"` and the wrapper has `<foreignobject ... height="-10">`
If I edit the height of the foreignobject to be positive, the labels show again.

This is with Chrome 48.

My current config looks like this:

``` javascript
const chartConfig = {
  axisX: {
    type: Chartist.AutoScaleAxis,
    showGrid: false,
    offset: 0,
    labelOffset: {
      x: 0,
      y: -25,
    },
  },
  axisY: {
    showGrid: false,
    offset: 0,
    labelOffset: {
      x: 25,
      y: 0,
    },
  },
  height: 340,
  showPoint: false,
  showArea: true,
  chartPadding: {
    top: 0,
    right: 0,
    bottom: 0,
    left: 0
  },
};
```

**Comment by gionkunz** [comment]
Closing this, for now, if there's still a need for fixes, please open a discussion again.
