### ISSUE TITLE
Adding class to path on hover

### ISSUE THREAD

**Issue by lucadegasperi** [chartist-js/chartist#374]
Hello, given this example
how does it come that no class is added to the element? The event gets fired correctly. Putting an alert inside does in fact work. Could you help me please?

``` js
var chart = new Chartist.Pie('.simple-donut', properties.chartsData[chartId], properties.options)
                    var c = $('.simple-donut');

                    c.on('mouseenter', '.ct-slice-donut', function(){
                        var $slice = $(this);
                        $slice.addClass('is-hovering');
                    });
```

**Comment by gionkunz** [comment]
Hi @lucadegasperi 

It looks like a jquery does not support addClass on SVG elements. You can use `classList` from the DOM API if IE is not an issue or use `$.attr` directly:

``` javascript
var chart = new Chartist.Pie('.simple-donut', {
  labels: [1, 2, 3, 4],
  series: [1, 2, 3, 4]
}, {
  donut: true
});

var c = $('.simple-donut');

c.on('mouseenter', '.ct-slice-donut', function() {
  this.classList.add('is-hovering'); // works, but not in IE
  $(this).attr('class', 'ct-slice-donut is-hovering'); // works too
});
```

**Comment by gionkunz** [comment]
Check this article by Todd Motto http://toddmotto.com/hacking-svg-traversing-with-ease-addclass-removeclass-toggleclass-functions/

**Comment by gionkunz** [comment]
Please re-open if there are still open issues.
