### ISSUE TITLE
Variable # of tick marks

### ISSUE THREAD

**Issue by Kevenin** [chartist-js/chartist#377]
This more of a request, but with graphics that display large numbers, the tick marks are so close together that they sometimes overlap. I was wondering if it was possible, in the axis options, to add a tick count option and base the number of ticks  & labels on that option.

Thank you.

E.G.

![image](https://cloud.githubusercontent.com/assets/13238483/8572069/49cb29da-2558-11e5-8c80-39e3d3ae3e92.png)

**Comment by Kevenin** [comment]
Never mind, if you play with scaleMinSpace in the axis options, it sort of does the same thing

`axisX: {
                scaleMinSpace: 100
            }`

**Comment by aaron4tc** [comment]
Or you can use 25k, 50k, etc instead
