### ISSUE TITLE
Horizontal Bars bug

### ISSUE THREAD

**Issue by bchang7** [chartist-js/chartist#379]
ct:value is the expected value followed by  ',undefined'.. this becomes kinda buggy for tooltip purposes

**Comment by bchang7** [comment]
![image](https://cloud.githubusercontent.com/assets/8278050/8586134/81b2b244-25b9-11e5-8185-40e813b3925b.png)

**Comment by yanbeihui** [comment]
I also want to how how to fix it

**Comment by gionkunz** [comment]
Thanks for the bug report. I've fixed that and it will be pushed into 0.9.2
