### ISSUE TITLE
Add support for zoom / scroll / pan options?

### ISSUE THREAD

**Issue by pjfsilva** [chartist-js/chartist#380]
My feature request is something similar to this demo on amcharts:
http://www.amcharts.com/demos/line-chart-with-scroll-and-zoom/

Most specifically: the top bar that allows you to zoom / scroll into a specific date for your data. This is really useful when you have lot's of data to show.

I agree that this should be implemented as a plugin but still, here is my feature suggestion...

**Comment by gionkunz** [comment]
Actually I'd love to have a plugin with that functionality!

**Comment by jordan-wright** [comment]
So what would this look like from a plugin functionality?

Let's assume the top bar idea doesn't work out and we want to just tackle the zooming. I suppose we could bind on mousedown and mouseup to start the selection process. I guess the important thing for us would be to get the first and last point in the selection window. Any suggestions how to get those values?

After we have that, I guess we could set `low` and `high` options and re-draw accordingly.

Would it be that simple?

**Comment by gionkunz** [comment]
Zooming is possible using the plugin https://github.com/hansmaad/chartist-plugin-zoom

**Comment by pjfsilva** [comment]
I see that plugin buy my initial idea was a bit more advanced as to have that top bar that amcharts has. Basically this UI allows you to have a big timeline of events where the chartist-plugin-zoom is a more simple approach that only provides zoom. When you have lot's of data to show, that plugin doesn't solve very much.

It's up to you if we should reopen this or drop it. I was just clarifying my initial idea.
