### ISSUE TITLE
How to control the last axisX label style in css?

### ISSUE THREAD

**Issue by code-tinker** [chartist-js/chartist#383]
here is what i want to make : 
![image](https://cloud.githubusercontent.com/assets/3404780/8771316/c135bc94-2ef2-11e5-81f0-232bed318b8e.png)

the first label in axisX is placed at the beginning, and the last label at the end , others center~
how can i make it by pure css?
( i found if axisX and axisY grouped in different <g>, i can use last-child to control the last label in axisX)

**Comment by gionkunz** [comment]
This is somewhat a problem since all labels are in the same group. Maybe we can add a class first and last to the vertical and horizontal labels within chartist. For the moment you can use the draw events (check the documentation and examples) to add the classes yourself.

**Comment by mtgibbs** [comment]
I found myself trying to do the same thing today.  I made super crude plugin to deal with my problem with it.

https://github.com/mtgibbs/chartist-plugin-labelclasses

If that's of any use.

**Comment by kittsville** [comment]
I've found a way to achieve this, although it's a bit of a hack:

``` js
chart.on('draw', function(event) {
    // If the draw event is for labels on the x-axis
    if (event.type === 'label' && event.axis.units.pos === 'x') {
        switch (event.index) {
            // First
            case 0:
                event.element._node.childNodes[0].style.marginLeft = '0px';
            break;

            // Last
            case SERIES_LENGTH:
                event.element._node.childNodes[0].style.marginLeft = '-51px';
            break;
        }
    }
});
```

Where `SERIES_LENGTH` is the number of data points - 1. Screenshot and JS Bin:
http://jsbin.com/zegotidisi/edit?js,output
![JS Bin Screenshot](https://cloud.githubusercontent.com/assets/6013087/15083064/2103811e-13c3-11e6-9cce-fa92c8ab5279.png)

**Comment by zanechua** [comment]
@kittsville 

Thanks! That came in handy because the chart wasn't displaying the last value properly.

Without your code:
![Without Code](http://i.imgur.com/SYSBDqx.png)

With your code:
![With Code](http://i.imgur.com/wStWjFQ.png)

**Comment by joeantonelli** [comment]
@kittsville - thanks!

For anyone else, his approach is also useful if you want to style other label attributes such as font-size, etc. For example, I'm rendering multiple graphs on the same page, but I want each graph to have different label styling.

Here's my code based on the structure outlined above:

    //specify more options before the chart is displayed
    chart.on('draw', function(data){

        //label size
        if (data.type === 'label') { data.element._node.childNodes[0].style.fontSize = '11px' }
    });

**Comment by ehdwns980416** [comment]
@kittsville Awesome!! Thanks a lot!! 😗

**Comment by duchuy** [comment]
have you tried to increase the chart padding:

`chartPadding: {
         right: 30,
          bottom: 30
      }`

**Comment by gionkunz** [comment]
Closing this, for now, if there's still a need for fixes, please open a discussion again.
