### ISSUE TITLE
Show tooltips anywhere on line (area) chart?

### ISSUE THREAD

**Issue by coax** [chartist-js/chartist#388]
Currenty possible to show tooltip only when mouseover point in line (area) chart:
![tooltip1](https://cloud.githubusercontent.com/assets/189817/8847095/07395ef4-312c-11e5-97ec-3cf329c8affa.gif)

Is it doable to show tooltip when mouseover any portion of line (area) chart (with the unique value of that portion):
![tooltip2](https://cloud.githubusercontent.com/assets/189817/8847108/1102fa76-312c-11e5-84ef-039653e5fe34.gif)

**Comment by gionkunz** [comment]
Hi there. Are you using the tooltip plugin? If yes this should be better placed there. If it's more a general question how to do this, I'd probably go ahead and transform the points into invisible (transparent) rectangles that have the full chart height and the width of each step. Check the draw event example on how to transform / exchange shapes: http://gionkunz.github.io/chartist-js/examples.html#using-events-to-replace-graphics

**Comment by coax** [comment]
Thanks for replying, I'm using plugin and will post there.
