### ISSUE TITLE
Stacked Horizontal Bar Chart for timeline?

### ISSUE THREAD

**Issue by victorhooi** [chartist-js/chartist#389]
I'd like to create a timeline-like graph, using a stacked horizontal bar chart:

![sample stacked horizontal bar chart for mplotqueries replication graph](https://cloud.githubusercontent.com/assets/243499/8848718/0050f92a-317d-11e5-87b0-46d006e0316d.png)

There are two series, A and B, and they are in different states (represented by colours) at various times - time is along the x-axis.

Is there any way at all to do this using Chartist.js?

**Comment by gionkunz** [comment]
Shouldn't be an issue. Did you made any progress?

**Comment by victorhooi** [comment]
Aha, ok, I think I've got it - I can use `stackBars: true` to stack the bars, and `horizontalBars: true` to make them horizontal.

So, using the example from http://gionkunz.github.io/chartist-js/examples.html:

```
new Chartist.Bar('.ct-chart', {
  labels: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  series: [
    [5, 4, 3, 7, 5, 10, 3],
    [3, 2, 9, 5, 4, 6, 4]
  ]
}, {
  stackBars: true,
  seriesBarDistance: 10,
  reverseData: true,
  horizontalBars: true,
  axisY: {
    offset: 70
  }
});
```

However, my question is, how do I work in time into that?

As in, I assume from my backend, what I can do is calculate each horizontal segment in terms of duration in seconds.

However, on the x-axis, ideally I'd like wall-time. Any thoughts on how to work that into Chartist.js?

**Comment by gionkunz** [comment]
Its totally fine to use timestamps as values and then format them with `labelInterpolationFnc` to display human readable. Sorry for the late reply. Please re-open if required.

**Comment by ashikvs** [comment]
hey @victorhooi  were you able to make this chart possible?? i am trying to do the same for my project but havent been succesfull :(
