### ISSUE TITLE
Make gruntfile more modular so it's easier to spot different tasks

### ISSUE THREAD

**Issue by valotas** [chartist-js/chartist#39]
It is all about [SoC](http://en.wikipedia.org/wiki/Separation_of_concerns) after all. Right?

Apart from that it will help a lot the newcomers to the project.

**Comment by gionkunz** [comment]
Please specify what you'd like to split? The site is very well separated in the current project and I like the benefit of having just one repo. Currently source/site, source/scripts/site and source/styles/site are relevant to the site. All other resources are relevant for the library.

I know it would also be nice to split it into a fully separated project. But, again, this has also a few drawbacks. For example the development pace is slower as you need to switch projects all the time and compile the library project to make use in the documentation project. 

Given the clean structure with the sites folder I'd not like to go with a separate project at the moment just to keep it compact and fast paced.

Cheers

**Comment by valotas** [comment]
In that case just split the `Gruntfile.js` to server and library.

**Comment by gionkunz** [comment]
Why? :smile: The gruntfile is the dev part of the library. It's there to provide a development environment with live reload, linting etc. and to create the distribution package as well as the documentation site. How would you like to split the Gruntfile? The "server" tasks share many sub-tasks with the library thing. What would make sense, would be to separate the Gruntfile into much smaller files in order to structure it a bit better.

**Comment by valotas** [comment]
Why? Mostly because I have to go through everything there when I only care about core js stuff :)

It makes me nervous when I write javascript and find `assemble` hanging around :)

**Comment by gionkunz** [comment]
hehe :smiley: Well its also nice to have a visual feedback of your javascript when you code ;-) Specially on such a visual project like this. Also assemble is responsible to create the API documentation from your javascript comments, so it's important to have feedback there too :-) I guess you need to conquer your fear :smile: 

I'll rename this issue to something more generic that I agree with.

Cheers
