### ISSUE TITLE
Double numbers in Y-axis labels in bar chart

### ISSUE THREAD

**Issue by sgraham3311** [chartist-js/chartist#391]
When the highest value in my series is less than the number of horizontal grid lines I get double numbers. As shown here in the image. How can I avoid or fix this?

![yaxis](https://cloud.githubusercontent.com/assets/3640686/8865248/80cb8366-317a-11e5-9e74-24e442a4410c.png)

**Comment by gionkunz** [comment]
Can you show us your configuration?

**Comment by sgraham3311** [comment]
``` javascript
 var dfaultChartOpts = {
            axisX: {
                showGrid: false
            },
            axisY: {
                labelOffset: {
                    x: 0,
                    y: 0
                },
                onlyInteger: false
            }
        };
```

**Comment by gionkunz** [comment]
I could never reproduce this issue. Please reopen if needed.
