### ISSUE TITLE
Horozontal chart squeezed

### ISSUE THREAD

**Issue by Bjolja** [chartist-js/chartist#392]
I am trying to use Chartist togheter with Knockout and i cannot figure out what is happening. The data from knockout is correct, and all the labels and the series are there. The problem comes when it is rendering:
![chartist](https://cloud.githubusercontent.com/assets/8234514/8876533/9c34387c-3220-11e5-90e1-78b0cc47af3f.PNG)

Everything is 1px high, labels and everything. I cannot reproduce this problem in a Fiddle either.

The only thing I can imagine can be the problem is that the div is not visible as first, but loads a few seconds after, to give the user a better experience (have a spinner while loading).

Do you know about this?

**Comment by gionkunz** [comment]
We need code to help you out. Please re-open if still a problem.
