### ISSUE TITLE
Horizontal bar chart doesn't have top grid line

### ISSUE THREAD

**Issue by miguelcb84** [chartist-js/chartist#395]
As seen in example from http://gionkunz.github.io/chartist-js//examples.html.

When the grid is more prominent, the lack of top line makes the chart weird.

**Comment by HopefulLlama** [comment]
+1

**Comment by JosefWN** [comment]
+1

Same issue with the vertical bar charts and the rightmost grid line. Adding a slight padding doesn't seem to help.

It might not look very bad in the examples, but with other stylesheets making the gridlines more prominent it's quite nasty on the eye.

**Comment by gionkunz** [comment]
This is because the chart does not draw in `fullWidth` mode by default (backwards compatibility). Switch on full width in the options and use `paddingRight` to get more padding for the last label.

**Comment by JosefWN** [comment]
Have tried that in my project and in your interactive examples on your site, it didn't work. fullWidth seems to be ignored for some reason :(

**Comment by gionkunz** [comment]
It works for me. Can you try again? `fullWidth` needs to be set directly in the options object and not on the axis configuration.

**Comment by JosefWN** [comment]
It works on some, not on all. Try it on the bi-polar chart for example. The W10 label is missing however I do it, and so is the rightmost grid line.

![screen shot 2015-10-19 at 16 03 18](https://cloud.githubusercontent.com/assets/12534742/10579895/06e927ec-767b-11e5-937b-8a3090d31092.png)

EDIT: This is in latest Chrome on OS X 10.11.

EDIT 2: Okay, the label is supposed to be missing there, but I still don't see this working on any bar chart example. I got it working on line charts though.

**Comment by gionkunz** [comment]
Yeah, because there is a `labelInterpolationFnc` in use that skips some labels / grid lines.

**Comment by JosefWN** [comment]
Let me pick a better example:
![screen shot 2015-10-19 at 16 13 09](https://cloud.githubusercontent.com/assets/12534742/10580136/5d47089c-767c-11e5-9698-785232f2c7fe.png)

Also, will this fix work for horizontal bar charts (the width there isn't the problem, it's the height)?

**Comment by gionkunz** [comment]
I'm sorry. You're right. The problem is with bar charts as they don't have a `fullWidth` option. I think we need to look at this again from all angles.

**Comment by gionkunz** [comment]
We should address this in #809
