### ISSUE TITLE
Bar chart draws full height when encounters null value

### ISSUE THREAD

**Issue by ghost** [chartist-js/chartist#396]
expected behaviour is to draw zero height

**Comment by ghost** [comment]
this https://github.com/gionkunz/chartist-js/blob/develop/src/scripts/charts/bar.js#L316 seems as a good place to add check for null, too

**Comment by gionkunz** [comment]
The data at that point is normalized by `Chartist.getDataArray` so there's only numeric values, multi values ({x, y}) or undefined.

Please show the configuration you're using.

**Comment by gionkunz** [comment]
https://github.com/gionkunz/chartist-js/blob/develop/src/scripts/core.js#L337-L381

**Comment by ghost** [comment]
This is configuration for bar chart

```
    new Chartist.Bar('.ct-chart-monthly-vol', dataVol, {
      chartPadding: {
        top: 0,
        right: 0,
        bottom: 0,
        left: 35
      },
      axisY: {
        labelInterpolationFnc: function (value) {
          return CF.Utils.monetaryFormatter(value);
        }
      },
      plugins: [
        Chartist.plugins.tooltip({
          transform: function (v) {
            return "Ƀ " + CF.Utils.readableN(v, 2);
          },
          labelOffset: {
            x: 0,
            y: -20
          }
        }),
        Chartist.plugins.ctAxisTitle({
          axisX: {
            axisTitle: '',
            axisClass: 'ct-axis-title',
            offset: {
              x: 0,
              y: 50
            },
            textAnchor: 'middle'
          },
          axisY: {
            axisTitle: 'Trade Btc',
            axisClass: 'ct-axis-title',
            offset: {
              x: 0,
              y: -4
            },
            textAnchor: 'middle',
            flipTitle: false
          }
        })
      ]
    });
```

and so far i just replace `null` values with `0`s

**Comment by gionkunz** [comment]
I've tested in 0.9.1 and Chartist draws 0 height on null and undefined and any other falsey value except 0. In 0.9.2 there seems to be a bug introduced where undefined will break the processing. I'll file a bug for that.

**Comment by gionkunz** [comment]
This should no longer be a problem with 0.9.8. Please re-open if needed.
