### ISSUE TITLE
Scaling width of chart according to the data, not according to the parent container

### ISSUE THREAD

**Issue by watsmyname** [chartist-js/chartist#398]
I have few issues
1. How to give a fixed space between scale points in X Axis. I m using string labels as x-axis label.
2. Right now graph can be scaled only on the basis of its parent container.  How can I scale chart on the basis of the data. That means if there are many data, the width should keep increasing accordingly.

How can I these be achieved?
Thanks, Sabin

**Comment by bartveneman** [comment]
Not tested, but you could try not to use the responsive container (with the padding-bottom in %) but use a fixed padding with px for example.

**Comment by gionkunz** [comment]
@watsmyname This is currently not supported. However, the approach @bartveneman describes would work.

**Comment by gionkunz** [comment]
Closing this while favoring the current way Chartist makes use of container to lay out the dimensions. An approach to pre-calculate a fixed height for the container is always possible.
