### ISSUE TITLE
Chartist.Svg.isSupported wrong url?

### ISSUE THREAD

**Issue by pomm0** [chartist-js/chartist#401]
Hey,

I went through your code and saw how you build your feature-string:

https://github.com/gionkunz/chartist-js/blob/develop/dist/chartist.js#L2187

Just wanted to ask, if this is correct, I have to say that after a bit of googling didn't figure out if it's correct or not and i never used "document.implementation.hasFeature".

Shouldn't it be:

return document.implementation.hasFeature('http://**www.**w3.org/TR/SVG11/feature#' + feature, '1.1');

instead of:

return document.implementation.hasFeature('**www.**http://w3.org/TR/SVG11/feature#' + feature, '1.1');

Thank You

**Comment by gionkunz** [comment]
Hey @pomm0 

Yes, you're right! This is a typo... Funny is that Chrome always returns true no matter what you pass e.g. document.implementation.hasFeature('Burritos With Hot Sauce', '1.1');

It should be: `document.implementation.hasFeature('http://www.w3.org/TR/SVG11/feature#' + feature, '1.1');`

Can you make a PR? Be sure the change this only in the source file: https://github.com/gionkunz/chartist-js/blob/develop/src/scripts/svg.js#L535-L537

Cheers
Gion

**Comment by pomm0** [comment]
I've made a PR and tried to link it to this issue, but i guess i failed :) I'm new in this stuff, sry ;) Can you work with the PR or do i have to make it again in the right way?
