### ISSUE TITLE
Display data on x-axis when value is 0

### ISSUE THREAD

**Issue by marceloferraz** [chartist-js/chartist#407]
Hi,

I'm using tooltips on a bar chart, so what i'm trying to do is when the value is 0, I can still show a small amout of data on the bar and being able to tooltip it. Like this example I got from shopify.
<img width="542" alt="captura de tela 2015-08-17 as 01 25 09" src="https://cloud.githubusercontent.com/assets/2467369/9298056/ea764be0-447e-11e5-8228-758859a2216a.png">

Is there any configuration I can add?
I tried setting every value 0 value to 1, and displaying it on the tooltip as 0, but I still have some trouble setting a min value on y-axis (when I set high to 100, every value above it is limited to it)

Thanks

**Comment by gionkunz** [comment]
Hi There. Can you file this issue against the chartist-plugin-tooltip repository please?
