### ISSUE TITLE
Firefox not dynamically responsive ?

### ISSUE THREAD

**Issue by Goodzilla** [chartist-js/chartist#41]
When I'm using Google Chrome, I can resize the window and the charts will scale accordingly, as you would expect.

When I'm using Firefox (latest version, which I believe is 32), the charts won't redraw if I resize the window. They seem to scale only once, when the page is being loaded.

**Comment by gionkunz** [comment]
Hiya! Thanks for the issue report! Looks like FF32 does not like node.className = "" anymore :)

I'll fix that and push a new release today when I've also fixed #40 

Cheers
Gion

**Comment by gionkunz** [comment]
Looks like FF32 does return a SVGAnimatable property when accessing className on an SVG element, which is kind of odd behavior if you ask me. I've filed a bug https://bugzilla.mozilla.org/show_bug.cgi?id=1067385

I'll provide a workaround in the bugfix release today.

Cheers
Gion

**Comment by Goodzilla** [comment]
Thanks, looking forward to using chartist !

**Comment by gionkunz** [comment]
This is fixed and Chartist v0.1.14 is just pushed
