### ISSUE TITLE
Feature request: Dual y-axes for line charts

### ISSUE THREAD

**Issue by mpskovvang** [chartist-js/chartist#412]
This is just a suggestion I could use myself.

Sometimes you'll want to display two series in a line chart, with two independent y-axes: a left axis for one series, and a right axis for another.

Like Google Charts:
https://developers.google.com/chart/interactive/docs/gallery/linechart#dual-y-charts

Maybe I will start working on it myself if I get time.

**Comment by gionkunz** [comment]
Hi there! Thanks for your thoughts on that. We actually had this already here #60 and I believe this should be implemented under #37. If you have any ideas / concepts before you write any code please lets discuss in #37. Cheers and thanks so much for your contribution.
