### ISSUE TITLE
Adding images to labels

### ISSUE THREAD

**Issue by codev0** [chartist-js/chartist#415]
I need to add images to labels area.
As here
![ScreenShot](https://i.imgur.com/2fPk6Rx.png)
I created bar chart

```
    /**
     * Init persons chart
     */
    var data = {
        labels: [
            '<img src="holder.js/60x60"> <a href="#">Person name</a>',
            '<img src="holder.js/60x60"> <a href="#">Person name</a>',
            '<img src="holder.js/60x60"> <a href="#">Person name</a>',
            '<img src="holder.js/60x60"> <a href="#">Person name</a>',
            '<img src="holder.js/60x60"> <a href="#">Person name</a>',
            '<img src="holder.js/60x60"> <a href="#">Person name</a>',
            '<img src="holder.js/60x60"> <a href="#">Person name</a>',
            '<img src="holder.js/60x60"> <a href="#">Person name</a>',
            '<img src="holder.js/60x60"> <a href="#">Person name</a>',
            '<img src="holder.js/60x60"> <a href="#">Person name</a>',
        ],
        series: [
            [1, 2, 3, 4, 5]
        ]
    };
```

But see this, and inline styles dont working
![ScreenShot2](https://i.imgur.com/NcfGHa1.png)

**Comment by gionkunz** [comment]
@codev0 Sorry for the late reply. Did you figured out a solution yet? I can definitely take a look and see help you find the best option.

**Comment by codev0** [comment]
Hi.
No, I did't. It would be nice

**Comment by brunocascio** [comment]
+1

**Comment by nadavcompedia** [comment]
+1

**Comment by JamesJosephFinn** [comment]
+1

**Comment by sconnors37** [comment]
+1

**Comment by slavajacobson** [comment]
+1

**Comment by gionkunz** [comment]
I'm sorry this took so long. After a bug which needed to be fixed for namespaced attributes, this can now be done relatively easy. http://jsbin.com/dilojuh/1/edit?js,output

**Comment by gionkunz** [comment]
Closing this for now, you should use SVG to draw this kind of chart.

**Comment by 1asolutions** [comment]
Hello gionkunz,

I am trying to adapt your code to add similar photos in a horizontal stacked bar taking the svg images from my disk but I get the same error than codev0 and I cannot even show stacked bars. Could you please help?
