### ISSUE TITLE
Chart labels vertical

### ISSUE THREAD

**Issue by AliYousif** [chartist-js/chartist#417]
In the html i use:

 "<#div class="ct-chart ct-perfect-fourth"></div> "
without #, its just so u can see it.

And in script:
I send the options for chart:

  var options = {
                seriesBarDistance: 15,
                width: 800,
                height: 500,
                low: low,
                high: 3600,
                onlyInteger: true,
                classNames: {
                    label: 'ct-label'
                }
            };

This gives me a chart with x and y axis, the are labels normal horizontal but the labels are rather long so i want to flip the labels on the x axis. what is the easiest solution?

**Comment by gionkunz** [comment]
If you want to rotate the labels use CSS. There are various cases where people already did this: #375, #237 and there are also other examples. This is maybe worth adding to the documentation. I've created #420 for that.

**Comment by AliFahim** [comment]
I look at those, i cant seem to make it work? they only rotate like 30degree like in #375 first picture.

**Comment by hurricaneffs** [comment]
@gionkunz Hello, i fixed it easy in the css.
Can you help me with this, i need to show the whole label. i tried edit labels margin and stuff nothing. what to do? and the last number is not showing fully why? Attach picture.
![unavngivet](https://cloud.githubusercontent.com/assets/5947224/9521007/41a12750-4ccc-11e5-95aa-1242ec0b9e18.png)

**Comment by mattiLeBlanc** [comment]
Eventually it would be nice to enable or disable the flipped or rotated labels based on the responsive rule in your chart definition.
And / or based on an x amount of columns.
When space becomes an issue it would be nice to have multiple ways to deal with it.
