### ISSUE TITLE
invalid value for ct:values (filled line chart)

### ISSUE THREAD

**Issue by yairEO** [chartist-js/chartist#424]
## Problem:

clearly `ct:values="[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]"` is not a valid value for an attribute...

only happens for `showArea : true`

![mozilla firefox 2015-08-27 22 34 51](https://cloud.githubusercontent.com/assets/845031/9531168/1232839c-4d0d-11e5-807d-db267a882f04.png)

**Comment by gionkunz** [comment]
Thanks for the report! This should be fixed. We have removed the serialization of values on lines so we  should also do that for area.
