### ISSUE TITLE
making "labels" optional

### ISSUE THREAD

**Issue by yairEO** [chartist-js/chartist#425]
There is no need to in forcing the input of a `labels` array... simply inputting empty array items is time-consuming and redundant.

**Comment by gionkunz** [comment]
Something we can definitely incorporate in a future version!

**Comment by rdpascua** [comment]
Or a way to hide the label

```
{
     xAxisLabel: false
}
```

**Comment by yairEO** [comment]
hiding is nothing compared to the problem of forcing a dev to create useless empty Array with N length just so the script would work..

**Comment by gionkunz** [comment]
@rdpascua hiding is already possible. See http://gionkunz.github.io/chartist-js/api-documentation.html#chartistline-declaration-defaultoptions

``` javascript
  // Options for Y-Axis
  axisY: {
    // If labels should be shown or not
    showLabel: true,
    // If the axis grid should be drawn or not
    showGrid: true,
    // Interpolation function that allows you to intercept the value from the axis label
...
```

This task is really about the possibility of skipping labels at all from the configuration when the AutoScaleAxis is created from the default configuration.
