### ISSUE TITLE
Charts not showing in firefox/IE

### ISSUE THREAD

**Issue by AliYousif** [chartist-js/chartist#427]
I have a problem showing the charts and correct css?
in chrome no problems what so ever, but FF, IE and Edge dosnt show correct.
I dont think it gets the css.

![unavngivet](https://cloud.githubusercontent.com/assets/5947224/9575325/1093bb04-4fcf-11e5-8fee-6c1202f27599.png)

This is the head of the page.
`<head>
        <script src="/Scripts/SB-Admin/plugins/knockout/knockout-3.2.0.js"></script>
        <script src="/Scripts/SB-Admin/plugins/chartist/chartist.js"></script>
        <link href="/css/SB-Admin/css/plugins/chartist/chartist.css" rel="stylesheet" type="text/scss">
        <link rel="stylesheet" type="text/css" href="/css/analytics.css">
    </head>`

**Comment by gionkunz** [comment]
Probably other browsers don't like the `type="text/scss"` attribute on your `link` element :-)

**Comment by gionkunz** [comment]
You can omit type attribute on stylesheet `link` element
