### ISSUE TITLE
Error: Problem parsing d="MNaN,NaNA40,40,0,0,0,70.5,75"

### ISSUE THREAD

**Issue by louy** [chartist-js/chartist#428]
Hello,

I'm trying to create a gauge chart (Pie) with custom classNames, but I'm getting the following error:

```
Error: Problem parsing d="MNaN,NaNA40,40,0,0,0,70.5,75"
```

My setup is:

```
    <ChartistGraph data={{
      labels: ['So Far', 'Expected'],
      series: [{
        data: 10,
        className: 'so-far',
      }, {
        data: 20,
        className: 'expected',
      }],
    }} options={{
      total: 200,
      showLabel: false,

      donut: true,
      donutWidth: 60,
      startAngle: 270,
    }} type={'Pie'} />
```

It works fine if I use `series: [10,20]`.

**Comment by louy** [comment]
Nevermind. It should've been `value` instead of `data`.
I read this https://github.com/gionkunz/chartist-js/issues/79#issuecomment-65817712 and it was misleading apparently.

**Comment by gionkunz** [comment]
Nice you figured it! And sorry I never replied to your issue.

**Comment by louy** [comment]
No worries. Maybe @DSpeckhals would want to update his comment.

**Comment by DSpeckhals** [comment]
@louy Ahhh...yes. It looks like @gionkunz [refactored that code a few months ago](https://github.com/gionkunz/chartist-js/commit/85e4e37f4b63a71e471858ccbb582381f89abae8). I edited my comment. Thanks!
