### ISSUE TITLE
showArea with multiple Line Charts breaking behavior of Tooltip Plugin

### ISSUE THREAD

**Issue by Ilphrin** [chartist-js/chartist#429]
Hi

I am working with Line Charts to show to lines with the parameter 'showArea' set to True, and I am using the Tooltip Plugin with it. When my mouse is hovering the highest line everything is working fine but if my mouse hover the line under this one, the tooltip is showed only with the points located on each side of the bar. When I disable 'showArea' everything is fine with the both lines. It seems that the .ct-area of the top Line is covering the other bar and then there is no way the tooltip may work correctly. Here is a screenshot to show you what I'm experiencing:
![chart02](https://cloud.githubusercontent.com/assets/7887258/9626012/c48a1cf2-515a-11e5-8c78-d6fb0456d333.jpg)

![chart01](https://cloud.githubusercontent.com/assets/7887258/9626019/caf74ce0-515a-11e5-9641-153fb80d4ff2.jpg)

By the way, thank you for this awesome Chart library, even if it is still in beta it is really powerfull and easy to use! :D

**Comment by gionkunz** [comment]
Hi there. For IE11+ and all other browsers you can use this style to fix the issue. Maybe it would be nice to have a fix for this in one of the tooltip plugins.

``` css
.ct-area {
  pointer-events: none;
}
```

**Comment by Ilphrin** [comment]
This work pretty well, thanks a lot! =)
