### ISSUE TITLE
Labels in IE9 gets the wrong size and can't be rotated

### ISSUE THREAD

**Issue by skristensen** [chartist-js/chartist#431]
A couple of issues regarding labels in IE9

**Sizing**
Label sizes are too wide in IE9. They don't get the size of the corresponding grid, causing them to overlap each other. Possible because IE doesn't use <foreignobject>  <span>, but instead uses a <text> element.

**Rotation**
Label rotation in IE9 through CSS doesn't seem possible.

I have tried the rotate attribute on the text tag which shows up in IE. This rotates the individual characters rather than the entire label.

CSS transform works fine in everything else than IE9 and below (CSS transforms do work in IE9, just not on SVG elements as far as I can see).

**Comment by thelongshot** [comment]
For others who run across this topic, I was having a similar problem in IE11.  I found this article:

https://css-tricks.com/transforms-on-svg-elements/

That says that CSS transforms don't work on SVG elements in IE11.  Now I need to figure out how to put an SVG transform on my labels.

**Comment by gionkunz** [comment]
I'm closing this issue for now
