### ISSUE TITLE
Strange draw lines

### ISSUE THREAD

**Issue by GPMMM** [chartist-js/chartist#432]
Hi,

It is possible to remove the curve (g->h) from the line?

![image](https://cloud.githubusercontent.com/assets/12935159/9682106/7dc40786-52fb-11e5-8fe8-4dc09c9fc636.png)

Code:
new Chartist.Line('.ct-chart', {
  labels: ['a', 'b', 'c', 'd', 'e','f','g','h','i'],
  series: [
    [1, 1,null, null, null,0, 1, 1, 1],
  ]
},{ axisY:{ scaleMinSpace: 200}, high:2});

Thanks,
Plácido

**Comment by gionkunz** [comment]
Hi there. You can use the simple line smoothing interpolation function: http://gionkunz.github.io/chartist-js/examples.html#example-line-simple-smoothing
