### ISSUE TITLE
Automatic height

### ISSUE THREAD

**Issue by OmeGak** [chartist-js/chartist#437]
Is there any way to have a chart growing in the Y-axis as necessary?

I have the following example:
http://plnkr.co/edit/5OGe2q3uJGD0ZOVmckT3

``` js
new Chartist.Bar('.chart', {
    labels: [...],
    series: [[...]]
}, {
    horizontalBars: true,
    reverseData: true,
    axisX: {onlyInteger: true},
});
```

For a long list of labels I would be expecting the chart to grow in height instead of overlapping the bars. So far, the only solution I have found is to manually set the height of the chart, but this gets tricky when the list of labels depends on user input. Is there a more correct way of doing this or are there plans to add some kind of `height: 'auto'` option?

**Comment by treadmillian** [comment]
If there is no option, you could just calculate the height based on the number of labels.  In your case, 16 labels \* 20 seems to look presentable.

**Comment by sardbaba** [comment]
@OmeGak you can try to remove the class for the aspect ratio. The container should grow up as the number of labels grows.

You could also have to add this:

```
        var ll = labels.length
        chartOptions.height = (ll*40+40)+'px'; // last 40pxs are for the labels

        var chartist = new Chartist.Bar(container_id, {
            labels: labels,
            series: [
                series
            ]
        }, chartOptions);
```

**Comment by OmeGak** [comment]
This is how I did it in the end.

``` js
var labels = [...]
var labelsHeight = labels.length * 20;
var containerHeight = $(elem).parent().outerHeight();
new Chartist.Bar(elem, {
    labels: labels,
    series: [[...]]
}, {
    horizontalBars: true,
    height: Math.max(labelsHeight, containerHeight) + 'px',
    axisX: {
        onlyInteger: true,
    }
});
```

I still think there should be at least a way in Chartist to specify the min-height for labels and then let it figure out the total height.

**Comment by HugCoder** [comment]
Yes, I'm in the same situation (pretty much). I have a horizontal bar chart which get data dynamically from server. It's basically showing statistics where it has a label and a count. I need a way to increase the height as more data/labels are added. I thought of using the labelInterpolationFnc to increase the height every time there's a label showing up but I'm not sure it's a good way or if I can make it work without some kind of hack.

**Comment by gionkunz** [comment]
If there's new data from the server, you should update the data in the chart and also update the options with a newly calculated fixed height.

I'm closing this issue for now, but I think we should include an example here #733 

Cheers and thanks for all the comments!
