### ISSUE TITLE
Change the order of a series in bar chart

### ISSUE THREAD

**Issue by cheposki** [chartist-js/chartist#438]
Hi i like to change the order of the series 

this is the actual order

var data = {
  labels: ['Jan', 'Feb', 'Mar', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
  series: [
    [5, 4, 3, 7, 5, 10, 3, 4, 8, 10, 6, 8],
    [3, 2, 9, 5, 4, 6, 4, 6, 7, 8, 7, 4]
  ]
};

i like sonething like this

var data = {
  labels: ['Jan', 'Feb', 'Mar', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
  series: [
    [5,3 ],
[ 4,2],
[ 3, 9],
[ 7, 5],
[10, 4],
[ 3, 6],
[ 4, 4],
[8, 6], 
[ 10, 8],
[ 6, 7],
[ 8,4]
]
};

Please help

**Comment by HopefulLlama** [comment]
I can't see any advantages your preferred formatting would bring. Most datasets are given as a series with an array of data, which would match the first and currently used formatting.

In addition, this way disabling a series is just removing an array from the view, rather than an index of multiple arrays.

Could you perhaps elaborate on why you would prefer your proposed formatting?

**Comment by cheposki** [comment]
I need this structure , because the information they are sending me come this way.

I have a table with different roles of employees and the total spent by each role in the month .

for example I have

{dba Sep 5000,dba oct 3000, dba nov 1000, dev sep 2000, dev oct 8000, dev nov 2000}

and I want to group data by the role and then the month
![rolchart](https://cloud.githubusercontent.com/assets/5551355/9735214/c4fef0a6-55fe-11e5-97d2-da94cc643165.PNG)

would be easy if i can put 

{dba,dev}
{5000,3000,1000}
{2000,8000,2000}

or

{dba{5000,3000,1000}},{dev{2000,8000,2000}}

**Comment by gionkunz** [comment]
There's nothing wrong with using some pre-processing of your data using the awesome Array extras introduced with ES5.1 ;-)

http://jsbin.com/somuva/edit?html,js,console

**Comment by gionkunz** [comment]
Closing this issue, please re-open if needed
