### ISSUE TITLE
Multiple representations of similar data.

### ISSUE THREAD

**Issue by ghost** [chartist-js/chartist#44]
I absolutely admired Chartist, it is my suggestion that if you want more people to use it. Just try to put a simple example of a certain set of information (anything at your ease) and try to represent it into various charts and figures to explain the versatility of Chartist. people will instantly will pick up.

**Comment by gionkunz** [comment]
Hi there! Thanks for your input. I'll defiantly consider this when I work on the documentation the next time.

Cheers
Gion
