### ISSUE TITLE
Chrome deprecated SMIL

### ISSUE THREAD

**Issue by celebro** [chartist-js/chartist#440]
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/5o0yiO440LM

In Chrome version 45 I'm getting a warning: SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.

The documentation should be updated to reflect this.

**Comment by gionkunz** [comment]
Yeah, I still need to dig into this a bit. But from what I can tell this is definitely too early and I think the Chrome Team are a bit trigger happy here. There are still many SMIL users out there (even the YouTube play / pause button is (or at least was quite recently) done with SMIL).

CSS Animations obviously can't replace SMIL as you can't animation individual properties. Web Animations API could possible replace but browser support is quite poor and the W3C spec is still in draft mode! Also I still see no way to do shape morphing (path animation) in the Web Animations API spec (but as already said, I didn't invest too much time researching).

As you can see, it's just too early to deprecate and I have no clue why they are really serious with this Warning already in the current Chrome.

As a short term solution we can already make a note on the documentation, but mid term and long term we need to evaluate and follow the open discussions of problems that come up in all sorts of projects at the moment.

Cheers and thanks for opening the issue.
Gion

**Comment by gionkunz** [comment]
Closing this issue in favor of #468

**Comment by athimannil** [comment]
@gionkunz  Thanks for your answer which is really helpful :+1:
