### ISSUE TITLE
Tooltips way off

### ISSUE THREAD

**Issue by peterbe** [chartist-js/chartist#442]
![screenshot 2015-09-08 13 36 55](https://cloud.githubusercontent.com/assets/26739/9746782/bc688dbe-562e-11e5-9e4c-c9efc0f49c7d.png)

Using Firefox 42. Haven't tested any other browser.

**Comment by treadmillian** [comment]
I found this temporary fix on the web.  In chartist-plugin-tooltip.js change this:

<code>
      $chart.on('mousemove', function(event) {
        $toolTip.css({
          left: (event.offsetX || event.originalEvent.layerX) - $toolTip.width() / 2 - 10,
          top: (event.offsetY || event.originalEvent.layerY) - $toolTip.height() - 40
        });
      });
</code>

to this

<code>
      $chart.on('mousemove', function(event) {
        $toolTip.css({
          left: (event.originalEvent.layerX || event.offsetX) - $toolTip.width() / 2 - 10,
          top: (event.originalEvent.layerY || event.offsetY) - $toolTip.height() - 40
        });
      });
</code>

**Comment by gionkunz** [comment]
Hi there. We will remove the example from the documentation there because tooltips should be implemented with one of the Chartist tooltip plugins. @treadmillian have you ever tested this / raised your solugion with the tooltip plugin? https://github.com/Globegitter/chartist-plugin-tooltip

**Comment by jayeshagwan1** [comment]
Can some post how to use tooltip plugin for angular 2 ?
