### ISSUE TITLE
Height is way off

### ISSUE THREAD

**Issue by yairEO** [chartist-js/chartist#443]
It seems the chart code does **not** respect the height of the container element (no idea why such a fundamental thing doesn't work).

https://jsbin.com/lipususega/edit?css,js,output

Any idea how to make the graphs just fit in their container? especially the negative one is really weird. they **must** fit in the container, which has fixed height in this example.

**Comment by yairEO** [comment]
I see by manually calculating `high` and `low` options, things appear a bit better

update: the generated SVG has very strange bounds and the only way to fit the graph 100% width and height is by a lot of hacks with `transform scale` and marings. too bad it can't just fit automatically.

# update:- found a bug

The `height` setting does _not_ work in Firefox, but works on Chrome.
https://jsbin.com/wogukuyosu/1/edit?css,js,output

```
showArea  : true,
showLine  : false,
showPoint : false,
fullWidth : true,
axisX: {
   showLabel: false,
   showGrid: false
},
height: '100px' 
```

**Comment by dreamyguy** [comment]
I thought `height` was defined with `height: 100` - not a string and without the `px`part, but it seems to work though. Maybe that's the way to support other units. But back to the problem you reported, I think it's the nature of SVGs to be sized without considering the parent element, so if you drop the inline `height: 75px` everything works.

**Comment by yairEO** [comment]
@deamyguy -  I repeat, `height` setting does not work in in Firefox, no matter what you do. and I will not drop off the CSS height to the container, that is the design demand and that demo link is a super simplified page of the actual design, so if the API says height does something and in reality it does not, that is a bug. I am currently stuck with firefox over thing issue. can't launch the product like this.

**Comment by gionkunz** [comment]
@yairEO There are couple of issues here with your Chart. First of all, if you'd like to hide the X-Axis labels you should use the appropriate configuration `showLabel` set to false on the `axisX`. Returning an empty string for labels to be skipped but gridlines to be drawn is a workaround where there shouldn't really be one.

Secondly there are a couple of things to configure if you'd want to get rid of the whole spacing Chartist applies to your charts.

The most obvious one is `chartPadding` as a global settings. There is also an `offset` configuration on the given axis that is preconfigured to fit regular text size labels. This value can be changed to something higher if the labels use a very big font.

Here's an example: http://jsbin.com/lujaro/edit?html,css,js,output

There are a couple of possible changes I would see as an option.
- Setting `showLabel` to false could also explicitly set `offset` of the same axis to 0
- axis offset and chartPadding are somewhat interrelated and I know it feels a bit redundant, however, it's important as start point of the labels should probably not be the container border but respect some padding that can be configured.
- Automatically calculate label width / height and reserve necessary space. This was done already in earlier Chartist versions and I just consider this very harmful as it involves rendering and measuring just for the purpose of automatically adjust their width / height. This causes reflow which we can't really use on mobile specially. There was also an issue where it was recommended as optional setting but that never made it though.

**Comment by yairEO** [comment]
@gionkunz - Thanks! setting  `axisX.offset` to `0` does solve things. But who could have possibly guessed such an **important** thing? but what about the bug? the demo works differently in FF than Chrome.

**Comment by gionkunz** [comment]
The offset setting is described in the default options hidden under the `show code` button ;-)

**Comment by gionkunz** [comment]
Which demo? The example I just provided looks the same in both browsers: 
![image](https://cloud.githubusercontent.com/assets/2203704/9816637/8d17d6b0-589e-11e5-9af3-523d0fbab1d1.png)

**Comment by yairEO** [comment]
well, I was referring to the bug I was reporting, so the demo link is the one with the bug report setup:

![js bin - collaborative javascript debugging - google chrome 2015-09-11 17 31 41](https://cloud.githubusercontent.com/assets/845031/9817364/0c33b3b8-58ab-11e5-84e0-3c737d450a29.png)

Very different result for FF and Chrome with the same setup.

---

what do you mean reflow? how much are we talking about here? i thought it only reflows when the browser window is re sizing. else, the measuring is only done once no?

**Comment by gionkunz** [comment]
@yairEO http://mir.aculo.us/2010/08/17/when-does-javascript-trigger-reflows-and-rendering/

**Comment by yairEO** [comment]
@gionkunz - http://www.vocabulary.com/dictionary/condescending

please, no condescending, lets keep this normal

**Comment by gionkunz** [comment]
Sorry?

**Comment by yairEO** [comment]
> Automatically calculate label width / height and reserve necessary space. This was done already in earlier Chartist versions and I just consider this very harmful as it involves rendering and measuring just for the purpose of automatically adjust their width / height. This causes reflow which we can't really use on mobile specially. There was also an issue where it was recommended as optional setting but that never made it though.

what EXACTLY took so many reflows? how many reflows? when did they occur? I can help you guys if you would share information instead of posting weird links about basic DOM things..

**Comment by gionkunz** [comment]
I was referencing to an article of Thomas Fuchs from 2010 about reflow triggered by measuring only. If you feel I was acting condescending, then I'm very sorry that was definitely not my intention :-)

I just tested in a very isolated example that setting a height in FF 40 in px is not working as expected. I'll need to debug this first.

**Comment by yairEO** [comment]
Thank you :) that was the bug I was issuing...the `height` property doesn't work on FF (doesn't matter with `px` or not)

**Comment by gionkunz** [comment]
If opened this bug #448 for tracking this issue with a little bit less noise, the example is reduced to the minimum to reproduce the issue.
