### ISSUE TITLE
Hide intersected area

### ISSUE THREAD

**Issue by brunocascio** [chartist-js/chartist#445]
Hi guys!

I need delete the intersected area of my chart. Example:

![captura de pantalla 2015-09-10 a las 12 28 05](https://cloud.githubusercontent.com/assets/2397875/9792616/74b68d88-57b7-11e5-849e-3c67f5736f0d.png)

Actually my chart look like this:

![captura de pantalla 2015-09-10 a las 12 29 34](https://cloud.githubusercontent.com/assets/2397875/9792659/9f483f2e-57b7-11e5-9179-b7b3fd556d08.png)

Expected result:

![captura de pantalla 2015-09-10 a las 12 29 34](https://cloud.githubusercontent.com/assets/2397875/9792762/2ea9412c-57b8-11e5-8684-fcce941dd52f.png)

My code:

``````
var chart = new Chartist.Line('#chart2', 
{
    labels: [1, 2, 3],
    series: [
    {
        name: 'investiment', 
        data: [3, 3, 3]
    },
    {
        name: 'roi',
        data: [1.75, 2.75, 10.75],
    }
    ]
}, 
{
    series: {
        'investiment': {
            showArea: false,
        },
        'roi': {
            showArea: true,
        }
    },      
    showPoint: false,
    fullWitdh: false,
    axisX: {
        showGrid: false,
        showLabel: true,
        labelOffset: {
            x: -55,
            y: -20
        },
        labelInterpolationFnc: function(value) {
            var lastPoint = chart.data.series[0].data.length;
            if ( value === lastPoint ) {
                return 'investiment';
            } else {
                return '';
            }
        },
    },
    axisY: {
        showGrid: true,
        showLabel: true,
        position: 'end',
    },
}
);```


``````

**Comment by gionkunz** [comment]
You can use the `draw` event to intercept the creation of the area and then use the `Path` API to modify the Area path. Search for `draw` on the github issues to find more infos. We still lack in event documentation #90

**Comment by gionkunz** [comment]
Let me know if you need more help. I don't have a lot of time atm but I'm sure I'll be able to provide an example if I'l find some time soon.

**Comment by brunocascio** [comment]
Ok, i will try, thanks @gionkunz !
