### ISSUE TITLE
Charts are not rendered on IOS 5.1 (IOS 6) works

### ISSUE THREAD

**Issue by jamesbrauman** [chartist-js/chartist#446]
Hi,

I've just noticed today that none of are charts are rendering on Safari on IOS 5.1 or below. Safari on IOS 6 renders the charts correctly.

We have other inline SVGs in this project that are rendered fine by the above IOS versions, so I'm not sure what the problem is.

What I've tried:
1. Add the `xmlns="http://www.w3.org/1999/xhtml` attribute to the `<html>` tag. This fixed some other issues with SVGs but the charts still do not render.
2. Hacked the chartist.js file to add `xmlns="http://www.w3.org/2000/svg" version="1.1"` attribute to every svg element created by Chartist. Charts still do not render.

Has anyone successfully used Chartist on Sfari IOS 5.1 or below? Is there any secret? Otherwise I will have to fall back to a normal image :(

Thanks

**Comment by gionkunz** [comment]
The charts on the example page of chartist are working fine in my iOS 5.1 (iPhone 6) simulator. 
![image](https://cloud.githubusercontent.com/assets/2203704/9814665/1a157d10-5890-11e5-887f-f53fffce750c.png)

I don't have a real device at hands but can you verify if the examples are not working on your phone?

I know the chart will not be displayed if you use the animation API on devices that dont support SMIL. Are you using any animations?

Cheers
Gion

**Comment by jamesbrauman** [comment]
Hi @gionkunz, thanks for the prompt response. It must be something that we're doing with the charts then, although I'm not quite sure what it could be. I should've thought to check the examples on the Chartist docs, doh!

If you like you can close this issue and I'll PM you with my findings once I've figured out what the problem is. Thanks for the excellent library btw!

**Comment by gionkunz** [comment]
No worries. If you post some code and maybe also css of yours maybe someone
can spot an issue here.

**Comment by Robzelf** [comment]
@thesnackalicious did you solve this? I'm having the same problem.

**Comment by jamesbrauman** [comment]
Sorry not yet, we've been super busy on this project and haven't had a
chance yet. Will update when I figure it out.

**Comment by gionkunz** [comment]
I think the documentation site is using es5-shim . Did you include that in your we application? Maybe the old IOS lacks in some of the ES5 api changes?

**Comment by jamesbrauman** [comment]
Hi,

I don't think that this is a problem with the Chartist library (though I can't get access to developer tools on IOS so I can't be sure). I think perhaps that because we're using ES6 in combination with `browserify` in this project it could be related to that, as some type of javascript error causes javascript to be halted on page load.

Would appreciate if anyone could their website where the charts are not working with IOS 5.1 and post any errors that are happening in the console. @Robzelf could you try this?

I'm closing this issue as it doesn't appear to be a problem with the fantastic Chartist library.
