### ISSUE TITLE
Update not working - Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by sebastiangrebe** [chartist-js/chartist#447]
I have got the following problems. I am using Meteor together with chartist. I execute a function when new data arrives and then the chart should update. I see that the data is correct because I log it before updating the chart but everytime I try to update it it gives me the error: 

``` javascript
TypeError: Cannot read property 'map' of undefined
    at Object.c.getDataArray (chartist.min.js:7)
    at e.d [as createChart] (chartist.min.js:7)
    at e.d [as update] (chartist.min.js:7)
    at logs.js?a5258c734e6b8e9ecbb232995675e21572fc62e8:46
    at Tracker.Computation._compute (tracker.js:294)
    at Tracker.Computation._recompute (tracker.js:313)
    at Object.Tracker._runFlush (tracker.js:452)
    at onGlobalMessage (setimmediate.js:102)
```

I init the chart with the `data: newdata` and I also update the chart with newdata and both data are correct but only the init is working not updating it. I also tried to instead of updating the chart to create a new chart with a second init and that worked correctly with the new data so it should not be an problem of the data.
I can also use the update function using `update()` but not `update(newdata)`. I also tried to give all three paramets like `update(newdata, {}, false)` but that did not work too.

**Comment by gionkunz** [comment]
Most probably the data you're using to update the chart is not how Chartist expects it. Can you please post a snippet of the data you're using?

**Comment by sebastiangrebe** [comment]
This was my idea too but would the init process then fail too? Because I tried init instead of update and that worked.
Here the data for the first init:
![1](https://cloud.githubusercontent.com/assets/923505/9814776/fb418d2e-5890-11e5-95f0-ab337be439ae.png)
Here the data for the update or the second init(init works, update not):
![2](https://cloud.githubusercontent.com/assets/923505/9814784/0aec44c6-5891-11e5-90e2-f41fa34405e0.png)

The data is always an array of arrays which hold the data as just ints

**Comment by gionkunz** [comment]
There must be something wrong with the data. Check this example which updates the data every second: http://jsbin.com/zaxope/edit?html,js,console,output

Can you use the unminified version of chartist and turn on breakpoints on exceptions in your developer tools? Then inspect the data. If you can't find an issue please run `JSON.stringify(data)` inside the update method so we can see the exact data.

Cheers

**Comment by sebastiangrebe** [comment]
Thanks it helped me much your example. I do not know what the exact problem was but I did it like in the example and used .series and .labels. I did not know that I need to specifiy series and labels I just gave the data array which I gave to the init (which of course used series: data) and have done `update(data)` and not `update({labels:labels, series:data});`
My data was 
`[{"name":"Test","data":[0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},{"name":"Test 2","data":[0,0,0,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},{"name":"Test 3","data":[0,0,0,0,6,0,0,0,0,5,26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}]`
It works no perfectly by giving the object like `update({labels:labels, series:data});`
