### ISSUE TITLE
Make chartPadding work inside the axisX & axisY objects, not only globally

### ISSUE THREAD

**Issue by dreamyguy** [chartist-js/chartist#450]
I've tried the following since the labels to the left of my chart are overflowing the SVG area.

```
axisX: {
    showLabel: true,
    showGrid: true,
    chartPadding: 20
}
```

...but didn't get the padding I expected. It's just a feature request... :stuck_out_tongue: 

Cheers for this great framework!
Wallace

**Comment by dreamyguy** [comment]
As a side-note, what I'd really like is to define padding independently, so these global values would be more convenient:

```
{
    chartPadding: 20, // for global padding
    chartPadding: '20px 15px 10px 5px',
    chartPaddingTop: 20,
    chartPaddingRight: 15,
    chartPaddingBottom: 10,
    chartPaddingLeft: 5
}
```

It would be more CSS-ish...

**Comment by gionkunz** [comment]
Hi Wallace

You are lucky and this is already supported  :-) Check http://gionkunz.github.io/chartist-js/api-documentation.html#chartistline-declaration-defaultoptions

``` javascript
  // Padding of the chart drawing area to the container element and labels as a number or padding object {top: 5, right: 5, bottom: 5, left: 5}
  chartPadding: {
    top: 15,
    right: 15,
    bottom: 5,
    left: 10
  }
```

**Comment by dreamyguy** [comment]
Cheers for this Gion, liking it more and more! :sparkles:
