### ISSUE TITLE
Reduce grid lines & label frecuency in Axis X

### ISSUE THREAD

**Issue by mroldan** [chartist-js/chartist#453]
Hi!

Let's say I want to plot a graphic like this:

var data = {
        labels: [1,2,3,....,50],  //50 values
        series: [2,3,6,7,...21] //also 50 values  
        };

new Chartist.Line('.ct-chart', data);       

I want to plot all the values in the graphic due to accuracy reasons, but I'd like to reduce the frequency of the grid lines in X axis, displaying labels i.e. on each 10th of them (so, the labels in X axis would be just 10, 20, 30,40 and 50).

Is there any way to accomplish that? I've tried to use "Chartist.FixedScaleAxis" property but I guess is not useful in this case.

Thank you in advance.

**Comment by gionkunz** [comment]
You can use the `labelInterpolationFnc` to return a falsey value on certain labels. For those there will be no label but also no grid line drawn. Check this example: http://gionkunz.github.io/chartist-js/examples.html#bi-polar-bar-interpolated

Cheers
Gion

**Comment by lambdalisue** [comment]
I faced same problem and your suggestion saved me thanks :-)
In case someone want to try.

``` javascript
    new Chartist.Line('#chart', {
        labels: X,
        series: [
//          X.map(function(x){ return s.betainc(1, 3, x); }),
//          X.map(function(x){ return s.betarinc(1, 3, x); }),
//          X.map(function(x){ return s.F.pdf(x, 5, 2); }),
//          X.map(function(x){ return s.F.cdf(x, 5, 2); }),
//          X.map(function(x){ return s.T.pdf(x, 5); }),
            X.map(function(x){ return s.T.pdf(x, 5); }),
        ]
    }, {
        height: '400px',
        axisX: {
            labelInterpolationFnc: function(value, index) {
                return Math.round(value) == value ? value : null;
            }
        }
    });
```

![](https://i.gyazo.com/354405496be808d5d2d1afd6989b013b.png)

**Comment by gionkunz** [comment]
Please re-open if you're still facing issues.
