### ISSUE TITLE
X-Axis Plot Line

### ISSUE THREAD

**Issue by khanhhaduc** [chartist-js/chartist#454]
Hi there, 

First of all, Thanks for the awesome library. I've been loving and implemented it into most of my projects :+1: :+1: :+1: 
I want to know is there anyway I can add a vertical plotline on the X-axis?
I'm building a timeline line chart and I really want to add a dotted line on today's timestamp on the x-axis.... Couldn't find it anywhere. If it's not supported yet, is there any alternative to get it done? Ta

**Comment by gionkunz** [comment]
Hi there! Thanks for the kind words :-)

Here's a simple example on how to write a plugin for this: http://jsbin.com/mayopi/edit?js,output

Hope this helps!

Cheers
Gion

**Comment by khanhhaduc** [comment]
Awesome! Works like a charm. Thanks a lot! :+1:
