### ISSUE TITLE
Mixed values on Y-Axis

### ISSUE THREAD

**Issue by ChrisCooney** [chartist-js/chartist#457]
I have implemented a chart with numerical values on the Y Axis:

![image](https://cloud.githubusercontent.com/assets/2631498/9975949/2766b040-5ec8-11e5-9bfc-705f1ccb1bb7.png)

The areas where the line appears to go below the X Axis is because I have added another value "5+" in there. This is because we don't capture the information if it is out of a certain range. The issue is that I need it to be above the 4, not pulling the line below the graph.

This seems to highlight a need for potentially mixed values in a single axis and a way of specifying their order.

**Comment by gionkunz** [comment]
Hi there. Can you tell more about the use-case? What do you mean with added another value 5+ ? Did you tried to use "holes in data" as shown on the examples, the `low` and `high` configuration and other things? This chart looks a bit broken to me.

**Comment by ChrisCooney** [comment]
Hi there, could probably do with explaining myself a little better!

If you imagine, for my labels I have a bunch of dates, as can be seen. Then in my dataset, I have a set of values for each date. Those values can be 1,2,3,4 or '?'. If I attempt to add '?' as a value, the behaviour above happens. So I tried replacing '?' with '5+' thinking that the number at the start would help the API order this naturally. Alas, that did not work either. 

If you create a graph with these labels:  labels: ['Mon', 'Tues', 'Weds', 'Thurs', 'Fri', 'Sat', 'Sun']

And this series:
            series: [
                [1,2,3,4,'?',3,2]
            ]

You'll be able to replicate. I tried it on JSFiddle but you guys don't host your library on a CDN and Github doesn't allow JS fiddle to treat the file like an external resource. But I expected the '?' to be included in the Y-Axis. Instead, it seems to not be included and where the value is a '?', it does the above mentioned behaviour. Has that made things any clearer?

**Comment by gionkunz** [comment]
Chartist is hosted on most major CDN's. We propose the super awesome jsDeliver CDN http://gionkunz.github.io/chartist-js/getting-started.html#use-a-cdn-alternatively

I know this is not entiertly clear when looking at the documentation in the current state, but the series arrays need to consist of numbers or of values that can be converted to a number. `'?` will be coerced to `NaN` and you should actually even see errors on your console as Chartist doesn't like `NaN` :smile: 

Isn't the holes in data feature exactly what you're looking for? Just use `undefined` for those values you're missing. The chart will break into segments like in this example: http://gionkunz.github.io/chartist-js/examples.html#example-line-data-holes

**Comment by ChrisCooney** [comment]
Perfect! Thanks I've got a JSFiddle for you: http://jsfiddle.net/vs8g0odo/

The reason I don't want to just ignore the '?' values is because they actually mean the number is not 1,2,3 or 4. Hence the '5+' instead. They're relevant because the numbers represent the finishing position in a race. Just because we didn't record their finishing position, doesn't mean they didn't run in the race, hence the need to include the data.

**Comment by gionkunz** [comment]
Then what about making them 5 and limit the range to max 5 by using the option `high: 5` ?

**Comment by gionkunz** [comment]
Sorry `high: 4`

**Comment by ChrisCooney** [comment]
Well then the implication would be that they finished in 5th, which isn't true. They finished in _at least_ 5th. Hence the "5+". I'm aware this is a very specific use case and part of me is thinking about forking the repo and just doing it myself, but I just wanted to see if you guys could offer any insight.

**Comment by gionkunz** [comment]
Actually if you cut off the chart at 4 with the `high: 4` option, the user will not know if its 5, 6, 20 or 100. 

The things I really don't get yet is how would you solve this with pen and paper? :-) Can you tell me how you'd like to present this?

**Comment by gionkunz** [comment]
That's how I'd solve it from all what I know from your usecase: http://jsbin.com/votipo/edit?html,js,output

**Comment by ChrisCooney** [comment]
Dude that's exactly, precisely what I had in mind. Cheers!
