### ISSUE TITLE
chartist in node

### ISSUE THREAD

**Issue by doubletaketech** [chartist-js/chartist#459]
How do you use chartist in node? I don't see an example on the npm site?

Looks like you require it on the server, but what code runs on the server and what runs on the client? If it depends on the DOM, then I'm not understanding why there is an npm package?

Donnie

**Comment by rdpascua** [comment]
Browserify dependencies.

**Comment by gionkunz** [comment]
NPM is only a package format and repository where Chartist is using it for publishing and users can install the dependency within their project using NPM. Chartist is not meant to be used within environments without DOM API. You can use jspm, browserify, webpack or any other framework that allows you to bundle NPM packages into the browser.
