### ISSUE TITLE
How to set min/max value of X in a AutoScaleAxis?

### ISSUE THREAD

**Issue by robachmann** [chartist-js/chartist#460]
I plot two JSONs with unix-timestamps as x-values and values from 0 to 300 as y-values. Unfortunately, I can't use the default step-axis, as there are missing values from time to time.

Both JSON files contain x-values of a single day from midnight to midnight. With Chartist set to AutoScaleAxis, x-min and x-max seem to get calculated based on a formula (?). It would be very nice, if the x-min and x-max values were taken from the series' first/last elements because currently, I see an offset of 10min at start and 50min at the end of the chart, as displayed in the screenshot:
![chartist](https://cloud.githubusercontent.com/assets/8127370/10078465/19ecd3d8-62e5-11e5-8606-b0082a132eb7.png)

Is there any way, I can tell chartist which value should be its first and last value for the x-axis? I found a commit (https://github.com/gionkunz/chartist-js/pull/435/files#diff-08851185f1de689719bcfd9c1353112b) possibly adressing this question ( min: this.bounds.min, ...) but I'm not sure how to configure it in the options. 

Thank you very much in advance and keep your awesome work up!

**Comment by gionkunz** [comment]
Hi there. You're right about the behaviour of the AutoScaleAxis. Part of it's behaviour is to use the order of magnitude to add some padding up to the next higher value or lower value that fits the steps. 

You could use a fixed step axis as this will narrow to the exact min / max of the axis. However, you'd then need to implement some logic that divides your axis into fixed points.

There's an open task to implement a time axis type that will be optimized to handle timestamp based data. This work is tracked under #116 and I'm looking for volunteers to implement this :-)

Cheers
Gion

**Comment by robachmann** [comment]
Hi Gion, I wasn't aware of the fact, that I can mix `{x: 1, y: 1}` objects with `FixedScaleAxis`. The only thing I had to adjust was the `divisor` setting for each `responsiveOptions`. Now it works like a charm! 

![parking](https://cloud.githubusercontent.com/assets/8127370/10133762/585d3d62-65e0-11e5-9ed8-8ddade54e814.png)

Thanks again for this awesome project and see you. 
Roman

**Comment by gionkunz** [comment]
Hi @240ch glad to see it worked out like that :-) Still we will work on a time axis that will help in implementing this kind of time based charts and maybe, if you find some difficulties working with time in `FixedScaleAxis` please post your feedback here on in #116 

Cheers
Gion
