### ISSUE TITLE
Got Cannot read property 'querySelectorAll' of null

### ISSUE THREAD

**Issue by ruwhan** [chartist-js/chartist#462]
Hi,

You have a cool lightweight charting library, but I got: `Uncaught TypeError: Cannot read property 'querySelectorAll' of null` error when trying your getting started example: 

The example code of Chartist [getting started](https://gionkunz.github.io/chartist-js/getting-started.html) guide: 

``` html
<div class="ct-chart ct-perfect-fourth"></div>
```

``` javacsript
var data = {

  labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],

  series: [
    [5, 2, 4, 2, 0]
  ]
};

new Chartist.Line('.ct-chart', data);
```

![screen shot 2015-09-25 at 11 08 13 am](https://cloud.githubusercontent.com/assets/533088/10092900/d090070a-6375-11e5-9708-4602277fbce8.png)

**Comment by gionkunz** [comment]
Hi. This error is thrown when cjartist cant find the element with the selector youve passed. Probably at the point where you execute the script your dom is not loaded? Make sure you execute all your javascript at the bottom in your body element or use the DOM content loaded event.

**Comment by ruwhan** [comment]
hanks for reply @gionkunz . I'm using Chartist with Backbone.js & Require.js. Any guide how to use Chartist with them? I've googled about it and found nothing.

**Comment by ruwhan** [comment]
**Resolved!**

Btw, I'm using Marionette.js (a Backbone.js extensions), and the chartists related code should be done in `onShow()` view event, previously, I was putted it in onRender instead.

**Comment by gionkunz** [comment]
Hey there! Glad you've resolved it and thanks for posting the resolution. This will help others for sure.

Cheers
Gion
