### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by jdvs1** [chartist-js/chartist#463]
Are there plans on introducing documentation on:
- how to label the Y axis
- adjusting the stroke width for a line chart

I could use these right about now :smile:

**Comment by gionkunz** [comment]
Hi there. This chapter should show you how to customize the styles: http://gionkunz.github.io/chartist-js/getting-started.html#customizing-the-default-css

On how to label the Y-Axis there are some examples here: http://gionkunz.github.io/chartist-js/examples.html#example-multiline-bar

More on the axis options you can find in the default configuration on the API page: http://gionkunz.github.io/chartist-js/api-documentation.html#chartistline-declaration-defaultoptions (click the show code button)

Or if you're talking about axis labels you should take a look at this plugin: http://gionkunz.github.io/chartist-js/plugins.html#axis-title-plugin
