### ISSUE TITLE
ct:value Not Set When Value=0

### ISSUE THREAD

**Issue by jordan-wright** [chartist-js/chartist#464]
On a line chart, it appears as though the `ct:value` is not set if the value is 0. Here's an example line where I use object notation for setting the value and meta of the object:

``` javascript
overview_data.series[0].push({meta : i, value: campaign.y})
```

If I run this and `campaign.y` is 0, then it results in the following:

![image](https://cloud.githubusercontent.com/assets/1317288/10119117/8798a9fc-6452-11e5-98ce-60c93a443b51.png)

This works just fine when `value` != 0. This typically wouldn't be an issue, but tooltips tend to try and grab the value to display and, if it's 0, it returns undefined. 

Not sure if you'd consider this a bug or not, just wanted to bring it to your attention.

Keep up the great work!

**Comment by gionkunz** [comment]
Hi there! Thanks for this report, this is a bug for sure :-) Some recent changes how we write values with multi dimensions introduced this bug: https://github.com/gionkunz/chartist-js/blob/develop/src/scripts/charts/line.js#L208-L210

We should fix that and add a test I guess.

Thanks again for the bug report!
