### ISSUE TITLE
Allow donutWidth in percent.

### ISSUE THREAD

**Issue by hansmaad** [chartist-js/chartist#465]
The current implementation allows to set the donut width on pie charts as absolute stroke width. This is not very helpfull, if the actual width of the rendered chart is not known. It would be great to specify the width relative to the outer radius (`donutWidth: '60%'`), to keep the look consistent for each screen and chart sizes.

**Comment by gionkunz** [comment]
Hi @hansmaad . This should be fixed with #330. We should pick of the work of @cdcarson and implement the missing changes.

**Comment by gionkunz** [comment]
Maybe you can pick up there where we left if you have time?

**Comment by gionkunz** [comment]
Closing in favor of #330
