### ISSUE TITLE
Full Width on 2D Line Graph doesn't seem to be working

### ISSUE THREAD

**Issue by samtgarson** [chartist-js/chartist#467]
Firstly, thanks so much for your great work on this.

Secondly; I'm using a 2D line graph with AutoScaleAxis on both axes. The Y axis works perfectly but the X axis seems to stick a bunch of varying space at the beginning and end of the axis, even with the high and low defined as the first and last values in the data.

_(Excuse the seemingly random-looking data, it is actually random data at this point...)_

![image](https://cloud.githubusercontent.com/assets/6242344/10167918/684f4b7e-66c2-11e5-8064-02cd7251c912.png)

I'm using a date/time based axis, so the x values are in UTC ms since Epoch, then I'm formatting them using the interpolation function. Here's a snippet of my options:

``` javascript
fullWidth: true,
axisX: {
  low: Date.parse(json[0].date),
  high: Date.parse(json[json.length - 1].date),
  scaleMinSpace: 40,
  showGrid: false,
  labelInterpolationFnc: function(value) {
    return moment(value).format('M/YY');
  },
  type: Chartist.AutoScaleAxis
},
```

I'm using the latest `master` branch (0.9.4).

Note: If I alter the low/high values to be further inward than the first/last values, the chart does stretch but as the amount of space either side seems to vary, this leads to the graph sometimes overlapping the Y axis.

**Comment by gionkunz** [comment]
Hi there, very similar to https://github.com/gionkunz/chartist-js/issues/460

**Comment by gionkunz** [comment]
Until we have time axes I'd recommend using the FixedScaleAxis with a meaninfull divisor and responsive setting overrides to change the divisors.

**Comment by samtgarson** [comment]
@gionkunz OK thanks for the quick reply. Is there somewhere I can see your progress on time axes?

**Comment by samtgarson** [comment]
@gionkunz found #116, will work on fixed scale for now and see if I can contribute to the time axes. Cheers

**Comment by gionkunz** [comment]
cool, yeah, it's a most wanted feature, so if no contributor is found, I will probably take this one up in my next Chartist hack weekend in October.

**Comment by gionkunz** [comment]
I hope, you're find when we close this issue for now. If you need more input on the `FixedScaleAxis` feel free to discuss here. Cheers

**Comment by gionkunz** [comment]
Unfortunately I didn't had time to pick this up so far. I'll look into this ASAP.
