### ISSUE TITLE
Change which area series appear on top of all series?

### ISSUE THREAD

**Issue by khanhhaduc** [chartist-js/chartist#470]
Hi again :)

![capture](https://cloud.githubusercontent.com/assets/6720949/10181203/acf74010-6771-11e5-94b2-cf7aece08fb5.JPG)

Is it possible to rearrange a serie to appear before all other series dynamically? or should I redraw the chart again?

Thanks a lot,
Ken.

**Comment by gionkunz** [comment]
Hey :) Just change the order of the series in the data array and call chart.update(reorderedData)`

**Comment by khanhhaduc** [comment]
:+1:  Thanks a lot :dancers:
