### ISSUE TITLE
Gauge min and max label positions

### ISSUE THREAD

**Issue by ghost** [chartist-js/chartist#475]
Hi @gionkunz and community,

I am struggling with positioning mix and max labels with gauge and don't really know where to start.

I need them to be positioned at the bottom of the mix and max sections, for example:

![screen shot 2015-10-05 at 14 36 24](https://cloud.githubusercontent.com/assets/803990/10281788/ddba7e96-6b6e-11e5-9efb-2b6d7ef98d3c.png)

Any ideas, advice or working code (if someone did that before).

Thank you.

**Comment by gionkunz** [comment]
Maybe this "plugin" will help you? Sorry for the late reply, this issue slipped through my attention. http://jsbin.com/boqonawufi/2/edit?js,output

I hope this will help anyone else who faces the same issue.

Once we've documented events better #90 , this should help a lot.
