### ISSUE TITLE
Force decimal places on y-axis

### ISSUE THREAD

**Issue by ErikVeland** [chartist-js/chartist#477]
Apologies if this is covered, but I've combed the documentation and come up empty. If I want to force two decimal places on the y-axis, how do I do that?

I.e I want it to display 1.60, 1.65, 1.70, 1.75 instead of 1.6, 1.65, 1.7, 1.75.

**Comment by gionkunz** [comment]
Hey there. Use label interpolation:

``` javascript
axisY: {
  labelInterpolationFnc: function(value) {
    return value.toFixed(2);
  }
}
```
