### ISSUE TITLE
Donut chart does not support labelPosition == 'center'

### ISSUE THREAD

**Issue by colegleason** [chartist-js/chartist#478]
I'm trying to build a donut chart like this:
<img width="70" alt="screen shot 2015-10-07 at 8 39 19 pm" src="https://cloud.githubusercontent.com/assets/232327/10354922/8aecf038-6d33-11e5-8289-dfcdcb05790b.png">

Unfortunately, the easy solution of setting `labelPosition` to `center` did not work as it seems to ignore this option with donut charts.

**Comment by gionkunz** [comment]
I'd use the `created` event for this and use `Chartist.Svg` to draw the percentage in the middle of the chart.  Check out this example: http://jsbin.com/buhoza/edit?js,output
