### ISSUE TITLE
Having same values for both X and Y axis

### ISSUE THREAD

**Issue by dheerajc** [chartist-js/chartist#479]
Hi All,

Please look at this snapshot:
![limiter](https://cloud.githubusercontent.com/assets/292018/10364465/31bc567e-6dd9-11e5-9975-90913162255e.png)

I have this requirement where there are different regions and many points on X-axis but I have only 3 points to show in the graph. Both X and Y values will be same at any given time. In the snapshot attached both X and Y values = -25

Is this possible using line graph in Chartist.js?

Thanks,
Dheeraj

**Comment by gionkunz** [comment]
This kind of charts are certainly possible using the `FixedScaleAxis`. Check this article: http://gionkunz.github.io/chartist-js/getting-started.html#switching-axis-type
