### ISSUE TITLE
[Chartist v0.9.4] Deprecation Warning in Chrome 43

### ISSUE THREAD

**Issue by haroldcampbell** [chartist-js/chartist#483]
Hi, 

I'm running Chartist.js v0.9.4 on Chrome Version 43.0.2357.132 (64-bit), and I'm seeing the deprecation warning (shown below). 

'DOMImplementation.hasFeature()' returning false is deprecated. Please do not use it, as per DOM it should always return true (https://dom.spec.whatwg.org/#dom-domimplementation-hasfeature).

Is anyone else seeing this error?

Cheers,

h

**Comment by gionkunz** [comment]
hey there. Thanks for the report. It looks like there's also a slight mismatch between the WHATWG DOM spec and the SVG 1.1 spec http://www.w3.org/TR/SVG/svgdom.html#FeatureStrings as there it seems to be a valid thing. As the method will still exist in the future and always return true I don't see an immediate action required. We should look at other ways to check for SMIL and foreignObject support though in the future.

**Comment by haroldcampbell** [comment]
Ok. I'll mark it as closed later.

Thanks.

On Monday, 12 October 2015, Gion Kunz notifications@github.com wrote:

> hey there. Thanks for the report. It looks like there's also a slight
> mismatch between the WHATWG DOM spec and the SVG 1.1 spec
> http://www.w3.org/TR/SVG/svgdom.html#FeatureStrings as there it seems to
> be a valid thing. As the method will still exist in the future and always
> return true I don't see an immediate action required. We should look at
> other ways to check for SMIL and foreignObject support though in the
> future.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gionkunz/chartist-js/issues/483#issuecomment-147527373
> .

## 

---

Harold Campbell
Cell: +27-76-825-2315 (c)
