### ISSUE TITLE
Setting a minimum height for bar charts

### ISSUE THREAD

**Issue by darren-edm** [chartist-js/chartist#484]
Hi,

I've added click events to my bar charts as I am using them as histograms for a search application. If the scale of the chart is massively varied then the smaller bars are almost impossible to click. Is it possible to set a minimum height on bars that contain a small value (but greater than 0)?

Regards,
Darren

**Comment by gionkunz** [comment]
You can use the `data` event.

``` javascript
chart.on('data', function(context) {
  // Manipulate the data in context to set a minimum value
});
```
