### ISSUE TITLE
Non-numeric axis labels

### ISSUE THREAD

**Issue by bozor** [chartist-js/chartist#487]
Hey,

I was wondering if it is possible to somehow add non-numeric label to either/both of the axis. I am trying to build a weight graph and would like to show a label on the y-axis as `10st 7lb` rather than `10.5`. Screenshot below:

![screenshot](http://i.imgur.com/1BSk4GV.jpg)

I have not been able to find anything that would allow me to do this so far - could you please point me in the right direction?

**Comment by woble** [comment]
You can format the labels fairly easy using labelInterpolationFnc in axisY option as follows:

``` js
axisY: {
    labelInterpolationFnc: function(value){
        // Insert value (10.5) to pretty value (10st 7lb) conversion here
        return yourNewValueAsString;
    }
}
```

If you are still stuck, have a look at the API page and search for labelInterpolationFnc to see how it is applied. Hope that helps.

**Comment by gionkunz** [comment]
@woble is right, that's the proposed way to format or string interpolate labels. If you need more help please re-open the issue.

**Comment by RavinderRikhi** [comment]
label interpolation method not working correctly when number of values are more than 10 .. It is showing the labels for the values in multiples of 5
