### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by VishwaKumar** [chartist-js/chartist#488]
I am working on a line chart and we have daily data to show. Is there any way i could paginate data points for 7 days at a time? Right now the data looks cluttered as in the attached image as we have the fixed width and we don't want to increase the width.

![capture](https://cloud.githubusercontent.com/assets/1298628/10634526/08edcaf2-7810-11e5-9875-3b7cce1235d8.PNG)

**Comment by woble** [comment]
Why not write your own custom pagination object that rebuilds the graph based on data from 7 days when you change weeks?

**Comment by SarasArya** [comment]
@woble  how would you suggest we go about that??

**Comment by gionkunz** [comment]
This would make a nice plugin. Let's keep a reference to #290
