### ISSUE TITLE
Using events to replace graphics example

### ISSUE THREAD

**Issue by atherdon** [chartist-js/chartist#489]
Hi @gionkunz, hope you well!
Can you tell me - is this possible to replace points by different images?
Can you share an example?

Thank you!

**Comment by woble** [comment]
Yes.

``` js
var chart = new Chartist.Line('#chart', {
    labels: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],
    series: [
        [12, 9, 7, 8, 5, 10, 12, 8, 5, 10, 12, 60]
    ]
});

var imgHeight = 20;
var imgWidth = 20;
chart.on('draw', function(data){
    if(data.type === 'point'){
        var foreignObject = new Chartist.Svg('foreignObject', {
            height: imgHeight,
            width: imgWidth,
            x: data.x - (imgWidth / 2),
            y: data.y - (imgHeight / 2)
        });

        var img = document.createElement('img');
        img.setAttribute('src', 'http://i.imgur.com/WTZShip.png');
        img.setAttribute('width', imgWidth);
        img.setAttribute('height', imgHeight);

        foreignObject._node.appendChild(img);

        data.element.replace(foreignObject);
    }
});
```

**Comment by gionkunz** [comment]
@woble 's example is correct. You could also use SVG image elements instead of foreignObject but both approaches are fine.

**Comment by hilary-L** [comment]
@gionkunz how would you go about doing this with the SVG image element?

**Comment by gionkunz** [comment]
Something like this, didn't tested it though.

``` javascript
var chart = new Chartist.Line('#chart', {
    labels: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],
    series: [
        [12, 9, 7, 8, 5, 10, 12, 8, 5, 10, 12, 60]
    ]
});

var imgHeight = 20;
var imgWidth = 20;
chart.on('draw', function(data){
    if(data.type === 'point'){
        data.element.replace(new Chartist.Svg('image', {
            'xlink:href': '/url/to/image.jpg',
            height: imgHeight,
            width: imgWidth,
            x: data.x - (imgWidth / 2),
            y: data.y - (imgHeight / 2)
        }));
    }
});
```

**Comment by hilary-L** [comment]
@gionkunz Thanks for the example. Something is off, though. When using this the svg image element is in my markup, and it's the correct size, but the image itself does not display. I've checked to make sure the path to my images is correct and they are. The line in my line chart displays fine, but the images won't display on top where the points should be.

Any thoughts?

I'd just go back to using the foreignObject method, but that's not supported in IE is it?

**Comment by gionkunz** [comment]
Hi there. The problem is that currently the SVG library is not respecting custom attribute namespaces. I've opened a issue for tracking this #584

In the meanwhile you can work around this by manually setting the attribute on the DOM element like this: http://jsbin.com/wihexo/edit?js,output

Cheers
Gion

**Comment by hilary-L** [comment]
Thanks @gionkunz! That did fix it.
