### ISSUE TITLE
Missing Sass Import

### ISSUE THREAD

**Issue by reergymerej** [chartist-js/chartist#49]
`grunt serve` aborts due to a missing Sass import.

```
Running "concurrent:test" (concurrent) task
    Warning: Running "sass:dist" (sass) task
    Warning: /home/grizzle/code/chartist-js/source/styles/site/main.scss:10: error: file to import not found or unreadable: "compass-mixins/lib/compass/css3"
     Use --force to continue.

    Aborted due to warnings.
```

**Comment by reergymerej** [comment]
I can't find this file, any recent commits in this area, or comments about this problem.  Maybe I'm the only one.

If that's the case, maybe there's something missing from https://github.com/gionkunz/chartist-js/blob/develop/CONTRIBUTING.md.

**Comment by gionkunz** [comment]
Did you do a bower install?

Can you check if you have the file compass-mixins/lib/compass/css3 in your bower_components folder?

**Comment by reergymerej** [comment]
That was it.  _facepalm_  `bower update` [didn't actually install anything](https://github.com/bower/bower/issues/640).  Should this be added to the **How to Run a Local Distribution** steps?

Thanks for the response.

**Comment by gionkunz** [comment]
Actually I always do bower install and not update. Not sure why someone would do an update initially. I've changed the documentation c31f4f971a83bb3aa703076f91ddb5568f28bc88

Thanks for reporting this issue.

Cheers
Gion

**Comment by reergymerej** [comment]
Thanks, Gion.

**Comment by yairEO** [comment]
There is a `scss` file but absolutely no instructions on how to use it!
I don't want to use bower or NPM or anything. The SCSS file is just a bunch of mixins.
