### ISSUE TITLE
Can't toggle 'showArea' option

### ISSUE THREAD

**Issue by glennfu** [chartist-js/chartist#490]
I have a chart with `showArea == true` and things look good. I want to be able to turn it off when I change settings. I've tried doing `chart.options.showArea = false; chart.update()'` but to no effect. I can do `chart.data = newData; chart.update()` and this works perfectly. Why can't I update options?

**Comment by gionkunz** [comment]
You can. Pass the new options as second argument to the update function. Cheers

**Comment by glennfu** [comment]
Ahh I should have found that! It's explained here: http://gionkunz.github.io/chartist-js/api-documentation.html#chartistbase-function-update

Thank you very much!
