### ISSUE TITLE
force plugins to rerender

### ISSUE THREAD

**Issue by perber** [chartist-js/chartist#494]
Hello,
Is it possible to redraw plugins? 
I'm using the legend plugin and i call update on chartist.js, but chartist shows
the old legends with the new data.

best regards 
Patrick

**Comment by logitimate** [comment]
Yea this would be very helpful. We are using an average line plugin and getting similar results.

**Comment by perber** [comment]
I've modified the plugin code. I listen now for a 'data' event and if the data changes I'll update the plugin. Maybe this helps you, too.

```
        return (chart) => {
            chart.on("data", function() {
                $('ul.ct-legend', $(chart.container)).remove();
                legend(chart);
            }.bind(this));
            return legend(chart);
        };
```

**Comment by logitimate** [comment]
Unfortunately, the plugin I'm using needs the data that comes back from the create event but I need access to it in the data event to make it work.

**Comment by gionkunz** [comment]
According to https://github.com/moxx/chartist-plugin-fill-donut/issues/1 this is no longer an issue

**Comment by adriennn** [comment]
@gionkunz the filldonut plugin uses a custom mechanisms to update the chart with new plugin data, the reference to new options is hardcoded (fillDonutOptions if you look at the source).

Is there a generic way to update  plugins options with the .update() function? I see you have referenced the above case in many other issues related to updating plugin options, but there doesn't seem to be a core meachnism yet, or am I missing something?
