### ISSUE TITLE
[Question] Scales

### ISSUE THREAD

**Issue by woble** [chartist-js/chartist#499]
What are `$ct-scales-names` exactly for? I've look in the documentation, examples and source but I can't seem to produce anything that warrants use of those class names. Are they placeholders for something in the future?

I'm rewriting SCSS to LESS for our own usage and those scales take almost half of the CSS for no reason whatsoever so I am trying to figure out whether they are needed or not.

Care to elaborate?

**Comment by bartveneman** [comment]
By the looks of https://github.com/gionkunz/chartist-js/blob/develop/src/styles/chartist.scss#L226 they are used to generate different aspect ratios for the charts. The docs page http://gionkunz.github.io/chartist-js/getting-started.html#as-simple-as-it-can-get shows a yellow button 'show available aspect ratios' to use in your HTML to have the right aspect ratio for your chart. These classnames reflect the ones in `$ct-scales-names`

**Comment by woble** [comment]
Ah, I see. You have to set those classes yourself depending on how you want to have the chart be scaled. They are not mandatory classes then.
