### ISSUE TITLE
Animated time serie

### ISSUE THREAD

**Issue by aseck** [chartist-js/chartist#502]
I have a time serie. Lets say a GDP serie from 1980 to 2014.
Is it possible to draw a point char for 1980 and animate 1980 serie to 1981 serie and so on ?

**Comment by gioppoluca** [comment]
+1, it could be interesting to have points on a map to evolve in time

**Comment by gionkunz** [comment]
Not very easy as of yet, but we should try to cover such usecases when working on #468
