### ISSUE TITLE
Getting instance of chartist.

### ISSUE THREAD

**Issue by logitimate** [chartist-js/chartist#503]
Is there a way to get an instance of chartist based off a selector? I'm trying to force a chart update based off a selector and it can't get the instance of chart.

**Comment by gionkunz** [comment]
I there, yes, you can use `element.__chartist__`. Cheers

**Comment by gionkunz** [comment]
Or to answer your question correctly: 

``` javascript
document.querySelector('#my-chart').__chartist__
```

:-)
