### ISSUE TITLE
Remove Reliance Upon Sass

### ISSUE THREAD

**Issue by jherdman** [chartist-js/chartist#504]
It'd be nice to not have to use Sass with Chartist. A project I'm using is migrating to PostCSS and the inclusion of Sass has forced us to compile Chartist's Sass down to CSS and vendor it. An ideal world would be to allow the Chartist developers to use Sass, and then the distributed copy to provide compiled CSS assets.

**Comment by archinal** [comment]
While I see your point, the counter-argument can be made that providing CSS assets would encourage pull requests for the CSS directly, not the Sass, which would be inconvenient.

**Comment by jherdman** [comment]
What if CSS was generated when the package was built?

**Comment by gionkunz** [comment]
We can provide a non-minified CSS as requested in #506 within the dist folder. I'm closing this issue in favor of #506 . Cheers
