### ISSUE TITLE
How to horizontal align to center - svg chart draws from left origin

### ISSUE THREAD

**Issue by D1no** [chartist-js/chartist#505]
Hi, I have trouble to center a simple area chart horizontally.

Straight from the example I have a `ct-chart` div with 100% width and an area chart with `fullWidth: true`. Still, the SVG chart stays misaligned from the center because - as it seems - the SVG does not stretch from the center, it is fixed on its left edge (origin).

Is that a bug or how is it done?

See
![chartist positioning](https://cloud.githubusercontent.com/assets/2397125/10925202/6724d2b0-828c-11e5-9654-52397e7c3809.gif)

``` JavaScript
new Chartist.Line('.ct-chart', {
            labels: ["", 1.0,   1.3,    1.7,    2.0,    2.3,    2.7,    3.0,    3.3,    3.7,    4.0, ""],
            series: [
                [0, 9.0,    8.5,    12.2,   11.1,   12.7,   14.8,   9.0,    9.0,    7.4,    6.3, 0],
                [0, 14.3,   3.6,    10.7,   21.4,   7.1,    7.1,    10.7,   14.3,   10.7,   0.0, 0],
                [0, 4.8,    11.9,   13.8,   17.0,   10.0,   13.5,   8.7,    9.3,    5.1,    5.8, 0]
            ]
        }, {
            low: 0,
            showArea: true,
            showLine: false,
            showPoint: false,
            height: '200px',
            fullWidth: true,
            axisX: {
                showLabel: true,
                showGrid: false
            },
            axisY: {
                showLabel: false,
                showGrid: false
            },
            lineSmooth: Chartist.Interpolation.cardinal({
                tension: 0.6
            })
        });
```

``` HTML
<div class="ct-chart ct-horizontal"></div>
```

thx

**Comment by gionkunz** [comment]
Hi there. Even if you specify showLabel: false on the Y axis, you still need to reset the preconfigured offset on the axis. The following example gets rid of any spacing:

``` javascript
new Chartist.Line('.ct-chart', {
  labels: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
  series: [
    [12, 9, 7, 8, 5],
    [2, 1, 3.5, 7, 3],
    [1, 3, 4, 5, 6]
  ]
}, {
  fullWidth: true,
  chartPadding: 0,
  axisX: {
    showLabel: false,
    offset: 0
  },
  axisY: {
    showLabel: false,
    offset: 0
  }
});
```

We've discussed to set `offset` a `0` default once the `showLabel` option is set to true, but I don't find the issue right away.

**Comment by mattiLeBlanc** [comment]
This offset command was what I was looking for. Is this documented? If not, might be nice to add it in somewhere. I do see the word offset set in one of the examples but you to run into it by accident.
I especially loved it when viewing on mobile because I need all the space I can get.
Great library, again!

**Comment by gionkunz** [comment]
All default options are documented in the API documentation, however we need to improve the presentation of the documentation #761
