### ISSUE TITLE
Provide non-minimized dist CSS file

### ISSUE THREAD

**Issue by mitar** [chartist-js/chartist#506]
There is non-minimized js file, but not CSS file. This makes it hard to include it into systems like [Meteor](https://github.com/mfpierre/meteor-chartist-js) which does its own minimization in production, but during development you get nice non-minimized CSS.

**Comment by archinal** [comment]
Hey @mitar , if it's helpful for you, the project does include its un-minified SCSS [here](https://github.com/gionkunz/chartist-js/tree/develop/dist/scss), which is then used to produce the minified CSS.

I would argue that it would be a bit of a mistake to provide the un-minified CSS as it is the _SCSS_ which is developed and maintained, not the CSS (so if you were to do some great work with the styles, it would be way more helpful to submit a pull request for the SCSS than for a new and unmaintained CSS file).

**Comment by mitar** [comment]
Of course, this is why CSS would be in `dist` directory, make it clear it is an output. Pull requests should be still against SCSS, of course. You write that also in the readme or contribution guide. But providing CSS allows one to directly use it in websites, and have debugging to understand where something is happening.

**Comment by gionkunz** [comment]
We can include that within the next build

**Comment by mitar** [comment]
Thanks!
