### ISSUE TITLE
Using reverseData also reverses series

### ISSUE THREAD

**Issue by JosefWN** [chartist-js/chartist#508]
For me, reversing the series (css-classes / styles) is undesirable. All I want is to be able to reverse the order in which the items appear for the bar chart. This is because I have non-reversed pie charts and reversed bar charts that I would like to use together (matching items = matching colors).

Is the current behavior really desirable with reverseData: true? Any advice on how to achieve this?

**Comment by gionkunz** [comment]
Why aren't you using class names for your series?

``` javascript
  series: [{
    className: 'series-1',
    data: [5, 2, -4, 2, 0, -2, 5, -3]
  }, {
    className: 'series-2',
    data: [4, 3, 5, 3, 1, 3, 6, 4]
  }, {
    className: 'series-3',
    data: [2, 4, 3, 1, 4, 5, 3, 2]
  }]
```

And then manually apply styles to those classes? This way the reversing wont have any effect on the automatically created class names.

**Comment by gionkunz** [comment]
Closing becauase of inactivity

**Comment by bugsel** [comment]
https://github.com/gionkunz/chartist-js/issues/851

**Comment by minusf** [comment]
i also find it confusing that `reverseData` reverses the order of the lists in the series as well, not just the elements of the individual lists. made our manually added legends incorrect...
