### ISSUE TITLE
Pie chart bug when large number in series

### ISSUE THREAD

**Issue by andrewspinks** [chartist-js/chartist#509]
When there is a large number in a series of 3, then there is a weird graphical bug.
e.g.
var data = {
  series: [5, 100000, 4]
};

var data = {
  series: [5, 4, 100000]
};

Strangely, this is fine:
var data = {
  series: [100000, 5, 4]
};

![screen shot 2015-11-06 at 11 30 39 am](https://cloud.githubusercontent.com/assets/1097463/10987801/0c51dba4-847a-11e5-80f6-b203a5a80d0c.png)

**Comment by yuanoook** [comment]
I met this problem too, and I just try to preprocess the data by changing it into percent and set min value as 0.001

```
var total = data.reduce(function(a,b){return a+b;});
if(total<=0) return;
data = data.map(function(x,i,a){
    var result = +(x/total).toFixed(2);
    return result || 0.001;
});
```

**Comment by andrewspinks** [comment]
I did something similar as a workaround. Thanks @yuanoook

**Comment by gionkunz** [comment]
This should no longer be an issue in 0.9.8
