### ISSUE TITLE
Move svg related util functions from core to svg

### ISSUE THREAD

**Issue by valotas** [chartist-js/chartist#51]
It looks like the svg has been written after core. Therefore I think that
- [x] `Chartist.getHeight` should be moved to `Charitst.svg.height`
- [x] `Chartist.getWidth` should be moved to `Charitst.svg.width`
- [ ] `Chartist.getAvailableHeight` should be moved to `Charitst.svg.availableHeight`
- [ ] `Chartist.projectLenght` should be moved to `Charitst.svg.projectLength` (maybe inline `getAvailableHeight` there too?)
- [ ] `Chartist.getBounds` should be moved to `Chartist.svg.bounds`
  `

**Comment by gionkunz** [comment]
First two I agree, also you can see a TODO comment for those. The rest I don't agree. getAvialbleHeight depends on chart options like xAxisOffset and chartPadding so it's well placed in the core. projectLength is also projecting a data value into pixel space and depends on options and chart data. Also it does not necessarily has something to do with SVG. getBounds is calculating min, max, low, high, range, step value and the whole chart model and definitely does not belong to the SVG lib.

**Comment by valotas** [comment]
But all of them are working on `Chartist.svg` and for the moment used only there.

**Comment by gionkunz** [comment]
I don't understand. What do you mean with "working on"? Chartist.svg has no dependency on Chartist.core. Chartist.svg is solely a SVG DOM manipulation library for Chartist. All those methods (except getHeight and getWidth where I agree that we move them into Chartist.svg) are depending on a lot of chartist relevant information like the options, padding, labels etc. so they do belong to the core and just delegate SVG related things to Chartist.svg.

**Comment by gionkunz** [comment]
I'm closing this as the refactoring is completed for the first two important points.
