### ISSUE TITLE
Conditional Formatting of a Point with null value

### ISSUE THREAD

**Issue by brianrhea** [chartist-js/chartist#511]
I love the way that Chartist handles gaps in line charts (I love the way Chartist does a lot of things!).

But, what I would like to do is instead of having a gap in the chart, display the point as an average of the value before and the value after it, and indicating the gap in the data visually in some way.

What I've done so far is instead of sending the data point as null, I send it as -1, and then I intercept it within `.on('draw')` like so:

```
if ( data.type === 'point' && data.value.y === -1 ) {
  var triangle = // some code that draws a triangle
  data.element.replace(triangle)
}
```

I would like to be able to write my own plugin to address this use case, but I can't figure out how to access the y values before and after this point, or if intercepting the data during the `draw` event is too late anyway.

Further, is it possible to affect the attributes of the line that connects the missing data point, or is the line only drawn as one element?

**Comment by brianrhea** [comment]
I've got the beginnings of a plugin started here:
https://gist.github.com/brianrhea/9ecde330b6c9fae136ba

It's still a little too specific to my particular application (currently requires Underscore.js and I have some custom CSS sprinkled in), but hopefully could serve as the beginnings of something.

That code will generate the following chart:

<img width="1140" alt="screen shot 2015-11-12 at 10 47 10 am" src="https://cloud.githubusercontent.com/assets/506725/11126140/c5581a82-892a-11e5-9628-b226ca8754cf.png">

from this data:

```
{
  "labels": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
  "series": [
    {
      "name": "Values",
      "data": [9,null,null,7,10,3,null,3,2,1]
    }
  ]
}
```

**Comment by gionkunz** [comment]
Awesome man! Looking forward for the plugin! :-) Tell me when it's ready so I can help you to make the pull request for adding it to the docs site.

**Comment by gionkunz** [comment]
Closing this issue, please submit a PR if you'd like to publish the plugin on the chartist website
