### ISSUE TITLE
How to display all data but only few labels?

### ISSUE THREAD

**Issue by thomaswhite** [chartist-js/chartist#513]
I need to display data for say 90 days as linear graph but display only few labels - the name of the months at every 30th position.  At the moment the the graph look like this:
![image](https://cloud.githubusercontent.com/assets/116980/11123805/bdc9c96c-8959-11e5-93dd-a675d1a00f5c.png)
How can I do this?

**Comment by archinal** [comment]
Hey @thomaswhite - you can achieve this by specifying a new parameter in the `options.axisX` object called `labelInterpolationFnc`. This function takes a `value` and an `index`, where `value` is the value of the graph at position `index`. To achieve what you're asking for above, your options would look like this:

```
var options = {
    axisX: {
                labelInterpolationFnc: function (value, index) {
                    return index % 30 === 0 ? value.getMonth() : null;
                }
            }
}
```

Note that the example above gives you the month as a number, but you get the idea.

There is an example usage of this in the chartist documentation [here](https://gionkunz.github.io/chartist-js/examples.html#line-scatter-random).

**Comment by gionkunz** [comment]
Thanks @archinal for the explanation. I'll close this issue, if you have more questions feel free to re-open or open a new issue.
