### ISSUE TITLE
How to remove the dotted background lines?

### ISSUE THREAD

**Issue by ShlomoRosenheimer** [chartist-js/chartist#517]
Every chart has these dotted grid lines, how to remove them or style them???

**Comment by ShlomoRosenheimer** [comment]
Okay made it using axisX: { showGrid: false }
The documentation is very weak here...

**Comment by JarLowrey** [comment]
`"victory": "^30.4.0"` ---

```js
<VictoryAxis independentAxis style={{ grid: {stroke: "none"} }} />
```

**Comment by ghost** [comment]
I'm using `showGrid:true` and no grid line appear when using `type: Chartist.FixedScaleAxis`.
