### ISSUE TITLE
Scaling fails when all values are null

### ISSUE THREAD

**Issue by ced-b** [chartist-js/chartist#523]
I ran into a use case where some line charts I want to display have all values at `null` in the beginning, and they fill up as time goes by. For nicety sake I would still like to display the empty grid.

However, when I pass the null array of values I get the following error on line `690` of `chartists.js`:

```
Error: Exceeded maximum number of iterations while optimizing scale step!
```

I was able to work around this by setting just the first value to 0, but it would be best if the library accounted for this scenario.

The version I am using is `0.9.5`

**Comment by miladghaznavi** [comment]
I had the same error because of an empty array. Make sure that your X or Y axises data for the line chart values are not empty.

**Comment by WolfOvs** [comment]
Same issue....but the X and Y axises are not empty...

Chartist.js 0.9.5

<img width="602" alt="screen shot 2016-04-15 at 16 37 07" src="https://cloud.githubusercontent.com/assets/9006823/14564793/6bf27e9c-0328-11e6-932b-ee01d8701a8d.png">

**Comment by gionkunz** [comment]
This should no longer be an issue since 0.9.6 https://github.com/gionkunz/chartist-js/blob/develop/CHANGELOG.md#v096---22-feb-2016
