### ISSUE TITLE
Chartist Pie chart series setting

### ISSUE THREAD

**Issue by Datagaard** [chartist-js/chartist#528]
I am, new to Chartist, and was hoping that you could point me in the right direction.

I am attempting to set the series in the data function to an array populated from a database table.

Code shown below

![chartistissue1](https://cloud.githubusercontent.com/assets/16074263/11461334/34214a22-9751-11e5-9155-4562986d16ef.png)

The values in the vars pLabels and pData are shown commented below each declared variable.

This is the output result:

![chartistissue2](https://cloud.githubusercontent.com/assets/16074263/11461336/4e894b94-9751-11e5-9b24-e0c2340ff690.png)

If I use the hard coded commented values, all works correctly, e.g.:
![chartistissue3](https://cloud.githubusercontent.com/assets/16074263/11461340/650f6e84-9751-11e5-8976-d8171d3804de.png)
![chartistissue4](https://cloud.githubusercontent.com/assets/16074263/11461343/7927a86e-9751-11e5-8000-9c3f5f5b78b5.png)

Could you show me what I am missing?

Regards

**Comment by gionkunz** [comment]
Sorry I never replied to this, please re-open if still needed
