### ISSUE TITLE
Bar chart: Incorrect label length for last X-asis label

### ISSUE THREAD

**Issue by wvteijlingen** [chartist-js/chartist#529]
The last label of the X-asis has a [minimum width of 30pixels](https://github.com/gionkunz/chartist-js/blob/4de57b360bb69e60b834ecf1f99d60ec822b6881/src/scripts/axes/axis.js#L55). This works for wide charts, but it causes the width of the last label to be wider than it should actually be in some cases.

The stated reason for this is "so that labels close to the border will still be visible inside of the chart padding."  In our instance this bug can be fixed simply by removing the `Math.max`. This results in a perfectly calculated width which is the same as the width of the other labels. However, I don't know the Chartist source well enough to decide whether this would be the correct path to take.

![screen shot 2015-11-30 at 13 29 15](https://cloud.githubusercontent.com/assets/1460535/11471525/974aab92-9766-11e5-8a90-0a6461397226.png)

**Comment by gionkunz** [comment]
Hi there. I guess this is fine for bar charts but the problem is for line charts with the `fullWidth` option. We'll need to find a better approach for this problem anyways. Let's keep this issue open for tracking.

**Comment by wvteijlingen** [comment]
Ah ok. From looking through the examples a bit, I assume the problem is that the last label isn't fully displayed when it overflows the SVG boundary. Is this correct?

If so, a possible solution could be to check whether a label fits the available space, and rotate it if it doesn't fit.

![screen shot 2015-12-12 at 16 15 04](https://cloud.githubusercontent.com/assets/1460535/11762592/85fb51b4-a0eb-11e5-936c-131e590ce81c.png)

**Comment by gionkunz** [comment]
We need to cover this when working on #809
