### ISSUE TITLE
Chart Bar: labels on different lines?

### ISSUE THREAD

**Issue by LeoIannacone** [chartist-js/chartist#53]
Hi,

In some of my graphs labels are really long and they are or too much close or they cover each other..
I would like to split them on different lines. 

Is it possible?

**Comment by gionkunz** [comment]
Hi,

This is not possible with Chartist currently. This is already tracked with #25 and will possibly be one of the next features, so please stay tuned.

Also please give your vote on issue #25 so we can track the popularity there.

Cheers
Gion

**Comment by gionkunz** [comment]
I'll close this issue in favor of #25
