### ISSUE TITLE
Line on a bar chart to demonstrate target vs. actual

### ISSUE THREAD

**Issue by chrisdeeming** [chartist-js/chartist#530]
@gionkunz, you recently helped someone with a very similar issue, here:
https://github.com/gionkunz/chartist-js/issues/235

I wondered whether you would advise how it would be possible to adapt this: http://jsbin.com/dajole/3/edit?css,js,output

To look similar to this:
![image](https://cloud.githubusercontent.com/assets/2158514/11482240/b45bdd54-9799-11e5-8e25-b4afbf7ac8c4.png)

To be clear, the target line would potentially have a different value each day.

Thank you for any advice :smile:

**Comment by gionkunz** [comment]
This would be feasible with #37 . Closing this until we can work on #37
