### ISSUE TITLE
filled holes in data problem

### ISSUE THREAD

**Issue by novikov-an** [chartist-js/chartist#531]
I've installed this library and tried to use "FILLED HOLES IN DATA" example in my project. Here is my code:

``` javascript
new Chartist.Line('#chart', {
         labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri','Sat'],
          series: [ [6, 9, 12, null, 6, 12], ]
        }, {
          fullWidth: true,
          chartPadding: {
            right: 40
          },
            lineSmooth: Chartist.Interpolation.cardinal({
                fillHoles: true,
            }),
        });
```

But it gives to me
![screenshot 1](https://cloud.githubusercontent.com/assets/11132186/11530288/9504ff78-991d-11e5-81bc-eb3eb83e88cd.png)

What I'am doing wrong?

**Comment by gionkunz** [comment]
Hi there. I've missed to push the tag v0.9.5 and therefore you've got an old version. Please re-install with bower or npm.

**Comment by novikov-an** [comment]
Hello. Thank for you respond. Now all is working fine.
