### ISSUE TITLE
update options for existing chart

### ISSUE THREAD

**Issue by simoooooon** [chartist-js/chartist#533]
hi everybody and hi @gionkunz !

chartist.js is awesome but currently i am struggeling a bit with bar charts.
i want to set seriesBarDistance and the width of the bars dynamically depending on the number of bars a barchart consists of. i would love to do this within a plugin. the number of the bars is not fixed, it should work with datasets of different length.

i am able to gain information on the charts underlying data with _Chartist.getDataArray(chart.data);_ - important for figuring out the number of bars - and i can manipulate the width of the bars (like its done in the _Stacked Bar Chart_ example). what i cannot do is setting the _seriesBarDistance_ dynamically. I can set it once in the default options but cannot change it on the fly.

How can i set _seriesBarDistance_ dynamically within a plugin?

<img width="637" alt="bildschirmfoto 2015-12-07 um 18 23 56" src="https://cloud.githubusercontent.com/assets/8035756/11634259/c4fcac8a-9d0f-11e5-9c56-61a5eefd1506.png">
_not cool, way to much empty space. the bars width (and the distance between them) should adapt to the total numbers of bars to nicely fill the area_

Thank you very much! cheers

**Comment by simoooooon** [comment]
getting closer …

chart.update() should do it but unfortunately it does not.
options get updated with new BarSeriesDistance but it has no effect on the rendered chart.
am i missing something?

```

import Chartist from 'chartist';

export function ctExtendFitBarsToData() {

    return function ctExtendFitBarsToData(chart) {

        // set seriesBarDistance
        chart.update(null, {seriesBarDistance: 46}, true);

        if(chart instanceof Chartist.Bar) { 
            chart.on('draw', function(data) {
                if(data.type === 'bar') {
                    // set width of bars
                    data.element.attr({style: 'stroke-width: 20px'});
                }
            }); 
        }
    };
};

```

**Comment by gionkunz** [comment]
Sorry I never replied to this, please re-open if still needed

**Comment by msanagu** [comment]
Was there ever a solution to this?
