### ISSUE TITLE
getNumberOrUndefined returns numeric values for 'true', 'false', and 'null'

### ISSUE THREAD

**Issue by arvinsingla** [chartist-js/chartist#534]
I'm unsure if this is intentional or not so I thought I would ask. The block comment for `getNumberOrUndefined` specifies that the function _"Returns a number if the passed parameter is a valid number or the function will return undefined"_.

Since the function relies on the javascript unary + operator if the values `true`, `false`, or `null` are passed we will get 1, 0, and 0 respectively. Especially in the case of `null` this may not be the desired result. Especially when tests for other falsey values returns `undefined` as specified in the tests.

If this is intentional then perhaps it should be documented in the comments as some people may consider `null` to represent no value instead of a 0 value.

**Comment by gionkunz** [comment]
We need to review this. It's used in the data normalization process and currently everything works as expected although I'm not sure if null should not return undefined instead. I'll flag it as a cleanup bug so it does not get lost.
