### ISSUE TITLE
Error on empty data set

### ISSUE THREAD

**Issue by mohlek** [chartist-js/chartist#537]
I get an error when I pass an empty data set.

Is it somehow possible to get an empty chart? I'd like to fill my data after page load due to lazy loading.

https://jsbin.com/wayohenane/edit?html,js,console,output

**Comment by mohlek** [comment]
It worked in version 0.7.4.
Well at least it doesn't throw an error so i can update the chart and get my data.

**Comment by buschtoens** [comment]
The error stems from [`core.js Chartist.getBounds`](https://github.com/gionkunz/chartist-js/blob/4d2ef6f48cc87af75c6167bdc11ba8083bfc7e6e/src/scripts/core.js#L669).

**Comment by gionkunz** [comment]
Hi. Can you please post some sample code to reproduce?

**Comment by mohlek** [comment]
Its in my first post...

**Comment by mohlek** [comment]
Are there any plans on fixing this?
I would help to fix but i dont know whats the hassle with this

**Comment by ashishUthama** [comment]
@gionkunz - In a line chart, when using Chartist.AutoScaleAxis for x-axis, setting data to [] for any series in a line chart results in:

![1](https://cloud.githubusercontent.com/assets/2106392/11910985/89efcd38-a5d5-11e5-8b76-948f5b463b68.png)

**Comment by mohlek** [comment]
PR #555
