### ISSUE TITLE
Large number issue 

### ISSUE THREAD

**Issue by novikov-an** [chartist-js/chartist#539]
Hello,

I've tried to put a large numbers to the chart and got this(please look to the labels  by X-ordinate):
![screenshot 1](https://cloud.githubusercontent.com/assets/11132186/11737218/5bb03e8c-a001-11e5-8fbc-cb4d4905118f.png)

Here is a code from example:

new Chartist.Line('.ct-chart', {
  labels: [1, 2, 3, 4, 5, 6, 7, 8],
  series: [
    [0, 50000000, 7000, 8, 5, 3, 5, 4]
  ]
}, {
  low: 0,
  showArea: true
});

In my chart I need to use  a huge ( 2-9 symbols) numbers.

How can I resolve this problem?

**Comment by bartveneman** [comment]
You could try to use offsets:

``` js
new Chartist.Line('.ct-chart', {
    labels: [1, 2, 3, 4, 5, 6, 7, 8],
    series: [
      [0, 50000000, 7000, 8, 5, 3, 5, 4]
    ]
  }, {  
  axisX: {
    offset: 60
  },
  axisY: {
    offset: 80
  }
});
```

From [the docs](http://gionkunz.github.io/chartist-js/examples.html#example-multiline-bar)

**Comment by gionkunz** [comment]
Or try to use simple smoothing. Check the examples for that. Cheers

**Comment by gionkunz** [comment]
I'm closing this, please comment and / or reopen as needed. Cheers

**Comment by MrMathias** [comment]
I think the issue here is about large y values being truncated. This can be alleviated via chartPadding. 
But it would be neat to have dynamic SI symbols (1.3k,2.4M,1.1G,...), for large numbers and order of magnitude differences in the data.
