### ISSUE TITLE
How to control the colors of a Stacked bar chart

### ISSUE THREAD

**Issue by rstudner** [chartist-js/chartist#542]
I've been able to control the colors of a bar chart.. and of a donut chart.

I can't seem to get the right format for defining the 'series of series' for controlling the bar colors in this case

is it something like:

```
      labels: ['D1', 'D2'],
      series: [
        [{meta:'one', value: 5}, {meta: 'two', value: 0}, {meta: 'three', value: 0}],
        [{meta:'one', value: 1}, {meta: 'two', value: 1}, {meta: 'three', value: 1}],
      ]
```

of course this being how to do it with no control:

```
      series: [
        [5, 0, 0],
        [1, 2, 1],
      ]}
```

**Comment by gionkunz** [comment]
Well if you're okay with the original class names within Chartist you can just style the bars within your chart like so. You can use `ct-series-a ...-b ...-c` etc.:

``` css
.ct-series-a .ct-bar {
  stroke: green;
}
```

Or you use your own class names by using the series object notation:

``` javascript
var data = {
  labels: ['D1', 'D2', 'D3'],
  series: [{
    className: 'first-series',
    data: [
      {meta:'one', value: 5}, 
      {meta: 'two', value: 2}, 
      {meta: 'three', value: 4}
    ]
  }, {
    className: 'first-series',
    data: [
      {meta:'one', value: 1}, 
      {meta: 'two', value: 1}, 
      {meta: 'three', value: 1}
    ]
  }]
};

new Chartist.Bar('.ct-chart', data);
```

I know this should be documented better. Let's track this here: #545

**Comment by rstudner** [comment]
Yeah. I had done #1 successfully but wanted to do #2 for various reasons. Thanks for the fast response. Much appreciated.

**Comment by ffradegrada** [comment]
So, if I add a className to the series, I can change the color ok, but how can I change the legend color??
