### ISSUE TITLE
force yAxis to show whole numbers on every responsive view

### ISSUE THREAD

**Issue by mattiLeBlanc** [chartist-js/chartist#543]
Hi,

First of all I am amazed by your library. It rocks. Coming from Chartjs.org, I am very happy with the customisability of this lib. Great job!

Being a Chartist Grasshopper, I was figuring out all the requirements I need for my chart application and I ran into a possible simple one:

The numbers on the yAxis go from 0 to 7 with this current dataset. I have set the high to 10 and the low to 0.
On bigger resolutions, the chart automatically adds broken numbers to the grid which don't make sense in my context (half an event??).

See picture:
![image](https://cloud.githubusercontent.com/assets/5285035/11760457/980103d6-a0f0-11e5-922b-03bff663e43a.png)

So I use the responsiveOptions and I can change the labelInterpolationFnc for each breakpoint to change how many lines are skipped. That might work.

However, Isnt' there an overal option where I say I do not want to see broken numbers on the yXasis?

**Comment by mattiLeBlanc** [comment]
This works for me (in coffeescript):

```
axisY:
  labelInterpolationFnc: (value, index) ->
     # check if the value is not a decimal
     return if value % 1 is 0 then value else null
```

Would that be the way to go?

**Comment by gionkunz** [comment]
Hi, you can use the `onlyInteger` option on the axis. The documentation is automatically generated and I've not had the time to put some more effort into this. It's sometimes not clearly visible where all those options are. In the chart axis configuration documentation it's mentioned that you should refer to the individual axis type options. By default the y-axis s of type `AutoScaleAxis` and the options are here: http://gionkunz.github.io/chartist-js/api-documentation.html#module-chartistautoscaleaxis

**Comment by mattiLeBlanc** [comment]
Ah, you are right. I did use onlylInteger, but I must have set it to the general options and not axis specific.

Concerning documentations: can you integrate Git with the docs so that people can suggest documentation for charttype or subjects? That way we can help you and you can approve, re-author the text?

**Comment by gionkunz** [comment]
The documentation can be improved using git: https://github.com/gionkunz/chartist-js/tree/673c45393e05cf6dd3bf2393c3a213c65abdaca8/site/data/pages

The API Documentation is generated from inline JSDoc comments in the code files.
