### ISSUE TITLE
Create Bar Stacked with serie date per label

### ISSUE THREAD

**Issue by mattiLeBlanc** [chartist-js/chartist#547]
Hi,
I want to create a stacked bar chart of serie data per label.

The only way I can do it now is by creating as many series as there are values and adding in 0 values to make the series complete

```
// dataset: "{"labels":["2015-03-23","2015-03-30","2015-04-06","2015-04-13"],"series":[ [329,219], [], [121],[2,2] ] }"

new Chartist.Bar('.ct-chart', {
  labels: ['2015-03-23', '2015-03-30', '2015-04-06', '2015-04-13'],
  series: [
    [ 329,0,0,0],
    [ 219,0,0,0],
    [ 0,0,121,0 ],
    [ 0,0,0,2 ],
    [ 0,0,0,2 ],
    [ 0,0,0,0 ]
  ]
}, {
  stackBars: true,
  axisY: {
    labelInterpolationFnc: function(value) {
      return value ;
    }
  }
}).on('draw', function(data) {
  if(data.type === 'bar') {
    data.element.attr({
      style: 'stroke-width: 30px'
    });
  }
});
```

I would prefer creating a serie like:

```
series   = [ [ 329,129], [] , [ 121 ], [2 , 2 ] ];
```

Is this hard to do?
I am a bit short on time since I have to deliver a report dashboard, however I could look in the source if I can enhance the bar chart?

**Comment by mattiLeBlanc** [comment]
I have converted my series to a grid  (coffee script)

```
      grid    = Array.apply( null, Array( rowCount ) )
      # create grid with lot's of zero's
      grid    = grid.map ->
        return Array.apply( null, Array( result.series.length ) ).map ->
          return 0

      col = 0
      currentRow = 0
      _.forEach result.series, ( serie ) ->

        _.forEach serie, ( val ) ->
          grid[ currentRow ][ col ] = val
          currentRow++
        col++

     result.series = grid
```

creating something like this

```
   [ 329,0,0,0],
    [ 219,0,0,0],
    [ 0,0,121,0 ],
    [ 0,0,0,2 ],
    [ 0,0,0,2 ],
    [ 0,0,0,0 ]
```

which works but now I don't get a colour reset per bar:
![image](https://cloud.githubusercontent.com/assets/5285035/11770982/6125f7f8-a25e-11e5-9643-50777aa1c50a.png)

It keeps using new colours so that is not ideal :(

Eventually when I hit more than 26 series I also get an issue that that the naming of the serie starts at A again. The result is a weird chart:
![image](https://cloud.githubusercontent.com/assets/5285035/11771082/8fa9bfbe-a25f-11e5-9b67-21d75bc308e6.png)
![image](https://cloud.githubusercontent.com/assets/5285035/11771086/9d8e66e8-a25f-11e5-93e3-d8774904d6c1.png)

I think the best way would be to have stack of a serie in one bar. 
I think it will be a mix between distributedSeries and stacked bar chart.

How hard is this?

**Comment by gionkunz** [comment]
Can you maybe take this a step back and explain more what you'd like to achieve?

> I want to create a stacked bar chart of serie data per label.

I don't understand your use-case here, can you elaborate?

Cheers
Gion

**Comment by mattiLeBlanc** [comment]
Hi Gion,

I think its a stacked distributed series.
So my dataset returns a label array with for example 5 week numbers. The
data array would be 5 arrays of data per week.
Which can differ per week.
Week 1 might have [230, 50, 100]
Week 2 might have [50]
Week 3 is empty []
Week 4 might have [200, 500]
Week 5 might have [ 149, 30, 60, 400 ]

Currently your stack bar chart expect eacho 'color' to have a value in each
week array, right.
I just want to stack whatever is in each week and show that in a bar per
week.
So week 1 stacked bar would be 230+50+100=380 etc.

Is it more clear now?

**Comment by mattiLeBlanc** [comment]
Gion, is this something that is easy to implement? It would make my chart much clearer because now I can't show per bar, what made it up (I only see the sum of for example 3 parts of 125, 200 and 50 which makes a bar of 375).
Cheers

**Comment by gionkunz** [comment]
I still don't understand what you're trying to achieve sorry :-) Can you maybe explain what data you have?

**Comment by mattiLeBlanc** [comment]
okay, so normally a serie is spread over multiple bars right, so i you have
for example 4 quarters, the data would be

q1: [ 12, 33, 54 ]
q2: [ 55, 0 ,343 ]
q3: [ 33, 5, 333 ]
q4: [ 12 ,0 0 ]

So per quarter, the amount of data points have to be equal.

In my case, I want to have a stacked serie where each quarter (each bar) is
based on one array set.
So:
q1: [ 12, 33, 54, 343, 2, ]
q2: [ 55, 0 ]
q3: [ 33, 5, 333, 44, 22, 1, ,65 ]
q4: [ 12  ]

So instead of creating a serie stacked bar by spreading the data out over
the bars, it will add up each value per quarter.
So the Q1 bar consist of 5 data values, Q2 consist of 2 values, Q3 of 7 and
Q4 of 1 data value.

The reason I want to do it like this, is because I show the amount of
registrations per event per quarter. And I want to give each amount a
different color so that you can see the bar with a total (q1) of 99 consist
of 3 blocks (12, 33 and 54). This way you can see if some events had a lot
of registrations and other had little or if they are all equal.

Did I explain it right this time?

Cheers buddy.

Mattijs

**Comment by gionkunz** [comment]
Okay, so your series are actually the events then right? In that case you should also have the events form the series and fill with 0 values when they have no registrations at the given quarter. You can use the series object notation to get around the problem of the alphanumeric class names clashing above 26 (this is going to change in chartist 1.0 #183 ). You should be fine if you're generating a class for each event that holds the color and then use the class names of the events within your series object notation:

``` javascript
new Chartist.Line('.chart', {
  labels: [1, 2, 3, 4],
  series: [{
    className: 'first-series',
    data: [1, 2, 3, 4]
  }, {
    className: 'second-series',
    data: [4, 3, 2, 1]
  }]
});
```

Here's an example (Check the CSS panel for the Sass code generating class names): http://jsbin.com/borino/edit?css,js,output

I can imagine that if you're talking about a lot of events, you might want to have some automatic logic to create colors or send the colors from the server within your data. You could implement a custom logic that sets the color of your bars using the `draw` event and some color you put into the meta data. Check the following example that is generating colors based on the name of the series: http://jsbin.com/pilibo/edit?css,js,output

I hope this gives you some options :-)

**Comment by mattiLeBlanc** [comment]
The problem is the amount of events per quarter differ.
So Q1 could have 10 events with a total of 1205 registrations.
Q2 could have only 3 events with 300 registrations.
etc..

So what I did the first time is the get the quarter with the most
registrations and then polyfill the other quarters until they had the same
amount of events.
However..the query is dynamic...there could be 40 events or 5...and the
polyfilling looks like a horrible hack.

The most easy solution for me as a user would be to just provide the data
per bar (=quarter).
So Q1 ,bar 1 : [ 34, 453, 3, 434, 22 ]
Q2, bar 2: [ 343, 34 ]
Q3, bar 3 [ 343 ,32, 232, 665, 232, 232, 88, 2 ]
Q3, bar 4: [ 30, 22, 565, 2 ]

This way I would have a stacked bar with different colours for q1  with 5
partitions. For Q2 I would have a stacked bar with 2 colours , 2 partitions
and so on.

I do understand this is not possible in the current setup. You expect a
serie to be evenly divided over the bars (labels).
But, it this a difficult thing to do in your code?

**Comment by mattiLeBlanc** [comment]
Hi,

Still not clear?

**Comment by gionkunz** [comment]
Hi this is clear to me now but it's just not how Chartist works at the moment. Actually each drawn bar on a chart would be a completely new series since there's no relation between one bar and an other. I don't think we will include this functionality very soon as we have other more important features with much less complexity cost. I think the best way to handle this is to transform the data. It would also be feasible to implement this as a plugin.

**Comment by mattiLeBlanc** [comment]
The project I used this for is over/closed so I am not pursing this feature right now.
