### ISSUE TITLE
Blurry grid lines due to anti aliasing and SVG sub pixel positing

### ISSUE THREAD

**Issue by stcqu** [chartist-js/chartist#548]
On my computer (with a resolution of 1366x768) grid lines often look blurry and look like they change size/color due to anti aliasing and SVG attempting to render lines between pixels. This probably isn't as big of an issue on high res Retina screens etc, but I was able to fix this by disabling anti aliasing for grid lines:

```
.ct-chart .ct-grids {
    shape-rendering: crispEdges
}
```

Because grid lines are horizontal and vertical they probably don't need anti aliasing.  Any thoughts on disabling anti aliasing by default for grid lines? 

Here are some screen captures:
Size and quality changing with position:
![grid lines changing quality with location](https://cloud.githubusercontent.com/assets/3856230/11795796/90c6afd4-a26d-11e5-8661-40e8b80fdc6e.PNG)
Lines with anti aliasing enabled:
![grid lines with aa](https://cloud.githubusercontent.com/assets/3856230/11795774/7216b048-a26d-11e5-8214-9daa7253ad58.PNG)
Crisper, more consistent lines without anti aliasing:
![grid lines without aa](https://cloud.githubusercontent.com/assets/3856230/11795779/7533c2fc-a26d-11e5-8b79-0b8745ecfd99.PNG)

**Comment by gionkunz** [comment]
`shape-rendering: crispEdges` is recommended if desired, so it was in the Smashing article http://www.smashingmagazine.com/2014/12/chartist-js-open-source-library-responsive-charts/

However, this is just a preference and I'd rather stick to opt-in, as it's healthier for the CSS monster.
