### ISSUE TITLE
Gauche Chart Area

### ISSUE THREAD

**Issue by gcstr** [chartist-js/chartist#550]
Gauge chart takes the same total area of a pie chart.
The half bottom is empty space and it makes responsiveness very hard to work with.

The screenshot below is from project's example page:
<img width="592" alt="screen shot 2015-12-16 at 02 19 52" src="https://cloud.githubusercontent.com/assets/62089/11832142/73a7c138-a39c-11e5-8867-0eec89829087.png">

**Comment by gcstr** [comment]
Just found a similar issue was posted here before:
https://github.com/gionkunz/chartist-js/issues/272
But the issue was closed when another bug was fixed.

**Comment by imaia** [comment]
I also had this issue. Had to give up on the gauge because of it.

**Comment by gionkunz** [comment]
We will need to rewrite the whole space calculations within the pie charts based on the arc bounding box width and height and align it to use as much space as possible. This shouldn't be too much of a thing but it requires some rethinking.

**Comment by gionkunz** [comment]
You can always use transforms to scale and move your chart within the container if desired: http://jsbin.com/vitota/edit?html,css,js,output

**Comment by imaia** [comment]
Gionkunz, your suggestion worked very well. Nonethless, it reminded me of another problem with the gauge. The gauge's base is not aligned in firefox. I'll open a issue. 
![gauge_base_alignment](https://cloud.githubusercontent.com/assets/14771411/12585628/9d0b6502-c42b-11e5-8014-915b6aa96799.png)

**Comment by EvanWieland** [comment]
In case anyone wants a live demo on how to fix this: [http://codepen.io/EvanWieland/pen/bpjrog](http://codepen.io/EvanWieland/pen/bpjrog). This solution also maintains proper chart height during browser resize thanks to the `created` event.

**Comment by utheron** [comment]
Thanks for the fix, works as intended.
