### ISSUE TITLE
How can I set min of Y axis?

### ISSUE THREAD

**Issue by uaNikita** [chartist-js/chartist#551]
I need to set to my chart minimum of Y axis. For example when I have range [1, 90]. The max label is 90. But when I have no data I want to have min label 10 not 1 like know. How can I do this? Low and high are not what I need.

Thanks.

**Comment by AlexanderKozhevin** [comment]
Maybe just make manually. First you set basic config and after that set simple condition to override (low & high) properties or not to override.

**Comment by gionkunz** [comment]
Why is low and high not what you need?

**Comment by gionkunz** [comment]
Please reopen if you have more input
