### ISSUE TITLE
Colouring a stacked bar chart

### ISSUE THREAD

**Issue by meghaklp** [chartist-js/chartist#552]
Hi,

I'm trying to colour a stacked bar chart. This is in my chartist-settings.css
$ct-series-names: (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) !default;
$ct-series-colors: (
  $grey-gravel,
  **$brand-purple**,
  $brand-red,
  $green-leaf,
  $orange-mild,
  $pink-salmon,
  $brand-turquoise,
  $blue-sky,
  $red-mild,
  $maroon,
  $blue-ink,
  $purple-amethyst,
  $brand-orange,
 **$brand-green**,
 **$brand-blue**
) !default;

As you'll see in the image below the colours being picked up are the ones i've bolded above. I would ideally want the top 3 colours. Couple of things that are unclear:
1) Why are colours being picked up in random order
2) I tried setting different colours in css to series-n , series-o and that doesn't seem to help

How do I go about this really
![image](https://cloud.githubusercontent.com/assets/465382/11893184/84dde244-a594-11e5-852d-28e0b45b7691.png)

**Comment by gionkunz** [comment]
Hi there, sorry for the late reply. Could it be that you're having some 0 series causing the colours to skip? Did you check the DOM elements of your rendered chart and the class names the series get? Also check your generated stylesheet if the colours really end up at the series names specified within the `$ct-series-names` variable.

Maybe you can also switch to the series object notation to set a custom class names for your series?

``` javascript
new Chartist.Line('.chart', {
  labels: [1, 2, 3, 4],
  series: [{
    className: 'first-series',
    data: [1, 2, 3, 4]
  }, {
    className: 'second-series',
    data: [4, 3, 2, 1]
  }]
});
```

**Comment by gionkunz** [comment]
Closing becauase of inactivity
