### ISSUE TITLE
How do I use CSS selectors for all ct-bar elements under a named ct:series-name ?

### ISSUE THREAD

**Issue by ashishUthama** [chartist-js/chartist#553]
[A bit of a novice with HTML/CSS]

Consider:
http://jsfiddle.net/dx8w6b64/

I am trying to create a CSS selector for all .ct-bar for say series 'first'.

`[ct:series-name="first"] .ct-bar` doesnt appear to work (chromium on linux). Searching appears to indicate that the : in the attribute name might be the culprit. I have tried :, \3A  etc to 'escape' the colon - no luck.

I understand that the in model-way might be to use `#myChart .ct-series-a .ct-bar`. I also understand that i could override the series ordering name (a/b/c etc) in the settings. I prefer naming the series and trying to look them up with specific names - I think this is easier when you have a lot of charts and cant really come up with a global a/b/c naming sequence which might make sense.

Curious to know about why we use ':' in the attribute name/

**Comment by ashishUthama** [comment]
For anyone else running into this:

http://stackoverflow.com/questions/34446361/selecting-an-element-by-its-attribute-when-it-has-a-colon-in-its-name

Has to do with namespace declarations:

```
 @namespace ct 'http://gionkunz.github.com/chartist-js/ct';

 [ct|series-name='second'] .ct-bar {
   stroke: black;
   stroke-width: 20px;
   stroke-linecap: round;
 }
```

**Comment by gionkunz** [comment]
Glad you found a solution!

**Comment by gionkunz** [comment]
You can also generate your series by using custom classes:

``` javascript
series: [{
    name: 'series-1',
    className: 'series-1',
    data: [5, 2, -4, 2, 0, -2, 5, -3]
  }, {
    name: 'series-2',
    className: 'series-2',
    data: [4, 3, 5, 3, 1, 3, 6, 4]
  }, {
    name: 'series-3',
    className: 'series-3',
    data: [2, 4, 3, 1, 4, 5, 3, 2]
  }]
```

And then style your series using those classes.

**Comment by ashishUthama** [comment]
Yes, finally went with using className.

I assume the way to think about it is: use seriesName to manipulate/handle data in JS, and className to style using CSS/etc.
