### ISSUE TITLE
Flip Y-axis

### ISSUE THREAD

**Issue by hbrotan** [chartist-js/chartist#556]
Is it possible to flip the Y-axis? I need a graph showing ranks (standings in a league table) during a time span. Rank 1 should be the top value of the Y-axis. 

Y-axis
1
2
3
4
etc. Date 1,  Date 2, Date 3 etc. -> X-axis

**Comment by gionkunz** [comment]
It's currently not possible but you can mimic this behaviour as discussed here: #382

**Comment by hbrotan** [comment]
Thanks for quick reply. Will try to mimic the behaviour.
