### ISSUE TITLE
Problem with the last label on the X-axis

### ISSUE THREAD

**Issue by novikov-an** [chartist-js/chartist#557]
Merry Christmas for everyone) 

I've got a some problem with last label on the X-axis:
![screenshot 1](https://cloud.githubusercontent.com/assets/11132186/12000696/65744828-ab05-11e5-8c67-f5edbaebe92a.png)

How can i put it to the one line? Bcs there is a lot of space there.

**Comment by gionkunz** [comment]
Happy new Year! :-) What browser are you using? Can you post your chart config?

**Comment by novikov-an** [comment]
Happy new Year too! :-) 

What browser are you using?
- Google Chrome. In all browsers it displays the same 

Can you post your chart config?

``` javascript
  var options = {
          fullWidth: true,
          chartPadding: { right: 100 },
          lineSmooth: Chartist.Interpolation.cardinal({ fillHoles: true }),
          height: self.table_height,
          showArea: true,
          axisX: { offset: 60 },
          axisY: { 
                offset: 80,
                labelInterpolationFnc: function(value) {
                  var new_value = value;
                  if(lang['system_currency_position'] == 'before') {
                    return self.shortPrice(lang['sys_currency'] + " " +new_value);
                  } else {
                    return self.shortPrice(new_value + " " +lang['sys_currency']);
                  }
                } 
          }
        }
```

**Comment by gionkunz** [comment]
Yeah, that's a problem of the `fullWidth` option and the Axis class that wont use the available chart padding to calculate the width of the last label. We should fix that on the axis. I'll flag your issue as a bug.

**Comment by gionkunz** [comment]
For now you have a few options:
- Don't use `fullWidth`
- Remove the last label
- Use the style `.ct-label.ct-horizontal { white-space: nowrap;}` on your labels
- Force the chart to fallback to SVG text instead of foreignObjects, which will cause all labels in your chart to be drawn with <text> elements. This will cause your text elements not to wrap, if you can forgo this feature. Check this bin for an example: http://jsbin.com/nepixe/edit?js,output

**Comment by sbaechler** [comment]
What is the best way to remove or hide the last label?

**Comment by gionkunz** [comment]
The easiest way is to set your last label to an empty string. If you want to implement this more like a plugin, you can use the draw event to remove the last label on the X axis:

``` javascript
var data = {
  labels: [1, 2, 3],
  series: [[1, 2, 3]]
};

Chartist.Line('#chart', data, {
  fullWidth: true
}).on('draw', function(context) {
  if (context.type === 'label' && 
      context.axis.units.pos === 'x' &&
      context.index === data.labels.length - 1) {
    context.element.remove();
  }
});
```

**Comment by sbaechler** [comment]
Great, thank you. I'm already listening on the draw event to add labels to the lines so I can hook in there.

**Comment by gionkunz** [comment]
We need to consider this when working on #809

**Comment by andrewdbate** [comment]
How do you do this for a bar chart on the x-axis?

In that case we cannot write `context.index === data.labels.length - 1` since the last position is not given by `data.labels.length - 1`. Any help would be much appreciated!

**Comment by nathanaelphilip** [comment]
In case someone else needs this:

```
if (context.type === 'label') {
   let labelCount = context.axis.ticks.length
    if ((context.index + 1) === labelCount) {
       context.element._node.childNodes[0].classList.add('the-last-of-the-labels')
   }
}
```

That’ll add a class to the last label, which you can use to position it via CSS

**Comment by Anoxy** [comment]
small modification to @nathanaelphilip answer did the trick for me

> 

            if (data.type === 'label') {
                let labelCount = data.axis.ticks.length
                if ((data.index + 1) === labelCount) {
                    data.width = labelWidth;
                    data.element._node.childNodes[0].style.width = labelWidth + "px";
                } else{
                    labelWidth = data.width;
                }
             } 

>

**Comment by oscarhogervorst** [comment]
Additionally; to hide any label on the Y-axis that is shown above the chart field you can use this:

```
var data = {
    labels: [1, 2, 3],
    series: [[1, 2, 3]]
};

Chartist.Line('#chart', data, {
    fullWidth: true
}).on('draw', function(context) {
     if (context.type === 'label' && context.y < 0 ) {
         context.element.remove();
     }
});
```

**Comment by harry-hathorn** [comment]
The best solution to this problem is just to add a css style to your svg:
```
this.chart.on('created', function() {
      document
        .getElementsByClassName('ct-chart-line')[0]
        .setAttribute('style', 'overflow: visible !important;');
    });
```
