### ISSUE TITLE
Absolute Y values on Line Chart

### ISSUE THREAD

**Issue by jiayihu** [chartist-js/chartist#559]
Is it possible to have absolute values on y axis when using a Line chart? I mean having fixed labels whereas the line changes according to its data.

**Comment by gionkunz** [comment]
Can you elaborate a bit more?

**Comment by jiayihu** [comment]
Suppose to have always the same labels on the Y axis, for example 5,10,15 and 20. Then you have 2 different cases. The first case has the following Y values for the line: 1,2,3,4 (y=x math function) whereas the second one has as values 5,10,15,20 (y=5x math function) for the same abscissa values.
Currently Chartist.js sets dynamic labels on Y axis based on the data used for the line, whereas I'd like to have always the same labels and the only thing that changes would be the line. (Updating from case 1 to case 2 you see only the line change its slope.)
Hopefully it's more clear.

**Comment by gionkunz** [comment]
You can use the `FixedScaleAxis` and limit your chart bounds with the `low` and `high` options on the axis. Then use multi values and generate the samples using your math equation. Check the "Switching Axis Types" topic on the doc site: http://gionkunz.github.io/chartist-js/getting-started.html#switching-axis-type
