### ISSUE TITLE
Pie chart array value proportions

### ISSUE THREAD

**Issue by jakefleming** [chartist-js/chartist#56]
If you have leading zeros in your chart array for a pie chart, then you'll get a weird result with  a sliver and the pie looks like its off the screen. Or if you values are really disproportionate to one another you will get a similar result where there is a sliver of pie and the rest is above and cut off. 
![screen shot 2014-09-29 at 4 40 11 pm](https://cloud.githubusercontent.com/assets/1312074/4450019/41584356-4821-11e4-857b-f06909a67d13.png)
![screen shot 2014-09-29 at 4 39 57 pm](https://cloud.githubusercontent.com/assets/1312074/4450020/41d3b95a-4821-11e4-8133-e0db13eb52d2.png)

**Comment by gionkunz** [comment]
Thanks for the issue @jakefleming ! This is something we should fix!

**Comment by jakefleming** [comment]
No problem! I'm using these charts for a bunch of dynamic data and am getting results for the array like the one's shown above so it's definitely a real use case! I love using chartist so far, so hopefully this is a relatively easy fix because I don't want to switch to a different library. Great work!

**Comment by gionkunz** [comment]
Hi There, I just missed to include this one in v0.2.0 :-( I will definitely go into 0.2.1! Sorry for this and please stay tuned!

**Comment by jakefleming** [comment]
Ok awesome. When do you think 2.1 will be available? Do you have a rough estimate?

**Comment by gionkunz** [comment]
0.2.1 is the next milestone which will focus on stability only. Maybe tomorrow, maybe in a few days but max 1 week.

**Comment by jakefleming** [comment]
Awesome! You dudes rock!

**Comment by danreed121** [comment]
Yea.. agreed..  This is good stuff.  I am finishing up some project work
but want to start looking at enabling a combo chart (bar/line).

On Mon, Oct 6, 2014 at 11:24 AM, jakefleming notifications@github.com
wrote:

> Awesome! You dudes rock!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gionkunz/chartist-js/issues/56#issuecomment-58033849.

## 

## 

Daniel Reed
Founder/Managing Director
Wrycan, Inc.
One Broadway, 14th floor
Cambridge MA 02142
office: +1 617.684.0182 x201
www.wrycan.com
CONFIDENTIALITY: This message and any attachments are the property of
Wrycan, Inc. They may contain privileged and confidential information
intended only for the use of the addressee named above. You are hereby
notified that any use, dissemination, distribution or reproduction of this
message and attachments is prohibited. If you received them in error,
please notify the sender and delete them immediately.

**Comment by gionkunz** [comment]
This is fixed with b01e1f3 and will be released with 0.2.1 next week.
