### ISSUE TITLE
Question : How can I get the height of chart 

### ISSUE THREAD

**Issue by sj82516** [chartist-js/chartist#561]
Hi all,
I wana get the chart height after rendered.
How can I do that?

**Comment by gionkunz** [comment]
Hey there. Check this bin: http://jsbin.com/vureke/edit?html,css,js,output

**Comment by sj82516** [comment]
Thanks for the answer (y)

By the way, i wana ask where can I learn how to use  
.on('created', (context)) and "data"  
I have no idea about the element and function belong to context and data.

**Comment by gionkunz** [comment]
yeah, this is something that we're lacking in :-/ Documentation of the events is on our plate #90 and #565

**Comment by gionkunz** [comment]
For the moment you can search the code base for `.emit` to find all events that are emitted within Chartist.

**Comment by sj82516** [comment]
I see.
Thanks for the nice library and quick answer again. :)
