### ISSUE TITLE
Proposal: Only show points on line chart if corresponding label shown

### ISSUE THREAD

**Issue by austenc** [chartist-js/chartist#562]
I'm not sure if this has been mentioned in the past or not, but it would be a pretty neat feature that I think others could use as well. The option would look something like this in chart options:

```
axisX: {
    ...
    // false (show every point) by default, constraints # of points shown to # of labels
    limitPointsLabels: false, 
    ...
}
... same for axisY of course
```

Basically, if you use something like `labelInterpolationFnc` to limit the number of labels shown, it would be really useful to be able to constrain the points shown to match that. I wasn't able to find anything in the documentation that accomplishes this. In my case I have daily data for an entire year (365 data items), but only want to show one x-axis label for every month. I've got my interpolation function setup to do this, but just need the ability to highlight just the data points at those label gridlines. I'm happy to discuss this further and/or submit a pull request if it's something that would be considered for a merge in a future version?

**Comment by gionkunz** [comment]
Hey there! Nice catch! :-) It's a salmon right? Sockeye? I love fishing!!!

I agree this would probably be a nice feature to have more control, but we'd need to think about the API design carefully to not make a mess with the labelInterpolationFnc. We'll rename this anyway in 1.0 #215 and probably we could also change its mechanics.

It very easy to achieve what you like to do already with the current version of Chartist using the `draw` events. Unfortunately we really lack in documentation there (not only there) see #90 

Checkout this bin: http://jsbin.com/jiluje/1/edit?html,js,output

**Comment by austenc** [comment]
This is awesome, thank you! Would it be worth submitting a pull request to document these events (or at least a start to doing so?), or is that something that's better left for post 1.0. Not being overly familiar with the chartist source I am just unsure if the api might change from the events that exist now. Let me know if you'd like some help documenting that stuff. 

Thanks for the bin link!! I'll implement this into my app as soon as I get a little time. Is there anything to be concerned about performance-wise with using this `draw` event?

**Comment by gionkunz** [comment]
No we should document the events ASAP. However, the thing is, we first need to enhance our documentation system that is generating documentation using handlebars and JSDoc. There are a lot of usability issues like searchability, cross links, better structuring and somehow annotate events that will then generate documentation. Once we have that system in place, I'll let you know!

**Comment by gionkunz** [comment]
#565

**Comment by gionkunz** [comment]
In regards to performance, clearly there is a bit of overhead when performing unnecessary DOM operations to add the elements and then again to remove them. However, as all of this happens within the same call stack, the browser can at least optimize so no reflows happen. There are also intentions to add "before" events that allow to avoid DOM creation for given elements or modifying before rendering.

**Comment by gionkunz** [comment]
#540

**Comment by austenc** [comment]
Thanks again for this awesome charting lib, it's worked out great for me so far!
