### ISSUE TITLE
Horizontal Label cuts off

### ISSUE THREAD

**Issue by ghost** [chartist-js/chartist#563]
I'm not sure, if this issue already exist. I tried searching for it in your archive but I couldn't find anything. I am having an issue where the Horizontal graph label is cutting off on the Y axis, I tried expanding the width of the label and font size using the CSS option but it continues to cuts the label off. I also tried expanding the graph but it continues the cut off. Is there an option to expand the label space?

<img width="320" alt="horizontalgraph" src="https://cloud.githubusercontent.com/assets/16549038/12104162/df27b678-b316-11e5-984e-f29eeef855c1.png">

**Comment by gionkunz** [comment]
You need to use axis offset option within the configuration for the Y axis. See http://gionkunz.github.io/chartist-js/api-documentation.html#chartistline-declaration-defaultoptions and click on show code.

**Comment by ghost** [comment]
Oh, thank you very much for the information!
