### ISSUE TITLE
Pie Chart label position move

### ISSUE THREAD

**Issue by sj82516** [chartist-js/chartist#567]
Hi all, 
when I use pie chart , the label show up in the wrong position. 
How can I rotate the label to fix the proper position? 
![bug](https://cloud.githubusercontent.com/assets/6858460/12137168/2e9accc2-b489-11e5-95f3-0d1fe021aef1.jpg)  
By the way , when I tried to set font size by 

<pre>
on('draw', function(data){
    if(data.type === 'label'){
        data.element.attr({'style':'font-size:15px;'})
        }</pre>

Nothing happened. I use css alternatively.
Why can't I use this method? Any syntax error?

**Comment by gionkunz** [comment]
Sorry I never replied to this, please re-open if still needed
