### ISSUE TITLE
Center single data point and label on a line chart

### ISSUE THREAD

**Issue by jasonlynx** [chartist-js/chartist#569]
Is there way to center horizontally a single data point and it's x-axis label on a line chart? See the attached image illustrating a situation where only one data point shows and this single point is pushed to the left of the chart.

<img width="820" alt="screen shot 2016-01-06 at 6 45 49 pm" src="https://cloud.githubusercontent.com/assets/15249825/12158241/41c7c116-b4a6-11e5-9bdc-496a8da2d40a.png">

**Comment by jasonlynx** [comment]
This should be resolved in release 0.9.9:

https://github.com/gionkunz/chartist-js/issues/716

**Comment by akbarkz** [comment]
I have the same problem with v 0.11.0, but in my case point is pushed to the right. Also all the ticks on X axis are also pushed to the right.
![screenshot from 2018-05-30 17-38-29](https://user-images.githubusercontent.com/15943863/40718019-5309639e-6430-11e8-917f-3dc26629df8e.png)
