### ISSUE TITLE
X axis data clickable

### ISSUE THREAD

**Issue by ninoCookies** [chartist-js/chartist#571]
Hello, 

i'm using chartist in angularjs project and i have calendar data (dates) on x axis and lets say temperature values on Y axis. Can someone point me in the right direction on how to make data on X axis clickable so that i can pull aditional data under chart for that specific day ? Would also be perfect if i could click on "peak" points on chart itself ? I tried going trough the chartist.js code and doc's and couldnt find anything - or maybe i'm not looking correctly. 

Thank you.

**Comment by gionkunz** [comment]
You can treat the DOM of chartist like all other DOM within your project. For example using jQuery delegation: `$(document).on('click', '.ct-point', function() { console.log('point was clicked ' + this }`

**Comment by ninoCookies** [comment]
Thank you very much for pointing me to right direction. There is ) missing in that example so i'm attaching what i ended up doing. Forgive me for lack of jquery knowledge - i work mostly in Angular 

``` javascript
$(document)
.on('click', '.ct-point', function(event) {
    console.log('point was clicked ');
    console.log(event);
});

$(document)
.on('click', '.ct-label', function(event) {
    console.log('point was clicked ');
    console.log(event);
});

```

**Comment by David-Hari** [comment]
Hi,

The above code is great, but is there a way to get the actual data point in the click event? I see a `data` property in the event object, but it's `undefined`.

I guess I could do `this.getAttribute('ct:value')`, but that seems like an internal attribute to me. It would be better to have the value passed directly to the function somehow.
