### ISSUE TITLE
How to create overlay tag on pie chart when mouse enter

### ISSUE THREAD

**Issue by sj82516** [chartist-js/chartist#573]
Hi all,
Here is what I want to do.
when mouse in, tag show up.
![1](https://cloud.githubusercontent.com/assets/6858460/12214502/edebdbfe-b6d0-11e5-81b6-3d7656cc231f.png)

I encountered two issue:
1.I know how to add event listener. 
The data type 'slice' only contains center position. 
Data type 'label' contain the position what I want but I don't want label shows up. 
So I set showLabel:false. 
2.I tried to append html and set z-index,x position, y position but not worked. 
How can I do?

**Comment by dominicrico** [comment]
there is a [plugin](https://github.com/Globegitter/chartist-plugin-tooltip) to do this.

**Comment by gionkunz** [comment]
Using the tooltip plugin or writing your own bridge to any tooltip library is the way to go.
