### ISSUE TITLE
Share : Create Pie Chart with check box and label

### ISSUE THREAD

**Issue by sj82516** [chartist-js/chartist#577]
Hey all, 
After several weeks work, 
I have some conclusion and want to share with you. 
Here is my jsbin. http://jsbin.com/tuyere/edit?html,css,js,output
![default](https://cloud.githubusercontent.com/assets/6858460/12219930/3d88dd20-b793-11e5-83c2-202716557bbe.jpg)
This example shows several thing:
-1.Create Pie chart with custom class name. You can style each slices easily by css. 
-2.Create checkbox to control pie chart. 
-3.Auto create label in js file.
-4.bind event listener to slice. 
Some data show up in console. 
Hope this help you. :) 

BTW, I have some problem here: 
http://stackoverflow.com/questions/34689590/javascript-how-to-make-overlay-tag-on-the-pie-chart-by-chartist-js?noredirect=1#comment57127684_34689590
Plz help me. OTZ

**Comment by gionkunz** [comment]
Thanks for sharing, I'm referencing this in #733

**Comment by thaijasa** [comment]
How did u call javascript file in html file?
