### ISSUE TITLE
[Bars Stacked] Visualization problem with firefox

### ISSUE THREAD

**Issue by monossido** [chartist-js/chartist#580]
I have problem with firefox and my chart with stacked bars
Any hint?

![Chartist1](http://monossido.lorenzobraghetto.com/share/chartist2.png)
![Chartist2](http://monossido.lorenzobraghetto.com/share/chartist1.png)

**Comment by gionkunz** [comment]
Can you add the chart to an online editor like jsbin so we can debug?

**Comment by monossido** [comment]
Reporting my chart using only javascript in jsbin unfortunally (or not) works.
You can see it here https://jsbin.com/wafeyu/edit?html,js,output

In my enviroment I use angular js, material angular js, angular-chartist and  a lot of stuff...actually I'm new to this enviroment so it's difficolut to understand for me where it's the problem.

Maybe it's better to report this to anngular-chartist

Thank you anyway

**Comment by gionkunz** [comment]
Hi there. Do you mean that you can't reproduce the issue using only JavaScript? I've tested your chart in Firefox and for me it's working (FF43)

**Comment by celiomesquita** [comment]
I have got the same problem with a line chart in firefox, but not in all machines.
