### ISSUE TITLE
Updating chart data and chart options

### ISSUE THREAD

**Issue by ninoCookies** [chartist-js/chartist#583]
Hello, 

is it possible to update the chart options using ng-model from angularJS? I was testing this in a way - i created 

``` javascript
    $scope.testWidth = 3000;

    var options = {
    width: $scope.firstWidth,
    height: 390,
    showArea: true,
}
```

And this works initially but the chart does not get updated when ng-model changes (i understand thats normal) so i was wondering how to solve this ? Should i integrate a button that calls update function?

**Comment by hansmaad** [comment]
Add a `$scope.$watch` on options and data and update your chart in the handler. 
I think there are some chartist directives available you could use instead of writing your own.
