### ISSUE TITLE
Horizontal bars are not appear as whole numbers

### ISSUE THREAD

**Issue by ghost** [chartist-js/chartist#585]
The horizontal Bar graph data series are whole number values, there are no decimal values in the data array series, but the graph keeps showing the bar strokes in between the values like they are decimal values. I hope that make sense.

<img width="318" alt="cut_bar_graph" src="https://cloud.githubusercontent.com/assets/16549038/12396249/5c821006-bdd4-11e5-8843-98c03598b3d9.png">

**Comment by gionkunz** [comment]
maybe some code would be beneficial in finding the issue :-)

**Comment by ghost** [comment]
Sorry for the delay, I posted the code below:
//Create the new series and labels
    var options = { seriesBarDistance: 5,
                                horizontalBars: true,
                                distributeSeries: true,
                                axisX: {
                                    labelInterpolationFnc: function(value) {
                                        return Math.floor(value);
                                    },
                                }, 
                                axisY:{
                                    offset: 110
                                    },
                                onlyInteger: true,
                                width: 650, height: 320};

```
                    for (var key in projectModelResultsArray.horizontalGraph) {
                        var actualValue = projectModelResultsArray.horizontalGraph[key];
                        console.log(key + " : " + actualValue);
                        labelsTxt.push(key);
                        seriesData.push({value: actualValue});

                    }
                    //console.log(seriesData);
                    barGraph = new Chartist.Bar('#chart2', {
                          labels: labelsTxt,
                          series: seriesData
                        }, options);

                    barGraph.on('draw', (ctx) => {
                          if (ctx.type === 'label') {
                            // adjust label position for rotation
                            const dX = ctx.width / 2 + (45 - ctx.width)
                            ctx.element.attr({ x: ctx.element.attr('x') - dX })
                          }
                    });
```

**Comment by gionkunz** [comment]
If you simply floor your labels, you'll see errors on the chart. The labels would probably show different values, not exactly at whole numbers, but you're flooring them. You problem is that you're using onlyInteger within the global configuration, but it belongs to your axis configuration. Put it into your axisX configuration and the problem should be gone.

**Comment by ghost** [comment]
Thanks that worked!
