### ISSUE TITLE
Label 'width' issues

### ISSUE THREAD

**Issue by rstudner** [chartist-js/chartist#586]
<img width="486" alt="screen shot 2016-01-19 at 9 08 59 am" src="https://cloud.githubusercontent.com/assets/209970/12420727/567ce09c-be8c-11e5-8edb-778560925449.png">

```
      axisX: {
        labelInterpolationFnc: function skipLabels(value, index) {
          return index % divider === 0 ? value : null;
        }
      },
```

So my axis labels are just 12-01 etc.. "strings".  And then I use the function to prevent 30 of them from ruining the X-Axis.

But, the 'calculated width' of each label (set directly on the element) is very narrow (despite now there being tons of available room).  Thus, they show up as in the screenshot.

Any thoughts on how to fix this?

(and for bonus points, the right side of my chart gets cut off once I use the label interpolation)

**Comment by gionkunz** [comment]
Maybe the fixed scale axis suits your use case better? http://gionkunz.github.io/chartist-js/getting-started.html#switching-axis-type

**Comment by rstudner** [comment]
I ended up with:
.ct-label.ct-horizontal { white-space: nowrap; }

which seems to solve it :)

is there a list of things like the above (or a list of functions like: labelInterpolationFnc?)

I don't mind the github/irc/read the code life heh.. just curious if i'm missing a link in the docs to 'more'

**Comment by gionkunz** [comment]
Yeah there is. However, it's not presented in a very usable way. We have #565 to cover this. Within the current API documentation system, if you go to the specific Chart type and expand the details of the default options using the "show code" button you'll see a list of options: http://gionkunz.github.io/chartist-js/api-documentation.html#chartistbar-declaration-defaultoptions

**Comment by rstudner** [comment]
brilliant! thanks.  <slaps myself for missing that>

**Comment by thomasqjohns** [comment]
I'm having the same problem. For some reason .ct-label.ct-horizontal { white-space: nowrap; } was working for months but recently stopped.
