### ISSUE TITLE
How to use plugins when connecting to Chartist via CDN ?

### ISSUE THREAD

**Issue by andrewflon** [chartist-js/chartist#587]
Hi - I’m using the suggested CDN code to link to Chartist.js.

If I want to use a plugin - e.g. Point Label Plugin - can I just do something like this in my header file?

 <script src="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
 <script src=“//<myWebsite>/admin/js/chartist-plugin-pointlabels.js"></script>

(I downloaded the scripts for the Point Label Plugin from here: https://github.com/gionkunz/chartist-plugin-pointlabels
and then added chartist-plugin-pointlabels.js to my admin/js scripts folder )

I then tried to create a simple line chart like this:

```
var data2 = {
  // A labels array that can contain any sort of values
  labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
  // Our series array that contains series objects or in this case series data arrays
  series: [
    [5, 2, 4, 2, 0]
  ]
};

new Chartist.Line('.ct-chart2', data2, {
  plugins: [
    Chartist.plugins.ctPointLabels({
      textAnchor: 'middle'
    })
  ]
});
```

however it doesn’t work ..
The chart is blank .. (until I remove the plugins code - then it works) ..

Did I do something wrong when trying to include the plugin script?

Thanks if you can help!

**Comment by gionkunz** [comment]
Make sure you're loading the plugin script after Chartist is loaded and before you execute the above code.

**Comment by gionkunz** [comment]
Did this do the trick? If you're still experiencing issues please reopen the issue.

**Comment by andrewflon** [comment]
Hi - my header.php file includes the following:

  <script src="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.js <http://cdn.jsdelivr.net/chartist.js/latest/chartist.min.js>"></script>
  <script src=“//<my server>/admin/js/chartist-plugin-pointlabels.js"></script>

I call this file at the beginning of my showcharts.php file (where I then run the JS to create my charts).

Will this work?

Andrew

**Comment by gionkunz** [comment]
Do you have any errors? Maybe you can show the code that you're executing to create the chart
