### ISSUE TITLE
labelInterpolationFnc not called when I pass series with undefined values

### ISSUE THREAD

**Issue by davehorton** [chartist-js/chartist#588]
I have a line chart (time series) where the user can choose to view the last hour, day, or week depending on a radio button selection.  Based on the selection, I retrieve data and call 'update'.  As part of the changed selection, I redraw the X-axis labels in my labelInterpolationFnc (for instance, the weekly view shows day names, the daily view hours etc).

The problem comes when they switch to a different time period, and I do not have data for that time period -- no data at all.  In that case, I simply want to show an empty chart -- but with the proper X-axis labels, according to their choice.  What I do in this case, since I have no data, is that I am calling Chartist.times() to generate a series with undefined values.  I then call 'update' but my labelInterpolationFnc does not get called.  The result is that if they user just clicked from the 'past hour' view to the 'past week' view the chart is empty but the chart still shows the X-axis for the past hour -- i.e. it appears to the user like nothing has happened and the view does not reflect their desire to see a weekly range.

Is there a different way to solve this problem?  Can I force an X-axis update somehow with my new labels and options?

**Comment by gionkunz** [comment]
Hi there. We should generally improve the way how chartist handles empty data sets and no labels. This PR will cover some of it #555

**Comment by gionkunz** [comment]
As a hacky workaround until we have this improved behaviour I suggest you render a dummy chart with some data and labels but then remove all elements using the `draw` event hooks.

**Comment by davehorton** [comment]
Thx, will do.  Appreciate the update and all the great work on this product!
