### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by alexpavel** [chartist-js/chartist#594]
Hello,

Do you know how can I export the piechart and the barchart to PDF? is there a way?

Thank you.

**Comment by ger-oss** [comment]
Hi,

you could try phantomjs rasterize
http://phantomjs.org/screen-capture.html
or jspdf/pdfkit

**Comment by gionkunz** [comment]
Maybe, https://www.npmjs.com/package/node-chartist is also what you could use and then use a PDF library for node to render to PDF.

**Comment by samuelgeojit** [comment]
@gionkunz  is it possible to provide a solution at client side itself
