### ISSUE TITLE
Make it possible to render empty chart and chart without explicit labels

### ISSUE THREAD

**Issue by gionkunz** [chartist-js/chartist#598]
It should be possible to avoid labels within the chart creation and also render charts without any data. Charts without labels will get labels should auto generate labels from the series counts. Charts without data should render an empty chart background with grid lines respecting low, high settings and any present labels.

This will help users in case of dynamic applications where there might be no data initial, but the chart will be updated with data later on.
#555 is required for providing this functionality.

**Comment by Quas94** [comment]
Has this been implemented yet? When I try to create a chart with

```
var chart = new Chartist.Line('.ct-chart', {
    labels: [1, 2, 3, 4],
    series: [[]]
});
```

I get the following error:

```
Uncaught Error: Exceeded maximum number of iterations while optimizing scale step!
```

**Comment by gionkunz** [comment]
Yes its there. However not released yet. Im planning the 0.9.6 release this weekend. You can build the dev branch lcally if you like to use the current state already.

**Comment by RomanShabanov** [comment]
Hey, by any chance you are close enough to release 0.9.6?

**Comment by gionkunz** [comment]
no unfortunately due to other priorities not. If we won't be able to finish the other issues in the 0.9.6 milestone within the next week or two, Ill postpone all unfinished features to 0.9.7 and ship 0.9.6.

**Comment by Quas94** [comment]
Any news on 0.9.6?

**Comment by gionkunz** [comment]
0.9.6 was just published
