### ISSUE TITLE
Line chart overshoots points at sharp turns

### ISSUE THREAD

**Issue by Quas94** [chartist-js/chartist#599]
I'm having this issue where the line chart is overshooting by a lot, vertically, when the turns are sharp. It's kind of hard to explain but if you take a look at this screenshot hopefully it's a bit easier to understand - the overshoots are circled in blue.

(ignore the array index - chart year mismatch, the indices are not meant to correspond to the years)

http://i.imgur.com/49YXw1K.png

The above is just one example, this problem is occurring consistently for me in a lot of places.

My chart options are as follows; pretty simple and nothing fancy...

```
var options = {
    width: width,
    height: height,
    showPoint: true,
    chartPadding: {
        right: 30 // so the labels on the far right don't get cut off
    },
};
```

Has anyone ever encountered this problem, or have any suggestions as to how I can approach it? I've been racking my brains all day on this and can't figure it out at all.

**Comment by gionkunz** [comment]
The thing with cardinal spline smoothing is that it looks very nice but it can create artifacts on rapid value changes. Try using simple interpolation as shown in the "LINE INTERPOLATION / SMOOTHING" exanple on the chartist example page.

**Comment by Quas94** [comment]
Hey, thanks! That fixed the problem perfectly.

**Comment by Quas94** [comment]
Oh, one question: could you explain what the divisor field in the simple interpolation means?

**Comment by gionkunz** [comment]
Search the API docs for interpolation simple. Youll find all the information there. Cheers

**Comment by gionkunz** [comment]
Did you find the information? Please re-open if you're still having issues.
