### ISSUE TITLE
Dual y-axis

### ISSUE THREAD

**Issue by sanjay** [chartist-js/chartist#60]
I'd love to have the ability to do dual y-axis on a graph (usually line or bar) so as to chart and overlay multiple data series on a single graph.

**Comment by gionkunz** [comment]
Hi Sanjay, can you please specify a bit more what you're looking for? Do you want to have a chart that allows you to have multiple different chart types in one chart? Like mixing a line chart with a bar chart?

**Comment by sanjay** [comment]
Would love to do that but also when doing a two line graph where the ranges are different (say 10-50 on one and 250-500 on the other).  Normally you do a left and a right y-axis and graph each on an independent y-axis.  Not sure there is a way to do that currently in Chartist.  If so, I totally missed it.

**Comment by gionkunz** [comment]
Do you have a visual example of such a chart?

**Comment by sanjay** [comment]
Searched for "dual y-axis chart" in DuckDuckGo and I got this as one example (of many):

http://www.tips-for-excel.com/wp-content/uploads/2011/05/Picture12.png

**Comment by gionkunz** [comment]
Okay, I think I get the idea. I'm not an expert in statistics but I guess in some cases this actually makes a lot of sense. I think this is only valid when you combine multiple charts into a combo / compound chart type. Lets track this issue in the following one #37 and let me close this one in favor of #37.

Thanks for your inputs! This is always very valuable.

Cheers
Gion
