### ISSUE TITLE
Gauge base is not aligned in firefox

### ISSUE THREAD

**Issue by imaia** [chartist-js/chartist#600]
As can be seen in the image, the gauge's base is not aligned when using firefox. 
![gauge_base_alignment](https://cloud.githubusercontent.com/assets/14771411/12585660/c20a210e-c42b-11e5-901d-e105ffe2a3a9.png)

Ths jsbin for the example can be found here https://github.com/gionkunz/chartist-js/issues/550#issuecomment-175067831 and here http://jsbin.com/vitota/edit?html,css,js,output

**Comment by gionkunz** [comment]
Sorry I never replied to this, please re-open if still needed
