### ISSUE TITLE
Transition between two states?

### ISSUE THREAD

**Issue by OscarGodson** [chartist-js/chartist#607]
I have a chart that is run on load and whenever a user changes the inputs (a calculator). I have an animation that I like:

``` js
    CalcChart.on('draw', function(data) {
      if(data.type === 'line' || data.type === 'area') {
        data.element.animate({
          d: {
            begin: 500,
            dur: 500,
            from: data.path.clone().scale(1, 0).translate(0, data.chartRect.height()).stringify(),
            to: data.path.clone().stringify(),
            easing: Chartist.Svg.Easing.easeOutBack
          }
        });
      }
    });
```

However, I was wondering how I would get it to animate between states. Like if someone has a series of `[1,2,3,4,5]` and then it becomes `[2, 4, 9, 16, 25]` how can I animate between those two states without refreshing the whole thing so it's smooth as they change values?

**Comment by gionkunz** [comment]
This is currently not supported with Chartist and wont be with Chartist 1.x. However, as part of a redesign this will be addressed by Chartist 2.x

**Comment by chrisabrams** [comment]
Any way to follow up on the progress of this? Maybe it's been implemented but just not clear in the docs?

**Comment by mgrybyk** [comment]
any updates?

**Comment by Lakston** [comment]
Any updates on this ? thanks :)

**Comment by samageloff** [comment]
I'm guessing not. :)

**Comment by alejandrombc** [comment]
Any news? @gionkunz

**Comment by emersonbottero** [comment]
var chart = new Chartist.Line('.ct-chart', {
  labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  series: [
    [1, 5, 2, 5, 3, 10],
  ]
}, {
  low: 0,
  //showArea: true,
  showPoint: false,
  fullWidth: true
});

chart.on('draw', function(data) {
  if(data.type === 'line' || data.type === 'area') {
    data.element.animate({
      d: {
        begin: 2000 * data.index,
        dur: 800,
        from: 'M 50 376.84 C 95.667  307.918 141.333 170.074 187 170.074 C 232.667 170.074 278.333 325.148 324 325.148 C 369.667 325.148 415.333 170.074 461 170.074 C 506.667 170.074 552.333 204.535 598 221.766 C 643.667 238.996 689.333 2.227 735 273.457',
        to: data.path.clone().stringify(),
        easing: Chartist.Svg.Easing.easeOutQuint
      }
    });
  }
});


paste that on the chartist path animation example page and change any value
