### ISSUE TITLE
Label maxSteps

### ISSUE THREAD

**Issue by OscarGodson** [chartist-js/chartist#608]
How would I do something like `maxSteps`? I don't want to skip certain ones I want to make sure that there's only ever, say, 1-20 labels. So if I normally would have had 100 points / 100 labels it would be replaced with only 20 labels like one every 5 points. I just don't want the labels to look like this: 
![kirby starterkit home 2016-02-09 00-13-25](https://cloud.githubusercontent.com/assets/20615/12910744/f6044890-cec1-11e5-8f02-872ff380e403.jpg)

**Comment by gionkunz** [comment]
The Auto axis contains a setting `scaleMinSpace` where you can define the minimum space allowed between generated grid lines.

**Comment by gionkunz** [comment]
Closing becauase of inactivity
