### ISSUE TITLE
Center label in donut 

### ISSUE THREAD

**Issue by maeishoj** [chartist-js/chartist#609]
I am trying to figure out how to center the label in a donut chart with the following options:

$scope.guageOptionsFull = {
        width: '100%',
        height: '150px',
        donut: true,
        donutWidth: 5,
        startAngle: 270,
        total: 100,
        // chartPadding: 10,
        showLabel: true,
        labelPosition: 'inside',
        labelDirection: 'neutral',
        labelOffset: -47,
        labelInterpolationFnc: function(value) {
            return value + '%';
        }
    };

I use only 1 segment  to simulate a gauge from 0 to 100%. I used labelPosition and labelOffset to fit it in the center in my screen, however when resizing it of course screws up. 

<img width="428" alt="screen shot 2016-02-09 at 10 24 38" src="https://cloud.githubusercontent.com/assets/1631903/12912295/cd1e8106-cf17-11e5-9750-fd6890018441.png">
<img width="297" alt="screen shot 2016-02-09 at 10 24 44" src="https://cloud.githubusercontent.com/assets/1631903/12912294/cd1e44ac-cf17-11e5-868c-1f1381348856.png">

Is there a smart way to keep this center as the graph resizes? Or do I need to just have a bunch of media queries to take care of different screen sizes and adjust the offset accordingly?

Cheers.

**Comment by gionkunz** [comment]
Hi there. I'd use the draw event to center labels to the middle of the chart. Check this bin http://jsbin.com/hipafu/edit?html,css,js,output

Also watch out for the styles:

``` css
.ct-label {
  dominant-baseline: central;
  text-anchor: middle;
}
```

**Comment by maeishoj** [comment]
That's great! thanks a bunch!
