### ISSUE TITLE
How to implement drill-down

### ISSUE THREAD

**Issue by David-Hari** [chartist-js/chartist#613]
Hi,

I have a bar chart, and I'd like to implement "drill-down" functionality, where clicking on a column shows more data related to that column.

For example,
Initial chart shows total stats for a bunch of people (axis x = person, axis y = number). Then you click on the column of, say, Bob, and it shows a break-down of those stats for Bob (axis x = category, axis y = number).

To do this, I'm thinking that I would need to store additional information for each bar, so that when I click it I can use that information to determine what data to update the chart with. But I'm not sure how to set the specific data for each bar.
Any ideas?

thanks

**Comment by gionkunz** [comment]
Search for "meta" here on github, youll find plenty of examples.

**Comment by David-Hari** [comment]
I found one example in "example-plugin-tooltip.js", but nothing on the [Examples](https://gionkunz.github.io/chartist-js/examples.html) page.
But thanks, that does seems to be what I need.

**Comment by David-Hari** [comment]
Oh, one other thing. How would I go about accessing that meta-data from a "click" event?

Currently I'm listening to the "draw" event and then attaching a click event handler on each node and using the data provided in the event:

``` javascript
chart.on('draw', function(event) {
    if (event.type === 'bar') {
        $(event.element._node).on('click', function() {
            // Either use event.index to determine what column was clicked, or use event.meta to access the meta-data
        });
    }
});
```

Is there a way where I don't have to use the "draw" event? As far as I know, the svg elements don't have direct access to the "meta" property.

**Comment by gionkunz** [comment]
Hi. I'd use delegation to add a click handler. This way you don't need to use the draw events: The meta attribute on values can also contain complex object where Chartist will then serialize the data onto the attribute. You can then use `Chartist.deserialize` to read the data from the attribute.

Check this bin for an example: http://jsbin.com/pabigi/edit?html,js,output

**Comment by David-Hari** [comment]
Ok, so the attribute is stored on the element. Great!
