### ISSUE TITLE
Adding a border to ct-grids

### ISSUE THREAD

**Issue by KeralPatel** [chartist-js/chartist#618]
Hello,

I am trying to add a border to the ct-grids

As you can see here : http://s14.postimg.org/tr5tdzb8x/chartist.jpg

It isn't working :(

Any other way to add a border around that area.

Thanks :)

**Comment by gionkunz** [comment]
Hi there. SVG elements cant have border. Usually you talk about strokes on SVG paths. However, group elements like the ct-grids element, can't have fills and strokes. You will need to create your own element using events. This is very easy to do: http://jsbin.com/kakixe/edit?html,js,output

**Comment by gionkunz** [comment]
Please reopen if you're not ok with the solution outlined in the bin.
