### ISSUE TITLE
CSP review and implement changes

### ISSUE THREAD

**Issue by craigfrancis** [chartist-js/chartist#620]
Related to Issue #619:

https://github.com/gionkunz/chartist-js/blob/develop/dist/chartist.js#L913

```
if(useForeignObject) {
  // We need to set width and height explicitly to px as span will not expand with width and height being
  // 100% in all browsers
  var content = '<span class="' + classes.join(' ') + '" style="' +
    axis.units.len + ': ' + Math.round(positionalData[axis.units.len]) + 'px; ' +
    axis.counterUnits.len + ': ' + Math.round(positionalData[axis.counterUnits.len]) + 'px">' +
    labels[index] + '</span>';

  labelElement = group.foreignObject(content, Chartist.extend({
    style: 'overflow: visible;'
  }, positionalData));
} else {
  labelElement = group.elem('text', positionalData, classes.join(' ')).text(labels[index]);
}
```

Can we remove the two `style` attributes?

Ideally the width, height, and overflow would be set directly, rather than relying on the HTML/CSS parsing :-)

That said, if you could use `document.createElement('span')`, `.setAttribute('class', ...)`, and `.textContent`, then that really would be magic (tedious to do with an existing code base, but it really helps the security, and sometimes even the performance).

**Comment by gionkunz** [comment]
Same problem here as relying on percentage inside of foreignObjects is an issue for some browsers. Can you open a generic issue for this and #614 to cover both? We can work on that then to identify all issues and find a way to support proper CSP.

**Comment by gionkunz** [comment]
As far as element creating is concerned I believe since Chartist.Svg now also supports rendering of plain HTML elements, we should be able to use it for the element creation so we won't need the content attribute anymore. We still need to investigate though.

**Comment by craigfrancis** [comment]
Hi @gionkunz, not sure what you mean by opening a generic issue? you might be best to do this, as I'm not really familiar with this project (I was just doing some debug, and I really should be getting back to work).

**Comment by gionkunz** [comment]
Well this is an open-source project so everyone is subject to contribute ;-) Thanks for your efforts so far. Let's see where this fits in.
