### ISSUE TITLE
labelInterpolationFnc changed/broken for 0.96

### ISSUE THREAD

**Issue by rstudner** [chartist-js/chartist#621]
For 0.95 and prior I'd do this:

```
    const divider = Math.floor(processedChartData.labels.length / 5);
.
.
.
      axisX: {
        labelInterpolationFnc: function skipLabels(value, index) {
          return index % divider === 0 ? value : null;
        },
      },
```

This would allow me to skip xAxis labels so they wouldn't be insanely over crowded.

Now, this will put the string "null" for every place that in the past, was skipped:
![screen shot 2016-02-22 at 8 52 11 am](https://cloud.githubusercontent.com/assets/209970/13220327/a287aee6-d943-11e5-9545-9b8a3ee1a7c4.png)

**Comment by gionkunz** [comment]
Okay, this is a bug that was introduced with b7c16ddeb7dcbbba8cc253725c9751dcb4e90a4e . I'll do a quick fix and publish 0.9.7
