### ISSUE TITLE
Wrong alignment of bars when using FixedScaleAxis in Bar chart

### ISSUE THREAD

**Issue by psalaberria002** [chartist-js/chartist#624]
Hi. 
I am not sure if this is a known issue, but when I try to use FixedScaleAxis in the X axis in a Bar chart I get a weird alignment of the bars. The first bar is shown on top of the Y axis, and the last bar is shown at the end. Labels are not aligned with the bars.

 <img width="778" alt="captura de pantalla 2016-02-26 a las 10 23 15" src="https://cloud.githubusercontent.com/assets/2410564/13348332/23f42c48-dc73-11e5-8ca0-67717eda1a3f.png">

```
new Chartist.Bar('.ct-chart', {
  series: [
    [{x:1,y:2}, {x:2,y:2}, {x:3,y:2}, {x:4,y:2}],
    [{x:1,y:2}, {x:2,y:2}, {x:3,y:2}, {x:4,y:2}],
    [{x:1,y:2}, {x:2,y:2}, {x:3,y:2}, {x:4,y:1}]
  ]
}, {
  axisX: {type: Chartist.FixedScaleAxis,
         ticks: [1,2,3]},
  stackBars: true
});
```

Have you seen this before? Any solution?

Thank you.

**Comment by psalaberria002** [comment]
I found a workaround.

Instead of using the FixedScaleAxis I use the default one, and use the labelInterpolationFnc to decide which ticks to show. I also needed the labels array in order to fetch the labels in the interpolation function.

```
new Chartist.Bar('.ct-chart', {
  labels: [1,2,3,4],
  series: [
    [{x:1,y:2}, {x:2,y:2}, {x:3,y:2}, {x:4,y:2}],
    [{x:1,y:2}, {x:2,y:2}, {x:3,y:2}, {x:4,y:2}],
    [{x:1,y:2}, {x:2,y:2}, {x:3,y:2}, {x:4,y:1}]
  ]
}, {
  axisX: {labelInterpolationFnc: function(d,ind){
                                   if((ind % 2) == 0) return d;
                                   else return null;
                                  }},
  stackBars: true
});
```

I still think the issue should not be closed.

**Comment by gionkunz** [comment]
Hi there. Well, the fixed axis is not really suited very well for bar charts. Bar charts are usually step based so the `Chartist.StepAxis` is actually the one that fits most for Bar charts. FixedScaleAxis is useful if you need to project on the axis with very granular control. The problem with bar charts is that they look weird if there's a bar siting at the first grid line and on the last one. However, that's how the fixed scale axis work. If you still need to use the `FixedScaleAxis` for your bar chart for some reason, you could work with the low and high values to simulate a gap at the start and end. Also you can override the default bar chart label sytels that center the labels. Check out this bin: http://jsbin.com/xigoya/edit?css,js,output

**Comment by psalaberria002** [comment]
Nice! Thank you for the great explanation.
