### ISSUE TITLE
Monotone cubic interpolation

### ISSUE THREAD

**Issue by ammojamo** [chartist-js/chartist#626]
This is related to line smoothing issues already discussed at #92 and #155.

I've just implemented Monotone Cubic Interpolation for Chartist, using the Fritsch-Carlson method, based on this math.stachexchange post: http://math.stackexchange.com/questions/45218/implementation-of-monotone-cubic-interpolation

The main problem I was trying to solve was where the extrema of the fitted curve lie beyond the extrema of the original data points. This is particularly bad when the curve dips below zero for a quantity that is inherently non-negative, e.g. number of units sold.

Results are pretty promising - unlike 'simple' interpolation it doesn't put artificial kinks into the curve, whilst still preserving monotonicity of the original data points.

<img width="1312" alt="monotonecubic" src="https://cloud.githubusercontent.com/assets/89878/13383119/6967f4aa-ded8-11e5-8bb6-963ef26f7e78.png">

Would you like me to submit a PR?

**Comment by gionkunz** [comment]
Hey there. Thanks for your contribution! Yes, sure. I would love to see that PR :-)

**Comment by farnabaz** [comment]
@ammojamo @gionkunz  It will be great if you rebuild in order to update library, by now this PR only applied in source of library

**Comment by gionkunz** [comment]
Hi sorry thats my fault. Ill publish a release the upcoming week.
