### ISSUE TITLE
Support for Custom Pie Chart Shapes

### ISSUE THREAD

**Issue by ryanjwilke** [chartist-js/chartist#628]
This isn't a bug, but could theoretically be a feature request I suppose. With that said, I'm curious if Chartist supports custom pie charts shapes? I'm trying to look into a few good options for implementing a pie chart design like this, but I'm guessing I'll likely have to do some form of masking over the top of a circular pie chart or another custom solution that I'd have to create. I'm already using Chartist so I figured I'd ask in case there's something I might be missing in the documentation.

![screen shot 2016-02-29 at 11 32 25 am](https://cloud.githubusercontent.com/assets/211597/13404741/62a9583e-ded8-11e5-8137-ed6e105eeb0a.png)

**Comment by gionkunz** [comment]
Plugins could do this in the future when we're implementing #810
