### ISSUE TITLE
Line chart line goes under chart

### ISSUE THREAD

**Issue by lesnyrysiek** [chartist-js/chartist#631]
There's  a problem with charts with spiking information. On sudden high values in the middle of the chart it draws a negative value line between two zero-values near the high values.
![chart](https://cloud.githubusercontent.com/assets/1105392/13457185/1e8f77d8-e067-11e5-89f5-62c2e96f4dc4.png)

**Comment by gionkunz** [comment]
Hi There, cardinal spline interpolation causes some artifacts on peeks. You can use simple interpolation as an alternative. Check out http://gionkunz.github.io/chartist-js/examples.html#example-line-simple-smoothing

**Comment by lesnyrysiek** [comment]
That worked, thanks!
