### ISSUE TITLE
Charts series colours and legends

### ISSUE THREAD

**Issue by ghost** [chartist-js/chartist#632]
Hi,
I have a html page where I have 4 charts and each chart' series should have a completely different colour. I haven't found the way to do it and couldn't find a solution online.

Can anyone please help me with this issue?

Thanks,
Ignacio

**Comment by gionkunz** [comment]
Hi there. Have you read this article? http://gionkunz.github.io/chartist-js/getting-started.html#colour-up-your-charts

**Comment by ghost** [comment]
Yep, it worked. thanks!
