### ISSUE TITLE
Charts have zero width/height in Pale Moon

### ISSUE THREAD

**Issue by David-Hari** [chartist-js/chartist#634]
![Zero size](http://s24.postimg.org/cxqc75uzp/zero_size.png)

Was working fine up until a few weeks ago.

I reported it at the [PM forums](https://forum.palemoon.org/viewtopic.php?p=79561#p79550), thinking it was likely a problem with their rendering engine. But it might be worth you having a look in case there is a work-around, or perhaps your current implementation isn't as robust as it could be.

I remember seeing another issue here where you mentioned a width/height hack for an older version of Firefox. Could be a related issue (as Pale Moon is related to Firefox).

**Comment by derekblank** [comment]
@David-Hari: I noticed this identical issue when testing older versions of Firefox (dating back to at least version 32.0.2) with the latest version of Chartist (0.9.7). Upgrading to the latest version of Firefox (45.0.1 ) resolved the issue immediately, which might suggest that this is an issue with PaleMoon rendering.

**Comment by David-Hari** [comment]
Ok, good to know. Hopefully Pale Moon will fix the issue soon.

**Comment by gionkunz** [comment]
Closing becauase of inactivity
