### ISSUE TITLE
Coloring area between two series

### ISSUE THREAD

**Issue by ShahnavazKazi** [chartist-js/chartist#635]
Hi, 

Is it possible to build up a chart something as shown below using Chartist? Also, is it possible to show labels at given point with a pointed arrow (i.e. 150%, 180%) and highlight a particular point for ex. a red dot in below image?

![area_chart](https://cloud.githubusercontent.com/assets/16203293/13570028/bc1e7368-e491-11e5-8d3d-bd8cd5d303e0.jpg)

Thanks, 
Shahnavaz

**Comment by gionkunz** [comment]
This is currently not possible and was already discussed here #283 and here #322 . I'm closing this issue as duplicate.
