### ISSUE TITLE
Bar chart distributeSeries 

### ISSUE THREAD

**Issue by dsburny** [chartist-js/chartist#638]
I have a test chart:
`<div class="col-lg-6">
                <h4>Test</h4>
                <div class="chart">
                    <div class="ct-chart ct-major-twelfth" id="test"></div>
                </div>
            </div>`

JQuery:

`new Chartist.Bar('#test', {
                        labels: ['XS', 'S', 'M', 'L'],
                        series: [20, 60, 120, 200]
                    }, {
                        distributeSeries: true
                    });`

But all I get displayed is the blank grid with labels displayed. If I change it to:
`new Chartist.Bar('#test', {
                        labels: ['XS', 'S', 'M', 'L'],
                        series: [[20, 60, 120, 200]]
                    });`
The grid is displayed, but I want the bars to be different colours.
There are no errors in the developer toolbar. Any ideas what the issue would be?

Thanks

**Comment by gionkunz** [comment]
Sorry I never replied to this, please re-open if still needed

**Comment by ghost** [comment]
I have the same problem, any help would be appreciated

**Comment by karneaud** [comment]
+1 I also am encountering this problem specifically with bar chart using **distributeSeries** set to true. 

Did you guys manage to fix this @albaker2007  @dsburny ?

**Comment by karneaud** [comment]
Ok after doing some research I came across this https://github.com/gionkunz/chartist-js/commit/b449c87673f3735cb2a176a6de5aa0c2f0f11d15 which suggest that distributeSeries cannot be used with multiple series data
