### ISSUE TITLE
Major and minor grid lines

### ISSUE THREAD

**Issue by duggi** [chartist-js/chartist#641]
I'm looking to make minor lines in my grid, like so:
(i've searched all the issues with no luck)

![image](https://cloud.githubusercontent.com/assets/370924/13853126/895d4844-ec22-11e5-9e7f-156e3def0e7b.png)

**Comment by jacobq** [comment]
This is a feature that I'd like as well (especially with log scaling). I'm new to this codebase but will submit a PR for this if time permits.

**Comment by gionkunz** [comment]
Major / minor grid lines can be achieved easily using a plugin. I've written a very simple plugin to achieve this.

http://jsbin.com/yemomu/edit?js,output

Just include the plugin function within your project and add the plugin to Chartist as shown in the bin.

**Comment by gionkunz** [comment]
Closing becauase of inactivity
