### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelectorAll' of null

### ISSUE THREAD

**Issue by nr007** [chartist-js/chartist#646]
Hello,

i have a problem when trying to use chartist class createSvg. I use lib like so: 

`
    chartConfig.chart18 = new Chartist.Line('#chart18', {
        labels: ['2008', '2009', '2010', '2011', '2013', '2013', '2014', "Q1'15"],
        series: [
            [0.3, 0.3, 0.4, 0.8, 1.6, 2.3, 2.6, 2.9]
        ]
    }, {
        axisX: {
            showGrid: false,
            offset: 50,
        },
        axisY: {
            scaleMinSpace: 50,
            labelInterpolationFnc: function(value) {
                return value.toString().charAt(0) + 'h/day';
            }
        },
        lineSmooth: false,
        low: 0,
        high:6,
        divisor: 4
    }, [
        ['screen and (max-width: 767px)', {
            height: '280px',
            chartPadding: {
                top: 50
            }
        }]
    ]).on('created', function(context) {
        context.svg.querySelectorAll('.ct-series').attr({
            'transform': 'translate(' + context.axisX.stepLength / 2 + ')'
        });
        addTooltip('#chart18', ' h/day');
    }).on('draw', function(data) {
        lineChartPlugin(data);
    });`

So after debugging i found out that container i provide in above function is null when triggering chartist.js lib function createSvg. Any ideas?

**Comment by DatScreamer** [comment]
Same console error, using with CDN.

**Comment by gionkunz** [comment]
This happens when Chartist can't find an Element with the selector provided at the time of the function call. The error could be more descriptive which would fall into #811
