### ISSUE TITLE
Donut Chart is not Displaying correctly.

### ISSUE THREAD

**Issue by SaadYasir** [chartist-js/chartist#648]
Donut Chart is not Displaying correctly. Upon changing the size of screen it shows correctly. 
![image](https://cloud.githubusercontent.com/assets/4014715/14017363/4b424368-f19d-11e5-9953-777cf2bed8c1.png)

**Comment by dmdevoss** [comment]
This is happening to me too, as soon as I updated to 9.7,after reverting back it's working for me again.

**Comment by hansmaad** [comment]
@dmdevoss @SaadYasir Can you please post how you create this chart. Could you prepare an example that shows this behaviour?

**Comment by SaadYasir** [comment]
@hansmaad  I am using NativeDroid2 JS Library for mobile development. 
Here is link: http://nativedroid.scripter.click/charts/
1. This happens when we are using one page theme. 
2. When populating values of chart from API ( Web services). 

My tweaks: To overcome this problem:
$(document).ready(function() { 
$("#loadinggraph").text('Loading Graph....');
$('.nd2-chart').hide();
$('.nd2-chart').delay(3000).queue(function() {
    $("#loadinggraph").hide();
    showgraph();
    $('.nd2-chart').show();
    $('.nd2-chart').dequeue();
 }); 

});

**Comment by gionkunz** [comment]
Whats the status of this issue?

**Comment by dmdevoss** [comment]
I moved to a different library so I don't have the specifics of what I did, but to make things work I needed to set heights on the svg pieces.
