### ISSUE TITLE
Proposed fix for blurred grid lines

### ISSUE THREAD

**Issue by MightyPork** [chartist-js/chartist#650]
Sorry for not making a PR, but I couldn't get grunt working so couldn't test it anyway - and honestly, I'm too lazy. You'll patch it quickly manually:

``` js
  Chartist.createGrid = function(position, index, axis, offset, length, group, classes, eventEmitter) {
    var positionalData = {};
    positionalData[axis.units.pos + '1'] = Math.round(position)+0.5; // EDITED: fix blurred grid
    positionalData[axis.units.pos + '2'] = Math.round(position)+0.5; // EDITED: fix blurred grid
```

(this "patch" is against the latest release dist)

If you round the value and add 0.5, the grid won't be blurred in Chrome. 
It's blurred in all the examples, but even worse looking if you have it white on black.

Compare:

![screenshot_2016-03-27_21-13-28](https://cloud.githubusercontent.com/assets/2041118/14067244/c96bcff0-f460-11e5-81ee-1b1648e87238.png)

![screenshot_2016-03-27_21-13-13](https://cloud.githubusercontent.com/assets/2041118/14067243/c72dbdc0-f460-11e5-9782-dad584124dd4.png)

**Comment by gionkunz** [comment]
We've decided to go with `shape-rendering: crispedges;` since this is up to the rendering engine how to handle it. What happens if the grid line is 2px or any other even number? Using the CSS approach, we can fix it in the rendering engine.
