### ISSUE TITLE
Is that possible to specify responsiveOptions in plugin option? 

### ISSUE THREAD

**Issue by moroshko** [chartist-js/chartist#651]
My plugin configuration requires a knowledge of window width. For example:

When window width is larger than 767px, I'd like to have:

``` js
Chartist.plugins.ctAxisTitle({
  axisX: {
    offset: {
      x: 300
    }
  }
})
```

But, when window width is between 510px and 767px, I'd like to have:

``` js
Chartist.plugins.ctAxisTitle({
  axisX: {
    offset: {
      x: 200
    }
  }
})
```

I tried to specify `responsiveOptions` in `options.plugins`, but it didn't work.

Is there a way to unregister the plugin and then register it again with the new options when window width changes?

What's the best way to go about this?

**Comment by gionkunz** [comment]
That's possible for sure. With the repsonsive settings overrides you can put your plugin configuration. Check some examples on the site for this.
