### ISSUE TITLE
How to update plugins with chart.update()?

### ISSUE THREAD

**Issue by moroshko** [chartist-js/chartist#652]
I'm calling `chart.update` with an updated version of `options.plugins`, and I expect the plugin function to be called again. But, unfortunately, it's not called.
Is there a way to call the plugin function again after it has been called for the first time?

**Comment by SarasArya** [comment]
Hey somebody solved it... See [here](http://stackoverflow.com/questions/36494308/javascript-how-to-return-a-function-every-time-i-update-some-value)

**Comment by gionkunz** [comment]
This is fixed.
