### ISSUE TITLE
Create stacked-bar, grouped charts in chartist js

### ISSUE THREAD

**Issue by SarasArya** [chartist-js/chartist#653]
Hi @gionkunz Nice work with chartist.js I love it. Except for 1 scenario.Chartist seems to adapt to all. 
The issue is I don't know if it's possible in chartist to create grouped stack bars. The use case I need to show is, useful time and idle time for workers. And Number of workers are grouped on a date. Like if I select Worker 1, Worker 2, Worker 3 . I want to know what was their comparative efficiency on let's say 27th March 2016. In this case I can should useful time and idle time on a scale of 0 to 100 in a stacked manner. like 65% is useful and 100 - 65 i.e. 35 is time wasted. 

I need to implement this and I can't find the solution to it. Could you help in telling if it's possible and if yes then how? and if no then can it be taken as a enhancement in the next release probably ?

**Comment by gionkunz** [comment]
Sorry I never replied to this, please re-open if still needed

**Comment by petref** [comment]
Please have a look at this enhancement, as it is requested an multiple threads ...  Thank you
