### ISSUE TITLE
Is there a way to get the Chartist object from the DOM...

### ISSUE THREAD

**Issue by kcecireyes** [chartist-js/chartist#655]
...once the chart has been drawn? i.e. get back the data and options from the svg element?

I was looking into Chartist.Svg.root() but that may not be it...

Thank you!

**Comment by cheese83** [comment]
It's set as a property of the svg element's container, e.g. `svg.parentNode.__chartist__`

**Comment by gionkunz** [comment]
That's right: 

``` javascript
document.querySelector('.chart-container').__chartist__
```

**Comment by pmpinto** [comment]
This `__chartist__` object is not exactly the same as what's returned when creating a new chart.
I need to animate a chart on a callback function and I'll need the instance of a chart for that.

For instance, this `__chartist__` object doesn't contain any `path`, `index` or `chartRect` properties.

Is there a way to get the actual instance from a DOM element?

EDIT: Correction! What I needed was the `data` object coming from the `draw` event of a chart. Doing a workaround right now, please ignore this 👍

**Comment by 1pavanb** [comment]
Hey @pmpinto did you get it working?
I need the exact same thing

Edit: Nevermind, got it. My usecase was adding an onClick and updating bar properties in it.
I just stored the data from draw function and used that data array to update properties.
