### ISSUE TITLE
Labels for months, data for days

### ISSUE THREAD

**Issue by benjaminallison** [chartist-js/chartist#657]
I'm attempting to do a line graph where my data points are in days, but the labels are in months. Now, I know about using labelInterpolationFnc to remove labels every nth position, but I'm looking for something a little more elegant.

Months have differing numbers of days, so it feels hacky to remove labels every so often. And ideally, the label should span the width of the entire month (for styling purposes).

Is there a way to achieve this?

**Comment by gionkunz** [comment]
You should switch to use `FixedScaleAxis` for these requirements. Take a look at this doc section: http://gionkunz.github.io/chartist-js/getting-started.html#switching-axis-type

And maybe this example: http://jsbin.com/lokozu/edit?html,css,js,output

**Comment by gionkunz** [comment]
Please re-open if needed
