### ISSUE TITLE
Legend and charts

### ISSUE THREAD

**Issue by biapar** [chartist-js/chartist#659]
How to add a legend for a pie chart?

**Comment by SarasArya** [comment]
I think there is a plugin for that. [chartist-plugin-legend](https://github.com/CodeYellowBV/chartist-plugin-legend). You could try that...

**Comment by biapar** [comment]
Hi, I tried it, but chart give an error when there is that plugin. How to use ( I read the readme before -:) )? Have you an example?

**Comment by SarasArya** [comment]
yeah.. I built one... Let me put up a github repository link

**Comment by biapar** [comment]
k

2016-04-06 16:17 GMT+02:00 Saras Arya notifications@github.com:

> yeah.. I built one... Let me put up a github repository link
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/gionkunz/chartist-js/issues/659#issuecomment-206392146

## 

_Cordiali Saluti / Best RegardsIng. Biagio Paruolo_

_Red Consulting s.a.s_

Via Garibaldi, 1/B - 83025 Montoro Inferiore ( AV ) - Italy

Tel: +39 3928196008 Fax: +39 36 3928196008

Web:  www.redconsulting.it

Email: biapar@redconsulting.it /  SkyPe: biagioparuolo  / Linkedin:
it.linkedin.com/in/biagioparuolo/

Microsoft Partner | Web, E-commerce and Mobile Solutions | Register Gold
Reseller | OVH Partner

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are
addressed. If you have received this email in error please notify the
system manager.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. If you are not the intended recipient
you are notified that disclosing, copying, distributing or taking any
action in reliance on the contents of this information is strictly
prohibited.

**Comment by SarasArya** [comment]
[There](https://github.com/SarasArya/Chartist-Legend-Example) you go... :)

**Comment by biapar** [comment]
Ok.. Thank you very much. I'll try asap.

**Comment by gionkunz** [comment]
Thanks guys for sorting this out
