### ISSUE TITLE
Curved line but no desired

### ISSUE THREAD

**Issue by kevincaradant** [chartist-js/chartist#66]
Hi there ,

I would like to have straight lines between each points. i took a screen capture of my problem.

![pb2](https://cloud.githubusercontent.com/assets/6093175/4606459/59599164-521f-11e4-8c43-46ea73abe7d5.PNG)

Is that possible ? thanks

**Comment by SekibOmazic** [comment]
Just put "lineSmooth": false in your chart options.

**Comment by kevincaradant** [comment]
Sorry about that , i'm confused because i tried to put that line but it was into the "axisY" ...

Thanks :).

**Comment by gionkunz** [comment]
That's the setting you should go for! :-) thanks @SekibOmazic !

**Comment by viswanathmantri** [comment]
Hi my Chartist number of curves is limited to 3 curves, How can i increase it to n number of curves in a Graph Chart
