### ISSUE TITLE
Axistitle plugin doesn't change on drop down option change.

### ISSUE THREAD

**Issue by SarasArya** [chartist-js/chartist#661]
Whenever I change the chart data I want to, update my plugins as well. One such plugin I want to update is `chartist-plugin-axistitle`. Now the issue is there is a `created` event in chartist but not an update event. So the axistitle plugin creates a axistitle when the chart is created, but no provision to update it. 
The issue is caused by this line. 
 `chart.on('created', function (data) {
});`

How do I call some update event so that I can update the axis title?

**Comment by gionkunz** [comment]
You should use the `data` event instead of the `created` event. It will be emitted in two fashions initial and update. Check https://github.com/gionkunz/chartist-js/blob/796992d0f83a54c7d38c739bfe2499a08215cf01/src/scripts/base.js

**Comment by SarasArya** [comment]
@gionkunz when the event `created` is called it has these fields. `axisX`,`axisY`,`bounds`,`chartRect` and most importantly `options`. When `data` event is fired. Only data object `labels` and `series` are provided and not updated options. How do I check if options field was updated?

**Comment by SarasArya** [comment]
@gionkunz does any plugin have an update function which I could see for an example, as far as I am concerned I downloaded around seven to eight plugin, none of them have any update code... The issue I am facing is with this line. 

```
 options = Chartist.extend({}, defaultOptions, options);  
     return function ctPointLabels(chart) {
     });
```

Whenever I update an option. The options are updated in line 1, which is seen on the console,  but the function. Which returns values once, doesn't operate on updated options. Also, the issue I mentioned above. the data event tracks changes in data not in options...  There seems to be a event called `optionsChanged` written for that specific purpose. But somehow on change of options it's not firing... Please help

**Comment by gionkunz** [comment]
There is an open issue with the `optionsChanged` event since version 0.7.3. It should be fixed with https://github.com/gionkunz/chartist-js/commit/537ec25d550c8827851adbecbc68f60b9311c46f and come in the next release which is up for this weekend.

**Comment by SarasArya** [comment]
Hey @gionkunz I figured out the error. [This](http://stackoverflow.com/questions/36494308/javascript-how-to-return-a-function-every-time-i-update-some-value) fixes it... Is it the right thing to do?? I have also raised an issue [#76](https://github.com/paradox41/angular-chartist.js/issues/76) here. This fixes it... But I feel it's more of a hack, then an actual solution. Would like your views on that

**Comment by SarasArya** [comment]
Hey, I just had an another look at the solution I suggested. It would break many modules, Like it does [here](http://plnkr.co/edit/vrdqN0pbdConkZXYKewl?p=preview) I have also reported this to @paradox41  so I wouldn't suggest it... Will wait for the next release and see if it fixes the issue... Then probably take a call on it..

**Comment by SarasArya** [comment]
@gionkunz When is the 0.9.8 release?? I am just following up as you said it will be released by this weekend... 
Regards

**Comment by gionkunz** [comment]
@SarasArya this is now fixed in the current release, I'm therefore closing this issue.
