### ISSUE TITLE
Feature request: secondary axis support

### ISSUE THREAD

**Issue by jacobq** [chartist-js/chartist#663]
For line charts, we frequently need to be able to plot some multiple series on a LineChart where some of the series use a secondary vertical axis. (e.g. https://support.office.com/en-us/article/add-or-remove-a-secondary-axis-in-a-chart-91da1e2f-5db1-41e9-8908-e1a2e14dd5a9 ) This doesn't appear to be supported with Chartist and I'm not sure whether or not this would be possible to do with a plugin. Has anyone else attempted this? What approach did you use?

As a hack for my demo I am transforming the data for the series that should be associated with the secondary axis so that it aligns with the primary one, but obviously this is not a good solution.

**Comment by jacobq** [comment]
Just realized this is a duplicate of #60 (didn't use the same name for this so didn't see it when I searched). If you want to close it in favor of that one that's OK with me, but I think this is a separate feature. In all of my use cases it would be applying to charts of the same type (e.g. all line/scatter data, just some series using alternate vertical scaling.)

**Comment by gionkunz** [comment]
Closing this in favor of #37
