### ISSUE TITLE
Axis label question

### ISSUE THREAD

**Issue by jiiins** [chartist-js/chartist#665]
Sorry for the lame title, it's not an issue per se. I'm using princexml to generate pdfs from html and unfortunately it still doesn't support <foreignObject>, so a line chart gets printed without axis labels (in contrast, the labels in pie charts print fine).

Is there any way to generate the labels differently?

**Comment by gionkunz** [comment]
Hi sorry for the late reply. You can disable foreignObject labels with the following code snippet:

``` javascript
var chart = new Chartist.Line('#chart', {
  labels: ...
  series: ...
});

chart.supportsForeignObject = false;
```
