### ISSUE TITLE
Values on charts

### ISSUE THREAD

**Issue by Aldegunde** [chartist-js/chartist#666]
Hi Gion, 

there is any way how to show values on the charts? I just saw how to show labels but not sure how can I do the same for values on pie and bars.

Thanks in advance.

**Comment by Aldegunde** [comment]
I saw it is possible to show values if I declare them as labels but I would love the option to place both info if it is possible, :). Thanks.

**Comment by gionkunz** [comment]
Sorry I never replied to this, please re-open if still needed

**Comment by marksq** [comment]
Hello! I need the solution too.
