### ISSUE TITLE
[Line Chart] FullWidth with one label throws javascript errors

### ISSUE THREAD

**Issue by osbornm** [chartist-js/chartist#667]
If you have a line chart that has only one point of data, think a new users, and thus only has one label and you have set the `fullWidth` options you calculations with result in `NaN` and thus throw several javaScript errors. 

```
new Chartist.Line('.ct-chart', {
  labels: ['my Label'],
  series: [
    [55]
  ]
}, {
  fullWidth: true
});

```

**Comment by jmlavoier** [comment]
This error was fixed in this PR
https://github.com/gionkunz/chartist-js/pull/800
