### ISSUE TITLE
How to change font size and color on chart?

### ISSUE THREAD

**Issue by balintfarago** [chartist-js/chartist#670]
The font size on the charts are to small and hard to read on certain colors. Is there a way to change these attributes?

I can do this do make the whole pie red but setting color or font-size doesn't make a change:

```
.ct-series-x .ct-slice-pie {
    fill: #f05b4f
}

<div class="ct-chart ct-golden-section ct-series-x ct-slice-pie" id="chart2"></div>
```

**Comment by cheese83** [comment]
If you look in chartist.css, you can see that the only class that has a `font-size` specified is `.ct-label`. You'll have to override that if you want to set the size and colour.

**Comment by gionkunz** [comment]
Yup, general approach of chartist is to use CSS for styling.

**Comment by illogicalextend** [comment]
I got stuck on this. Remember CSS priority and to import your custom stylesheet after the chartist one.
