### ISSUE TITLE
2 instance of stacked bar graph

### ISSUE THREAD

**Issue by gnvsuneetha** [chartist-js/chartist#672]
Hi,

Is it possible to have 2 stacked bars next to each other? Some thing like in attached image.

Thanks in advance.

Suneetha

<img width="507" alt="screen shot 2016-04-14 at 1 42 21 pm" src="https://cloud.githubusercontent.com/assets/18036376/14542981/c0118a5a-0246-11e6-8cee-cea31ccbfbaa.png">

**Comment by tedbreen** [comment]
I would also like this feature. It seems like one solution would be to generate two charts, superimpose one on top of the other, and shift one of them over one bar-width so they don't overlap.

**Comment by gionkunz** [comment]
I'd draw two charts where one hides the yAxis labels
