### ISSUE TITLE
Add custom label to Pie chart

### ISSUE THREAD

**Issue by middledeveloper** [chartist-js/chartist#673]
Hello! Help me to add a custom label please? It must be near the end of green part of chart.
I need to post some text information in _yellow_ place (not name, not value).. Is it possible?

![234](https://cloud.githubusercontent.com/assets/16412379/14558366/2191da9c-0313-11e6-98de-7ac681df08a7.PNG)

**Comment by gionkunz** [comment]
Check this plugin idea: http://jsbin.com/huroho/3/edit?html,css,js,output

**Comment by middledeveloper** [comment]
Thank you!
