### ISSUE TITLE
Write inside the donut chart

### ISSUE THREAD

**Issue by MariusGarbea** [chartist-js/chartist#674]
I want to write something inside the donut chart. I came with an unorthodox solution and I am sure that there is something better out there (basically added a 0 value to series and labeled it). http://codepen.io/ananasqwer/full/ZWreyE/

I would also like to display only the label inside the donut chart. Thanks!

**Comment by joshiste** [comment]
My approach to this problem is to add a centered `div` behind the svg with the same extents as the donut (cause I needed wrapped text and this is a bit tedious with svg). The text even get updated when hovering over the slices.

**Comment by gionkunz** [comment]
Duplicate of #255
