### ISSUE TITLE
3 axis chart

### ISSUE THREAD

**Issue by ghost** [chartist-js/chartist#676]
First, I would like to thank you, chartist is amazing!, you've done a great work!

I have been trying to create a chart with 3 axis (left, bottom and right). Is there any way to do this with chartist?, I couldn't find a solution for this, and I don't know whether this is a bug or an improvement for you guys.

Thanks again for taking the time to read it,
Ignacio

**Comment by gionkunz** [comment]
This will be possible with Chartist 1.0 see #37

**Comment by ghost** [comment]
Thanks for coming back.
Have you got any idea of when Chartist 1.0 will be released?

**Comment by gionkunz** [comment]
I'm right now working on a rough project plan https://github.com/gionkunz/chartist-js/projects/1 I think the goal is early 2017.
