### ISSUE TITLE
Pie chart animation (not donut)

### ISSUE THREAD

**Issue by daon** [chartist-js/chartist#677]
Hi, I'm trying to animate the pie chart but without any luck. I tried the [donut animation example](https://gionkunz.github.io/chartist-js/examples.html#example-donut-animation) on the chartist homepage with the donut option set to _false_ but it just render directly. Any suggestions how to solve this?

Thanks
/Dan

**Comment by gionkunz** [comment]
Animating an arc is not possible with SVG unfortunately, without using a custom JavaScript animation library.

**Comment by daon** [comment]
Ah I see. Thanks for the fast response anyway.

**Comment by orest22** [comment]
@gionkunz Hi! Could you suggest one that works nice with chartist?
