### ISSUE TITLE
labelDirection undocumented

### ISSUE THREAD

**Issue by gsnedders** [chartist-js/chartist#678]
`labelDirection` appears in one of the examples for `Chartist.Pie`, but isn't otherwise defined. Would be nice to document what values it can take, for example.

**Comment by gionkunz** [comment]
Yeah, well it's actually hidden in the default options within the API docs: http://gionkunz.github.io/chartist-js/api-documentation.html#chartistpie-declaration-defaultoptions

We need to work on our documentation structure. See #565

**Comment by gionkunz** [comment]
Closing in favor of #565
