### ISSUE TITLE
Chart padding?

### ISSUE THREAD

**Issue by samdoidge** [chartist-js/chartist#679]
Hi guys, can anyone tell me of anyway to add 'padding' between the blue line at the top, and the end of my grid? [Screenshot](https://raw.githubusercontent.com/samdoidge/issues/master/chartist.png)

chartPadding property looks like it is for the whole chart, not for the data within the grid.

Thanks

**Comment by gionkunz** [comment]
You can use a custom `high` configuration on the axis: http://jsbin.com/giqoya/edit?js,output

Depending on your use case this will be difficult if you don't know the data that comes into your chart. Also the AutoScaleAxis is creating the range based on order of magnitude calculation. You should probably look into the fixed scale axis: http://gionkunz.github.io/chartist-js/getting-started.html#switching-axis-type

**Comment by samdoidge** [comment]
Thanks @gionkunz. I can parse the data before putting into the chart to determine the max value I will need, and increase this by a small percentage.

The X axis is logging dates, is the AutoScaleAxis causing them to record multiple days in the middle versus the edges? I was generally happy with the appearance at the moment, but the range of time covered will be increasing.

Thanks for your work on the library - it best met my needs vs a lot of others I've looked at.

**Comment by gionkunz** [comment]
The X Axis is by default a StepAxis which will use fixed ticks (by default the labels) to increase in steps. If you want your X axis to display dates you should use AutoScaleAxis or FixedScaleAxis for your X axis. Check this example http://jsbin.com/lokozu/edit?html,css,js,output
