### ISSUE TITLE
How can I get the y-axis max value after auto scale?

### ISSUE THREAD

**Issue by sunry81914** [chartist-js/chartist#680]
Hi~

I only fine how to get height of the chart answer.
However, I want to know the y-axis max/min value after auto scale.
Is there have any method to get the y-axis max/min value ? thx.

PS:  Beacuse I want to add another polygon element on the auto-scale line chart.
So I need a actual max y-axis value & chart height value to caculate the  corresponding y value

**Comment by gionkunz** [comment]
Hi

You can use the `created` event to extract the axis bounds object: http://jsbin.com/liquli/edit?js,console,output

**Comment by sunry81914** [comment]
@gionkunz  thx a lot. It worked for me

By the way,  How do i 'prepend' a coutomer element in the svg rather then append ?
Here is my some code : 

```
.on('created', function(data) {
    var maxWeight = data.axisY.bounds.valueRange;
    var weight_from = vm.period.targetRange.weight.weight_from;
    var weight_to = vm.period.targetRange.weight.weight_to;
    var y_from = autoScaleY(weight_from, maxWeight);
    var y_to = autoScaleY(weight_to, maxWeight);

    var points = '75,' + y_from + ' 1100,' + y_from + ' 1100,' + y_to + ' 75,' + y_to;

    function autoScaleY (weight, maxWeight) {
        return 30 + ((372 - 30 ) * ( maxWeight - weight ) / maxWeight);
    }

    // how can i 'prepend' the element ?
    createOverlay(data.svg, {
        rangeRect: {
            type: 'polygon',
            id: 'rangeRect',
            points: points,
            fill: '#71c0ba',
            'fill-opacity': '0.15'
        }
    });

    function createOverlay(svg, options) {
        var defs = svg.elem('g');
        defs.elem(options.rangeRect.type, options.rangeRect);
    }
});
```

**Comment by gionkunz** [comment]
Second argument for Svg.append needs to be true: http://gionkunz.github.io/chartist-js/api-documentation.html#chartistsvg-function-append
