### ISSUE TITLE
Pie chart with legend AND percentages in the chart itself

### ISSUE THREAD

**Issue by SabineMa** [chartist-js/chartist#681]
I want to create a pie chart with chartist.js with labels (which are shown in the legend) AND also with percentages in the pie itself.

This is the pie chart:  http://i.stack.imgur.com/SiIKb.png. 
I want to add percentage values to the pieces.

Here (https://gionkunz.github.io/chartist-js/examples.html) is an example with percentages in the pie. But this only works if I do NOT add labels.

Adding labels to the data (e.g. labels: ['Dog','Cat','Cow','Snake',],) results in "NaN%" display.

I want to see the percentages in the pie itself and also put labels (for the legend) into the data.

Is this possible?

**Comment by SpaceK33z** [comment]
Did you look at [chartist-plugin-legend](https://github.com/CodeYellowBV/chartist-plugin-legend) for this?

**Comment by SabineMa** [comment]
Sure, I did. I use it.
But what I want is, _additional_ to the legend having the percentages (e.g.
25%) as labels within the pie chart.

2016-06-10 10:29 GMT+02:00 Kees Kluskens notifications@github.com:

**Comment by SpaceK33z** [comment]
Oh awesome (I made that haha). chartist-plugin-legend has a `legendNames` option, so you can pass `legendNames: ['Dog', 'Cat', ...]` to the plugin, and still use the `labelInterpolationFnc` method to calculate the percentages for the labels in the chart.

**Comment by SabineMa** [comment]
Great that you made it, i like it very much.

question: with the legendNames - will there the be the possibility to have
the legend names _in the legend_ AND _the percentages in the pie_ itself.
See as an example what I men this please: http://i.stack.imgur.com/DX64E.png

2016-06-10 10:45 GMT+02:00 Kees Kluskens notifications@github.com:

**Comment by SpaceK33z** [comment]
Yeah I think so. The legend will use the labels as legend names by default, but if you specify `legendNames: ['Work', ...]` it will use that instead of the labels. Then in the chart options you can use `labelInterpolationFnc` to calculate the percentage.

**Comment by SabineMa** [comment]
can you please give me an example where to add the legend names?
to the data? to the options?

**Comment by SpaceK33z** [comment]
Like this: `Chartist.plugins.legend({ legendNames: ['name 1', 'name 2'] })`

**Comment by SabineMa** [comment]
Oh great, I just tried with dummy data. It works. Thank you very much!

2016-06-10 12:44 GMT+02:00 Kees Kluskens notifications@github.com:

**Comment by SpaceK33z** [comment]
Nice! Could you close this issue?

**Comment by SabineMa** [comment]
Thank you for your help!

**Comment by SabineMa** [comment]
thank you SpaceK33z, this works fine for me:

var data = {
series: [666,222,222,444,]};
var options = {
height: 350,
distributeSeries: true,
labelInterpolationFnc: function(value)  {
function getSum(total, num) {return total + num;}
return  Math.round(value / data.series.reduce(getSum) \* 100) + '%';},
plugins: [Chartist.plugins.legend({
legendNames: ['Geschenke','Fortbildungskosten','Taxi','Weitere',],
})
]};
new Chartist.Pie('#chartist_m3', data, options);

**Comment by leem32** [comment]
The above code wasn't working for me at first. I was getting NaN% for the percentages inside the pie chart, but when I commented out the legend plugin the percentages then showed correctly.

The answer is to make sure you place `clickable` to false in the `legend` options:
```
plugins: [Chartist.plugins.legend({
legendNames: ['Geschenke', 'Fortbildungskosten', 'Taxi', 'Weitere'],
clickable: false
})]
```

**Comment by grgoncal** [comment]
I actually found a way to deal with this without having to use the plugin.

1 - Calculate the sum of yout data.

`            sum = 0;
            for( i = 0; statusData.series[i] != undefined; i++ ){
              sum += statusData.series[i];
            }
`

2 - Iterate thru your stuff inside labelInterpolationFnc

`
i = -1;
[...]
labelInterpolationFnc: function(value){
                i += 1;
                return value + ' ' + Math.round((statusData.series[i]/sum)*100) + '%';
}
`
