### ISSUE TITLE
Does the library feature the ability to make a label a link?

### ISSUE THREAD

**Issue by paul-apacio** [chartist-js/chartist#682]
... or will I need to create a plugin?

**Comment by paul-apacio** [comment]
Okay ignore this question, but for reference, it appears you can just put straight html into the label string and it will render happily.

**Comment by Rio517** [comment]
Maybe you can share an example?

I tried to pass in labels like `["<a href="/book/legend-of-danger-friday">Pasty Reichert</a>", "<a href="/book/dr-tears">Eura Rohan</a>", "<a href="/book/killer-jungle">Micah Block</a>"]` without luck.  I also tried passing dom nodes and passing strings w/ HTML and dom nodes in `labelInterpolationFnc` function.

**Comment by robinchow** [comment]
@Rio517 Not sure if you solved this, but I managed to get links going by replacing _content.innerText_ with _content.innerHTML_ inside _createLabel_ (around line 1000).

Is it safe? Probably not.

**Comment by dkobia** [comment]
@robinchow probably not safe, but looks like the only option.
