### ISSUE TITLE
Change of state of first bar object in draw method does not affect graph

### ISSUE THREAD

**Issue by TomasMatusek** [chartist-js/chartist#683]
Hello, I have troubles with changing state (y1,y2) of first bar object in Bar graph. I use Chartist.js 0.9.7.

I want to customize my graph by using on('draw') method, but when I change state of first bar object
 it does not affect final graph.

As you can see I set y1 and y2 to 100. That means all bar element should have same position in graph.

![bug_2](https://cloud.githubusercontent.com/assets/6783891/14818893/bb37aadc-0bbf-11e6-9210-fd93e546af5f.png)

Bug here as you can see first bar element ignore change that I did. All others are fine.

![bug_1](https://cloud.githubusercontent.com/assets/6783891/14818892/bb351a74-0bbf-11e6-8af3-820af0b50eb4.png)

Do I somethink wrong ? or it's a bug ? Thanks!

**Comment by gionkunz** [comment]
The `chartRect` should never be modified. What are you trying to achieve?

**Comment by gionkunz** [comment]
And I'm really sorry for the late reply :-(

**Comment by gionkunz** [comment]
Please re-open if needed
