### ISSUE TITLE
graph is not render in chartist

### ISSUE THREAD

**Issue by daniuniperu** [chartist-js/chartist#691]
hi friends anybody can help me with that, I got this graphic that builds without a problem a jira burn down chart from Jira's API. but the problem arise when i have to render the line chart dynamically (explained right below).

var chart = new Chartist.Line('.ct-chart', {
  series: [{
    name: 'remaining',
    data: [
      {x: new Date(143134652600), y: 53},
      {x: new Date(143334652600), y: 40},
      {x: new Date(143354652600), y: 45},
      {x: new Date(143356652600), y: 41},
      {x: new Date(143366652600), y: 40},
      {x: new Date(143368652600), y: 38},
      {x: new Date(143378652600), y: 34},
      {x: new Date(143568652600), y: 32},
      {x: new Date(143569652600), y: 18},
      {x: new Date(143579652600), y: 11}
    ]
  }, {
    name: 'stories',
    data: [
      {x: new Date(143134652600), y: 53},
      {x: new Date(143334652600), y: 30},
      {x: new Date(143384652600), y: 30},
      {x: new Date(143568652600), y: 10}
    ]
  }]
}, {
  axisX: {
    type: Chartist.FixedScaleAxis,
    divisor: 5,
    labelInterpolationFnc: function(value) {
      return moment(value).format('MMM D');
    }
  },
  axisY: {
    onlyInteger: true,
    low: 0
  },
  series: {
    remaining: {
      lineSmooth: Chartist.Interpolation.step(),
      showPoint: false
    },
    stories: {
      lineSmooth: false
    }
  }
});

But the problem arise when i want build the graph from a database building the structure and passing it to series but it doesn't render the image please anything that i am doing wrong. Any ideas will be really helpfull.

$scope.linegraph1 = {
                labels: [], //la que aparece en el circulo
                series: []

```
    };
```

function getAgileBoardData(data) {
            //var labeltrending = [];
            var seri = [];

```
        ctrl.totalAgileBoards = data;

        if (data != undefined) {    
            //debugger;
            for (var i = 0; i < data.length; i++) {             
                var date = data[i].date;
                var rt = data[i].remainingTime;
                var wt = data[i].workedTime;
                var val="";



                for(var j = 0; j < data[i].remainingTime.length ; j++){
                    if(data[i].remainingTime.length-1==j){
                        val=val+ '{x: new Date('+data[i].date[j]+'), y: '+ data[i].remainingTime[j]+'}';
                    }else{
                        if(data[i].remainingTime[0]==j){
                            console.log("IMPRIMIR: >"+data[i].remainingTime[j]);
                            val=val+'{x: new Date('+data[i].date[j]+'), y: '+ data[i].remainingTime[j]+'},';

                        }else{
                            console.log("IMPRIMIR: >"+data[i].remainingTime[j]);
                            val=val+'{x: new Date('+data[i].date[j]+'), y: '+ data[i].remainingTime[j]+'},';
                        }
                    }                       
                }
                var seri= " { name: 'remaining', data: ["+val+"]}"; 
                $scope.linegraph1.series = [seri];


            }   

        }




    }
```

**Comment by gionkunz** [comment]
Please use http://stackoverflow.com/ for these kind of questions, we should only track bugs, feature requests or questions on internals within this Github repository.
