### ISSUE TITLE
Multiple lines in a chart via a custom JSON - similar to your example...

### ISSUE THREAD

**Issue by mashedcreative** [chartist-js/chartist#692]
Hi, a while back you posted a way which you could map custom JSON data and map the nodes to the array for series and labels.... here it is: http://jsbin.com/lawimadena/edit?html,js,console,output

I've been trying to figure out why the example you have given doesn't work with a multiple line chart but only for bar charts.

A multiple line chart would work with a simple JSON set up like the following:

```
var jsonData = '{"labels":["4th May", "5th May", "6th May"],"series":[[ 100,200,300 ],[ 220,150,330 ]] }';      
var data = JSON.parse(jsonData);
var chart = new Chartist.Line('#chart', data);
```

But the JSON data input wouldn't be as simple as the snippet above. It would be more like the the one you have given in the example where you map the data to the axis.

The JSON data would be something like below, ideally **date** would be on the X axis, and the **value** on the Y axis, plotted as a multiple line chart.

```
[
  {
    "id": 1,
    "name": "Alan",
    "email": "alan@somewhere.com",
    "date": "4th May",
    "value": 5
  },
  {
    "id": 2,
    "name": "Bob",
    "email": "bob@somewhere.com",
    "date": "5th May",
    "value": 5
  }
]
```

**Comment by gionkunz** [comment]
You need to have the date as timestamp, and then you can use it for the xAxis while using value for the Y axis. Here is an example with a agile burndown chart: http://jsbin.com/lokozu/edit?html,css,js,output

**Comment by gionkunz** [comment]
Closing becauase of inactivity
