### ISSUE TITLE
Y Axis scale steps (increments) of 10

### ISSUE THREAD

**Issue by JordanSayner** [chartist-js/chartist#693]
Hello,

I have a chart that goes from 0 to 100, i would like to show scale steps (increments) of 10 in the Y axis, so it would display like

```
100
90
80
70
...
20
10
0
```

but by default it only shows as

```
100
75
50
25
0
```

I couldn't see anything in the Documents on the main website. Here is my current options

``` javascript
            var lineChartOptions = {
                height: '500px',
                low: 0,
                high: 100,
                showArea: true,
                showPoint: true,
                fullWidth: true,
                //chartPadding: {
                //  right: 40
                //},
                axisY: {
                    onlyInteger: true,          
                },
                lineSmooth: Chartist.Interpolation.cardinal({
                    fillHoles: true,
                }), 
                plugins: [
                    Chartist.plugins.tooltip()
                ],
            };
```

**Comment by JordanSayner** [comment]
i Figured this out btw, the code need is 

```
    axisY: {
            type: Chartist.FixedScaleAxis,
            ticks: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
            low: 0
    },
```

**Comment by danthedanman** [comment]
@JordanSayner how did you figure that out? Documentation is so skimpy.  Are there other resources?

**Comment by JordanSayner** [comment]
> i Figured this out btw, the code need is
> 
> 
> ```
>     axisY: {
>             type: Chartist.FixedScaleAxis,
>             ticks: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
>             low: 0
>     },
> ```

It was a long time ago, but judging by this thread, this is the code i used. i cant remember the project to go back and double check.

**Comment by gionkunz** [comment]
This example can actually be copied from the skimpy documentation and code examples here https://gionkunz.github.io/chartist-js/getting-started.html#switching-axis-type 😆

**Comment by danthedanman** [comment]
Thanks!

**Comment by jeznacki** [comment]
It is skimpy
