### ISSUE TITLE
Can't interact with points when using showArea

### ISSUE THREAD

**Issue by bowd** [chartist-js/chartist#694]
### What I want to achieve

I want a line graph with showArea in which I can interact with the points. By interact I mean have tooltips on hover and actions on click.
### Problem

As far as I can tell due to the drawing order of the graph components, the points end up under polygons that represent the "area" portion of the lines. This means I can't have pointer events on them.
I don't have that much experience with SVG but as far as I understand `z-index` is represented by drawing order and can't be manipulated any other way.
### Potential Solutions
- It would be cool if there would be an option that would make all `points` of the graph be drawn last so that you can interact with them.
- Or maybe there could be a plugin that queues up the points instead of drawing them and then draws them at the end of the drawing cycle --- tho I'm not sure it's possible.

> Disclaimer: I might be totally off bat and I'm looking for some validation on my thought process. I haven't fully investigated this but I thought it would be cool if somebody with a better understanding could point me in the right direction and I would be more than happy to work on a PR if you think this makes sense.

**Comment by gionkunz** [comment]
Hi there. Nice disclaimer :-)

For a quick solution you could use the CSS style:

``` css
.ct-area {
  pointer-events: none;
}
```

This will make your areas irrelevant for mouse interaction and therefore pass on to the points below.

**Comment by bowd** [comment]
Well, don't I feel silly now 👍 I dunno why in my head that wouldn't have worked with SVG elements, but I didn't even look it up. Thanks a lot!
