### ISSUE TITLE
How to get x axis value when we click on a bar of a bar chart

### ISSUE THREAD

**Issue by gnvsuneetha** [chartist-js/chartist#695]
Out requirement is to show specific data for that bar on click as a popup. Could you please let me know how we can achieve this

**Comment by gionkunz** [comment]
the value is stored in the attribute `ct:value` on the bar

**Comment by gnvsuneetha** [comment]
Let me re frame my question.  I want to get the label of the bar clicked

**Comment by adrianparr** [comment]
You can get the label using jQuery.
http://codepen.io/adrianparr/pen/QEjyLx

**Comment by gionkunz** [comment]
Or you can put the label into meta data. Check the example here: https://github.com/gionkunz/chartist-js/issues/542

**Comment by mestaritonttu** [comment]
The codepen by @adrianparr is not working. I wonder where the bug is?

**Comment by adrianparr** [comment]
It's working for me in Chrome, Firefox and Safari on Mac. I've not tested in IE or Edge.

**Comment by mestaritonttu** [comment]
Ok, looks like it was a temporary glitch
