### ISSUE TITLE
Dynamic line colors

### ISSUE THREAD

**Issue by eox2** [chartist-js/chartist#697]
Hi 

I was wondering how to achieve dynamic line color for a line chart. I want to use different colors to represent different ranges of values.

I did try using the on draw function and i am able to manipulate the point colors but it seems the line is drawn all at once not in segments so it doesn't seem possible to change color of the line in between points.

Ex: 0-10: Geren
      10-20 Yellow
       20-30 Red

Thanks alot!

**Comment by eox2** [comment]
Something like this is what I am looking for:

http://dimplejs.org/advanced_examples_viewer.html?id=advanced_dynamic_line_color

**Comment by DatScreamer** [comment]
http://www.w3schools.com/css/css3_gradients.asp

**Comment by gionkunz** [comment]
You can use SVG gradients: https://www.sitepoint.com/getting-started-svg-gradients/

**Comment by titaniumbones** [comment]
Hey I know this is an old issue, but it comes up pretty high in google search results and doesn't contain any explanation of how to actually introduce a color gradient into a line segment on drawing. Wondering if that could be added here, or if I ought to file a new issue.  Thanks!
