### ISSUE TITLE
Strange black stripes on pie chart

### ISSUE THREAD

**Issue by MariusGarbea** [chartist-js/chartist#698]
Hi! Does anyone know where do these black stripes come from?

![capture](https://cloud.githubusercontent.com/assets/15181021/15216463/d5e77e6e-185f-11e6-9292-7873d985392a.PNG)

**Comment by Vamiris** [comment]
Looks like an css issue, maybe some fill colours do not match.

Can you identify the object in firebug or developer tools?

**Comment by gionkunz** [comment]
For proper assistance with you issue please create a reproducible and isolated version of the issue within an online code editor like JSBIN. You can use this template to get started: http://jsbin.com/zuqejof/edit?html,js,output
