### ISSUE TITLE
Custom label for pie chart

### ISSUE THREAD

**Issue by raphaelcahri** [chartist-js/chartist#699]
Hello, i had so much fun working with chartist but i would like to do something like this 
( label who match with the chart part, and be customizable ) 
http://grab.by/Qhio
I dit it with span and paragraph with css but i would like to know if there is a way to do labels like that with with chartist, because my problem is, the div that i did does not line with my chart..

Thank you guys :) 
@kennygrant @drewbarontini @psalaets @deckool @joshuawarner32

**Comment by DatScreamer** [comment]
http://www.w3schools.com/css/css3_gradients.asp

**Comment by gionkunz** [comment]
Use this plugin https://github.com/CodeYellowBV/chartist-plugin-legend
