### ISSUE TITLE
Great idea! Please port it to Dart!

### ISSUE THREAD

**Issue by Emasoft** [chartist-js/chartist#7]
I agree with you on all the project premises. Please make a Dart version of it.

**Comment by gionkunz** [comment]
Hi, and great to hear you also feel that way!

What about finding a group of people who would port it to dart? For me it's not a priority, as I really like to stick to the standard, but if there are enough people who would like to port it to Dart why not!

**Comment by jonkirkman** [comment]
Sounds like fun. Later this week I can take a look at porting this to Dart.

@gionkunz - Great work work so far!

**Comment by gionkunz** [comment]
Tnx, jon. Let's see where all this is going, we have exciting plans!

**Comment by gionkunz** [comment]
Was there any progress on this?

Cheers
Gion

**Comment by jonkirkman** [comment]
Yes. I was able to review the API and the javascript. Overall it looks to be a smooth port of the primary methods but there are a handful of the utility / private-ish methods that won't make sense in Dart. 

@gionkunz - Over the past few weeks I haven't had time to follow the issue list but have noticed a lot of activity. Is the API stable at this point? 

Thanks.

**Comment by gionkunz** [comment]
Hi @jonkirkman 

The API did change a bit but everything was backwards compatible. However, the implementation changed quite a bit as there is now a base chart and some prototypal inheritance. Also there are now Events that get emitted in order to intercept the drawing process.

**Comment by gionkunz** [comment]
As there is no progress on this I'll close the issue. Please reopen if you're working on something.
