### ISSUE TITLE
Need to get the radius of a Pie chart

### ISSUE THREAD

**Issue by chasd00** [chartist-js/chartist#702]
For positioning a legend I need to get the radius of the pie chart. I've looked through the svg object but didn't see anything. Is there a way to calculate it based on the stroke width and size of the containing element perhaps? Thanks for any help you guys can provide and keep up the good work

**Comment by gionkunz** [comment]
Sorry for the late reply. The radius is currently not exposed via event. However, you can simply read the width or height of the generated SVG object during the `created` event and then divide it by 2 to get the radius:

``` javascript
var chart = new Chartist.Pie('#chart', {
  series: [1, 2, 3]
}).on('created', function(context) {
  var radius = context.svg.width() / 2;
})
```

**Comment by gionkunz** [comment]
Closing becauase of inactivity
