### ISSUE TITLE
Remove white space when not show the label for axis

### ISSUE THREAD

**Issue by littlewall** [chartist-js/chartist#703]
Hi,
I'm just curious if there's any chance to remove white space thats left on the left side of bar chart, when I set `showLabel: false` for axisY?

Thank you,
Milan Zítka

**Comment by gionkunz** [comment]
Yes

``` javascript
var options = {
  axisY: {
    showLabel: false,
    offset: 0
  }
};
```

**Comment by gionkunz** [comment]
Closing becauase of inactivity
