### ISSUE TITLE
Custom images.

### ISSUE THREAD

**Issue by andresperezc** [chartist-js/chartist#704]
Hi @gionkunz, 

I want  to replace points by different custom images. I saw one of your examples and worked perfectly, but I want to have two or more custom images in  the same graph. Could you please send me an example of how can I do this? 

`var chart = new Chartist.Line('#chart', {
        labels: ['1', '2', '3', '4', '5'],
        series: [{
            name: 'series-1',
            data: [2, 10, 2, 5, 3]
        }, {
            name: 'series-2',
            data: [null, 1, z1, null, z2]

```
    }]
}, 
        {
            width: 500,
            height: 500,
            low: 0,
            chartPadding: {
                right: 40
            },
            axisY: {
                onlyInteger: true,
                offset: 20
            },
            series: {
                'series-1': {
                    lineSmooth: Chartist.Interpolation.step()
                }}
        });
var starImage = 'star.png';

var imgHeight = 20;
var imgWidth = 20;
chart.on('draw', function(data){
    if(data.type === 'point'){
        var image = new Chartist.Svg('image', {
            height: imgHeight,
            width: imgWidth,
            x: data.x - (imgWidth / 2),
            y: data.y - (imgHeight / 2)
        });
        image._node.setAttributeNS('http://www.w3.org/1999/xlink', 'xlink:href', starImage);
        data.element.replace(image);
    }
});`
```

Thanks so much!!!

**Comment by gionkunz** [comment]
The issue for image xlink namespace detection is now fixed so you don't need to use setAttributeNS directly anymore. You can use the meta data to store an image url in your data for each point. Here's a simple example:

http://jsbin.com/wadoteg/edit?html,css,js,output

**Comment by andresperezc** [comment]
Hi gionkunz!!!

Amazing!!! Thanks so much for your support!!!
