### ISSUE TITLE
Add chart options to API

### ISSUE THREAD

**Issue by jfunction** [chartist-js/chartist#705]
Hello, I am new to this library and one barrier for me is figuring out what options are available to pass into, eg, the `Chartist.Line` constructor. 

The [API](http://gionkunz.github.io/chartist-js/api-documentation.html#chartistline-function-line) says to "Check the examples for a detailed list.", however I couldn't find documentation for example on the `fullWidth` option (I did a Ctrl-F search of the page). Would it be possible to link the user to a more full list of options and, more immediately, could I get some input as to where I might look to find out? 

Thanks for the library by the way, I almost went back to highcharts for my project but am glad I did some searching :)

**Comment by gionkunz** [comment]
Hi there. Thats an issue of the documentation site which is not very clear. We have an issue to track this #565 .

You need to look for `declaration defaultOptions` in the corresponding module (Line, Bar etc.) and then hit the show code button.

Cheers
Gion
