### ISSUE TITLE
Custom text inside donut chart

### ISSUE THREAD

**Issue by ghost** [chartist-js/chartist#706]
I need to add some custom text inside the donut chart as seen below:
http://i.imgur.com/tBrkNpc.png

The total value needs to show the total of donut chart values. What is the best way to do this?

**Comment by simas93** [comment]
if you don't need animated donut, trys this plugin https://github.com/moxx/chartist-plugin-fill-donut

**Comment by gionkunz** [comment]
Duplicate of #255
