### ISSUE TITLE
cannot display on firefox

### ISSUE THREAD

**Issue by NguyenThaiAn** [chartist-js/chartist#707]
https://codepen.io/gionkunz/pen/zHBtn
It can display chart on chrome, safari but cannot on firefox? What Should I do?

**Comment by NguyenThaiAn** [comment]
Please help me. Thank you very much

**Comment by gionkunz** [comment]
This is an extremely old version of Chartist. Please refer to the documentation site for examples: http://gionkunz.github.io/chartist-js/

There's a more recent CSS animation and 3d transform example here: http://jsbin.com/wupuhu/edit?css,js,output
