### ISSUE TITLE
Animating donut chart from a new position

### ISSUE THREAD

**Issue by informa** [chartist-js/chartist#709]
Hi,  I have an example using your animate method on your site
http://codepen.io/informa/pen/rLVOyo?editors=0010

But rather it animating from the start position I was trying to make it animate from the previous data.element._node.getTotalLength()

**Comment by gionkunz** [comment]
You'd somehow need to keep track of the old positions. But the problem is for animating decreasing values which you'd need to animate differently by reversing start and end. Here's a very simple example of keeping track the previous value: http://codepen.io/gionkunz/pen/ezvOpe?editors=0010

**Comment by gionkunz** [comment]
Closing becauase of inactivity
