### ISSUE TITLE
axisY labels are off by one with position 'right' option

### ISSUE THREAD

**Issue by ajdust** [chartist-js/chartist#713]
It appears that using axisY position 'right' causes the y axis labels to shift up by one incorrectly.

See [here](http://jsbin.com/wiqufijifu/edit?html,js,output) for an example. The 0 label should be on the bottom line.

**Comment by gionkunz** [comment]
I can confirm this bug. Let's fix it ASAP. Thanks for the report!

**Comment by drewatk** [comment]
I looked into this a bit. The axis is only checking for `'start'` and `'end'`, as opposed to `'right'` or `'left'`

An if statement (`axis.js` lines 71 and 92) checks and moves the label offset accordingly either for `'start'` or not start. But a non valid input like `'right'` doesn't match up with the `classNames` object (`bar.js` lines 103-104, `line.js` lines 107-108), so the correct class isn't applied.

@gionkunz What would the best way to approach this be? Throw an error for bad input? Or also accept `'left'` and `'right'` as valid?

**Comment by gionkunz** [comment]
Should be tracked with #811

**Comment by ariellevitsky** [comment]
Sorry, so how would one fix the offset? I checked out the linked issue, but I'm not sure how to apply it to my instance.
