### ISSUE TITLE
Default SCSS only colors up to "o" in a series (disappearing bars)

### ISSUE THREAD

**Issue by afiaka87** [chartist-js/chartist#714]
Was having a lot of trouble figuring out why certain bars in my chart weren't showing up. Found out it was because the CSS for a one dimensional series only colors up to the generated "o" series name. 

> // Series names and colors. This can be extended or customized as desired. Just add more series and colors.
> $ct-series-names: (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) !default;
> $ct-series-colors: (
>   #d70206,
>   #f05b4f,
>   #f4c63d,
>   #d17905,
>   #453d3f,
>   #59922b,
>   #0544d3,
>   #6b0392,
>   #f05b4f,
>   #dda458,
>   #eacf7d,
>   #86797d,
>   #b2c326,
>   #6188e2,
>   #a748ca
> ) !default;

I realize there's a comment specifying that it can be modified, but this caused me a good deal of troubleshooting as my bar chart had values which weren't getting a stroke, hence invisible.  At the very least, the default series should extend to 'z'.

**Comment by gionkunz** [comment]
Hi there, I'm not sure if chartist is made for such large count of series. However, I agree that we should include proper default colours so at least we're getting visible series. Anyway, we're going to refactor the series names to be numeric and with this change probably also re-evaluate how we're generating colours. I'd like to include an option to automatically create series colours based on scales and colour spaces like LAB https://en.wikipedia.org/wiki/Lab_color_space

**Comment by gionkunz** [comment]
Parts of this we're keeping track in #183, I'll close this issue in favor of the series renaming and keep a reference to it.

**Comment by afiaka87** [comment]
Thanks. For what it's worth, after re-styling them to have colors, I think Chartist works really well with a large count of series, especially when making use of vertical space.
