### ISSUE TITLE
Line chart with a single value

### ISSUE THREAD

**Issue by erasethis** [chartist-js/chartist#716]
If I only have a single value to display the corresponding dot in the chart is drawn to the left of the y-axis, and in the browser console I get messages such as

`chartist.js:1810 Error: <line> attribute x1: Expected length, "NaN".`

**Comment by gionkunz** [comment]
I've confirmed this as a bug. Let's fix this ASAP. Thanks

**Comment by gionkunz** [comment]
Should be fixed once 0.9.9 is released

**Comment by Webbrother** [comment]
Reproduced in 0.10.1, but not sure about reason of such errors.
