### ISSUE TITLE
Line chart point and label placement

### ISSUE THREAD

**Issue by LandonSchropp** [chartist-js/chartist#718]
First of all, thanks for creating such an awesome library! It's been a joy to switch to it from Highcharts. 😄 

I have a quick question about the difference in placements between line charts and bar charts. In a line chart, the dot is placed on the axis grid lines, and the label is left aligned under it:

<img width="833" alt="screen shot 2016-06-16 at 3 37 33 pm" src="https://cloud.githubusercontent.com/assets/361591/16135431/687b4998-33d8-11e6-8b0c-f960bf06a3ea.png">

In a bar chart, the bar is placed between the grid lines, and the label is centered under it.

<img width="805" alt="screen shot 2016-06-16 at 3 38 01 pm" src="https://cloud.githubusercontent.com/assets/361591/16135434/6d6530ea-33d8-11e6-956b-2d7afc1f7844.png">

What I really need is a line graph, but with the points placed between the grid lines and the labels centered under them. Is there a way to accomplish this with Chartist? Thanks in advance!

**Comment by gionkunz** [comment]
Hi there. Thanks for the kind words :-) Unfortunately I didn't had much time to spend on chartist recently, but this will change very soon.

Using the `draw` event you could easily offset the points and lines by half a step length. Check this bin: http://jsbin.com/joloqac/edit?js,output

Cheers
Gion

**Comment by LandonSchropp** [comment]
That did the trick! Thanks for the help Gion.

**Comment by EmirGluhbegovic** [comment]
Hey,
I having the same issue, your solution solved it @gionkunz Thank you!
And again awesome charting library. 
Quick question, how would I move the chart area, the area highlighted beneath the line chart with the line?
