### ISSUE TITLE
Infinite loop on Chartist.getBounds()

### ISSUE THREAD

**Issue by pedrofsantoscom** [chartist-js/chartist#72]
On Chartist 0.2.3, Chartist.getBounds() line 304 (unminified):

``` js
// Optimize scale step by checking if subdivision is possible based on horizontalGridMinSpace
while (true) {
    var length = Chartist.projectLength(svg, bounds.step / 2, bounds, options);
    if (length >= options.axisY.scaleMinSpace) {
        bounds.step /= 2;
    } else {
        break;
    }
}
```

the while loop enters into an infinite loop if the values of "high" and "low" of the "bounds" object, are string numeric values.
The length variables gets "Infinity" value.

``` js
var length = Chartist.projectLength(svg, bounds.step / 2, bounds, options);
```

**Comment by gionkunz** [comment]
Thanks for the bug report! Lets check whats best to do here. Can you post the exact config and data?

**Comment by pedrofsantoscom** [comment]
Sorry for the late response.

``` js
Chartist.Line('.chart', data);
```

Using default config with data:

``` js
data:
{
    labels:
    [
        "2014-07-29",
        "2014-08-20",
        "2014-09-24",
        "2014-10-02"
    ],
    series:
    [
        {
            data:
             [
                 "17.45",
                 "17.45",
                 "17.45",
                 "17.45"
             ],
             name: "A"
        },
        {
            data:
             [
                 "6.99",
                 "6.99",
                 "6.99",
                 "5.35"
             ],
             name: "B"
        }
    ]
}
```

**Comment by gionkunz** [comment]
Hi @ledjdm 

I could reproduce the issue with string values in data. The API can only handle numeric values at the moment. I'll include some type conversion in the data normalization method for a upcoming release.

**Comment by pedrofsantoscom** [comment]
Ok, thanks. Either way, my data values should have been numeric instead of string numeric. An accidental mistake that worked great for catching a bug.
