### ISSUE TITLE
Error: <path> attribute d: Expected number, "MNaN,NaNA145,145,…" when filling a pie chart.

### ISSUE THREAD

**Issue by ArvidHamersma** [chartist-js/chartist#725]
I keep getting 3 errors in consol log when filling a pie chart.
The errors are:
chartist.js:1984 Error: <path> attribute d: Expected number, "MNaN,NaNA145,145,…".
chartist.js:1984 Error: <text> attribute dx: Expected length, "NaN".
chartist.js:1984 Error: <text> attribute dy: Expected length, "NaN".
The content of the HTML page is:
`<!DOCTYPE html>`
`<html>`
`<head>`
`<meta charset="utf-8" />`
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`
`<link href="/Intake/favicon.ico" rel="icon" />`
`<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,700' rel='stylesheet' type='text/css'>`
`<title>...</title>`
`<link href="/Intake/Content/jquery-ui.css" rel="stylesheet"/>`
`<link href="/Intake/Content/bootstrap.css" rel="stylesheet"/>`
`<link href="/Intake/Content/site.css" rel="stylesheet"/>`
`<link href="/Intake/Content/autocomplete.css" rel="stylesheet"/>`
`<link href="/Intake/Content/chartist.css" rel="stylesheet"/>`
`<link href="/Intake/Content/themes/base/core.css" rel="stylesheet"/>`
`<link href="/Intake/Content/themes/base/autocomplete.css" rel="stylesheet"/>`
`<link href="/Intake/Content/themes/base/theme.css" rel="stylesheet"/>`
`<script src="/Intake/Scripts/modernizr-2.6.2.js"></script>`
`</head>`
`<body>`
`...`
`<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12" style="padding: 15px">`
`<div id="widget-panel-9" class="panel" data-link="" style="background-color: #F0F2F9">`
`<div class="panel-heading" style="background-color: #BFC8E6">`
`<h4>Open tickets per priority</h4>`
`</div>`
`<div class="panel-body" style="background-color: antiquewhite;height: 290px;min-width: 330px;">`
`<div id="widget-peichart-ticketsPerPriority" class="ct-chart ct-perfect-fourth" data-source="TicketsPerPriority" style="align-items:center;"></div>`
`</div>`
`</div>`
`</div>`
`...`
`</div>`
`<script src="/Intake/Scripts/jquery-2.2.3.js"></script>`
`<script src="/Intake/Scripts/jquery-ui-1.11.4.js"></script>`
`<script src="/Intake/Scripts/jquery.ui.autocomplete.html.js"></script>`
`<script src="/Intake/Scripts/bootstrap.js"></script>`
`<script src="/Intake/Scripts/respond.js"></script>`
`<script src="/Intake/Scripts/chartist.js"></script>`
`<script type="text/javascript">`
`document.addEventListener('DOMContentLoaded', function () {`
`$('.ct-chart').each(function (index, Element) {`
`var url = $(this).data('source');`
`var elm = '#' + $(this).attr('id');`
`$.getJSON(url, null,`
`function (data, text, state) {`
`var options = {`
`labelInterpolationFnc: function (value) {`
`return value[0];`
`}`
`};`
`new Chartist.Pie(elm, data, options);`
`}`
`);`
`});`
`});`
`</script>`
`</body>`
`</html>`

The response text from the AJAX call is:
{"labels":["1. Kritiek","2. Hoog","3. Gemiddeld","4. Laag","5. Planning","Niet gevuld"],"series":[[0,4,30,42,15,5]]}

I use Chartist.js 0.9.8 and Chrome 51.0.2704.103 m (64-bit).
Probably I made a mistake, but I can't find it....
Please help me in the right direction.

Arvid Hamersma

**Comment by gionkunz** [comment]
Series in Pie charts should be a one dimensional array.

**Comment by ArvidHamersma** [comment]
Gionkunz, 

The JSON I return with the AJAX call is not correct.
Is the correct something like:
`{"labels":["1. Kritiek","2. Hoog","3. Gemiddeld","4. Laag","5. Planning","Niet gevuld"],"series":[0,4,30,42,15,5]}`
If i'm wrong, can you point me the error?

**Comment by ArvidHamersma** [comment]
I changed the responce and it works fine now!!
Thanks for the tip :)
