### ISSUE TITLE
Setting the number of tick marks in the y-axis

### ISSUE THREAD

**Issue by tedbreen** [chartist-js/chartist#728]
I'm trying to limit the number of tick marks that are drawn in my bar chart. Currently, the `#getBounds` method will figure out what the y-axis values will be and will create as many ticks as the `minScaleSpace`  option will allow. What I would like to do is limit the number of ticks to a max number every time (i.e. 10). 

This is not hard to do if you know the min/max range ahead of time; you can set `minScaleSpace` to a fixed number. My problem is that my min/max range changes a lot, depending on what data I am using. The value I set for `minScaleSpace` may work for one set of data, but not for another. I'm currently trying to figure out how to calculate what the best `minScaleSpace` value is and dynamically set the value in the chart.

Has anybody else struggled with this? I know this was raised in issue #377 , but the author of that issue seemed content to just set a `scaleMinSpace` value. One solution I had was doing something like this to the `#getBounds` method:

``` js
  // insert this before the values array is filled
  if (bounds.max / bounds.step > maxNumberTicks) {
    bounds.step = Math.floor(bounds.max / maxNumberTicks)
  }

  bounds.values = [];
  for (i = bounds.min; i <= bounds.max; i += bounds.step) {
    bounds.values.push(Chartist.roundWithPrecision(i));
  }
```

**Comment by gionkunz** [comment]
`FixedScaleAxis` is not an option?

**Comment by tedbreen** [comment]
Doy! 😛 I somehow missed this option. Thank you!
