### ISSUE TITLE
connect non-continious data sets?

### ISSUE THREAD

**Issue by BernieGraham** [chartist-js/chartist#73]
I'm trying to chart some time series data for each hour for an entire day. (24 data points along the Y-axis.) However, I don't always have 24 data points along the X-axis. (i.e. I may only have 18 hours of data, with gaps in the middle). Sure I can fill in the gaps with zero, but I'd rather not because it gives the illusion of zero value instead of unknown value. But if I do leave gaps, chartist won't connect the points (draw the lines). 

Any thoughts to keep the line drawn even when there's data gaps along an axis?

Thanks!

**Comment by gionkunz** [comment]
Hi there

I think this is very depending on a preference how 0 data should be handled in a chart and it's also very context dependent.

I'd recommend to use a transformation function for your data that does the job. Something like this:
http://jsbin.com/nukod/edit?js,output

Cheers
Gion

**Comment by gionkunz** [comment]
Hi I'm closing this issue, if you have more questions, feel free to ask.
