### ISSUE TITLE
How to identity a label and it's corresponding color for "external" labels?

### ISSUE THREAD

**Issue by rsjorslev** [chartist-js/chartist#737]
As seen on the attached screenshot i have a few small slices on a Pie chart and the labels are hard to make out what they are aligned to.
What i would like to achieve is an "external" label that sits outside the chart but shows that Red = Deactivated, Blue = Denied etc. (like what you see with the bullet items at the bottom of the image)
The pending, approved, denied bullets that i have now is just a mock-up as i dont know how to extract the corresponding label and its color.

Hope that makes sense - thank you for an awesome library!
![screen shot 2016-07-07 at 12 31 38](https://cloud.githubusercontent.com/assets/7449026/16650555/17f2ff76-443f-11e6-98b2-1e44a7ff65bc.png)

**Comment by gionkunz** [comment]
Hi there. Checkout the chartist legend plugin.

**Comment by rsjorslev** [comment]
exactly what i was looking for! Thank you -
