### ISSUE TITLE
Drawing Pie Chart from Dynamic Data

### ISSUE THREAD

**Issue by Zaid-Mirza** [chartist-js/chartist#738]
Scenarioa is,

I m new to Chartist, I have read its documentation. I took pie chart example code from API documentation and used it in my AngularJS Application. Example is for static data and it works fine for static data but but but! when I give it some dynamic data it shows half pie chart or empty pie chart within HTML page. Here is code from my Controller 
`var data = {
               labels: [mylabels],
             series: [myseries]
         };

```
     var options = {
         labelInterpolationFnc: function (value) {
             return value[0]
         }
     };

     var responsiveOptions = [
       ['screen and (min-width: 640px)', {
           chartPadding: 30,
           labelOffset: 100,
           labelDirection: 'explode',
           labelInterpolationFnc: function (value) {
               return value;
           }
       }],
       ['screen and (min-width: 1024px)', {
           labelOffset: 40,
           chartPadding: 20
       }]
     ];
     var chart = new Chartist.Pie('.ct-chart', data, options, responsiveOptions);`
```

whole code is same as mention in documentation except that Im giving it dynamic list as you can see in var data={} code above. mylables and myseries are arrays populated by other function. @gionkunz

**Comment by drewatk** [comment]
I think you'll have to set up an angular watch event and call [the update function](https://gionkunz.github.io/chartist-js/api-documentation.html#chartistbase-function-update) for the chart each time the data changes.

There is also an [Angular 1 Directive](https://github.com/paradox41/angular-chartist.js) you could check out.

Hope this helps!

**Comment by gionkunz** [comment]
``` javascript
var data = {
labels: [mylabels],
series: [myseries]
};
```

Looks suspicious too... should be more likely something like:

``` javascript
var data = {
labels: mylabels,
series: myseries
};
```

**Comment by gionkunz** [comment]
Also I'm treating questions like this differently going forward, sorry for the troubles

**Comment by gionkunz** [comment]
Please use http://stackoverflow.com/ for these kind of questions, we should only track bugs, feature requests or questions on internals within this Github repository.
