### ISSUE TITLE
Order/Sort data for a Bar chart

### ISSUE THREAD

**Issue by rsjorslev** [chartist-js/chartist#742]
I would like to - client side - be able to sort/order the Bar chart i am showing based on the the value of the data i am using. I get this from my REST API currently:

``` javascript
"requestPerApp": [
    {
      "name": "Notepad++",
      "value": 33
    },
    {
      "name": "Box.Net",
      "value": 7
    },
    {
      "name": "SugarCRM",
      "value": 9
    },
    {
      "name": "Adobe Reader 9.1",
      "value": 5
    },
    {
      "name": "Salesforce",
      "value": 39
    },
    {
      "name": "AXIOM",
      "value": 41
    }
  ]
```

and i have tried to feet that directly into series: [requestsPerApp] without specifying a labels key on the object i pass in. For a Pie chart this works as it reads the name and value property of what i pass in but not for Bar chart it seems?
I dont know how to preserve my order if i first have to split the JSON response i get into 2 arrays (one for labels and one for series) or if i can somehow preserve that i have already?

Thanks!

**Comment by drewatk** [comment]
Would this work?

``` javascript
var labels = []
var series = []
jsonData.requestPerApp.map(function(app) {
  labels.push(app.name);
  series.push(app.value);
}
```

Then pass labels and series to chartist

**Comment by rsjorslev** [comment]
Thank you - that's perfect!
I tried to use lodash sort on the array I get from my API and that allows me to sort and then split as your code suggests.

Much appreciated.

**Comment by drewatk** [comment]
No problem! Lodash also has a map function, but this has an advantage of having no dependencies.

**Comment by drewatk** [comment]
You might want to use `forEach` instead of `map` to avoid ambiguity
