### ISSUE TITLE
Meta attributes in named series sequences

### ISSUE THREAD

**Issue by gawyndragonspawn** [chartist-js/chartist#743]
Hello,
First off, thank you for your work on Chartist. I've tried numerous charting libraries until I found yours, and none of them came even close to fitting the needs of my application until I stumbled across it, and the open source aspect of it immediately drew me to it. I've already created a couple custom code hacks to the library specific for my application.
I've spent the last few days and poured through the documentation and the issue tracker, and wasn't able to find anything relevant to my question, so I thought I'd post in case it's something that hasn't been considered or tried as of yet. I'd also like to state that as of yet, I haven't turned to the source code itself in an attempt to write anything custom, as I thought perhaps this was an issue that may have been encountered before, and that if it hadn't, it might be something that the fine developers working on the project may wish to take into consideration.
In short, I've tried using the meta attribute I read about both in the tooltip plugin example, as well as in various places throughout the issue tracker. Take the following:

``` javascript
var data = {
    labels: ['2016-01-01','2016-01-02','2016-01-03','2016-01-04','2016-01-05','2016-01-06','2016-01-07'],
    series: [
    {
        "name":"Series Name",
        "data":[23,18,20,48,104,37,45]
    }]
};
```

As you can see, I have my labels set following a date range (I'm using a PHP back-end to create dynamic charts, using serialised data). I've also named the series, although it's been redacted in my example to protect my data source (it's a private application). My data flows properly along the x-axis, as intended, and the accessibility table plugin properly shows my series name, the date range, and the data as it applies.
Everything works fine, and if I attempt to use the tooltip plugin, it also works fine. It will correctly display the series' name, as well as it's data for the particular point in question. What I wish it to do, however, is to display not just that information, but the appropriate label (in my case, the date of the value) in addition to what it already displays, but I can find no documentation on anything that specifically opens access to the label information. I could study the DOM of the element and attempt to reiterate through each label, but from what I understand in reading some of these issues, there's a fail safe method somewhere in the source that will cause the SVG elements to revert to a span if SVG isn't supported by the browser? Forgive me if I don't have it quite correct, but I haven't really worked with any HTML5 elements until this project - I'm mostly a back-end developer.
To the meat of my question, the documentation I've found on the meta tag, suggests that the input data be formatted something like follows:

``` javascript
var data = {
    labels: ['2016-01-01','2016-01-02','2016-01-03','2016-01-04','2016-01-05','2016-01-06','2016-01-07'],
    series: [
        [
            { "meta": '2016-01-01', "value": 35 },
            { "meta": '2016-01-02', "value":38 },
            { "meta": '2016-01-03', "value": 37 },
            { "meta": '2016-01-04', "value":45 },
            { "meta": '2016-01-05', "value":33 },
            { "meta": '2016-01-06', "value":34 },
            { "meta": '2016-01-07', "value":34 }
        ]
    ]
};
```

This is fine, as it's easy enough to construct my input string in this manner in PHP, but the moment I attempt to add in the series name, it breaks. The closest I can get is formatting the individual datapoints as `{"name": "Series Name", "meta": '2016-01-01', "value": 35 }`. This sort of fixes the tooltip plugin issue, as the tooltip now displays the date which is contained in the meta tag, however the accessibility chart will only display "Series" instead of "Series Name" for the name of my series, and that name will not show up in the tooltip.
Is there an API that exposes the label data, or am I going to be looking into custom coding something specific for my application?
Is this something that the developers of Chartist may want to look into enabling in the future?
If there is something similar to what I want to do, is there documentation available on it, or is it something that's obscure and the average person may not be aware of without digging through the source code?

Forgive my long and rambling question, but I believe in providing as much data for an issue as I can.

**Comment by gionkunz** [comment]
Hi there, you're on the right path :-) There's an open issue for better documentation of meta data. You're already using object notation for data values, but the series name needs to be put on the series not on the datapoint. For this you'll need to use object notation for the series as well:

``` javascript
var data = {
    labels: ['2016-01-01','2016-01-02','2016-01-03','2016-01-04','2016-01-05','2016-01-06','2016-01-07'],
    series: [
        {
          name: 'Series One',
          data: [
            { "meta": '2016-01-01', "value": 35 },
            { "meta": '2016-01-02', "value":38 },
            { "meta": '2016-01-03', "value": 37 },
            { "meta": '2016-01-04', "value":45 },
            { "meta": '2016-01-05', "value":33 },
            { "meta": '2016-01-06', "value":34 },
            { "meta": '2016-01-07', "value":34 }
          ]
        }
    ]
};
```

**Comment by gionkunz** [comment]
And just for a side note, this will be the new predefined answer for issues like this. Sorry for the troubles.

**Comment by gionkunz** [comment]
Please use http://stackoverflow.com/ for these kind of questions, we should only track bugs, feature requests or questions on internals within this Github repository.

**Comment by gawyndragonspawn** [comment]
Hey,
Thanks for the help, and I apologise for opening it as an issue.
After following your example I now have my tooltips displaying almost the way I want them, but it looks like a couple more hacks will be needed to get it just right. Thanks for your help, and again for all the work you do!
