### ISSUE TITLE
Trailing 0 stripped from value

### ISSUE THREAD

**Issue by stitchy** [chartist-js/chartist#747]
Hi,

I'd like to include 2 decimal places in the label of the chart I'm creating. The problem is that if the value is something like 9.60, the trailing 0 gets removed, which won't work for my purposes because the values for my project are all dollar amounts. Is there any way to include the trailing 0s?

For example, 
http://codepen.io/anon/pen/BzxrrL

If you click on the bar, the values are shown with the trailing 0s removed.

Thanks!

**Comment by gionkunz** [comment]
You can pass a `referenceValue` to the axis configuration.

**Comment by gionkunz** [comment]
``` javascript
var config = {
  axisY: {
    referenceValue: 0
  }
};
```

**Comment by stitchy** [comment]
Thank you for the quick response, but I was not able to get the values to show both decimals if there's a 0 at the end. Could you elaborate on how I could use referenceValue for my purpose?

I added referenceValue: 0 to the y-axis, but I don't see a difference?
http://codepen.io/anon/pen/BzxrrL

**Comment by gionkunz** [comment]
Ah sorry I guess I didnt get your initial question. You can use the `labelInterpolationFnc` open to pass a function wich will receive every label value. You can then return a tranformed label value. You can search google on how to format numbers in javascript.

**Comment by stitchy** [comment]
Thanks again for your response. I tried using:

`labelInterpolationFnc: function(value) {
    return value.toFixed(2);
  }`

For the y-axis, but now the chart is completely broken. Please let me know what I am doing incorrectly. 
http://codepen.io/anon/pen/BzxrrL

**Comment by gionkunz** [comment]
Well, on horizontal bar charts it needs to go to the `xAxis` ;-)

**Comment by stitchy** [comment]
Oops haha. My bad.
I added it to the x-axis, but I still don't see the trailing 0 though :(

**Comment by gionkunz** [comment]
This has been resolved right? I can see trailing 0 in your codepen. Please re-open if this is still an issue.
