### ISSUE TITLE
Distance manipulation between bars

### ISSUE THREAD

**Issue by metodribic** [chartist-js/chartist#749]
First of all thans for great work!

I'm new to Chartist and this is probably more a question than an issiue but I simply can not figure it out how to set distance between bars in horizontal (or vertical) bar chart. I know there is seriesBarDistance property but this only applies to series when stackBars is false. I would like horizontal bars to be n pixels apart. Is there any way to achieve that? See attached picture for what I'm trying to achieve.

<img width="599" alt="screenshot 2016-07-28 11 11 46" src="https://cloud.githubusercontent.com/assets/6840850/17207346/77e69714-54b4-11e6-822d-803b26179da1.png">
Horizontal bars without any space between bars

<img width="609" alt="screenshot 2016-07-28 11 14 21" src="https://cloud.githubusercontent.com/assets/6840850/17207360/846b9a0c-54b4-11e6-8063-212c8ed4d537.png">
Horizontal bars with some space.

Is there any property or known solution to set this distance ?

**Comment by metodribic** [comment]
It seems I can achieve that by manipulating with chart height, but is this prefered way of doing this ?

**Comment by gionkunz** [comment]
Yes, the chart is height / width is the container where the elements align in. Chartist is not adjusting the chart dimensions based on the elements. Therefore to achieve fixed spacing, you need to fiy the chart dimensions when working with a predefined amount of series. If the series are dynamic, you'll need to precalculate the width / height of your chart and set it as value.

**Comment by metodribic** [comment]
I thought so, thank you for quick response!
