### ISSUE TITLE
example animation doesn't work on IE11

### ISSUE THREAD

**Issue by luisrudge** [chartist-js/chartist#75]
http://gionkunz.github.io/chartist-js/#chart-css-animation-example

This example only animates the yellow line. The other two lines are both static.

**Comment by gionkunz** [comment]
@luisrudge, please check the note on this below the example. CSS animations on SVG style attributes are not supported so widely yet. Firefox also doesn't support and dash-offset animations yet. I hope this will come soon though. There could be a SMIL fallback but not sure if it fits into chartist.

**Comment by luisrudge** [comment]
So, it's just for chrome, then?

**Comment by gionkunz** [comment]
Im not 100% sure but as far as animation of stroke-dashoffset goes its only supported in chrome i believe. However, as its an animatable property in svg 1.1 and its available as CSS property it will only be a matter of time until other browsers support it.

**Comment by gionkunz** [comment]
I've closed this issue. If you need more information or think we should document better please let me know.

**Comment by gionkunz** [comment]
Firefox 31 supports stroke-dashoffset animations.
