### ISSUE TITLE
Chartist numbers rounding

### ISSUE THREAD

**Issue by achook** [chartist-js/chartist#750]
While making chart, Chartist.js is making strange numbers on Y axis like:
- 28.77499999999997
- 28.79999999999997
- etc.

My configuration:

```
var data = {
labels: ['16:19:52','16:14:51','16:09:50','16:04:48','15:59:47','15:54:45','15:49:44','15:44:43','15:39:41','15:34:40','15:29:39','15:24:37','15:19:36','15:14:35','15:09:33'],

series: [   
          [ 28.31,28.37,28.25,28.25,28.31,28.25,28.37,28.50,28.62,28.56,28.68,28.75,28.81,28.81,28.75 ]
     ]
            };

var options = {
 width: 1700,
height: 700
        };

new Chartist.Line('.ct-chart', data, options);
```

[Whole on codepen](http://codepen.io/kk2345/pen/AXdzRj)

**Comment by kimhaegyeong** [comment]
AxisY label value not changed rounding number.

**Comment by kimhaegyeong** [comment]
I'm so sorry about mess commit...

bounds.vlaues not round off.
beacuse not rounding data pushed into values array. 

so, change `values.push(i)` -> `values.push(value)`

**Comment by gionkunz** [comment]
Let's address this with #815
