### ISSUE TITLE
Line area rendering improperly

### ISSUE THREAD

**Issue by Tammerabi** [chartist-js/chartist#752]
It seems that when showing the area beneath a line chart, the svg path ends at the final data point, then returns to the start (without going down to the bottom of the chart).

![image](https://cloud.githubusercontent.com/assets/4252546/17345996/9ca38820-58bd-11e6-8444-7919e21d6caf.png)

This results in the entire area beneath that diagonal line being filled in. Is there a solution to this? I tried setting areaBase to 0, but that didn't help. Thanks.

`

```
    var options = {
      width: '150px',
      height: '50px',
      showPoint: false,
      showLine: true,
      showArea: true,
      fullWidth: true,
      showLabel: false,
      axisX: {
        showGrid: false,
        showLabel: false,
        offset: 0
      },
      axisY: {
        showGrid: false,
        showLabel: false,
        offset: 0
      },
      chartPadding: '10px',
      lineSmooth: false,
      low: 0
    };`
```

**Comment by gionkunz** [comment]
This must be an issue with your data

**Comment by gionkunz** [comment]
For proper assistance with you issue please create a reproducible and isolated version of the issue within an online code editor like JSBIN. You can use this template to get started: http://jsbin.com/zuqejof/edit?html,js,output
