### ISSUE TITLE
gauge chart not working in grid list

### ISSUE THREAD

**Issue by hinal19** [chartist-js/chartist#755]
I am trying to show small gauge chart into grid. But it is only displaying on first row.

**Comment by gionkunz** [comment]
For proper assistance with you issue please create a reproducible and isolated version of the issue within an online code editor like JSBIN. You can use this template to get started: http://jsbin.com/zuqejof/edit?html,js,output

**Comment by gionkunz** [comment]
Please use http://stackoverflow.com/ for these kind of questions, we should only track bugs, feature requests or questions on internals within this Github repository.
