### ISSUE TITLE
Pie: If there is a zero value in "series" data is ambiguous

### ISSUE THREAD

**Issue by ajusa** [chartist-js/chartist#760]
Whenever there is a zero value being passed into the series array, its label shouldn't show up. I didn't see it in the options for pie, so I created an issue. Here is a screenshot of the problem
![piepng](https://cloud.githubusercontent.com/assets/7073362/17713025/ca1bfa4e-63c6-11e6-875a-066c97cb10b4.PNG)

You cannot tell what is 100%, whether it is incorrect or correct.

**Comment by artparks** [comment]
isn't this just proof that pie charts are innately awful, confusing things?

**Comment by ajusa** [comment]
They are, but the people I am developing this application for like pie charts more. The only "fix" I had was to put the series values right next to the labels, like Correct: 0 and Incorrect: 0

**Comment by gionkunz** [comment]
I can't think of any solution for this. If you're dealing with 0 data in pie charts, it's probably best to remove this data before you draw the chart.

**Comment by ajusa** [comment]
Okay, I'll do that. Thanks!

**Comment by marco-lavagnino** [comment]
In case you can't remove the data before drawing the chart (because it messes up with colors), you can replace the label with an empty space, like this:

```
const labels = ['a', 'b', 'c']
const values = [93, 0, 7]

Chartist.Pie('#myId', {
  labels: labels.map((label, index) => values[index]? label: ' '),
  values: values
})
```

**Comment by pgksunilkumar** [comment]
its working try this one 
 ```
var data = {
                series: [43,0,57]
            }; 
            var labels = ['Auto Loan', 'Credit Card', 'Home Loan'];

 labelInterpolationFnc: function (value, idx) {
                    var calculatePercentage = Math.round(data.series[idx] / data.series.reduce(sum) * 100);
                    if (calculatePercentage > 0){                        
                    return value + " \n" + calculatePercentage + '%';
                    }
                }
```
![image](https://user-images.githubusercontent.com/11393456/52316592-1305b680-29e2-11e9-8089-7c305f06c6d0.png)

**Comment by bahadirdogru** [comment]
Thanz thats help alot :)
