### ISSUE TITLE
Internet explorer label custom axis style

### ISSUE THREAD

**Issue by dhgomezg6** [chartist-js/chartist#762]
I have been using chartist with custom label axis style, the chart should have the x-axis on top, each label have a letter and a number with different styles, in Chrome I have this:

![image](https://cloud.githubusercontent.com/assets/6265813/17743974/69eb406c-646b-11e6-9ac8-9c1447a5faf3.png)

With this code:

```
//Clear the data
data.labels = [];
data.series[0] = [];

//Iterate each report
for(var i=0; i<$scope.reports.length; i++){
    //Get date
    var reportDate = new Date($scope.reports[i].date);

    var dayW = reportDate.getDay();
    var dayN = reportDate.getDate();

    if(dayW==0) data.labels.push('<p class="style1">L</p> '+dayN);
    if(dayW==1) data.labels.push('<p class="style1">M</p> '+dayN);
    if(dayW==2) data.labels.push('<p class="style1">M</p> '+dayN);
    if(dayW==3) data.labels.push('<p class="style1">J</p> '+dayN);
    if(dayW==4) data.labels.push('<p class="style1">V</p> '+dayN);
    if(dayW==5) data.labels.push('<p class="style1">S</p> '+dayN);
    if(dayW==6) data.labels.push('<p class="style1">D</p> '+dayN);  

    data.series[0].push($scope.reports[i].level);
    }
}

new Chartist.Line('.ct-chart', data, options);
```

`

But in IE and Edge the axis have not style, and looks like:

![image](https://cloud.githubusercontent.com/assets/6265813/17744248/7e28d6b0-646c-11e6-9c6e-e64247784d96.png)

how could I fix this in IE ??

**Comment by gionkunz** [comment]
Hi there. This is because IE does not support foreignObject which is used to draw the labels. Without foreignObject there's no way to represent HTML within SVG.

**Comment by gionkunz** [comment]
Closing becauase of inactivity
