### ISSUE TITLE
FixedScaleAxis incorrect tick numbering

### ISSUE THREAD

**Issue by amichair** [chartist-js/chartist#763]
For example, using the data
`series: [[{x:5, y:10},{x:6, y:11},{x:7, y:12},{x:8, y:13},{x:9, y:14}]]`
and axisX type set to `Chartist.FixedScaleAxis` I can't find any way to get the first data point to be labeled with the tick label 5 as is should be. It doesn't matter whether I use `divisor: 4`, or any list of explicit `ticks` values, it always treats the first data point as if its x value was 4 instead of 5. Changing low/high options affects the visible range, but does not affect the numbering (which is still off by one).

This might be a bug in special handling of the first tick, since there is a similar bug in handling of the last tick (e.g. if one specifies only `ticks: [7]`, the 7 tick is shown at the edge of the chart instead of where the 7 x value is (even if one ignores the off-by-one bug).

Please fix it so that the ticks correspond to the correct values.

**Comment by amichair** [comment]
Further investigation found the culprit, which is a `direction: rtl`css style on an ancestor element of the chart. I'm not sure if this module should be protecting itself from that and setting the direction to make sure it's correct, or leave it to the user.

**Comment by gionkunz** [comment]
Thanks for the investigation! Problem with protective CSS is that this has no end if we start doing so. I'd rather leave it up to the user to do this protection using shadow DOM container or just by making sure there's no interfering styles.
