### ISSUE TITLE
Draggable points

### ISSUE THREAD

**Issue by amichair** [chartist-js/chartist#764]
Is there any example or plugin that enables dragging points on a line/scatter chart to update the data? e.g. tweaking future value estimates on a timeline graph and then calculating stuff based on the edited data. I could not find any mention of this anywhere.

For a demonstration, try dragging the points on [this jqPlot example](http://www.jqplot.com/deploy/dist/examples/customHighlighterCursorTrendline.html) - I'm looking for the Chartist equivalent.

If there is no existing plugin or even an example demonstrating how this might be done, please consider adding one!

**Comment by gionkunz** [comment]
Hi there. I've added your plugin idea to our plugin idea issue. Cheers

**Comment by amichair** [comment]
Hi again,

I've created a prototype drag plugin at https://github.com/amichair/chartist-plugin-drag, and would be grateful if someone could review it and provide feedback (I have only a few hours of experience with Chartist before writing this plugin, so I'm sure there is room for improvement). In particular:
- Is there a way to partially update the chart rather than redrawing the whole thing from scratch (as the current chart.update method seems to do)? It's quite slow on some devices.
- Is there a better way of getting axis data than checking every draw event?
- Is anything in the plugin not cross-browser or cross-device enough?
- Is there a better way of getting chart elements such as the grid without hard-coding class names such as 'ct-grids'?
- Is there a way of getting the graph data g element (which doesn't have any class or id to search by)?
- Since there is no real Chartist plugin or internal API documentation that I could find, is everything that this plugin uses (internal data structures etc.) safe to use? Will it break in a future update of some internal core data or functions? Are there any guidelines on how a plugin should and should not interact with the Chartist core?
- Is there a better way of getting the tooltip plugin to work during drag than the ugly workaround I used?
- Anything else that could be improved?
- And finally, can I contribute this plugin to the upstream codebase or are all plugins maintained externally (i.e. only by me)?

Thanks!

**Comment by amichair** [comment]
Would you like to reopen this issue until the discussion is complete and the plugin is released? I wouldn't want it to be forgotten just because it was marked as closed.

**Comment by hansmaad** [comment]
> And finally, can I contribute this plugin to the upstream codebase or are all plugins maintained externally (i.e. only by me)?

Plugins are maintained in their own repositories. Most plugins have their own npm and bower packages. I would recommend to publish these packages, so people can start testing your awesome plugin. If it's stable enough you can make a PR to the chartist plugins doc sites.
