### ISSUE TITLE
Fill holes in data not working in 0.9.7

### ISSUE THREAD

**Issue by danielalvenstrand** [chartist-js/chartist#766]
Hi,

I'm trying to use the functionality to fill holes in data in my line chart but it won't work. This is my config:
`lineChartOptions:any = {
    animation: false,
    responsive: true,
    fullWidth: true,
    chartPadding: {
      right: 40
    },
    lineSmooth: Chartist.Interpolation.cardinal({
      fillHoles: true,
    }),
    low: 0
  };`

which looks like this: 
![image](https://cloud.githubusercontent.com/assets/14288758/17803110/7cb88b8e-65f4-11e6-99c8-dac77d5c065d.png)

How to I make this work? I get no errors and everything is working except for this.
On version 0.9.7

**Comment by gionkunz** [comment]
Tested with 0.9.8. does not seem to be an issue. http://jsbin.com/linegah/edit?js,output

**Comment by gionkunz** [comment]
Please re-open if issue persists

**Comment by danielalvenstrand** [comment]
@gionkunz Thank you, will check later.
