### ISSUE TITLE
Dynamically editing charts (drag and drop?)

### ISSUE THREAD

**Issue by Quas94** [chartist-js/chartist#768]
I need my charts to be editable, maybe by dragging anchor points, etc..

So I'm wondering if this is at all possible using Chartist.js? Has anyone else tried this, or can I get some pointers on where I should start looking in order to accomplish this?

Thanks

**Comment by amichair** [comment]
What a coinkidink!

I just wrote a prototype [chartist-plugin-drag](https://github.com/amichair/chartist-plugin-drag), feel free to try it out and contribute. See also #764.

**Comment by gionkunz** [comment]
Not supported by core, very feasible using plugins
