### ISSUE TITLE
Animated donut graphs not displaying correctly on IE

### ISSUE THREAD

**Issue by Craig-Fisk** [chartist-js/chartist#770]
This is happening on all versions on IE but was tested on IE11 using version 0.9.8 of chartist.

Issue is visible on the example page at https://gionkunz.github.io/chartist-js/examples.html (the very bottom example). I'm guessing it has something to do with the stroke-dasharray.

**Comment by gionkunz** [comment]
IE has never supported SMIL animations, even when it has been considered as a solid and recommended standard. Standard CSS animations would work, but the example on the chartist site uses SMIL (Chartist.Svg.animate). We're planning to switch to Web Animation API #468 which will be supported by Edge.
