### ISSUE TITLE
axis labels are not rounded anymore (since 0.9.8)

### ISSUE THREAD

**Issue by benib** [chartist-js/chartist#771]
The commit https://github.com/gionkunz/chartist-js/commit/bfdc8f26173a2b05b3ce38f2987f6763040e24c5 changed the way `bounds.values` is defined. before the values went through `Chartist.roundWithPrecision` to prevent rounding errors. With this commit the return value from `roundWithPrecision` is  just used to check if it's already in the values array, but the unrounded value is pushed to `bounds.values`.

Changing this back to use the rounded value breaks the test here https://github.com/gionkunz/chartist-js/blob/develop/test/spec/spec-core.js#L398-L405

I do not really get all the details why this was changed. So I am not sure if it's a bug or on purpose. 

Maybe I can submit a PR fixing this if someone can explain me the reason for the changed behaviour and what the test linked above exactly wants to test.

I can also round the value myself in a `labelInterpolationFnc`, but I think the behaviour should not get changed in a way like this with a minor version update.

**Comment by hansmaad** [comment]
I agree that this implementation looks buggy, but I can't remember if this was intentional. Can you please post the output of the failing test?

**Comment by benib** [comment]
@hansmaad sure:

```
X Chartist core getBounds should return single step if range is less than smallest increment
   Expected [ 1000 ] to equal [ 999.9999999999999 ].
```

here is the commit that restores the behaviour and thus causing the test to fail: https://github.com/benib/chartist-js/commit/614f1bc2b07a4cb6c1ab599dc92841317df5670c

I do not send a PR just now. We should first decide whats the right way to go.

**Comment by hansmaad** [comment]
`[1000]` seems to be a valid result to me. But what happens if `roundWidthPrecision(i) > bounds.max` in benib@614f1bc? I think this value shouldn't go to `values`.
Maybe, we can do this instead:

```
for (i = bounds.min; i <= bounds.max; 
     i = Chartist.roundWithPrecision(safeIncrement(i, bounds.step))) {

    if (i !== values[values.length - 1]) {
      values.push(i);
    }
}
```

Hmm, can we find a test case for this corner case? @gionkunz can you have a look on the `getBounds` tests. I added comments to some of these tests. because I wasn't sure if the current behaviour was correct.

**Comment by gionkunz** [comment]
Let's discuss further in #815
