### ISSUE TITLE
Trouble adding dynamically creating charts - "container is null"

### ISSUE THREAD

**Issue by qgoehrig** [chartist-js/chartist#774]
Hi there, I'm a newbie to chartist and am having some issues with creating dynamically created charts.
Here is a snippet of my javascript:

```
var details = $(document.createElement("div"))
details.addClass('ct-chart')
details.addClass('ct-perfect-fourth 
var data = {
series: [3,4,5]
var options = {
width: 500,
height:300
};
new Chartist.Line('.ct-chart', data, options);
```

Upon doing running this code, I get this error message in my firefox console:

> TypeError: container is null 
> 
> > Chartist.createSvg()
> > createChart()
> > initialize()
> > bound initialize();

It seems that chartist somewhat recognizing the element as in the inspector I can see that the .ct-chart div has created pseudo elements of :before and :after. 

Any help here would be greatly appreciated!

**Comment by benib** [comment]
Whatever you pass as the first argument to `Chartist.Line` is passed to `Chartist.querySelector` which does this:
`return query instanceof Node ? query : document.querySelector(query);`

So you either pass `details.get(0)` (the actual Node inside the jQuery wrapper, I guess you use jQuery) or something that will return an element when running `document.querySelector` with it as a parameter. In your case this is not returning something as the element with the class `ct-chart` is not yet appended to the DOM when you call `Chartist.Line`. Append it first using something from jQuery like `appendTo` (https://api.jquery.com/appendTo/)

**Comment by qgoehrig** [comment]
@benib Thank you so much! You've just helped me solved a three hour headache. 
Adding a variable to keep track of the jQuery selector worked great.
