### ISSUE TITLE
change bar width dynamically according to data

### ISSUE THREAD

**Issue by Zaid-Mirza** [chartist-js/chartist#778]
Hi, 

is there any options to change width and seriesBarDistance dynamically? look at pic there is only one set of series. I want it to occupy  all chart width and increase Bar width 
![chartist](https://cloud.githubusercontent.com/assets/13308482/18045271/7ab363fa-6deb-11e6-9b05-eb1f8698898e.png)

**Comment by Zaid-Mirza** [comment]
its my 4th issue on chartist, not a single comment any of them? thats bad @gionkunz

**Comment by gionkunz** [comment]
@Zaid-Mirza I didn't had a lot of time to work on Chartist lately but I'm just in the process of cleanup up the backlog and pick up my work on the library again so sorry for that.

Nevertheless I need to post my standard answer for this type of issue :-/

**Comment by gionkunz** [comment]
Please use http://stackoverflow.com/ for these kind of questions, we should only track bugs, feature requests or questions on internals within this Github repository.

**Comment by gionkunz** [comment]
Btw. you should use the distributeSeries option for this use-case https://gionkunz.github.io/chartist-js/examples.html#example-bar-distributed-series

**Comment by Zaid-Mirza** [comment]
@gionkunz sorry for late response, I was expecting feature which can increase/decrease bar width according to number of data bars on Chart

**Comment by gionkunz** [comment]
Sorry I never replied to this, please re-open if still needed

**Comment by chasegiunta** [comment]
Btw, for anyone else looking for a solution - I found a fiddle that addresses this https://jsfiddle.net/traviss0/gg1oj35x/

Setting the stroke width to the step length, or a fraction of the step length, in the `created` event seems to be a decent way.

**Comment by 1pavanb** [comment]
the above jsfiddle link isn't working.
I figured out a way to do it with a similar idea.

```
        var chart = new Chartist.Bar('.ct-chart', data, options);

        var yOffset = chart.options.axisY.offset;
        var chartWidth = chart.container.clientWidth;
        var xWidth = chartWidth - yOffset;
        var stepLength = xWidth / chart.data.series.length;

        chart.on('draw', function (data) {
            if (data.type == 'bar') {
                data.element._node.style.strokeWidth = stepLength * 2 / 5;
            }
        });
```
This answers the Bar width being dynamic.
