### ISSUE TITLE
update() erase previous data

### ISSUE THREAD

**Issue by AngryElephant** [chartist-js/chartist#779]
I'm trying to update my chart with the update function:

```
chart = new Chartist.Line(".chart-line", {
                labels: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"],
                series: series
                }, {
                lineSmooth: Chartist.Interpolation.none(),
                fullWidth: !0,
                showArea: true,
                chartPadding: {
                    right: 40
                },
                plugins: [
                Chartist.plugins.tooltip()
                ]
            })

 chart.update({series: newSeries})
```

It's working, the chart is updated with the new series but all other data are erased. i have no labels or options anymore. 

Any way to really update the chart without passing all datas and options again ?

**Comment by gionkunz** [comment]
The update function works as expected. You can pass a new data object as first parameter which will be used to re-draw the chart. The data object needs to include to new series data as well as the labels. Check this example: http://jsbin.com/gunahi/1/edit?html,js,output

**Comment by gionkunz** [comment]
Closing becauase of inactivity

**Comment by salampv** [comment]
Hi @gionkunz 
How could I manage if I want to update both label and series values? I mean I want to grow the graph towards x and y ?

first set of values are 
{labels:['01012018', '02012018', '03012018', '04012018', '05012018']
, series:[5,10,7,15,9]}

then on button click I want to update the graph with the follwing

{labels:['01012018', '02012018', '03012018', '04012018', '05012018', '06012018', '07012018', '08012018', '09012018']
, series:[5,10,7,15,9,3,5,7,8]}


Thanks 
AS
