### ISSUE TITLE
using chartist in NodeJS

### ISSUE THREAD

**Issue by MichaelJC91** [chartist-js/chartist#780]
How would I go about using Chartist in NodeJS? I installed the npm package and keep getting 'window' is not defined. How can I resolve this?

**Comment by gionkunz** [comment]
It's not only the window object which is not defined but also the rendering is difficult since it uses a lot of DOM operations at the moment. Fully functional rendering in Node.js will be supported once #810 is implemented.

**Comment by gionkunz** [comment]
Also #814 plays a major role here

**Comment by designbyadrian** [comment]
Hello, I'm using Chartist via ECMA6 imports and server-side rendering. How do I conditionally disable chartist when on server-side? I have the variable, but you can't do conditional imports in Node, maybe you have a solution before server-side graphs are implemented?

Edit: I shall follow the discussion on #87
