### ISSUE TITLE
labels placement is confusing

### ISSUE THREAD

**Issue by AngryElephant** [chartist-js/chartist#781]
Hello,

Is there any way to center the labels according to the grid and points ? The right align is confusing especially when there is a lot of labels.

<img width="230" alt="screenshot at aug 30 17-52-09" src="https://cloud.githubusercontent.com/assets/14820782/18086533/969c5e1a-6eda-11e6-9a71-6aa3e33471bf.png">

Also wanted to say thank you for this great charts library :)

**Comment by hansmaad** [comment]
Duplicate of #439
