### ISSUE TITLE
chartist Y axis spacing issue

### ISSUE THREAD

**Issue by preetcam** [chartist-js/chartist#782]
The last number on Y axis gets very close to second last element.
The spacing in between Y axis elements is not even.

Code : 
       stackBars: true,
        lineSmooth: true,
        fullWidth: false,
        chartPadding: 10,
        height: "280px",
        stretch: true,
        strokeWidth: 10,
        low: 0,
        axisY: {
            offset: 25,
            scaleMinSpace: 25,

```
        labelInterpolationFnc: function(value) { return (value); },

    }
```

<img width="198" alt="screen shot 2016-08-30 at 12 32 26 pm" src="https://cloud.githubusercontent.com/assets/4131188/18104117/6d80ad64-6eae-11e6-95bc-20e50e2f3a66.png">

**Comment by gionkunz** [comment]
Hi there, can you please post your full code?

**Comment by gionkunz** [comment]
For proper assistance with you issue please create a reproducible and isolated version of the issue within an online code editor like JSBIN. You can use this template to get started: http://jsbin.com/zuqejof/edit?html,js,output

**Comment by gionkunz** [comment]
Closing becauase of inactivity
