### ISSUE TITLE
NaN for Piechart with [0,0] as series-data

### ISSUE THREAD

**Issue by skuhnow** [chartist-js/chartist#783]
I have a dynamically generated Piechart with a series with two values. In the case of both values equals 0 I expect and get an empty chart, but I also get some errors in my console:

`
new Chartist.Pie('.ct-chart', {
    series: [0,0]
}, {});
`

> Error: <path> attribute d: Expected number, "MNaN,NaNA395,395,…".
> Error: <text> attribute dx: Expected length, "NaN".
> Error: <text> attribute dy: Expected length, "NaN".
> Error: <path> attribute d: Expected number, "MNaN,NaNA395,395,…".
> Error: <text> attribute dx: Expected length, "NaN".
> Error: <text> attribute dy: Expected length, "NaN".

**Comment by gionkunz** [comment]
I guess we should check whether all values are 0 and then remove the values when creating the chart. Creating a chart with an empty values array, does not cause any errors. For the moment I suggest you're passing an empty array if all values are 0.

**Comment by alexandervaneck** [comment]
I've addressed this in #797.
