### ISSUE TITLE
Display Google Rank

### ISSUE THREAD

**Issue by merlinro** [chartist-js/chartist#784]
Hello!
It is possible to display a chart like this?
![rank](https://cloud.githubusercontent.com/assets/16841807/18274122/3788a37c-7441-11e6-8fc7-aea305bcb93e.PNG)

**Comment by tarekis** [comment]
This is not an actual github issue; github issues are meant for code- or doc-relevant issues/request not for vampire questions. But yes you can, just read the [API](http://gionkunz.github.io/chartist-js/api-documentation.html) and you're fine.

**Comment by merlinro** [comment]
ok sorry
Thanks!

**Comment by merlinro** [comment]
Found a solution: http://jsbin.com/xoqulakite/edit?js,console,output

**Comment by tarekis** [comment]
Close the issue then please
