### ISSUE TITLE
X axis scroll

### ISSUE THREAD

**Issue by ugurcanatas** [chartist-js/chartist#785]
Hey !
I wonder if its posible to make a chart like the one in the picture.I want to limit the number of labels and show the rest of it while scrolling through x-axis. I couldnt find any examples or plugins regarding this.

![agfyb](https://cloud.githubusercontent.com/assets/22047299/18305181/fe11d466-74ee-11e6-8c51-b979a9e4c583.png)

Thanks.
Ugurcan

**Comment by ugurcanatas** [comment]
Okay,i solved this by adding some height and width values to Css and Js libraries.I added buttons for moving forward, backwards and reset. Here 's an example:  http://codepen.io/anon/pen/XjbdPv  (its a little bit messy)

I still have some problems with buttons and whatnot but i figured it out.Thanks anyways.

**Comment by gionkunz** [comment]
This should be implemented in a plugin. Using this as a reference #290
