### ISSUE TITLE
Change length of specific grid line?

### ISSUE THREAD

**Issue by wekii** [chartist-js/chartist#786]
Hi,

first of all I would like to say that chartist.js is amazing library and it's real pleasure to work with.
I'm interested is it possible to change length of the specific grid line? In my case it's the first horizonal grid line that should go over offset and padding area.

I would also like to know is it possible to create a full height vertical line that's going to be used as an separator for years between months?

Best regards.

![chart](https://cloud.githubusercontent.com/assets/8656086/18385157/16cccda2-768f-11e6-8c5b-28acd3500f01.png)

**Comment by gionkunz** [comment]
Thats possible using the draw event of chartist. Just search in the github repo for draw event and check the issues. You'll find plenty of examples. We're also tracking documentation with #90
