### ISSUE TITLE
tooltip not coming at correct position in firefox in chartlist.js

### ISSUE THREAD

**Issue by BhuvneshGupta** [chartist-js/chartist#788]
Tooltip on chart is coming fine on all other browsers except firefox I cant find any solution over google and there is no support page on chartlist website.

already using this code

```
$toolTip.css({
      left: (event.originalEvent.layerX || event.offsetX) - $toolTip.width() / 2 - 10,
      top: (event.originalEvent.layerY || event.offsetY) - $toolTip.height() - 40
    });
```

this [issue](https://github.com/gionkunz/chartist-js/issues/381) is not yet resolved actually.

please help me in this

**Comment by gionkunz** [comment]
Chartist does not provide Tooltip functionality. Check the plugin https://github.com/Globegitter/chartist-plugin-tooltip
