### ISSUE TITLE
How to word wrap Horizontal Bar Text

### ISSUE THREAD

**Issue by ghost** [chartist-js/chartist#791]
http://codepen.io/eternal_wanderer/pen/LRkQrg

> `/_Controls Horizontal Labels_/
> .ct-label.ct-vertical.ct-start {
>   -webkit-box-align: flex-end;
>   -webkit-align-items: flex-end;
>   -ms-flex-align: flex-end;
>   align-items: flex-end;
>   -webkit-box-pack: flex-end;
>   -webkit-justify-content: flex-end;
>   -ms-flex-pack: flex-end;
>   justify-content: flex-end;
>   text-align: right;
>   text-anchor: end; 
> 
>   white-space: nowrap
>   white-space: -moz-pre-wrap; /\* Firefox _/
> white-space: -o-pre-wrap; /_ Opera _/
> white-space: pre-wrap; /_ Chrome _/
> word-wrap: break-word; /_ IE */
> }`

I've tried that, I've tried increasing the width, I've tried deleting everything label from the css file but I still can't get the text to stop wrapping.   I've also tried adding:

```
 scaleMinSpace: 100
```

but nothing I do has had any real effect on it. Any suggestions?

**Comment by gionkunz** [comment]
Controlling the space you have on the left side for the y-axis labels is controlled by:

``` javascript
axisY: {
  offset: ...
}
```

Setting the offset to a large enough number will expand the foreignObject element used to contain the label. This will fix the word wrapping. With `white-space: nowrap` you can force the label to be on one line.
