### ISSUE TITLE
Line Chart with percentage

### ISSUE THREAD

**Issue by PhilippZTUL** [chartist-js/chartist#792]
Hey there!

I am trying to set up a line chart with percentages on the Y-Axis. The data series have float values between 0 and 1, but I would like to have the axis labeled with 0% to 100%, with ticks of 10%. How do I do this?

My current code is this:

```
new Chartist.Line('.ct-chart', data, {
        axisY: {
            type: Chartist.FixedScaleAxis,
            ticks: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1],
            low: 0,
            high: 1
        },
        showPoint: false
    });
```

Thanks in advance!

**Comment by gionkunz** [comment]
``` javascript
new Chartist.Line('.ct-chart', data, {
        axisY: {
            type: Chartist.FixedScaleAxis,
            labelInterpolationFnc: function(value) {
              return (value * 100) + '%';
            },
            ticks: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1],
            low: 0,
            high: 1
        },
        showPoint: false
    });
```

**Comment by gionkunz** [comment]
For the future:

**Comment by gionkunz** [comment]
Please use http://stackoverflow.com/ for these kind of questions, we should only track bugs, feature requests or questions on internals within this Github repository.

**Comment by gionkunz** [comment]
Please re-open if you're still facing issues
