### ISSUE TITLE
default horizontalBar height is compressed

### ISSUE THREAD

**Issue by flyfloor** [chartist-js/chartist#794]
<img width="1393" alt="2016-09-22 7 28 45" src="https://cloud.githubusercontent.com/assets/5626417/18746585/d8f3ca00-80fa-11e6-8693-56ccd59f7f5c.png">

**Comment by gionkunz** [comment]
You're missing a container height I guess. Please read about intrinsic containers here: https://gionkunz.github.io/chartist-js/getting-started.html#as-simple-as-it-can-get

**Comment by gionkunz** [comment]
Please re-open if needed. For the future:

**Comment by gionkunz** [comment]
Please use http://stackoverflow.com/ for these kind of questions, we should only track bugs, feature requests or questions on internals within this Github repository.
