### ISSUE TITLE
Fetch chart from chartist using Html2Canvas

### ISSUE THREAD

**Issue by preetcam** [chartist-js/chartist#795]
Hi,

I am trying to convert the whole html page to PNG, so I am using Html2Canvas on top of chartist.

Bt I am not able to fetch chart data, but I am able to fetch all other elements from that page. 
I also included the sample svg element and I am able to fetch that svg element. But I am not able to fetch the chart.

**Comment by gionkunz** [comment]
There are still open issues with this mostly related to #813, #810 and #814 . Please tack those issues to see progress

**Comment by m7ammad7assan** [comment]
this is still a problem for me
