### ISSUE TITLE
Customize labels on gauge

### ISSUE THREAD

**Issue by pruhstal** [chartist-js/chartist#796]
Hi there,

I've found the following example, but am curious if I could customize the labels on each of the sections of this gauge:

http://jsbin.com/boqonawufi/2/edit?js,output

Essentially I want to replace the `50` on either portion of the chart with a custom label.

Has anyone done anything similar?

**Comment by gionkunz** [comment]
Hi, sure. Just provide `labels` array to the data object.

``` javascript
new Chartist.Pie('.chart', {
  series: [20, 80],
  labels: ['Apples', 'Bananas']
});
```

**Comment by pruhstal** [comment]
@gionkunz awesome! Thank you so much!
