### ISSUE TITLE
Add more tests and refactor to make code more testable

### ISSUE THREAD

**Issue by gionkunz** [chartist-js/chartist#8]

**Comment by valotas** [comment]
Shall I put the tests under `source/scripts` named with a `spec.js` suffix? I really  do not like creating test in a different folder.

**Comment by gionkunz** [comment]
I also like to put test files into the folder where the component under test lives. However, for a library project with less components I don't see the same benefit as with an application where you might end up with 30+ components. Also it's still quite common to use a test folder and given possible future contributions with people who are more used to a test folder, I'd rather go with the current approach.

**Comment by gionkunz** [comment]
It would be awesome if the project also contains everything required so we can run the tests on Travis!

**Comment by valotas** [comment]
I'll start with the tests first :)

**Comment by valotas** [comment]
And I think I'll integrate first istanbul so that I'll know what to test

**Comment by gionkunz** [comment]
Cool, istanbul is awesome! :-)

**Comment by gionkunz** [comment]
As we have now some code coverage I'll close this issue. There is still need for more tests but this is no longer a blocker for 1.0.0
