### ISSUE TITLE
Multiple lines with different resolution in one chart. 

### ISSUE THREAD

**Issue by jensstruemper** [chartist-js/chartist#802]
Hi! 
I'd like to use a line chart with two different lines having different resolution on the x axis. The first line would be based on static data, lets say eleven different vales (from 0 to 300 in steps of 30) The second line shall be based on dynamic data and show a new datapoint in steps of "1". 
I fiddled around with the auto and fixed scale options but it didn't really make a difference. Also, I added an additional label array for the second data series but then both spans wouldn't line up, so the 0 to 300 in steps of 30 would't match to 0 to 300 in steps by 1.  
I didn't find an example which would come close to want to achieve, so perhaps somebody could point me in the right direction. I should mention that I'm using chartists with the angular2 wrapper in an ionic 2 project. Thanks, Jens

**Comment by gionkunz** [comment]
Hi there. Using FixedScaleAxis with x/y data should work for your use-case. Check this example: http://jsbin.com/lokozu/edit?html,css,js,output

**Comment by jensstruemper** [comment]
ok, I got it! Thanks for your swift response! Cheers,Jens
