### ISSUE TITLE
Required node version has increased from 0.8 to 5.5

### ISSUE THREAD

**Issue by jtimlin-immt** [chartist-js/chartist#803]
Looking at the package.json, it seems that the latest release of chartist (0.9.8) has increased the required node version to 5.5, compared to node version 0.8 in the previous release of chartist (0.9.7). Was this intentional? As the current LTS version of node is 4.6, this seems like a fairly big restriction.

**Comment by gionkunz** [comment]
Hi there. Well, I'm not really concerned too much about this since we only use node for our tooling. As long as all the tools work as expected we should be fine. I guess we should stick to 4.x LTS since it's in active mode this October.

Let's move back to 4.6 with the next patch release.

**Comment by jtimlin-immt** [comment]
Thanks for the reply. I noticed the issue when trying to use [Yarn](https://github.com/yarnpkg/yarn) to install chartist, which fails saying the engine version isn't met (Since I'm using node 4.6).

**Comment by gionkunz** [comment]
I'll now switch to 6.9.0

**Comment by jtimlin-immt** [comment]
Sorry to harp on about it, but I still think this will be a problem for many users, including anyone who uses Yarn. The "recommended for most users" version of node is 4.6, at least right now.

**Comment by gionkunz** [comment]
Im using Yarn with 6.9.0 without any issues. Besides that, its now the officially active LTS version. Also again, this does not affect Chartist users, only contributors.

**Comment by jtimlin-immt** [comment]
Actually, if you look at the nodejs website, both node versions are LTS versions, with the 4.6 version listed as "recommended for most users". And it does affect chartist users, as it breaks the ability to install chartist using Yarn when using node 4.6.

**Comment by gionkunz** [comment]
Well thats true for users using browserify or webpsck i guess. Also for dependent packages. We can lower the required version in the package json to 4.6 but I just want to keep the .nvmrc so that Im sure the build server and my contributors test with 1 version.
