### ISSUE TITLE
gulp serve : serves blank page sometimes

### ISSUE THREAD

**Issue by preetcam** [chartist-js/chartist#804]
Hi,

If I frequently make changes to my UI, sometimes my UI crashes and using gulp serve shows blank page. Every time this happens I need to clone my project and start from scratch.
There is no error in console, API and UI.

Please share if you know the root cause

I also tried gulp build and gulp clean. But dint work. Could you please guide me.

server.js file is as below: 
'use strict';

var gulp = require('gulp');

var util = require('util');

var browserSync = require('browser-sync');

var middleware = require('./proxy');

function browserSyncInit(baseDir, files, browser) {
  browser = browser === undefined ? 'default' : browser;

  var routes = null;
  if(baseDir === 'src' || (util.isArray(baseDir) && baseDir.indexOf('src') !== -1)) {
    routes = {
      '/bower_components': 'bower_components'
    };
  }

  browserSync.instance = browserSync.init(files, {
    startPath: '/',
    server: {
      baseDir: baseDir,
      middleware: middleware,
      routes: routes
    },
    ghostMode: false,
    browser: browser
  });

}

gulp.task('serve', ['watch'], function () {
  browserSyncInit([
    '.tmp',
    'src'
  ], [
    '.tmp/{app,components}/**/*.css',
    'src/{app,components}/**/_.js',
    'src/assets/images/__/_',
    '.tmp/_.html',
    '.tmp/{app,components}/__/_.html',
    'src/_.html',
    'src/{app,components}/__/_.html'
  ]);
});

gulp.task('serve:dist', ['build'], function () {
  browserSyncInit('dist');
});

gulp.task('serve:e2e', ['wiredep', 'injector:js', 'injector:css'], function () {
  browserSyncInit(['.tmp', 'src'], null, []);
});

gulp.task('serve:e2e-dist', ['build'], function () {
  browserSyncInit('dist', null, []);
});

<img width="1272" alt="screen shot 2016-10-13 at 8 03 27 pm" src="https://cloud.githubusercontent.com/assets/4131188/19374496/d9791034-9180-11e6-8bf3-c9d315d8c96a.png">

**Comment by gionkunz** [comment]
Closing since this is not at all related to Chartist.
