### ISSUE TITLE
Not able to dynamically change line/area color of graph

### ISSUE THREAD

**Issue by SilvioLi** [chartist-js/chartist#805]
Hi,

I've been trying to change the 'ct-line' and 'ct-area' color of a graph when a user clicks on a button.

I tried mostly with JQuery:

```
  $('.ct-series-a .ct-line').css('stroke', 'pink');
  $('.ct-chart .ct-series-a .ct-area').css('fill', 'orange');
```

I've tried adding all classes from ct-chart to ct-area/ct-line. I've tried only typing $('ct-line'). There are many things I attempted to do for the past hours, but nothing seems to work.

The only class I am able to change onClick is the 'ct-chart. For example:  $('.ct-chart').css('background-color', 'yellow');

Any help is appreciated.

**Comment by gionkunz** [comment]
Hi, did you follow this guide? http://gionkunz.github.io/chartist-js/getting-started.html#colour-up-your-charts

**Comment by inthenameofmusik** [comment]
Hello @gionkunz. The Section titled "Dynamic Colouring" at the URL you provided, says that there is a live example below showing off dynamic coloring of graphs. I believe the actual live code and example is missing from the webpage. Is there anyway to get access to that as this section particularly interests me.

**Comment by gionkunz** [comment]
Its not missing for me. Sure youre in the right section?

**Comment by SilvioLi** [comment]
Hi @gionkunz. Sorry for the late reply. I found the right section and will give it a try a bit later. I will let you know how it goes.

**Comment by SilvioLi** [comment]
Hello @gionkunz. It worked like a charm, I'm not sure if @inthenameofmusik is still having issues with it.

I will close this issue for now. Thanks a lot!
