### ISSUE TITLE
Convert .pem to .cert and .key file

### ISSUE THREAD

**Issue by preetcam** [chartist-js/chartist#806]
Hi,

I am trying to fetch .key and .crt file from my .pem file. Could you please guild me with the steps. I am not much familiar with OpenSSL commands. I tried various ssl commands but not able to fetch the key.
Please guide. 

Or can I directly use .pem in apache conf file.?

**Comment by gionkunz** [comment]
Hi Fellow, I think your issue ended up in the wrong repository :-) I'll close that for you.

Cheers
Gion
