### ISSUE TITLE
ChartistJS Angular2 - chart only rendering after resizing window

### ISSUE THREAD

**Issue by gwsampso** [chartist-js/chartist#807]
I understand this is not exactly a issue with Chartist, rather an issue with how I'm capturing my data.

I'm trying to render a chart using ChartistJS

Whats weird is that if i resize the window my charts data displays.

This suggests I'm rendering the Chart with incomplete data.

Currently I am using my API service to get my data.

Below is my component

I would love your help here please

Thanks

GWS

`import { Component, ViewEncapsulation, 
  ChangeDetectionStrategy, ChangeDetectorRef } from '@angular/core';
import { ChartistJsService } from './chartistJs.service';
import { PortfolioReturns } from './returns-interface';
import { BaThemeConfigProvider } from '../../../../theme';

@Component({
  selector: 'chartist-js',
  encapsulation: ViewEncapsulation.None,
  styles: [require('chartist/dist/chartist.css'), require('./chartistJs.scss')],
  template: require('./chartistJs.html'),
  providers: [ ChartistJsService ]  
})

export class ChartistJs {

  errorMessage: string;
  returns: PortfolioReturns[];
  arr = [];
  seriesdata = [];
  lablesdata = [];
  isDataAvailable : boolean = true;

  data = {
    simpleLineOptions: {},
    simpleLineData: {}
  };

  constructor( private _chartistJsService: ChartistJsService, 
  private _baConfig: BaThemeConfigProvider,
  private _cdRef: ChangeDetectorRef ) {
  }

  ngOnInit() {  
    this.ChartistChart();
     }

ChartistChart() {

 let chartdata = {
  labels: this.getlablesdata(),
  series: [ this.getseriesdata(),
  ]
};

 this.data = {
    simpleLineOptions: {
      color: this._baConfig.get().colors.defaultText,
      fullWidth: true,
      height: '300px',
      chartPadding: {
        right: 40
      }
    },
    simpleLineData: chartdata
    };
 }

 getseriesdata() {
   this._chartistJsService.getReturns()
            .subscribe((res: PortfolioReturns[]) => {
                this.returns = res;
                for (let i = 0; i < this.returns.length; ++i) {
                   this.seriesdata.push(this.returns[i].logReturnGross.toString());
    }} );
    return this.seriesdata;
  }

 getlablesdata() {
   this._chartistJsService.getReturns()
            .subscribe((res: PortfolioReturns[]) => {
                this.returns = res;
                for (let i = 0; i < this.returns.length; ++i) {
                   this.lablesdata.push(this.returns[i].performanceDate);
                  }} ) ;
    return this.lablesdata;
  }

   getResponsive(padding, offset) {
    return this._chartistJsService.getResponsive(padding, offset);
  }

}`

**Comment by gionkunz** [comment]
Hi, it's very hard to tell by this code snippet. Can reproduce the issue by putting your example online at https://plnkr.co/ ?

**Comment by gwsampso** [comment]
Hi thanks for your response, I understand it's hard to tell from the snippet (especially since i didn't format it sorry). I'll try and reproduced an example but given the complexity of the base project I'm really unsure how long that will take me. 

I've also raised the issue with the dashboard framework I've forked [https://github.com/akveo/ng2-admin]

So they may have so more information.

I'm thinking I may need to do the manipulation of my JSON data within my dataservice or try and following this solution [http://stackoverflow.com/questions/35655361/angular2-how-to-load-data-before-rendering-the-component?rq=1](url)

**Comment by gwsampso** [comment]
Do you know of a way to upload projects to plnkr?

**Comment by gwsampso** [comment]
The problem was solved by .subscribe after my web service get

```
ChartistChart() {
 this._chartistJsService.getReturns()
        .subscribe((res: PortfolioReturns[])  => {
            this.returns = res;
            for (let i = 0; i < this.returns.length; ++i) {
               this.seriesdata.push(this.returns[i].logReturnGross);
               this.lablesdata.push(this.returns[i].performanceDate.toString());
              };
               this.data = {   
                simpleLineOptions: {
                  color: this._baConfig.get().colors.defaultText,
                  fullWidth: true,
                  height: '300px',
                  chartPadding: {
                    right: 40
                  }
                },
                simpleLineData: {
                  labels: this.lablesdata,
                  series: [ this.seriesdata]
                }
                };
            });
        }`
```

**Comment by gionkunz** [comment]
Im glad you were able to resolve the issue :-) ill close this issue now. Cheers
