### ISSUE TITLE
Review number precision and rounding within Chartist

### ISSUE THREAD

**Issue by gionkunz** [chartist-js/chartist#815]
We've had couple of issues with the latest version of Chartist with Number rounding and rounding issues. We should try to fix those issues and simplify the solution in that regards. A pragmatic approach would be appreciated.

CC @hansmaad

**Comment by danielserrao** [comment]
I'm not sure if this was already solved. But a easy workaround it to use this:

`          'axisY': {
            'labelInterpolationFnc': function(value) {
              return value.toFixed(2);
            }
          }`
