### ISSUE TITLE
Complete stand alone web page example for javascript newbies

### ISSUE THREAD

**Issue by maphew** [chartist-js/chartist#818]
Hi, I'm coming at chartist as someone who knows how to build html + css pages by hand but doesn't know anything significant javascript. It would be good to have an example that shows the beginning how Chartist is loaded and used in a page. The existing [examples page](https://gionkunz.github.io/chartist-js/examples.html) shows how to use and modify the different chart types starting mid-stream, after the javascript library has already been loaded and instantiated.

Say we take the Single Line Chart as our starting point, where does the code `new Chartist.Line('.ct-chart', {  labels: ... });` go? Inside the web page's header in a `<script>` tag? What if our data is in a .csv?

Maybe I'm not your target audience. That's ok too, let me know and I'll not add more noise here. ;-)

**Comment by gionkunz** [comment]
Did you try looking at the Getting started pages? :-)

**Comment by maphew** [comment]
Yes I did, but... "Create your first chart" shows a "var data = ..." island, but not where it goes. I got lost and started looking at the examples page to see where to put it, and just got more confused.

After a a night's sleep and reading the rest of the Getting Started page, specifically the "more than on chart section" it looks like var does go inside `<script>`(?) Not sure if it makes a difference if data is before or after `new.Chartist.bar.`  And so on.

I think if the examples on that page were bundled as a complete all in one zip bundle, where I could inspect everything at once it would be clearer to me how the pieces fit together.

thanks for the kind response btw. I was braced for "hey dummy, go .." ;-o

**Comment by gionkunz** [comment]
Okay, no problem :-) Everyone needs to start somewhere. Here's a simplified example:

``` html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>Chartist</title>
  <link href="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css" rel="stylesheet" type="text/css" />
</head>
<body>
<script src="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
<div class="ct-chart ct-golden-section"></div>
<script>
  var data = {
    labels: ['One', 'Two', 'Three'],
    series: [
      [8, 13, 21],
      [1, 2, 3]
    ]
  };

  var options = {
    fullWidth: true,
    showArea: true
  };

  var chart = new Chartist.Line('.ct-chart', data, options);
</script>
</body>
</html>
```

With this, and the example pages, you should be fine.

**Comment by maphew** [comment]
thank you!
