### ISSUE TITLE
re-order svg output

### ISSUE THREAD

**Issue by bobhuf** [chartist-js/chartist#82]
The current svg output of a line chart with area enabled is:
- labels
- grid
- line
- area
- points

Can this be changed to an order of my choosing? My issue is that at the moment the area is covering up parts of my line:
![Image](https://dl.dropboxusercontent.com/u/2177001/Schermafbeelding%202014-11-13%20om%2015.12.34.png)

Adjusting opacity won't fix this. Ideally, I would also prefer the grid to be on top of the area.

**Comment by gionkunz** [comment]
Hi there. So you'd like to have a solid color for your area is this correct? You'd not be fine with an area that is black and has opacity of lets say 0.2 ?

**Comment by gionkunz** [comment]
Currently the order can't be changed with configuration but you could use events (I guess it would be possible somehow) to modify the SVG dom. Also this will get easier and less hacky when #80 will be in the next release. There you could just switch the order or the different DOM elements each time after the chart is rendered.

**Comment by bobhuf** [comment]
That's right. Because my line would still partly be covered with another color.

But no worries, I moved around around some lines of code and was able to get the line to be outputted on top of the area.

Thanks.

**Comment by gionkunz** [comment]
Hi there. We now have an event `created` and you can do something like this:

```
chart.on('created', function(data) {
  //rearanging things after chartist created the DOM
});
```
