### ISSUE TITLE
Change stroke color of bar depending on bar size

### ISSUE THREAD

**Issue by SilvioLi** [chartist-js/chartist#821]
Hi,

I am trying to change the color of a bar (among many in the graph) if it's bigger than 40. See picture below:

<img width="552" alt="capture" src="https://cloud.githubusercontent.com/assets/17534190/19787447/a4385d9e-9c57-11e6-875f-6f6ba676f7b1.PNG">

I've been trying to change it inside the chart.on('draw')

```
chart.on('draw', function(data) {
  if(data.type === 'bar') {
       data.element.attr({
        style: 'stroke: red'
       });
  }
)};
```

but I'm not sure how to or if it's possible.

Any help is appreciated.

**Comment by gionkunz** [comment]
Yes, just one piece missing ;-)

``` javascript
chart.on('draw', function(data) {
  if(data.type === 'bar' && data.value > 40) {
       data.element.attr({
        style: 'stroke: red'
       });
  }
)};
```

**Comment by SilvioLi** [comment]
I tried that, but it didn't work.

So I did a for loop to check what values were being extracted.

`for (var value in data.value) {
        alert(value);  
    }`

The output was "x", "y","x", "y","x", "y","x", "y", and not the actual value.

**Comment by gionkunz** [comment]
Yes, sorry. Value on line and bar charts are so called multi value objects (contains the value for X and Y axis depending on which axis configuration you're using).

In your setup you'll need to do this:

``` javascript
chart.on('draw', function(data) {
  if(data.type === 'bar' && data.value.y > 40) {
       data.element.attr({
        style: 'stroke: red'
       });
  }
)};
```

**Comment by SilvioLi** [comment]
Wow. I knew it would be something simple.

Thank you very much, it works like a charm!

**Comment by yurtkuran** [comment]
need to do something similar...where does this code go?

**Comment by kannan09** [comment]
Hi,

I am trying to set each bar color different bar
