### ISSUE TITLE
As user I want to see Pie(donut) chart, if all series data is zero

### ISSUE THREAD

**Issue by Zadvornyi** [chartist-js/chartist#822]
For example:
I have Pie chart and when I get zero series data, I have an Error

```
chartist.js:1984_` Error: <path> attribute d: Expected number, "MNaN,NaNA45.5,45.…".(anonymous function) @ chartist.js:1984attr @ chartist.js:1974Svg @ chartist.js:1941constr @ chartist.js:1678elem @ chartist.js:2002createChart @ chartist.js:4171initialize @ chartist.js:1842
chartist.js:1984 Error: <text> attribute dx: Expected length, "NaN".
```

As user I want to see "stub" chart:
![image](https://cloud.githubusercontent.com/assets/10829855/19802314/c689176c-9d0b-11e6-900e-c85dda271bb2.png)
Something like that

Thank you.

**Comment by gionkunz** [comment]
That's the dilemma with Pie charts. What do you draw when there are no values? Or just one value, which would always make 100%?

If you want to display a stub chart, you can currently just pass a dummy value greater than 0.

``` javascript
new Chartist.Pie('.ct-chart', {
  labels: [],
  series: [1]
});
```

To indicate and style your stub chart you can use the created event to check for series count and add an additional class:

``` javascript
var chart = new Chartist.Pie('.ct-chart', {
  labels: [],
  series: [1]
}, {
  donut: true
}).on('created', function(context) {
  if (chart.data.series.length === 1) {
    context.svg.addClass('ct-stub');
  } else {
    context.svg.removeClass('ct-stub');
  }
});
```
