### ISSUE TITLE
drawing line graphics with the time (hours, minutes) ?

### ISSUE THREAD

**Issue by KiryaAfimin** [chartist-js/chartist#824]
Hello ! Is it possible to draw a graph based on minutes, hours? Here is a link to the [Fiddle](http://jsfiddle.net/3uL7zu4o/151/) schedule.

![2016-10-31 16 03 33](https://cloud.githubusercontent.com/assets/21101743/19850619/9944acf6-9f83-11e6-9bb3-a7b2be0e8d4b.png)

**Comment by kezkankrayon** [comment]
@KiryaAfimin, try changing line 49 of your javascript to `return moment(value).format('H:mm');`.
