### ISSUE TITLE
Incorrect span XML namespace

### ISSUE THREAD

**Issue by alfmatos** [chartist-js/chartist#826]
I've been trying out several ways to convert the chartist svg into a canvas/png. One of the reasons it kept failing was due to incorrect svg namespaces on the span elements.

Span elements are generated with `xmlns="http://www.w3.org/2000/xmlns/` but the xml serializer only works with `xmlns="http://www.w3.org/1999/xhtml`

I've tracked this down through http://stackoverflow.com/questions/36534581/svg-to-image-conversion-trouble.
I've hacked the fix on the client side through:
```
var svg = document.querySelector('svg');
var elements = svg.querySelectorAll('span');

for (var i=0, max=elements.length; i < max; i++) {
  elements[i].setAttribute('xmlns', 'http://www.w3.org/1999/xhtml');
}
```

This generates a proper SVG that doesn't break `XMLSerializer()).serializeToString(svg)` calls.

Should this be fixed on the svg generation?

**Comment by alfmatos** [comment]
Turns out the fix looks quite simple, as you already keep track of namespaces:

```
var content = '<span class="' + classes.join(' ') + '" xmlns="' + Chartist.namespaces.xhtml + '" style="'
```

Have a look at https://github.com/alfmatos/chartist-js/commit/e5d1561bcdc7f94b8761a9318ed9ba1588acd376 and let me know if you want a PR.

**Comment by gionkunz** [comment]
Hi there, thanks for the investigation. I think that's perfectly valid. Can you make a PR for this? Cheers

**Comment by alfmatos** [comment]
Awesome. Created new pull request https://github.com/gionkunz/chartist-js/pull/827.

**Comment by alfmatos** [comment]
Pull request #827 effectively solves the issue. Closing.
