### ISSUE TITLE
Label's height

### ISSUE THREAD

**Issue by wekii** [chartist-js/chartist#828]
Hi,

I'm doing some bar chart and I noticed that the last label on axisY always has different height (30px) than other labels on axisY.

Is it possible that this last label has the same height as all other labels on axisY?

Also, is it possible to achieve that all lables on axisX have height which is the same as axisY labels height?

Best regards.

**Comment by minusf** [comment]
i see the same issue.  `30px` seems to be hardcoded to width/height of the last label on the axis.

consider this screenshot, how the top label sticks out with its height:

<img width="317" alt="screenshot 2018-12-14 at 11 35 14" src="https://user-images.githubusercontent.com/3632883/49998704-40f7ed00-ff95-11e8-999c-c17fad97d22e.png">

is there a reason why the calculation is not applied to the last element?

**Comment by Gratouille** [comment]
Same issue here. Could be great to know why the last one isn't like its siblings.

Setting the same height for all the labels in the draw event doesn't change the problem, last one is always 30px height.

![image](https://user-images.githubusercontent.com/13222018/63170710-2ac99180-c03a-11e9-8a00-ab53ff45fcf9.png)

I'll add that I don't have this issue with only 5 elements on my Y axis. Only with ~10 (chart's height is 250px).

**Comment by artuska** [comment]
Same problem — last label is always 30px in width or height.

**Comment by Arantiryo** [comment]
Hello @artuska 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the issue is still relevant to you so we can further look into it!
