### ISSUE TITLE
CDN latest has old version

### ISSUE THREAD

**Issue by Kimball31** [chartist-js/chartist#829]
//cdn.jsdelivr.net/chartist.js/latest/chartist.min.js has Chartist.js 0.9.8, not 0.10.0

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage

Example https://cdn.jsdelivr.net/npm/jquery@3.1.1
Example directory listing https://cdn.jsdelivr.net/npm/jquery@3.1.1/

**Comment by gionkunz** [comment]
This should be fine now, I'm closing this issue.
