### ISSUE TITLE
Predefined month labels in combination with MOMENT.JS dates

### ISSUE THREAD

**Issue by adilbenmoussa** [chartist-js/chartist#831]
First of all i want to thank you this amazing library!

My question is:
Is there any way of having a predefined labels `['januari', 'februari', 'maart', 'april', 'mei', 'juni', 'juli', 'augustus', 'september', 'oktober', 'november', 'december']` in combination with date object?

it is almost the same as `TIME SERIES WITH MOMENT.JS` the only different is that it should put the predefined months in the labels, and draw the date object data in the corresponding month range.

Looking forward for you answer.

Note: if the answer is no, can you please give me some hints for extending the `Chartist.Axis` to achieve that.

Regards,
Adil

**Comment by adilbenmoussa** [comment]
No one? :(

**Comment by adilbenmoussa** [comment]
I decided to create my own solution for this issue and share it here:
link: https://github.com/adilbenmoussa/chartist-plugin-months-axis
codepen: http://codepen.io/benmoussa/pen/qqJgPB/
Note there is one know issue with the plugin: https://github.com/adilbenmoussa/chartist-plugin-months-axis/issues/1

**Comment by gionkunz** [comment]
Hi @adilbenmoussa I'm so sorry for the late reply. I've been under water with other things. I'm very happy you're created your own plugin for your use case. That's exactly the reason why we've created the plugin architecture in the first place. Nice one!

We're working on Chartist 1.0.0 release which will include a customizable TimeAxis.

I'll close this issue for now.

**Comment by adilbenmoussa** [comment]
Thanks @gionkunz!
