### ISSUE TITLE
Issue with x/y pair data series

### ISSUE THREAD

**Issue by jnehring** [chartist-js/chartist#833]
I want to draw a scatter plot using Chartist. The data series consists of x/y pairs. The examples in the documentation show only simple arrays and no x/y pairs and I cannot get it running.

I have this code

```
var data = {
  labels: [1,2,3,4,5],
  series: [
    [{x:3, y: 3},{x: 4, y: 3}, {x: 4.2, y: 4}]
  ]
};
		
var options = {
  showLine: false
}

new Chartist.Line('.relation-chart', data, options);
```

and it creates this chart

![image](https://cloud.githubusercontent.com/assets/10537540/20179098/bef680ae-a754-11e6-845b-be2c407646f9.png)

As you see it ignores the "x" values. Is there a possibility to specify the x-values for each data point?

**Comment by gionkunz** [comment]
Series should be a list of series which include the x/y values. So:

``` javascript
series: [
  [{x: 0, y: 5}, {x: 10, y: 8}, {x: 12, y: 10}]
]
```

**Comment by gionkunz** [comment]
Oh sorry you have that already :-) The x axis is still the standard StepAxis. Switch to an AutoScaleAxis or FixedScaleAxis. Check the advanced part on the getting started page to see examples on how to switch axis types.

**Comment by jnehring** [comment]
That solved the problem for me. Thank you very much. The code in this example solved the problem: https://gionkunz.github.io/chartist-js/getting-started.html#switching-axis-type

**Comment by rgraciama** [comment]
Solve it to me to. Thanks.
