### ISSUE TITLE
Doesn't work on firefox 31.6.0esr

### ISSUE THREAD

**Issue by cartifon** [chartist-js/chartist#834]
In the documentation says that it should work in firefox 31, but it doesn't.

![captura de tela 2016-11-11 as 10 12 14](https://cloud.githubusercontent.com/assets/7103578/20214798/7ae77aa0-a7f7-11e6-9c3f-f05faf53a7b6.png)
![captura de tela 2016-11-11 as 10 12 24](https://cloud.githubusercontent.com/assets/7103578/20214799/7ae9c18e-a7f7-11e6-8e91-441fec7b4559.png)
![captura de tela 2016-11-11 as 10 12 33](https://cloud.githubusercontent.com/assets/7103578/20214800/7aea65f8-a7f7-11e6-9cfa-546314ca3ed8.png)
![captura de tela 2016-11-11 as 10 12 39](https://cloud.githubusercontent.com/assets/7103578/20214797/7ae71aa6-a7f7-11e6-8411-b16738ee53e1.png)

**Comment by iamtheddrman** [comment]
Has anyone looked at this? My company has a customer that needs to support FF 31 with our web application, and it's hopelessly broken with the current rendering issues in Chartist. FF 34+ seem to work without issue.

**Comment by cartifon** [comment]
@iamtheddrman, if you ALWAYS set the height and width of the chart, it will work.
