### ISSUE TITLE
Rotating scatter chart causes incorrect scale

### ISSUE THREAD

**Issue by JosefWN** [chartist-js/chartist#836]
0.9.5:
<img width="247" alt="screen shot 2016-10-25 at 22 07 59" src="https://cloud.githubusercontent.com/assets/12534742/19702517/4dddf4e8-9b00-11e6-9ff9-1287dafef088.png">

0.10.1:
<img width="244" alt="screen shot 2016-10-25 at 22 08 35" src="https://cloud.githubusercontent.com/assets/12534742/19702516/4dda1648-9b00-11e6-8f32-a53dbfd97008.png">

This is only after upgrading. I'm not changing anything in my own code.

Tried disabling all your CSS (and most of mine) to have a nearly naked version, but it looks the same. I tried offsetting the svg group and found that chartist seems to think that my container is bigger than it is, making it look like the points are misplaced. In fact, it's the scale of the background that is not the same as the scale of the plot area.

<img width="220" alt="screen shot 2016-11-08 at 23 55 57" src="https://cloud.githubusercontent.com/assets/12534742/20120982/6cb8e502-a60f-11e6-84b8-988440fac1c4.png">

The issue seems to be my CSS transform applied to the parent of ct-chart:
> transform: translateX(-50%) translateY(-50%) rotate(-22deg);

This regression was introduced in Chartist >0.9.5. Being able to transform the parent is a pretty neat use-case for chartist.

It does work if I apply my transform after your transform has been applied (by commenting it out when the page is rendered, then enabling it in Chrome developer tools), suggesting that the two transforms occur in the wrong order?

**Comment by gionkunz** [comment]
Hi sorry for the late reply. Can you please post a fully working example in order to reproduce the issue?

**Comment by JosefWN** [comment]
I can confirm this is still an issue in v0.11.0. Tried to do add the transform and top/left 50%, parent set to "position: relative" and div wrapping ct-chart set to "position: absolute" but it does not exhibit the same erratic behavior.

Will dig a bit deeper...

Sometimes after playing around with the Chrome dev tools it still looks wonky, until I close the dev tools toolbar (without reloading the page), then it starts looking proper all of a sudden. Very confusing... Could be some sort of edge case, but it appears in latest versions of Chrome/Safari/FF.

**Comment by JosefWN** [comment]
The cause is this commit: https://github.com/gionkunz/chartist-js/commit/79e00f6b5c3d4dbca57110945ae0e26110622324

The width/height calculations are off because of my initial rotation of the plot (the bounding box width/height are greater than the width/height pre-rotation). In my case, the width/height of the plot should be that of the bounding box before it was rotated.

To re-create this issue, a scatter chart has to be rendered initially using rotation.

I don't know which of these two solutions are favorable, perhaps it could be a setting?

**Comment by JosefWN** [comment]
I have patched my own code now, and can verify that the PR in question is causing this issue. With the patch reverting the PR, the latest release (0.11.0) works fine with rotated scatter plots.
