### ISSUE TITLE
X and Y scale text color 

### ISSUE THREAD

**Issue by BeginnerBen** [chartist-js/chartist#837]
Hi I would like to change the light grey X and Y scales to black, is there a way to do this is chartist js

**Comment by Arantiryo** [comment]
Hello @ahurlburt 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

To answer your question, it can be done with CSS, all labels share `ct-label` class.
