### ISSUE TITLE
dynamic data update

### ISSUE THREAD

**Issue by maciejbuchert** [chartist-js/chartist#838]
Hello. 
I'm creating service monitor, where I can see how my servers works on air.
Ajax run PHP script, which return ping value of server. JQuery adding this value to array. Chartist geting value from this array.
Code:

        var series = [];
        var time = 0;
        $(document).ready(function() {
            ping_server();
        });

        function ping_server() {
            time++;
            $.ajax({
                url: "ping.php",
                success: function (data) {
                    series.push({x:time,y:data});
                }
            });
            console.log(series);
            setTimeout(ping_server, 3000);
        }

        var chart = new Chartist.Line('.ct-chart-1', {
            series: [series]
        }, {
            fullWidth: true,
            axisX: {
                type: Chartist.AutoScaleAxis,
            },
            axisY: {
                showGrid: false,
            },
            lineSmooth: Chartist.Interpolation.simple(),
            showArea: true,
            showPoint: false,
            scaleMinSpace: 20,
        });

I have problem with refreshing data on site. Data refresh only when I open developer-tool on web browser.

**Comment by maciejbuchert** [comment]
Anybody ? :)

**Comment by mishli** [comment]
maybe try calling chart.update();
for me, it helped rerender the chart on tabs as they got stacked.

**Comment by maciejbuchert** [comment]
But I don't know how tu build this function? :/

**Comment by snhasani** [comment]
@drozdz I didn't test code, but I think it can be useful for you 😄 

```javascript
var pingChart = null;
var pingCounter = 0;
var pingChartInterval = 0;
var pingChartData = {
	labels: [],
	series: [new Array]
}

var pingChartUpdateHandler = function(callback) {
	callback = callback || function() {};
	$.get('ping.php').then(
		function(data) {
			pingChartData.labels.push(pingCounter++);
			pingChartData.series[0].push(data);
			pingChart.update(pingChartData);
			callback();
		},
		function(err) {
			console.log("$.get failed!", err);
		}
	);
}

var setPingChartInterval = function(intervalTimer) {
	pingChartInterval = setInterval(pingChartUpdateHandler, intervalTimer);
}

$(document).ready(function() {

	pingChart = new Chartist.Line('.ct-chart-1', pingChartData, {
		fullWidth: true,
		axisX: {
			type: Chartist.AutoScaleAxis,
		},
		axisY: {
			showGrid: false,
		},
		lineSmooth: Chartist.Interpolation.simple(),
		showArea: true,
		showPoint: false,
	});

	// first time draw chart
	pingChartUpdateHandler(setPingChartInterval(3000));
});
```

**Comment by maciejbuchert** [comment]
@snhasani Doesn't work. JS Console: 'Error: <path> attribute d: Expected number, "MNaN,190LNaN,157.…".'

**Comment by coax** [comment]
I'm using this:
```
//create array with 50 values
var activity_array = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];
//create line chart
var activity = new Chartist.Line('.ct-chart-1', {
	series: [activity_array]
}, {
	fullWidth: true,
	axisX: {
		offset: 0,
		showLabel: false,
		showGrid: false,
	},
	axisY: {
		offset: 0,
		showLabel: false,
		showGrid: false,
	},
	showLine: true,
	showPoint: false,
	showArea: true,
});
//call refresh function
Refresh();
//update chart every 3 seconds
function Refresh(){
	$.ajax({
		url: "ping.php",
		success: function(data) {
			//add new ajax data to existing array
			activity_array.push(parseInt(data));
			//remove first array entry
			activity_array.splice(1, 1);
			//update data object with new array
			var data = {
				series: [activity_array],
			};
			//update and refresh chart
			activity.update(data);
		}
	});
}
setInterval(Refresh, 3000);
```

My ping.php returns only 1 numeric value.
