### ISSUE TITLE
Is it possible to animate only the chart delta on update?

### ISSUE THREAD

**Issue by ahurlburt** [chartist-js/chartist#839]
I'm trying to generate a donut chart that goes from 0 - 360 deg as events are triggered. So for instance the chart may start with a 0-90 deg filled, then after second event it may be 0-180 deg filled.

I can achieve this by say setting the donut total to 100 and setting the series to be [ 25 ] for the first event and [ 50 ] for the second event and then calling chart.update.

This works as expected however, I haven't been able to animate the change. I used the example code to get the chart animating and this does work as described but everytime I call update the chart re-animates starting at 0. I'm trying to only animate the "growth" in the chart ie the path from angle 90 to 180. I tried manipulating the start angle in the chart.on("draw") function but this doesn't seem to affect anything. 

Is what I'm trying to achieve possible with the current library? If not is there a good place to start looking at how I could modify the code to achieve this?

Thanks

PS library is very simple to use so thanks for that!

**Comment by gionkunz** [comment]
Animating Arcs in SVG isn't that easy. Unfortunately there's no good approach for this at the moment. Donut charts can be animated using the stroke-dasharray trick also found on the example page on the chartist website. We'll have a nicer approach for animations in Chartist 1.0.0

**Comment by gionkunz** [comment]
I'll close this issue for now
