### ISSUE TITLE
Added a less version

### ISSUE THREAD

**Issue by ghost** [chartist-js/chartist#84]
I added a less version based on sass. Please find it in the pull request

**Comment by gionkunz** [comment]
Hi there. If we can't find a way to convert the sass files into less files during dist build time in the dev stack, I don't really see the point in maintaining two different code bases. If you're willed to keep this maintainable manually please go ahead and create a repository with your LESS port. If you do so I'll definitely mention you in the 3rd party list so people who use Less can spot you easily. I'll close this issue for now.

**Comment by pimbrouwers** [comment]
https://github.com/jonschlinkert/grunt-refactor
