### ISSUE TITLE
Some values not scaling properly along axis.

### ISSUE THREAD

**Issue by ahurlburt** [chartist-js/chartist#840]
Some values do not scale properly to take up full width of chart. For instance if I have a max value of 10, 100, 200, 300, etc these all take up full chart width, but a value of say 225 does not. See attached. Is this by design?

![screen shot 2016-11-19 at 3 36 33 pm](https://cloud.githubusercontent.com/assets/16481642/20458107/582397d0-ae71-11e6-913b-af67a23c0af5.png)

**Comment by Arantiryo** [comment]
Hello @ahurlburt 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the question is still relevant to you so we can further look into it!
