### ISSUE TITLE
Change axis color but the whole grid

### ISSUE THREAD

**Issue by YafimK** [chartist-js/chartist#841]
Is there any way to change the color of the main axis and not the rest of the grid? 
I.e. the main axis should be black and rest gray.

I've tried by catching the "draw" event and later on trying setting the style or trying to change the class of each one that it different than the first - but no success.
For example:
```
var chart = new Chartist.Line('.ct-chart', {
  labels: [1, 2, 3, 4, 5],
  series: [
    [1, 3, 2, 5, 3]
  ]
}, {
  fullWidth: true
});

chart.on('draw', function(data) {
  if(data.type === 'grid' && data.index !== 0) {
    data.element.setStyle="stroke:rgb(255,9,0);stroke-width:2";
  }
});
```

**Comment by metodribic** [comment]
You could set style of grids using this: 
```javascript
chart.on('draw', function(data) {
  if(data.type === 'grid' && data.index === 0) {
    data.element.attr({"style": "stroke:rgb(255,9,0);stroke-width:2"});
  }
});
```

but adding style via JavaScript is not the best solution, appending class on grid elements would be better in my opinion: 

```javascript
chart.on('draw', function(data) {
  if(data.type === 'grid' && data.index === 0) {
    data.element.attr({"class": data.element.attr('class')+" bold-grid"});
  }
});
```
and then define class bold-grid: 

```css
.bold-grid {
  stroke: #000;
  stroke-dasharray: 0px;
  stroke-width: 3px;
}
```

**Comment by juworld** [comment]
@metodribic 

This is cool, but I noticed that this will only work if my y-axis doesn't have any negative number.

![image](https://user-images.githubusercontent.com/4934557/36706780-73dc6a08-1ba6-11e8-8f52-d012fede2e44.png)


My dataset has y values less than zero. Hense, my x-axis is in the middle of the graph. If I were to change the x-axis color where index is not equal to 0, is there a way do to do that?

**Comment by nagualcode** [comment]
how to change the grid color?

**Comment by Arantiryo** [comment]
Hi @nagualcode 👋 

All grid lines share a class `ct-grid` and you can change the color with CSS.
