### ISSUE TITLE
Click events

### ISSUE THREAD

**Issue by peetwindhoek** [chartist-js/chartist#846]
What I am trying to do is allow the user to select data points on the graph and for me to now what selections the user made. Is that at all possible using chartist.js?

**Comment by peetwindhoek** [comment]
[http://stackoverflow.com/questions/40861541/chartist-js-and-events/40866702#40866702](http://stackoverflow.com/questions/40861541/chartist-js-and-events/40866702#40866702)

This helped me. 

Awesome work on the lib!!

**Comment by varshinichowdary27** [comment]
The above link is not working can you please mention clearly where you found the solution

**Comment by peetwindhoek** [comment]
Let me edit, the text is correct in the URL but the href might be wrong. Just copy the text and paste it in browser:
[https://stackoverflow.com/questions/40861541/chartist-js-and-events/40866702#40866702](https://stackoverflow.com/questions/40861541/chartist-js-and-events/40866702#40866702)
