### ISSUE TITLE
Missing Bars

### ISSUE THREAD

**Issue by ghost** [chartist-js/chartist#847]
after adding 16 data series the bars are not shown 

notice the missing bars in the middle of the graph.

![image](https://cloud.githubusercontent.com/assets/11362891/20881450/4339b3f8-bad4-11e6-8cd1-b6e4a02f9a94.png)

**Comment by ghost** [comment]
The problem was in the css

.ct-series-a, b ,c, ..., o but from p to z there is nothing that is why the bars where missing because they where colourless.

**Comment by gionkunz** [comment]
This will be addressed in a future version of Chartist #183
