### ISSUE TITLE
Add "ct-slice" class to all svg elements with "ct-slice-donut" or "ct-slice-pie"

### ISSUE THREAD

**Issue by blaues0cke** [chartist-js/chartist#848]
Just an idea, would make it easier to style both elements. What do you think?
In my case I want to set the `stroke-width` to `0` for all slices. So I have to do:

```
.ct-slice-donut,
.ct-slice-pie
{
    stroke-width: 0;
}
```

instead of

```
.ct-slice
{
    stroke-width: 0;
}
```

**Comment by Martinomagnifico** [comment]
Use css selector like this: (the ^= means 'starts with')
[class^="ct-slice-"] {stroke-width:0}

**Comment by blaues0cke** [comment]
@Martinomagnifico Nice, this is also an option. Thanks!
