### ISSUE TITLE
Rendering charts on detached nodes to allow templating 

### ISSUE THREAD

**Issue by tylrob** [chartist-js/chartist#855]
I see this issue has been discussed in the past, particular in #287. Is there any workaround or solution for wanting to render a chart on a detached node and then attaching that node to the DOM? My particular use case is with Backbone Marionette. I want to render the chart in a Marionette view client side and then use Marionette to attach that view to the DOM.

**Comment by Arantiryo** [comment]
Hello @tylrob 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the question is still relevant to you so we can further look into it!
