### ISSUE TITLE
Chartist.Bar X-Axis labels as Hyperlinks

### ISSUE THREAD

**Issue by ramarajubvvs** [chartist-js/chartist#856]
Hi

I need X-Axis labels as hyperlinks.  It is working fine in Chrome but not in IE.  The hyper link (anchor tag) is displaying as text.  Any help is appreciated?

Thanks
Veera

**Comment by jacobq** [comment]
Could you supply some code to demonstrate this (e.g. on jsbin.com)? I remember I had to modify the axis title processing code once to implement superscript and subscript text and the main challenge was that the elements were SVG not native HTML and markup was not being parsed; just passed through as text content.
