### ISSUE TITLE
JSON Data Chart

### ISSUE THREAD

**Issue by michaelmang** [chartist-js/chartist#859]
I searched through the issues and saw this example of using external JSON data to create a graph:
http://jsbin.com/wiyolaruka/edit?html,js,console,output

I can't figure out as to why it only works for bar graphs. Am I missing something?

Loving the library so far! Would love to see JSON example on the examples page.

**Comment by jacobq** [comment]
With a line chart the `series` property needs to be an array of arrays not just a single array. I'm not sure if this is a bug or by design, but you can modify your example to work by just wrapping the series value in another set of `[]`'s:

http://jsbin.com/budugo/1/edit?js,output

**Comment by michaelmang** [comment]
Great thank you!
