### ISSUE TITLE
How to show label on Y-axis instead of X-axis

### ISSUE THREAD

**Issue by erashu212** [chartist-js/chartist#860]
Hi @gionkunz,

Is there any way to show labels on Y-axis instead of X-axis.

Thanks

**Comment by Arantiryo** [comment]
Hello @erashu212 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the question is still relevant to you so we can further look into it!
