### ISSUE TITLE
How do I scale?

### ISSUE THREAD

**Issue by DreadBoy** [chartist-js/chartist#864]
I'm looking through examples and group (`<g>`) that contains paths is always scaled to match `<svg>`'s size but I can't replicate that. Whatever example I copy, graph (group containing paths) is smaller than container and sometimes not even centered. Am I missing something?

**Comment by FreedCapybara** [comment]
Looks like you can add the scaling classes found in the "Create your first chart" section of the getting started page https://gionkunz.github.io/chartist-js/getting-started.html hidden in the "show available aspect ratios" button.

`.ct-square` worked for me.
