### ISSUE TITLE
Which line is which series?

### ISSUE THREAD

**Issue by badtant** [chartist-js/chartist#865]
I have a line chart with some series. How can I determine which line is which. I've added name to the series but that doesn't show anywhere. I want a list of the colors (of the lines) and the matching series name. How do I get that?

```
{
      labels: ['Maio', 'Junho', 'Julho', 'Agosto'],
      series: [
        {
          name: 'oleo',
          data: [2.7, 2.6, 1.9, 1.5]
        },
        {
          name: 'margarina',
          data: [4.2, 4.5, 3.4, 2.8]
        },
        {
          name: 'acucar',
          data: [11.3, 11.2, 7.2, 5.7]
        }
      ]
    }
```

Thanks

**Comment by gionkunz** [comment]
Hi there, you can use this plugin: https://github.com/CodeYellowBV/chartist-plugin-legend
