### ISSUE TITLE
Y-axis labels not aligned in IE11 on horizontal bar chart

### ISSUE THREAD

**Issue by mheisig** [chartist-js/chartist#866]
I'm having trouble getting the y-axis labels aligned on a horizontal bar chart in IE11. Alignment is fine in Chrome, Safari and Firefox. I'm noticing the same problem on the Chartist example page:

![screen shot 2017-01-10 at 13 54 56](https://cloud.githubusercontent.com/assets/427274/21826475/76969520-d73c-11e6-8cbd-d97866f789cd.png)

**Comment by StK88** [comment]
+1, same issue

**Comment by sbaechler** [comment]
Same issue with the x-axis labels on a vertical bar chart. It looks like a flexbug.
Also mentioned in #268

**Comment by gionkunz** [comment]
IE can't render `foreignObject` and that's the reason why the labels are misaligned. Search for `foreignObject` in github to find some solution on how to fix the positioning using the `draw` event.

**Comment by mayank-adap** [comment]
This worked for me:
foreignObject span{
        height: 70% !important;
    }
