### ISSUE TITLE
Can chart animations be triggered only when the chart becomes visible on screen?

### ISSUE THREAD

**Issue by wadetregaskis** [chartist-js/chartist#867]
I've followed the examples in the 'Getting started' guide to add "build in" animations to my charts.  However, these animations trigger on page load (since I just create the charts immediately on load), regardless of whether they're visible or not.  I'd like to have the animations not start until the chart is actually visible to the end user (for some hopefully configurable definition of visible - e.g. only once the chart's baseline scrolls into view).

I did spend some time web searching, and reviewing the Github issues here, but found surprisingly few cases of other people trying to achieve the same thing, and no answers.

Is it possible to do this?  If so, can you point me in the right direction, please?

**Comment by gionkunz** [comment]
You should also check the SMIL documentation, since we're still using SMIL to build animations. However, for your use-case there would be a simple workaround to redraw the chart once the user scrolls the chart into the view. Simply call `chart.update()` once the chart is scrolled into the view.
