### ISSUE TITLE
How to fill labels dynamically according to raw api data in chartistjs in vanillajs?

### ISSUE THREAD

**Issue by itisnas** [chartist-js/chartist#868]
Hey there,

I'm pretty sure someone might have asked this (if so please direct me there).

I've looked over the documentation of chartistjs, but did not find any satisfactory answer.

So I have created a line chart (which works beautifully). However, the documentation has hardcoded the values for labels field followed by series like so:

`var chart = new Chartist.Line('.ct-chart', {`
      `labels: ["1", "2", "3", "4", "5"],`
      `series: [{`
        `name: 'series-1',`
        `data: [0, 2, 4, 8, 10, 8, 4, 2, 0, -2, -4, -4, 0, 4, 8, 4, 2, -5, -4, 0]`
      `}, {`
        `name: 'series-2',`
        `data: [-2.5, 0, 2, -2, 0, 2, 4, 8, 4, 2, 4, 8, 10, 8, 2, 0, -2, 4, 8, 10]`
      `}, {`
        `name: 'series-3',`
        `data: [-5, -5, -5, -5, -4, -2, 0, 2, 4, 8, 10, 10, 7, 8, 2, 0, 0, 0, 0, -3]`
      `}]`
    `}`

However, since I'm getting raw data from an API, I'd like to set the labels field according to the data taken from API, which means any number of labels can differ.

So I have this method which filters my data:

`var getLbl = function(callBack) {`
  `let labels = []`
  `DashBoard.CachedAPI.GDP(`
    `2010, 2015, i => {`
      `i.filter(j => j.country.value === "Arab World")`
        `.forEach(p => callBack(p.date))`
    `}`
  `)`
`};`
Let's assume the response for the method returns: 2010, 2011, 2012, 2013, 2014, 2015
How can I take each value above and place it in the labels field?

**Comment by Arantiryo** [comment]
Hello @bitabs 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the question is still relevant to you so we can further look into it!
