### ISSUE TITLE
Pie chart size

### ISSUE THREAD

**Issue by detilium** [chartist-js/chartist#873]
Creating a pie chart inside a bootstrap col-md-4 gives me some problems when it comes to the actual size of the chart. I can clearly see that width is set to 100%, but it doesn't really fill out everything. I can't seem to figure out what the issue lies. I've tried to override the width in the options object of the chart, but it doesn't seem to make any difference.

Basically I'd like the width to be 100% and the height to be automatic, thus filling out the entire col-md-4 width that the element has available. 

![pie-chart-size](https://cloud.githubusercontent.com/assets/7237574/22179152/71e9a68a-e04b-11e6-8fc4-cedbab009fb1.JPG)

Further information.

Here's the HTML markup:
```
<div class="col-md-4" id="#users">
    <svg xmlns:ct="http://gionkunz.github.com/chartist-js/ct" width="100%" height="100%" class="ct-chart-pie" style="width: 100%; height: 100%;">...</svg>
</div>
```

**Comment by gionkunz** [comment]
Just use a chart container with the `ct-square` class:

```html
<div class="col-md-4" id="#users">
    <div class="ct-chart ct-square"></div>
</div>
```

**Comment by detilium** [comment]
Did the job. Thank you.
