### ISSUE TITLE
Updating data with animation

### ISSUE THREAD

**Issue by kenteramin** [chartist-js/chartist#877]
Guys, is there some way to animate charts data updating/changing?

Like chart.js or google-charts do.

**Comment by AlexanderKozhevin** [comment]
Yeah, or like here. 
http://www.chartjs.org/samples/latest/charts/line/basic.html

I tried to animate it via events but looks like it's not the case.

**Comment by Arantiryo** [comment]
Animations can be done via [the `animate` function](https://gionkunz.github.io/chartist-js/api-documentation.html#chartistsvg-function-animate). And here's [an example](https://codesandbox.io/s/github/chartist-js/chartist/main/sandboxes/line/path-animation).
