### ISSUE TITLE
Problem with axisY labels

### ISSUE THREAD

**Issue by abadondev** [chartist-js/chartist#878]
Hello,

I have a problem. A try to add labels (axisY), from 0 to 100 (every ten), but when I try to use

```
        var verticalLabels = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100];

        axisY: {
                labelInterpolationFnc: function (value, index) {
                    return verticalLabels[index];
                }
            }
```

I have labels only to 80. So max value of index is 8. I dont know why. What it depends on? Please help.

**Comment by Andi-Lo** [comment]
I can relate to that. Having the same problem

**Comment by Arantiryo** [comment]
Hello @abadondev 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the question is still relevant to you so we can further look into it!

Might be related to #1022.
