### ISSUE TITLE
Last x axis value label truncated for large x values

### ISSUE THREAD

**Issue by mwri** [chartist-js/chartist#879]
The last x axis value label can be truncated. This shows it:

    <div class="ct-chart ct-major-tenth"></div>
    <script type="text/javascript">
    var data = { series: [[{x: 100, y: 0.2}, {x: 10000, y: 0.26}, {x: 20000, y: 0.25}, {x: 100000, y: 0.29}, {x: 5000000, y: 0.37}]] };
    new Chartist.Line('.ch-chart', data, { axisX: { type: Chartist.AutoScaleAxis, scaleMinSpace: 30 } });
    </script>

**Comment by gionkunz** [comment]
Yes, we're currently not measuring text labels and adjust container spaces. You'll need to manually set `chartPadding: {right: xxxxx}`
