### ISSUE TITLE
chart.update() aborts other events on touch devices

### ISSUE THREAD

**Issue by Hazantip** [chartist-js/chartist#882]
My task is update line chart points on mouse/touch move.

`
this.chart = new Chartist.Line(container, data, options);
this.el = document.querySelector(container);
....
this.el.addEventListener('touchmove', (e) => {
  // ...do smth,, and at the end
  this.chart.update();
}
`

on desktop all ok(of course for desktop attached mouse events);
events triggering order:
- 'mousedown/touchstart'
- 'mousemove/touchmove'
- this.chart.update()
- !!! - update event calling `this.chart.on('create' )` event
- **!!!!! - HERE is a point when all my events aborts on touch devices**
- 'mousemove'
- this.chart.update()
- 'mousemove'
- this.chart.update()
- 'mousemove'
- this.chart.update()
.. etc

**Comment by Hazantip** [comment]
if i will attach all my events to the documents - problem will be partly solved;

Partly, because if i will start my touchmove from chart container i will get the problem that i described above.

If start from out of the chart container - everything work.

 At this moment i created div which like an overlay for my chart and attaching events to him, but this is just dumb workaround =(

**Comment by rodolv-commons** [comment]
Hallo! I am having the same issue (more or less), I have implemented a pinch behavior in Js which works fine with HTML canvas but it fails with chartist library. For debugging reasons I want simply to repaint the chart every time I move my finger onto the screen, modifying width and height of 3px, each time touchmove fires. Calling he update() on the chart method just stops everything, after the first fire of the touchmove event. Therefore, I have to leave the screen and repeat the touch. Did you get it?

**Comment by Arantiryo** [comment]
Hello @Hazantip 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the question is still relevant to you so we can further look into it!
