### ISSUE TITLE
Custom Y axis

### ISSUE THREAD

**Issue by rlcasper** [chartist-js/chartist#884]
I have a very varied data set I need to plot on a single bar chart, so some values are quite small and others are massive. This is making the small values very difficult to see. Is there a way to have custom yaxis values but give them the same space so 1,2,5,10,100,200

I can get the label I want using stepaxis but can each step be the same size visually?

(I know this is quite random but it's what the client wants it to look like!)

**Comment by gionkunz** [comment]
You'd want to use some sort of a logarithmic scale right? This is probably a duplicate of #64 then

**Comment by Arantiryo** [comment]
Duplicate.
