### ISSUE TITLE
Question: Create Control Charts?

### ISSUE THREAD

**Issue by coderabsolute** [chartist-js/chartist#885]
I wonder is it possible to create Control Charts which displays the horizontal lines for 'Upper Control Limit', 'Lower Control Limit' along with 'Median' on a Line Chart?

Here is the [link](https://www.spcforexcel.com/files/images/red_beads.png) which demonstrates what I want to achieve.

**Comment by willpnw** [comment]
Did you ever find a solution to this?

**Comment by coderabsolute** [comment]
@wilpatterson I didn't give a try. Unfortunately, the project didn't get kick off. But, am still interested to figure out how the `Control Charts` can be plotted using this library.

**Comment by Arantiryo** [comment]
Hello @coderabsolute 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the question is still relevant to you so we can further look into it!
