### ISSUE TITLE
Stacked Bar Chart Displaying with Inconsistent Width

### ISSUE THREAD

**Issue by joeantonelli** [chartist-js/chartist#886]
I'm using a stacked bar chart that displays at the correct width sometimes, and at an incorrect smaller width at other times, with no obvious pattern to the bug. Has anyone else encountered this issue? I've attached pics below. Thanks in advance.

Here's how the chart's supposed to look:

![stacked_bar_chart_correct](https://cloud.githubusercontent.com/assets/7494307/22863407/fc33f3d6-f171-11e6-8761-9402df1f961f.png)

Here's the error:

![stacked_bar_chart_error](https://cloud.githubusercontent.com/assets/7494307/22863410/1cd7961a-f172-11e6-9f00-300b7a77eb7b.png)

**Comment by Arantiryo** [comment]
Hello @joecantonelli 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the question is still relevant to you so we can further look into it!
