### ISSUE TITLE
vue js + chartist , how can i force redraw it?

### ISSUE THREAD

**Issue by g0ld3lux** [chartist-js/chartist#890]
ive check all possible solution and old thread here...

ive already tried using v-show  

which allows me to toggle the chart

i also add a watcher that will toggle it 

but i cant simple make it redraw the chart

i want it to redraw because all the axios fetch data

is not being drawn during the mounting of the component...

i also tried using windows event of resize ...

but its also not being able to show my chart...

the chart only display properly if

i click on one of the label

2nd if i resize the window...

please someone help me achieve the result i want thanks

**Comment by Yopadd** [comment]
Hi,

Have you tested [vue-chartist](https://github.com/Yopadd/vue-chartist) ?

**Comment by g0ld3lux** [comment]
Im having issue with that package , i can use this much better off than the one with vue js version, except i cant force redraw the chart

**Comment by roshimon** [comment]
@g0ld3lux Hi can you show me an example usage of this in Vue ?

**Comment by Arantiryo** [comment]
Hello @nerissaolaes 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the question is still relevant to you so we can further look into it!
