### ISSUE TITLE
Chart with much labels overlap

### ISSUE THREAD

**Issue by paddibr** [chartist-js/chartist#893]
Hi, I have a chart with many labels:

![chartist](https://cloud.githubusercontent.com/assets/9463756/23104888/8b0cb994-f6d6-11e6-8fa1-65803d23fc57.jpg)

How can I display just the half of them or get a better styling?

can be found here: https://www.kt-media.de/kunden/test/schlusskurse.php

**Comment by gionkunz** [comment]
Check this example: http://gionkunz.github.io/chartist-js/examples.html#line-scatter-random

You can use the line interpolation function and return null to skip a label.
