### ISSUE TITLE
Updating grunt-umd

### ISSUE THREAD

**Issue by gionkunz** [chartist-js/chartist#894]
We should update to the latest grunt-umd version #403

**Comment by powerbuoy** [comment]
Any progress on this? I'm unable to `import Chartist from 'chartist'` from my Aurelia CLI project.

**Comment by powerbuoy** [comment]
FYI v0.9.7 works fine.

**Comment by gionkunz** [comment]
No progress unfortunately, but any contribution would be much appreciated
