### ISSUE TITLE
Iframe problem

### ISSUE THREAD

**Issue by dextermoser** [chartist-js/chartist#896]
Hi,

I am new to chartist and github and this is my first question.

I am preparing an application with an **iframe menu**. The graph is working fine.
![1](https://cloud.githubusercontent.com/assets/25984200/23264893/93e666c4-f9eb-11e6-9c99-8d649fb17cda.JPG)

But when I refresh or come back to page the graphic is turn to this.
![2](https://cloud.githubusercontent.com/assets/25984200/23264911/a2cdc416-f9eb-11e6-8651-073e8920a7e0.JPG)

Here is my code
`<div class="ct-chart" id="chart"></div>

<script type="text/javascript" src="https://rawgit.com/gionkunz/chartist-js/master/dist/chartist.js"></script>

<script>
new Chartist.Line('.ct-chart', {
  labels: [
  
<% 
sql = "SELECT * FROM a" 
set query = Conn.execute(sql)
do while not query.eof
%>	  

	<%=query("1")%>,

<%
query.movenext
loop
%>  
  
  ],
  series: [
    [
	
<% 
sql = "SELECT * FROM a" 
set query = Conn.execute(sql)
do while not query.eof
%>	
	
	<%=query("2")%>,
	
<%
query.movenext
loop
%>	
	]
  ]
}, {
  low: 0,
  showArea: true,
});

</script></div>`

**Comment by Arantiryo** [comment]
Hello @dextermoser 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the question is still relevant to you so we can further look into it!
