### ISSUE TITLE
options width and height

### ISSUE THREAD

**Issue by andyleung** [chartist-js/chartist#897]
Hi, I try to resize my graph and follow the default example and adding
var options = {
    width : 800,
    height : 600
}
However, it has no effect. Tried on different browsers. 
Could you tell me how to fix it?

**Comment by silsha** [comment]
Hej, please try
```
var options = {
  width: '800px',
  height: '600px'
};
```
These parameters should be strings.

**Comment by andyleung** [comment]
Thanks Silsha. Got it. It works. 

Also, I forgot to put 'options' inside Chartist.line ... sorry, rookie mistake.
Please close this one.

**Comment by sydorT** [comment]
But now the chart is not responsive after we added height!

**Comment by djaho** [comment]
@sydorT If you want to keep the chart responsive, then you have to use the available aspect ratios. To use them, just add the correct class (e.g. .ct-major-tenth) to the chart container.
https://gionkunz.github.io/chartist-js/getting-started.html#create-your-first-chart
