### ISSUE TITLE
Enhancement request: getBarWidth function

### ISSUE THREAD

**Issue by AmitMY** [chartist-js/chartist#900]
I went over the API and I did not encounter a bar width getter. (may have missed one though)
An example use case is having a bar chart with unknown amount of bars (lets say, 2 to 10) and wanting that on 2 bars every bar would be 40%, and on 10 bars every bar would be 8%.

I am migrating from Chart.js, which automatically does that for bars.

**Comment by AmitMY** [comment]
Note, that a current solution is something like:
```
@for $i from 1 through 10 {
    line:first-child:nth-last-child(#{$i}),
    line:first-child:nth-last-child(#{$i}) ~ line {
        stroke-width: calc(100% / #{$i+1})
    }
}
```

Which is not ideal, because it does not generate for every N

**Comment by Arantiryo** [comment]
Hello @AmitMY 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the question is still relevant to you so we can further look into it!
