### ISSUE TITLE
Not showing on Firefox 51

### ISSUE THREAD

**Issue by tnvrsingh** [chartist-js/chartist#904]
Works just fine on Chrome and Safari but fails to draw anything on Firefox.

**Comment by gionkunz** [comment]
Hi there. Can you provide a reproducible code example?

**Comment by TheWebTech** [comment]
Hi we're experiencing the same issue, and are unsure why.
http://spin.d.pr/BXiDyh+


http://www-goodwillsew-com.sandbox.hs-sites.com/community-impact/2016-financials


Chart in other browsers displays as:
http://spin.d.pr/75CoCK+
