### ISSUE TITLE
On draw calling multiple times

### ISSUE THREAD

**Issue by sdrebel** [chartist-js/chartist#908]
Hi chart renders based on select option. Every time I update on draw, it's triggering multiple times.

**Comment by gionkunz** [comment]
Hi, the `draw` event is tiggered for each drawn element on the chart (grid lines, bars, lines, points etc.). If you're looking for an event for when the chart is fully drawn, you should use the `created` event.

**Comment by sdrebel** [comment]
Here draw will trigger and complete onload. Then when I select some option the chart needs render redraw again based on value that time it calls multiple times. Ex: I have  6 column bar , so draw should trigger 6 times right?it does but when on change of select option draw will trigger 12 times, again if you I do it will trigger 18 times .. like that it will go on ... Is there anyway I can clear it?

**Comment by gionkunz** [comment]
Please share your code so we can check what the issue might be. Cheers

**Comment by sdrebel** [comment]
Hey @gionkunz , Thank you so much.  I was doing the update each and every time I get the data. Now it's resolved.
