### ISSUE TITLE
How to increase the height of the yAxis

### ISSUE THREAD

**Issue by sdrebel** [chartist-js/chartist#911]
Hi 
I'm having stacked column. Is there anyway I can increase the y1 and y2 value or give a space? Because I'm adding the legend values here. Wherever values are less like 0.2, 0.3, 2, etc text is getting overlapped.

![untitled](https://cloud.githubusercontent.com/assets/19382262/24038642/5497827a-0b28-11e7-9151-42289f09d743.png)

**Comment by gionkunz** [comment]
How are you adding the values? Since this is not supported by the Chartist core, I guess you'd need to change your custom functionality to distribute the text.

**Comment by Arantiryo** [comment]
Hello @sdrebel 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the question is still relevant to you so we can further look into it!
