### ISSUE TITLE
NuGet packages

### ISSUE THREAD

**Issue by tiesont** [chartist-js/chartist#912]
Would it be okay for me to publish a NuGet (https://www.nuget.org/) package for this project? I'm going to create a package for my own use, but I won't publish it if it's not okay to do so.

Here are the NuGet packages I will be creating:

- [x] ChartistJS - https://www.nuget.org/packages/ChartistJS/
- [x] ChartistJS.Accessibility - https://www.nuget.org/packages/ChartistJS.Accessibility/
- [x] ChartistJS.AxisTitle - https://www.nuget.org/packages/ChartistJS.AxisTitle/
- [x] ChartistJS.FillDonut - https://www.nuget.org/packages/ChartistJS.FillDonut/
- [x] ChartistJS.PointLabels - https://www.nuget.org/packages/ChartistJS.PointLabels/
- [x] ChartistJS.Threshold - https://www.nuget.org/packages/ChartistJS.Threshold/
- [x] ChartistJS.Tooltip - https://www.nuget.org/packages/ChartistJS.Tooltip/
- [x] ChartistJS.Zoom - https://www.nuget.org/packages/ChartistJS.Zoom/

These will correspond to the equivalent repositories. If you have a NuGet account or want to create one, I will assign you as the owner, or you can tell me who should be the owner.

**Comment by gionkunz** [comment]
Sure! Go for it! :-)

**Comment by tiesont** [comment]
Cool beans. I'm going to create separate packages for the plugins, and then set this package as a dependency. I assume that's okay for the plugins **you** have created? 

I'll ask the same question for the third-party plugins.

**Comment by gionkunz** [comment]
That sounds fantastic :-)

**Comment by tiesont** [comment]
Okay, as you can tell by the updates and the referenced issues, I've published the main library and your plugins to NuGet. I'm waiting on permission for the other plugins to publish their packages.

Thanks!

**Comment by gionkunz** [comment]
Cool thats aswesome! Thanks for your efforts!

**Comment by tiesont** [comment]
All current plugins have been published. I'll go through the repos and check for updates, but this should be good-to-go.
