### ISSUE TITLE
Chart cannot be displayed by using with AngularJS ng-show directive

### ISSUE THREAD

**Issue by htetmyomyint-kmp** [chartist-js/chartist#913]
I am using Chartist with AngularJS.
I used ng-show to display only one chart according to user selection.
My code is like following:
`<ul>`
 `<li><a href="" ng-click="chart='line'"> Line Chart </a></li>`
 ` <li><a href="" ng-click="chart='bar'"> Bar Chart </a></li>`

`</ul> `
<div class="line-chart" ng-show="chart=='line'"></div>
<div class="bar-chart" ng-show="chart=='bar'"></div>

`<script src="js/sample-line-chart.js"></script>` <br>
`<script src="js/sample-bar-chart.js"></script>`
`
According to this, when I click "Line Chart", line chart will be shown. (This is also same to "Bar Chart").
Problem is that while line chart is displaying, I clicked "Bar Chart", at that time bar chart display is broken and vice vera. ( I attached capture for both expectation and actual). But when I open browser debugging tool (or if already opened, just adjusting size a little), chart is displayed correctly. 

For sample-line-chart.js and sample-bar-chart.js, I used example code from chartist web site.
And I used Firefox browser.

![actual](https://cloud.githubusercontent.com/assets/16056053/24125071/1532f996-0df5-11e7-891c-06abd295893b.png)
![expected](https://cloud.githubusercontent.com/assets/16056053/24125074/1922c770-0df5-11e7-912e-f5db40751005.png)

**Comment by HairMachine** [comment]
Hi there

I'd guess this is probably the same as your issue? https://github.com/willsoto/angular-chartist.js/issues/16

I had a similar problem but calling the update() method as described there fixed the issue.

**Comment by htetmyomyint-kmp** [comment]
Yes, this is same issue. 
For me, I solved by setting width and height manually.
Thank you very much @HairMachine .
