### ISSUE TITLE
How to assign a custom class for the line inside ct:series-name in stacked bar chart?

### ISSUE THREAD

**Issue by nosheen-javed** [chartist-js/chartist#915]
How can we assign custom class for a specific line only, inside series-name of stacked bar chart? I want to add a custom className with ct-bar.

![graph](https://cloud.githubusercontent.com/assets/23119591/24146838/595aa880-0e59-11e7-95d8-b9000d72516f.png)

Here is the code as well.

               labels: ['NY''],
		 series: [
				{
					className: 'ct-series-a',
					name: 'ABC',
					meta: 'one',
					data: [
							  {	
								meta:'one', 
								value: 5 , 
								className: 'my-custom-data-line',
							  }, 
							  {meta: 'two', value: 2 , classes: 'class'}, 
							  {meta: 'three', value: 4 , className: 'class'},
							  {meta: 'four', value: 4 , className: 'class'}
						
						]
				}]

**Comment by gionkunz** [comment]
Hi, that's not possible by default, since usually all objects in a series should look the same. What are you trying to achieve?

**Comment by nosheen-javed** [comment]
I am actually showing the Week progress of the Employee and I want to disable the bars for Weekends.

**Comment by gabrieldrs** [comment]
Wow, I was just looking for this too. I would like to be able to click certain points/bars/pie-slices and have them in a "selected" state, so adding a "selected" class to them would be really cool. Manually adding the class to the element is not an option, since the chart redraws itself on window resize...

**Comment by nosheen-javed** [comment]
But we can assign the color to the nth child of the series-name in css? I am actually trying to add the color in the css but its also not working.

**Comment by Arantiryo** [comment]
Hello @nosheen-javed 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the question is still relevant to you so we can further look into it!
