### ISSUE TITLE
Pie chart labels to image

### ISSUE THREAD

**Issue by msihe** [chartist-js/chartist#917]
I got an [object Object] when i try make pie labels to images, any help here?
Here is jsfiddle: https://jsfiddle.net/hxupngs3/

**Comment by gionkunz** [comment]
Hi, you need to get hold of the original data object and use the label index to get the object you've specified for the label. The draw event text property will be converted to string which results into [object Object].

https://jsfiddle.net/xej24khw/1/

**Comment by msihe** [comment]
Thanks!
