### ISSUE TITLE
Only display 4 string labels - Axis X 

### ISSUE THREAD

**Issue by ThomasGRILLERE** [chartist-js/chartist#918]
Hello !

I have 30 or more labels (1 for each day) but i only want to display 4 of them on my line chart.

How is it possible ?

Thank you !!!
![screen shot 2017-03-23 at 11 50 10](https://cloud.githubusercontent.com/assets/1277908/24244413/0ac16594-0fbf-11e7-881d-a1a49f0775d3.png)
![screen shot 2017-03-23 at 11 50 23](https://cloud.githubusercontent.com/assets/1277908/24244412/0ac064e6-0fbf-11e7-921c-6676c4ce5324.png)

**Comment by gionkunz** [comment]
Hi there, you can use `labelInterpolationFnc` and return null to skip labels / grid lines to be rendered. Check this example: https://gionkunz.github.io/chartist-js/examples.html#line-scatter-random

**Comment by ThomasGRILLERE** [comment]
Thanks !
