### ISSUE TITLE
Dynamically custom colors

### ISSUE THREAD

**Issue by Jeketerri** [chartist-js/chartist#919]
Hi, and sorry with my very bad English

I'm making a horizontal chart with ajax, I extract labels, data and colors from the database, and try to paint the chart with the colors of the database, I use two functions:
`
// use te custom colors
f_graph_custom_colors(nId, Fcc);
// painting the graph
f_graph_paint(nId, Fnombres, data_final); // nId is on graph is painted, Fnombres is an array of labels, and data_final is an array of arrays
`
I don't have a problem painting the graph, I have probles utilizing the custom colors there is the function:
`
function f_graph_custom_colors(nId, Fcc) { //
    document.head.innerHTML = document.head.innerHTML + '<style>' +
        nId + ' .ct-series.ct-series-a line {fill: ' + Fcc[0] + ';} ' +
        nId + ' .ct-series.ct-series-b line {fill: ' + Fcc[1] + ';} ' +
        nId + ' .ct-series.ct-series-c line {fill: ' + Fcc[2] + ';} ' +
        nId + ' .ct-series.ct-series-d line {fill: ' + Fcc[3] + ';} ' +
        nId + ' .ct-series.ct-series-e line {fill: ' + Fcc[4] + ';} '
        + '</style>';
`
I try to inject the css in the header, after the css of the chartist, I read about utilizing custom color changing the css, but I need it dinamically.

Thanks for the responses, and sorry for the inconvenience.

**Comment by gionkunz** [comment]
Please read this guide: https://gionkunz.github.io/chartist-js/getting-started.html#dynamic-colouring

Cheers
Gion

**Comment by Jeketerri** [comment]
Thanks for the answer, but it, don't work for me, in my horizontal bar chart I put from zero to 5 items per label, your solution works on a single bar per label, but doesn't work on multiple, maybe I'm missing something.
checking the output code:
Single bar per label
`
<g class="ct-series ct-series-a"><line x1="82.5" x2="82.5" y1="869" y2="21.35419443750436" class="ct-bar" value="73.44940235553241" style="stroke: #60c92e;"></line><line x1="147.5" x2="147.5" y1="869" y2="62.064153650368894" class="ct-bar" value="69.92184148697038" style="stroke: #60c92e;"></line><line x1="212.5" x2="212.5" y1="869" y2="350.9296762228437" class="ct-bar" value="44.89133953104165" style="stroke: #60c92e;"></line><line x1="277.5" x2="277.5" y1="869" y2="279.50660639287696" class="ct-bar" value="51.080223802022374" style="stroke: #60c92e;"></line></g>`

but in multi bar per label
`<g class="ct-series ct-series-b"><line y1="134" y2="134" x1="80" x2="156.5" class="ct-bar" value="15" style="fill:&quot;#e8260b&quot;;"></line><text x="158.5" y="138" style="text-anchor: start" class="ct-label ct-label-above">15</text><line y1="100" y2="100" x1="80" x2="156.5" class="ct-bar" value="15" style="fill:&quot;#e8260b&quot;;"></line><text x="158.5" y="104" style="text-anchor: start" class="ct-label ct-label-above">15</text><line y1="66" y2="66" x1="80" x2="156.5" class="ct-bar" value="15" style="fill:&quot;#e8260b&quot;;"></line><text x="158.5" y="70" style="text-anchor: start" class="ct-label ct-label-above">15</text><line y1="32" y2="32" x1="80" x2="202.4" class="ct-bar" value="24" style="fill:&quot;#e8260b&quot;;"></line><text x="204.4" y="36" style="text-anchor: start" class="ct-label ct-label-above">24</text></g>`

At this moment I have 3 diferent <g> labels for each (a,b,c) bars, I try to put diferent target, but only work with the (context.type === 'bar') option, the library aparently try to paint the bars, but finally I only get the css color scheme.

Thanks for the responses, and sorry for the inconvenience.

**Comment by Jeketerri** [comment]
Well, I try it again, thanks to a friend got a single color for all the bars, but I need to change the `context.type === 'bar'` to something like `context.type === 'series-(letter) bar` if it have a similar mode, for change the color in each series.

**Comment by Jeketerri** [comment]
Okey, I'm doing some researches and I found this, `context.type` are `label, grid and bar`, then `if(context.type === 'bar')` get all the bars, but, how can I select the bars depending on the `ct-series-(letter)`? because I need a diferend color for each serie.

**Comment by Jeketerri** [comment]
Finish!! Thanks for helping sire, and thanks for your beautiful Lib, This is my final function:
```
function f_graph_custom_colors(nId, chart, Fcc) {
    var flagstone = true;
    chart.on('draw', function (context) {
        if (context.type === 'bar' && flagstone ) {
            flagstone = false; // only enter to this if once
            document.head.innerHTML = document.head.innerHTML + '<style>' +
                nId + ' .ct-series.ct-series-a line {stroke: ' + Fcc[0] + ';} ' +
                nId + ' .ct-series.ct-series-b line {stroke: ' + Fcc[1] + ';} ' +
                nId + ' .ct-series.ct-series-c line {stroke: ' + Fcc[2] + ';} ' +
                nId + ' .ct-series.ct-series-d line {stroke: ' + Fcc[3] + ';} ' +
                nId + ' .ct-series.ct-series-e line {stroke: ' + Fcc[4] + ';} '
                + '</style>';
        }
    });
}
```

**Comment by nagualcode** [comment]
how to change the grid color? (normal is grey)
