### ISSUE TITLE
Option - Width: '100%' - is not working.

### ISSUE THREAD

**Issue by DanilChugaev** [chartist-js/chartist#926]
In issues I did not find a similar question.

When i establish option (width: '100%') graph looks like that:

![screenshot_1](https://cloud.githubusercontent.com/assets/18678200/24643105/15a6d88a-1925-11e7-9ef6-3fdaf6a67af1.png)

When i resize window then graph looks like that:

![screenshot_2](https://cloud.githubusercontent.com/assets/18678200/24643140/5f032a2e-1925-11e7-9027-f6c39bc0e6e2.png)

How do I make it so that the graph initially stretches across the entire width of the container? (only (fullWidth: true) doesn't help me 
![screenshot_3](https://cloud.githubusercontent.com/assets/18678200/24643200/d8891fca-1925-11e7-9bce-9ace35364a40.png)
)

`
var chart = new Chartist.Line('.ct-chart', {
                    labels: ['100', '200', '300', '400', '500', '600', '700', '800', '900', '1000', '2000', '3000', '4000', '5000', '6000', '7000', '8000'],
                    series: [{
                        name: 'series-1',
                        data: [0, 2, 5, 3, 2, 2, 7, 8, 5, 3, 7, 0, 2, 5, 4, 8, 0]
                    }]
                }, {
                    fullWidth: true,
                    showArea: true,
                    showPoint: false,
                    showLine: false,
                    width: '100%',
                    height: '198px',
                    low: 0,
                    axisX: {
                        showLabel: false,
                        showGrid: false
                    },
                    series: {
                        'series-1': {
                            lineSmooth: Chartist.Interpolation.step()
                        }
                    }
                });
`

**Comment by ghost** [comment]
I have had same issue, I think it's because container size change **after** new Chartist.Line() call.
be sure you call draw function when styles and/or width-change content already loaded.
