### ISSUE TITLE
Question: Single Gradient Applied to Bar Graph

### ISSUE THREAD

**Issue by bureauoftruth** [chartist-js/chartist#927]
Hi @gionkunz,

I built a bar graph which loads data dynamically. Is there a way to apply a single gradient across all of the bars? I attached an image for reference.

thanks,

Shawn

<img width="1187" alt="screen shot 2017-04-04 at 1 31 38 am" src="https://cloud.githubusercontent.com/assets/17035286/24647907/ad8c8a18-18d6-11e7-81c6-c1b6e10b294e.png">

**Comment by Arantiryo** [comment]
Hello @bureauoftruth 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the question is still relevant to you so we can further investigate it!
