### ISSUE TITLE
Is it possible to update chart with new data without re-rendering?

### ISSUE THREAD

**Issue by opensourcegeek** [chartist-js/chartist#930]
I haven't used chartist yet, but looks compelling. I have time series data, I've been using smoothie for that but I'm looking for something that is responsive. With smoothie, I can just add data to series. Is there something along those lines in chartist?

**Comment by Arantiryo** [comment]
Hi @opensourcegeek 👋 

I don't believe it's possible to add data to series without rerendering the chart.
