### ISSUE TITLE
Possible to change stroke color based on label value?

### ISSUE THREAD

**Issue by yurtkuran** [chartist-js/chartist#935]
Would like to change the stroke color based on the label text? This is my code so far:

    new Chartist.Bar('#chart1', data, options)
        .on('draw', function(data) {
            if(data.type === 'bar' && data.value.x < 0) {
                data.element.attr({
                    style: 'stroke: red'
                });              
            } 
        })
        .on('draw', function(data) {
            if(data.type === 'bar' && data.labels === 'SPY') {
                data.element.attr({
                    style: 'stroke: red'
                });              
            } 
        });  

The first .on('draw' is working - all negative values are red. 

The second .on('draw' is not working. Any suggestions?

Thanks in advance!!

**Comment by diegoaguilar** [comment]
Did you solve this? Why not to handle it at in same event handler?

**Comment by danielabbatt** [comment]
I too would like to be able to colour a bar based on whether it's a weekday/weekend etc. I assumed this would be done via labels.

**Comment by gionkunz** [comment]
You can use the series index from the context object passed to the draw event callback. Then extract the corresponding label for that index and color the bar based on that.

**Comment by kannan09** [comment]
How to set each individual bar in a bar chat to a different color

**Comment by Arantiryo** [comment]
Hi @kannan09 👋 

This can be achieved by setting `distributeSeries` to `true`. Here's [an example](https://codesandbox.io/s/practical-snowflake-s6y4zu?file=/index.ts).
