### ISSUE TITLE
[Bug] HTML on labels not working anymore since 0.11.0

### ISSUE THREAD

**Issue by ghost** [chartist-js/chartist#937]
Since version 0.11.0 the labels cannot have HTML anymore in it.

Reason is this commit:
https://github.com/gionkunz/chartist-js/commit/3857a194b101eb5268469df3c0be6120c40927a3#diff-24396d76ef1bcec041b43d683ecd750bR978

There we now use "innerText". We should change it to "innerHtml" or something else that supports HTML code.

**Comment by ghost** [comment]
Hi @gionkunz,
we use this chartist feature (HTML on labels) for a very important customer (a big customer web portal for a very big concern) and we really want to update to the latest chartist version. Can you provide a valid fix? I don't have time to provide a fix myself.

You can find an idea how to solve it inside #938 but I don't have time to test it and check why tests are failing.

Thanks!

**Comment by gionkunz** [comment]
Check #1015
