### ISSUE TITLE
AddClass for a data point?

### ISSUE THREAD

**Issue by spyhunter99** [chartist-js/chartist#941]
Is it possible to do something like

````
    series[{
     name:'test',
     data: [
      {x:1, y:100, addClass:'myCustomCssClass'},
     ]
   }]
````

I know the syntax is probably wrong, but i want to override the render color of individual points and hopefully define the property inline as depicted above. Is this supported or documented anywhere?

**Comment by gionkunz** [comment]
Use `meta` to add your meta data to your chart data. Then use the `draw` event to extract the color from the meta data and colorize it. Check the examples for dynamic coloring in the getting started section on the website.

**Comment by spyhunter99** [comment]
that's what i ended up doing, but it would be helpful if all properties defined were accessible on the  on draw event. Going off of the above example the property addClass is not available in the on draw event. Using meta works well, but if you're also using the tooltip plugin, then that's not viable.

**Comment by gionkunz** [comment]
Yeah, that's true. Meta data is shared across all plugins and the core. This is something we will improve with version 2. You can always put data in your initial data object and make that accessible in the closure of your draw callback. Then use the index of the data point and series to access your original data, where you can store / read any information from.
