### ISSUE TITLE
chart redraw on resize of parent div 

### ISSUE THREAD

**Issue by gulshan-escalon** [chartist-js/chartist#943]
I understand that on the window.resize event that chart redraws itself. I was wondering what the best way to do the same when the chart's container div changes size?

thanks

**Comment by gionkunz** [comment]
Until we have element queries, there's no other way than monitoring the parent div size with a time interval I guess :-(

**Comment by themepixels** [comment]
Include this js file in your page https://github.com/flowkey/resize-sensor

var chart = new Chartist.Line({ ... });

new ResizeSensor($('#chart-container'), function(){
   chart.update();
});
