### ISSUE TITLE
X axis last label not visible (Example "SVG Path Animation")

### ISSUE THREAD

**Issue by arapoport** [chartist-js/chartist#945]
I was looking through examples in the hope to find a solution for the last label of the X axis hanging outside and noticed that "SVG Path Animation" example has the same problem (Firefox 53, Chrome 58):

![svg_path_ani_example](https://cloud.githubusercontent.com/assets/3393725/26026838/5a57ce1a-3803-11e7-99f5-e3bf3a672753.JPG)

**Comment by gionkunz** [comment]
You can use the options `chartPadding = {right: ...}` to fix this problem.
