### ISSUE TITLE
No labels in Firefox V39

### ISSUE THREAD

**Issue by Subcode** [chartist-js/chartist#946]
Hi, 
When i look at https://gionkunz.github.io/chartist-js/examples.html with Firefox V39 no labels are shown.
Is there any way to fix this?

To add to this: The page https://gionkunz.github.io/chartist-js/ shows that chartist is compatible with Firefox V31, however when i browse to the examples page using Firefox V31 this does not seem to be the case. Every chart is extremely small and labels are also not shown.

**Comment by pborunda** [comment]
I'm seeing the same issue on Firefox V36

**Comment by pborunda** [comment]
@gionkunz, if you change innerText to textContent, then this fixes the problem.     
FROM
content.innerText = labels[index];
TO
content.textContent = labels[index];
