### ISSUE TITLE
[Feature] Add support for inline style colors

### ISSUE THREAD

**Issue by lubomirblazekcz** [chartist-js/chartist#947]
Styling the chart with only CSS can be sometimes limiting. Eg. if you have chart that is generated via CMS and user wants to specify color. Yes I could include this via <style> attribute into body, but that is not w3c valid solution. I would prefer something like inlineColor: ["#333333", "#000000"], so I could pass the array via data attribute.

Or has somebody better idea how to approach this? Thanks!

**Comment by gionkunz** [comment]
Hi, did you look at this? https://gionkunz.github.io/chartist-js/getting-started.html#colour-up-your-charts

**Comment by lubomirblazekcz** [comment]
Sorry! I've totally missed that example, this should do it. Thanks!

**Comment by lubomirblazekcz** [comment]
Although this solution can be problematic with animations etc. values can get overwritten.  Eg. with the donut chart, the stroke-width style was overwritten with the color
