### ISSUE TITLE
Create a double category bar chart

### ISSUE THREAD

**Issue by tawani** [chartist-js/chartist#949]
Is it possible to create a double category bar chart using the chartist library?
![double category bar chart](https://cloud.githubusercontent.com/assets/235173/26060435/0eaaed52-3953-11e7-91ce-ba9d9bf7a973.png)

**Comment by Arantiryo** [comment]
Hi @tawani 👋 

In case it's still relevant here's [an example](https://codesandbox.io/s/github/chartist-js/chartist/main/sandboxes/bar/bi-polar-interpolated?file=/index.ts).
