### ISSUE TITLE
Tooltips out of place on examples page

### ISSUE THREAD

**Issue by pavlos256** [chartist-js/chartist#95]
I only have Firefox available here so I haven't tested it on other browsers. The tooltips seem to be out of place on the "Line chart with tooltips" example.

![tooltip](https://cloud.githubusercontent.com/assets/311595/5217913/60a91f26-764f-11e4-8069-a37961d44bd3.png)

**Comment by baires** [comment]
Same here on Firefox 33.1

**Comment by gionkunz** [comment]
Hi Guys, thanks, I've noticed this too in FF. It looks like an issue with position: relative / absolute. Firefox is usually more strict about positioning. I'll fix that asap.

Cheers and thanks!
Gion
