### ISSUE TITLE
Change Color settings (stroke) dynamically; depends on value

### ISSUE THREAD

**Issue by djsunrise19** [chartist-js/chartist#950]
Hi,

I'm not very fimilar with javascript and I searched for a solution the last few days. Perhaps it's very easy (it seems so) but I didn't get it.

I have a bar chart and wan't to have red for negativ values (< 0) and green for the other ones ( > = 0). The circles should have the same color as the bars. That's my code:

`var Chartist3 = new Chartist.Bar('#chart3', {
  labels: [],
  series: [
    myDatalast10
  ]
    }, {
        height: 240,
		fullWidth: true,
		showGrid: true,
		showLabel: true,
          axisY: {
            onlyInteger: true,
            offset: 20
        },  
  axisX: {
    labelInterpolationFnc: function(value, index) {
      return index % 2 === 0 ? value : null;
    }
  },
        plugins: [
            Chartist.plugins.tooltip()
        ]
});
Chartist3.on('draw', function(data) {
  if(data.type === 'bar') {
	data.group.append(new Chartist.Svg('circle', {
      cx: data.x2,
      cy: data.y2,
      r: Math.abs(Chartist.getMultiValue(data.value)) * 1.2 + 2.5
    }, 'ct-slice-pie'));
  }
});`

And that's my actual chart:

![image](https://cloud.githubusercontent.com/assets/14234570/26069712/2e16603c-39a2-11e7-949e-5141722ffbd1.png)

Perhaps anybody have a solution for me.

Thanks and greets
Maurice

**Comment by emcdng** [comment]
Hi Maurice,

I think this: https://gionkunz.github.io/chartist-js/getting-started.html#colour-up-your-charts documentation should resolve your problem.

regards 

Mario

**Comment by djsunrise19** [comment]
@mtrax : Thank you! I know that documentation. But it doesn't work. I tried it with:

`if(data.type === 'bar' && data.value.x < 0) {
            data.element.attr({
                style: 'stroke: red'
            });              
        } `

I saw that in another topic here. Is  `data,value.x` correct?

**Comment by emcdng** [comment]
@djsunrise19 you are entering the if statement, right?

You can try adding 'fill: red' too.

**Comment by djsunrise19** [comment]
I thought I can do it like that:

```
Chartist3.on('draw', function(data) {
	
  if(data.value.x < 0) {
            'fill: red'
            };              

  if(data.type === 'bar') {
	data.group.append(new Chartist.Svg('circle', {
      cx: data.x2,
      cy: data.y2,
      r: Math.abs(Chartist.getMultiValue(data.value)) * 1.2 + 2.5
    }, 'ct-slice-pie'));
  }  
});
```

But I get:

![image](https://cloud.githubusercontent.com/assets/14234570/26076100/e7ad18be-39b7-11e7-9ed2-a1c5e7d01742.png)

**Comment by emcdng** [comment]
and what about data.value.**y**?

in my case is x undefined too

**Comment by djsunrise19** [comment]
![image](https://cloud.githubusercontent.com/assets/14234570/26076264/795e89e6-39b8-11e7-8f80-c39f170e3a4d.png)

**Comment by emcdng** [comment]
```
                var red= '#ff0000';

                chart.on('draw', function (context) {
                        if (context.type === "bar") {
                            if (context.value.y < 0) {
                                context.element.attr({
                                   style: 'stroke: ' + red + '; fill: ' + red + ';'
                                });
                            } 
                        }
                    });
```

**Comment by djsunrise19** [comment]
@mtrax : Great, that looks fine:

```
Chartist3.on('draw', function (context) {
        if (context.type === "bar") {
            if (context.value.y < 0) {
                context.element.attr({
                style: 'stroke: ' + red + '; fill: ' + red+ ';'
                });
            };
			if (context.value.y >= 0) {
            context.element.attr({
            style: 'stroke: ' + green + '; fill: ' + green+ ';'
				});
			} 
        }
});

Chartist3.on('draw', function(data) {         
  if(data.type === 'bar') {
	data.group.append(new Chartist.Svg('circle', {
      cx: data.x2,
      cy: data.y2,
      r: Math.abs(Chartist.getMultiValue(data.value)) * 1.2 + 2.5
    }, 'ct-slice-pie'));
  }
});
```
How can I implement those circles in that function, too?

**Comment by emcdng** [comment]
You can move your circle code snippet into the upper logic...

**Comment by djsunrise19** [comment]
I'll try that! Thank you very much!!
