### ISSUE TITLE
Navigation on the docs are not scrollable on low res devices

### ISSUE THREAD

**Issue by Azd325** [chartist-js/chartist#96]

**Comment by gionkunz** [comment]
Hi there. I'm actually working on a concept for the navigation. Also on desktop I'd like to have the side navigation collapsing / expanding the topics / subtopics based on scroll position. On mobile it'd be nice to have a different navigation concept (maybe sticky drop down, offcanvas ?)

Any ideas are welcome!

Cheers
Gion

**Comment by Azd325** [comment]
Also I think the Navigation is broken on Examples. On API Documentation it works.
