### ISSUE TITLE
vertical/horizontal classes wrong

### ISSUE THREAD

**Issue by pomm0** [chartist-js/chartist#967]
Hey,

i've seen that the .ct-vertical and .ct-horizontal classes are wrong. The horizontal grid lines have the .ct-vertical class and the vertical grid lines have the .ct-horizontal class in svg see (See css colors in dev tools and the chart above):

![selection_145](https://user-images.githubusercontent.com/6084030/27232562-c75db3da-52b6-11e7-9a8a-2db6777cb1dc.jpg)

**Comment by thetrav** [comment]
Open to interpretation.  The lines are vertical sure, but they denote positions on the horizontal axis, which is what the class refers to
