### ISSUE TITLE
How do you define a line that is parallel to the X axis?

### ISSUE THREAD

**Issue by nhua2013** [chartist-js/chartist#968]
How do you define a line that is parallel to the X axis?
[http://files.cnblogs.com/files/fx2008/QQ%E5%9B%BE%E7%89%8720170622110006.gif](url)

**Comment by glvangorp** [comment]
For what I'm doing right now, just filling the array with the same y value works. If someone knows of a better way, they can let me know.

**Comment by Arantiryo** [comment]
Hello @nhua2013 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the question is still relevant to you so we can further look into it!
