### ISSUE TITLE
Border Radius on ct-grids

### ISSUE THREAD

**Issue by ghost** [chartist-js/chartist#969]
Hello, awesome job on charts!
Is there any option to put border radius on .ct-grid-background?
Or maybe stroke-linejoin="round" on path.
My example: http://mlimasolucoes.com.br/etalent/chartist/ i want border radius on background

**Comment by ghost** [comment]
solved by:
var addedEvents = false;
normalChart.on('draw', function() {
  if (!addedEvents) {
    $(".ct-grid-background").attr("rx",10);
    $(".ct-grid-background").attr("ry",10);
  }
});

**Comment by NetherGranite** [comment]
Oh, that's good to know. If you solved it and don't need further help, please close this issue.
