### ISSUE TITLE
This project is still active ?

### ISSUE THREAD

**Issue by l2aelba** [chartist-js/chartist#970]
> We are currently still heavily developing

But I see its latest commit **3 months ago**.

I hope you guys are still developing this Chartist-js. **I love the concept** , You came to right way !

Im still waiting for **Release v1** 

**Good job anyway !**, and please come back ❤️

**Comment by NetherGranite** [comment]
I also hope this is still under development. I've spent over fifteen hours researching chart libraries, and this is hands-down the best combination of practicality and customization that I've found.

**Comment by l2aelba** [comment]
@NetherGranite, Yep hope also. But this no so flexible right now (beta version)

Now im using **[eCharts](https://github.com/ecomfe/echarts)** is most flexible chart library on this time.

**Comment by Arantiryo** [comment]
Hello @l2aelba 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).
