### ISSUE TITLE
Option to disable adding points with Chartist.Interpolation.step()

### ISSUE THREAD

**Issue by hrst** [chartist-js/chartist#971]
Right now, charts with Chartist.Interpolation.step() and showPoint:true are highly confusing, as each data point shows up twice in the chart. Especially when the chart is a time series, it is impossible to understand:

![image](https://user-images.githubusercontent.com/164351/27629194-d614d108-5bf1-11e7-9e08-8092ae27473d.png)

It would be nice to have the options to disable adding points with Chartist.Interpolation.step() and receive this result:

![image](https://user-images.githubusercontent.com/164351/27629277-1aa9fc30-5bf2-11e7-9141-3e284f30978f.png)

I.e. the chart shows points but only the ones which actually resemble a data point.

**Comment by ghost** [comment]
`
function isInArray(array, search)
{
    return array.indexOf(search) >= 0;
}


var addedEventsE = false;
var changeLines = [];

Overchart.on('draw', function(data) {
  if (!addedEventsE) {
	$(".ct-grid-background").attr("rx",10);
	$(".ct-grid-background").attr("ry",10);

	if(data.type == 'point') {
	//  console.log(data);
	  //triangulo
	  var triangle = new Chartist.Svg('path', {
	    d: ['M',
	      data.x,
	      data.y - 5,
	      'L',
	      data.x - 5,
	      data.y + 4,
	      'L',
	      data.x + 5,
	      data.y + 4,
	      'z'].join(' '),
	    style: 'fill-opacity: 1'
	  }, 'ct-area');

	  //triangulo pra baixo
	  var triangle2 = new Chartist.Svg('path', {
	    d: ['M',
	      data.x,
	      data.y + 5,
	      'L',
	      data.x + 5,
	      data.y - 4,
	      'L',
	      data.x - 5,
	      data.y - 4,
	      'z'].join(' '),
	    style: 'fill-opacity: 1'
	  }, 'ct-area');

    if(!isInArray(changeLines, data.index))
    {
      changeLines.push(data.index);
      if (data.index % 3 === 0) {
         if(data.value.x > data.value.y) {
           data.element.replace(triangle2); 
         } else if(data.value.x < data.value.y) {
          data.element.replace(triangle); 
         }
      }
      else {
        if(data.value.x < data.value.y && data.value.y - data.value.x < 10 ) {
          data.element._node.className.baseVal = 'ct-quadrado';
        }
      }

    } else {
      data.element._node.className.baseVal = 'ct-hide';
    } 

    }  
  }
});`

**Comment by ghost** [comment]
QUICK FIX but cant find before draw event on documentation

**Comment by Arantiryo** [comment]
Hello @hrst 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the issue is still relevant to you so we can further investigate it!
