### ISSUE TITLE
ctPointLabels Not Displaying on Line Chart

### ISSUE THREAD

**Issue by purplelady105** [chartist-js/chartist#972]
I am attempting to add point labels to my line chart using the ctPointLabels plugin, but they are not appearing on the chart. I am already using the tooltip plugin, which is working, so I am not sure what I am missing. 

I have included the plugin stylesheets in the <head></head> tags:

```
<link href="css/plugins/chartist.min.css" rel="stylesheet">
<link href="js/plugins/chartist-plugin-tooltip-master/src/css/chartist-plugin-tooltip.css" rel="stylesheet">
```
And I have included the js scripts at the bottom of the page right before my chart scripts:

```
<!--Chartist Plugins-->
<script src="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
<script src="js/plugins/chartist-plugin-pointlabels-master/src/scripts/chartist-plugin-pointlabels.js"></script>
<script src="js/plugins/chartist-plugin-tooltip-master/src/scripts/chartist-plugin-tooltip.js"></script>
```

Here is my script for drawing the line chart:

```
<script>
            // Loads per Broker (Red Chart)
            new Chartist.Line('#chart1', {
                labels: [1, 2, 3, 4, 5, 6, 7, 8],
                series: [
                  [5, 9, 7, 8, 5, 3, 5, 4]
                ]
              }, {
                  plugins: [
                    Chartist.plugins.tooltip({
                        /*currency: '$',*/
                        anchorToPoint: true
                  }),
                    Chartist.plugins.ctPointLabels({
                        textAnchor: 'middle'
                  })
                ],
                low: 0,
                showArea: true
              });
</script>
```
Here is a screenshot showing that the tooltips are working, but not the point lables:

![image](https://user-images.githubusercontent.com/28715727/27655539-993b57a8-5bfa-11e7-9b37-9476f3249870.png)

Thank you for your assistance!

**Comment by sshanzel** [comment]
I hope someone will be able to help. I'm having the same problem here.

**Comment by purplelady105** [comment]
@sshanzel I had posted a ticket on the page for the actual plugin and received an answer from @dustinnulf that solved the issue. See the post here: https://github.com/gionkunz/chartist-plugin-pointlabels/issues/16
