### ISSUE TITLE
How can miss point to draw line to next point?

### ISSUE THREAD

**Issue by ghost** [chartist-js/chartist#974]
Hi, Gion!

For example, I have 12 label and 12 points. Let's pretend that one+ are missed.

Are there any possibilities to draw line from last existing point to first existing point ? 

Thank You.

Screenshot 1 - Desirable behavior
![screen](https://user-images.githubusercontent.com/16815531/27735936-9f36ef9e-5daa-11e7-8bba-09356ee87382.jpg)

Screenshot 2 - No point at all makes points pulling to left
![screen2](https://user-images.githubusercontent.com/16815531/27736221-f15ca538-5dab-11e7-9695-70535019db95.jpg)

Screenshot 3 - No x or y breaking the line
![screen3](https://user-images.githubusercontent.com/16815531/27736222-f1616366-5dab-11e7-8814-406896fae18c.jpg)

**Comment by ghost** [comment]
Sorry, Gion!

My bad!

Good chart.

**Comment by ghost** [comment]
Hey, Gion.

It's me again.

I have another issue.

Here's my code:

new Chartist.Pie('.ct-chart-pie',
        {
            labels: ['14%', '7%', '8%', '71%'],
            series: [
                {
                    className: 'affiliate-affiliate-pie',
                    value: 14
                },
                {
                    className: 'other-affiliate-pie',
                    value: 7
                },
                {
                    className: 'jv-affiliate-pie',
                    value: 8
                },
                {
                    className: 'product-affiliate-pie',
                    value: 71
                }
            ]
        },
        {
            donut: true,
            donutSolid: true,
            donutWidth: 65,
            width: '242px',
            height: '242px',
        }
    );

I want to get pie chart with donutSolid: true, but it's doesn't work for me. 

![screen4](https://user-images.githubusercontent.com/16815531/27754002-c0cf66ae-5df0-11e7-9ab6-9a8efe6695b8.jpg)

**Comment by NetherGranite** [comment]
https://www.npmjs.com/package/chartist-plugin-fill-donut

Is it possible you needed this? I don't really know anything about it, but I came across it so I thought I'd mention it.

**Comment by ghost** [comment]
NetherGranite, plugin is not what I need. Documentaion says "No need any plugins".

Found another issue. 
Labels are placed incorrect. 
![screen5](https://user-images.githubusercontent.com/16815531/27783121-997ad8ce-5fdd-11e7-8bca-08be78b78011.jpg)
