### ISSUE TITLE
Hide Grid Scale

### ISSUE THREAD

**Issue by mwsasser** [chartist-js/chartist#975]
Hi guys, sorry if I've missed this is the documentation.  Is there a method to turn off the grid scale and it's labels on a bar chart?

I've been able to hide them in the css using `.ct-grid {  stroke: white;}` but I didn't know if there was a configuration setting that I'd missed.

**Comment by NetherGranite** [comment]
Ah, I came across this same obstacle just a few days ago. I solved it by adding the following to the options for my chart:

```
axisX: {
	showGrid: false,
	showLabel: false
},
axisY: {
	showGrid: false,
	showLabel: false
},
```

**Comment by mwsasser** [comment]
Oh awesome, thanks!
