### ISSUE TITLE
Possible to draw chart without axis labels?

### ISSUE THREAD

**Issue by nicmendoza** [chartist-js/chartist#98]
I am trying to match a design in which we render several miniature graphs, with a tooltip on mouseover, but have been stumped as to how I can draw a chart without axes shown on it. I have managed to hide the labels, but there is still a space in their place.

Here is the design:
![image](https://cloud.githubusercontent.com/assets/5489626/5250217/1df9d538-7958-11e4-9092-bbcabc435808.png)

Here is where I have gotten it so far (leaving the grid in to make the gap more obvious):
![image](https://cloud.githubusercontent.com/assets/5489626/5250258/5a07e31c-7958-11e4-8ecd-18eb7970ebea.png)

Is there an option or a clever way to do something like this? It seems to me like a pretty reasonable use case to not draw an axis on a chart.

**Comment by nicmendoza** [comment]
Ok, after further reading of the documentation, I think I'm going to fake the last part with axis margins, along these lines:

```
axisY: {
    offset: 0
},
axisX: {
    offset: 0
}
```

**Comment by th317erd** [comment]
For anyone else who finds themselves here I was also able to remove the chart labels by using the `labelInterpolationFnc` and returning an empty string:

```
axisY: {
  offset: 0,
  labelInterpolationFnc: () => ''
}
```
