### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by Avcajaraville** [chartist-js/chartist#985]
Hi there !!

Im experiencing some terrible performances issues when drawing two pie (donut) charts at the same time.

I need to create two donuts charts at the same time. The have different data, but I want them both to be painted at the same time and having the same duration.

When I trigger the paint; the second chart, which have more than 12 regions, suffers really noticeable delays and make this a deal breaker. When the first graph is over painting, the second one goes back to be smooth.

I also tried with CSS animations, but Im not able to make then run in sequences.

Any help would be much appreciated !

**Comment by Shawnxkwang** [comment]
Did you find any solutions? Why is this issue closed?

**Comment by Avcajaraville** [comment]
@Shawnxkwang  Its been a while, but I believe it was my mistake, mostly due to not changing the ids of the chart I was referencing. Let me know if you are still stuck; I will try to help :)
