### ISSUE TITLE
Chartist.js not showing on Safari, Ipad, Iphone...  or any webkit core

### ISSUE THREAD

**Issue by miobit** [chartist-js/chartist#989]
![graph-issue-before](https://user-images.githubusercontent.com/8502205/28455502-901c7ed8-6dff-11e7-81a8-a68f480322c4.png)
Graph doesnt show or responsive width doesnt work on webkit.
I tried update() but issue persist.
After adding fixed width, chartist.js show graph but responsive width missing. 
Solution width fixed width:
![graph-issue-after](https://user-images.githubusercontent.com/8502205/28455615-efbdeaa2-6dff-11e7-813e-7d47c515fe05.png)

What about min-width and max-width (and on webkit?) ?

**Comment by gionkunz** [comment]
The problem must be with your code since all the examples on http://gionkunz.github.io/chartist-js/examples.html are working without any issues. Can you reproduce the issue in an environment which you can share? Like jsbin, jsfiddle or Plunker?

**Comment by miobit** [comment]
I installed new Safari 5.1.7 (b. 7534.57.2) on windows7 and win 10 ... this is chartist website: 
![image](https://user-images.githubusercontent.com/8502205/28457677-5879861c-6e07-11e7-8db1-2157d8eefeba.png)
few minutes ago. 
I can share setting... but i cant share project. width is added for example (from first comment)
> var options_big = {
            width: 800,
            height: 70,
            fullWidth: true,
            stretch: true,
            divisor: 2,
            series: {
                "data": {
                    showPoint: true,
                    //lineSmooth: false,
                    showArea: false,
                    showLine: false,
                    chartPadding: {
                        right: 10
                    },
                    lineSmooth: Chartist.Interpolation.cardinal({
                        fillHoles: false,
                    }),
                }
            },
            axisX: {
                showGrid:false,
                showLabel: true,
                position: "start",
            },
            axisY: {
                offset: 100,
                showGrid: false,
                showLabel: false,
                onlyInteger: true,
                low: 0,
                high: 0.00001,
            }
        }

**Comment by gionkunz** [comment]
Safari 5.1.7 for Windows is from 2012 and is not supported. Check the compatibility table: http://gionkunz.github.io/chartist-js/#browser-compatibility

**Comment by miobit** [comment]
Yep, but only Safari 5 really simulate this iPad issue: if width is not set, graph width is zero. Ill try check ipad version of embeded web view core ( safari 5/6/7) and ill write you back

**Comment by miobit** [comment]
A1566 and A1567 ....   a1567 : graphs are great, responsive...    A1566 : graphs are destroyed, width is equal zero. 
Image: A1567
![image](https://user-images.githubusercontent.com/8502205/28463036-93876366-6e1e-11e7-9ffe-5c0dbfea05ee.png)
Image: A1566
![image](https://user-images.githubusercontent.com/8502205/28463574-5e4043be-6e21-11e7-844f-f062ec6c3844.png)

Any idea?

**Comment by gionkunz** [comment]
Whats the browser version of A1566, User Agent headers are always a bit cryptic.

**Comment by miobit** [comment]
This version is from whatsmybrowser:
![image](https://user-images.githubusercontent.com/8502205/28513149-3a457f5c-7055-11e7-8648-1e0fdccd9574.png)
and this from settings page on iPad A1566 and 
![image](https://user-images.githubusercontent.com/8502205/28513160-464293c6-7055-11e7-9baf-0c58ac0851c4.png)
issue is same in Mobile Safari UIWebView - i think this is embedded Safari browser,  same version = same troubles

**Comment by qbikaris** [comment]
+1 

We have the same issue!

**Comment by miobit** [comment]
Then you have same troubles 

One static solution is to create a fixed width value with fixed padding only forhadware where chartist doesnt work :  

if (browser_name == "safari") {
graph_options = 
   ...
   // if safari browser  then set options, stupid solution but work.
   fullWidth: true, 
   stretch  true,
   width: 800 ,
   padding: -80,
   ...

here is browser checker
 ```
var browser_name = '';
            isIE = /*@cc_on!@*/false || !!document.documentMode;
            isEdge = !isIE && !!window.StyleMedia;
            if(navigator.userAgent.indexOf("Chrome") != -1 && !isEdge)
            {
                browser_name = 'chrome';
            }
            else if(navigator.userAgent.indexOf("Safari") != -1 && !isEdge)
            {
                browser_name = 'safari';
            }
            else if(navigator.userAgent.indexOf("Firefox") != -1 ) 
            {
                browser_name = 'firefox';
            }
            else if((navigator.userAgent.indexOf("MSIE") != -1 ) || (!!document.documentMode == true )) //IF IE > 10
            {
                browser_name = 'ie';
            }
            else if(isEdge)
            {
                browser_name = 'edge';
            }
            else 
            {
               browser_name = 'other-browser';
            }
            $('html').addClass(browser_name);
```

**Comment by qbikaris** [comment]
The fixed width doesn't solve my issue. 
It is solved however when I no longer use the FixedScaleAxis plugin.
