### ISSUE TITLE
Reduce number of labels shown for bar and line charts

### ISSUE THREAD

**Issue by jbwl** [chartist-js/chartist#99]
On the bar and line charts, I would like to reduce the number of labels shown for building a date histogram charts. For instance, if I have many data points (days) on the x-axis, there will be a cluttered mess of labels that are unreadable. 
I'd rather only display every nth label. Is the labelInterpolationFnc of the axisX option a good place to determine whether a label is printed or not? 
I have not found a built-in option to "skip" labels.

**Comment by gionkunz** [comment]
Hi there. Yes `labelInterpolationFnc` can be used to do interpolation but also to replace and / or skip labels. In order to skip a label just return a falsey value (except the number 0, this will count as valid). Something like this:

``` javascript
{
  axisX: {
    labelInterpolationFnc: function skipLabels(value, index) {
      return index % 5  === 0 ? value : null;
    }
  }
}
```

**Comment by gionkunz** [comment]
Also be aware that currently skipping a label will also skip the grid line.

**Comment by jbwl** [comment]
Thank you! I wasn't aware that index was available as an argument. This works nicely for me.

**Comment by jbwl** [comment]
But I have forgot to include this into the question: Now when I do not show all labels below the axis, I would like to include the x-axis label (i.e. a date) on the data point. If I use the tooltips line chart from your examples, I'd like to somehow be able to let the tooltip know the xAxis label for the point it belongs to, and thus be able to display the label inside the tooltip.

The tooltip's text could then read: 
2014-12-02: 1841 Units

I am not aware of a way to hand over the x-axis label's text value to the point and therefore its tooltip. Any ideas?
