### ISSUE TITLE
TIME SERIES WITH MOMENT.JS - MISSING LINE

### ISSUE THREAD

**Issue by growlead** [chartist-js/chartist#990]
var chartCTR = new Chartist.Line('#ctr-chart',
        {   
            series:
            [
                {
                    name: 'ctrChart',
                    data: ctrChart
                }
            ]
        },
        {
            axisX:
            {
                type: Chartist.FixedScaleAxis,
                divisor: 10,
                labelInterpolationFnc: function(value)
                {
                    return moment(value).format('MMM D HH:mm');
                }
            },
            showArea: true,            
            plugins:
            [
                Chartist.plugins.tooltip()
            ]
        });
![ctrchart](https://user-images.githubusercontent.com/13239431/28471117-b1722b56-6e44-11e7-8943-18c9caeef2be.png)

What the problem? What i do wrong?

**Comment by ubermanl** [comment]
I got it working by specifying the y axis type.

**Comment by gionkunz** [comment]
Great! :-)
